<?php return array (
  'SubcategoryID' => 1489,
  'SubcategoryName' => 'SPDIYPCCombos',
  'PropertyName' => 'SPDIYPCCPUSeries',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'AMD A10 APU',
    1 => 'AMD A4 APU',
    2 => 'AMD A6 APU',
    3 => 'AMD A8 APU',
    4 => 'AMD APU',
    5 => 'AMD Athlon',
    6 => 'AMD FX',
    7 => 'AMD FX 4000 Series',
    8 => 'AMD FX 6000 Series',
    9 => 'AMD FX 8000 Series',
    10 => 'Intel Celeron',
    11 => 'Intel Core i3',
    12 => 'Intel Core i3 4th Gen',
    13 => 'Intel Core i3 6th Gen',
    14 => 'Intel Core i5',
    15 => 'Intel Core i5 4th Gen',
    16 => 'Intel Core i5 6th Gen',
    17 => 'Intel Core i7',
    18 => 'Intel Core i7 4th Gen',
    19 => 'Intel Core i7 6th Gen',
    20 => 'Intel Core i7 Extreme',
    21 => 'Intel Pentium',
    22 => 'Intel Xeon',
  ),
) ?>