<?php return array (
  'SubcategoryID' => 2841,
  'SubcategoryName' => 'HIFlushMounts',
  'PropertyName' => 'HIFlushmountsmaterial',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 1,
  'PropertyValueList' => 
  array (
    0 => 'Acrylic',
    1 => 'Alabaster',
    2 => 'Aluminum',
    3 => 'Bamboo',
    4 => 'Beaded',
    5 => 'Brass',
    6 => 'Ceramic',
    7 => 'Crystal',
    8 => 'Etched Glass',
    9 => 'Fabric',
    10 => 'Faux Leather',
    11 => 'Fossil Stone',
    12 => 'Glass',
    13 => 'Iron',
    14 => 'Leather',
    15 => 'Linen',
    16 => 'Metal',
    17 => 'Mica',
    18 => 'Mosaic',
    19 => 'Onyx',
    20 => 'Paper',
    21 => 'Rattan',
    22 => 'Reclaimed Wood',
    23 => 'Resin',
    24 => 'Silk',
    25 => 'Slate',
    26 => 'Steel',
    27 => 'Stone',
    28 => 'Tiffany Glass',
    29 => 'Wicker',
    30 => 'Wood',
  ),
) ?>