<?php return array (
  'SubcategoryID' => 502,
  'SubcategoryName' => 'PSPAccessories',
  'PropertyName' => 'PSPACCType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Adapter',
    1 => 'Armored Case',
    2 => 'Battery',
    3 => 'Cable',
    4 => 'Case',
    5 => 'Charger',
    6 => 'Charging Station',
    7 => 'Controller',
    8 => 'Grip',
    9 => 'HDD',
    10 => 'Memory Card',
    11 => 'Miscellaneous',
    12 => 'Movie',
    13 => 'Other',
    14 => 'PortaLock',
    15 => 'Power Station',
    16 => 'Sound',
    17 => 'Stand',
    18 => 'Starter Kit',
    19 => 'UMD Accessories',
  ),
) ?>