<?php return array (
  'SubcategoryID' => 1927,
  'SubcategoryName' => 'HIWireCableConnectorsInsulation',
  'PropertyName' => 'HIWireCapConnectorsType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Battery & Cable Connectors',
    1 => 'Battery Clamp Accessories',
    2 => 'Battery Clamps',
    3 => 'Bullet & Pigtail Electrical Connectors',
    4 => 'Butt Splice Electrical Connectors',
    5 => 'C Tap Compression Connectors',
    6 => 'Cable Connectors',
    7 => 'Cable Protection Systems',
    8 => 'Disconnect Terminal & Tab Electrical Connectors',
    9 => 'Electrical Tape',
    10 => 'Electrical Wire Connector & Terminal Kits',
    11 => 'Flag Electrical Wire Connectors',
    12 => 'Fork Terminals',
    13 => 'Grommets',
    14 => 'Heat Shrink Tubing',
    15 => 'Insulation Displacement Connectors',
    16 => 'Lug Compression Connectors',
    17 => 'Mechanical Connectors',
    18 => 'Modular Electrical Connectors',
    19 => 'Motor Lead Disconnect Accessories',
    20 => 'Motor Lead Disconnects',
    21 => 'Pin Terminals',
    22 => 'Push-In Electrical Wire Connectors',
    23 => 'Ring Terminals',
    24 => 'Splice Connectors',
    25 => 'Splice Kits',
    26 => 'Split Bolt Connectors',
    27 => 'Street Light Disconnects',
    28 => 'Two Way Compression Connectors',
    29 => 'Wire Cap',
    30 => 'Wire Connector Kits',
    31 => 'Wire Connectors',
    32 => 'Wire Disconnects',
  ),
) ?>