<?php return array (
  'SubcategoryID' => 3439,
  'SubcategoryName' => 'SinksFountains',
  'PropertyName' => 'SinkType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Bar Sinks',
    1 => 'Bathroom Sinks',
    2 => 'Classroom Sinks',
    3 => 'Dish Table Sinks',
    4 => 'Drainboards',
    5 => 'Drinking Fountains',
    6 => 'Drop In Sinks',
    7 => 'Freestanding Sinks',
    8 => 'Hand Sinks',
    9 => 'Hot Water Dispensers',
    10 => 'Janitorial Sinks',
    11 => 'Kitchen Sink Accessories',
    12 => 'Kitchen Sinks',
    13 => 'Medical Scrub Sinks',
    14 => 'Replacement Parts',
    15 => 'Wash Fountains',
    16 => 'Water Chillers',
    17 => 'Water Refilling Stations & Retrofit Kits',
  ),
) ?>