<?php return array (
  'SubcategoryID' => 3106,
  'SubcategoryName' => 'MTLightingElectrical',
  'PropertyName' => 'MTLightingType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Accessory Lights',
    1 => 'Bulbs',
    2 => 'Cigarette Lighters & Power Ports',
    3 => 'Dash Lighting',
    4 => 'Dual Sport Kits',
    5 => 'Electrical Parts & Accessories',
    6 => 'Flasher Units',
    7 => 'Fuses & Connectors',
    8 => 'Headlights',
    9 => 'Horns',
    10 => 'Lenses',
    11 => 'Light Kits',
    12 => 'Rectifiers & Regulators',
    13 => 'Switches',
    14 => 'Tail Lights',
    15 => 'Turn Signals',
    16 => 'Wire & Tubing',
    17 => 'Wiring Harnesses',
  ),
) ?>