<?php return array (
  'SubcategoryID' => 389,
  'SubcategoryName' => 'DigitalCameraFlashes',
  'PropertyName' => 'DCFlashBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Bescor',
    1 => 'Bower',
    2 => 'Canon',
    3 => 'FUJIFILM',
    4 => 'INSTEN',
    5 => 'Joby',
    6 => 'Kodak',
    7 => 'KONICA MINOLTA',
    8 => 'Lightscoop',
    9 => 'Litepanels',
    10 => 'Nikon',
    11 => 'OLYMPUS',
    12 => 'Panasonic',
    13 => 'PENTAX',
    14 => 'Polaroid',
    15 => 'Samsung',
    16 => 'SIGMA',
    17 => 'SONY',
    18 => 'SUNPAK',
    19 => 'Vivitar',
    20 => 'ZEIKOS',
  ),
) ?>