<?php return array (
  'SubcategoryID' => 2562,
  'SubcategoryName' => 'SGLightingHeatingPower',
  'PropertyName' => 'SGLightingColor',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Army Green',
    1 => 'As Shown',
    2 => 'Beige',
    3 => 'Black',
    4 => 'Black Body Red Glow Stick',
    5 => 'Black White',
    6 => 'Blue',
    7 => 'Brown',
    8 => 'Burgundy',
    9 => 'Charcoal',
    10 => 'Clear',
    11 => 'Coral',
    12 => 'Dark Blue',
    13 => 'Dark Green',
    14 => 'Disc O',
    15 => 'Gold',
    16 => 'Green',
    17 => 'Grey',
    18 => 'Ivory',
    19 => 'Khaki',
    20 => 'Light Blue',
    21 => 'Light Green',
    22 => 'Metallic',
    23 => 'Multi-Color',
    24 => 'Olive',
    25 => 'Orange',
    26 => 'Pink',
    27 => 'Platinum',
    28 => 'Purple',
    29 => 'Red',
    30 => 'Silver',
    31 => 'Smoke',
    32 => 'Teal',
    33 => 'White',
    34 => 'Yellow',
  ),
) ?>