<?php return array (
  'SubcategoryID' => 2576,
  'SubcategoryName' => 'SGHuntingKnivesTools',
  'PropertyName' => 'SGKnivesType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Accessories',
    1 => 'Axes',
    2 => 'Bowie Knives and Daggers',
    3 => 'Camping Knife',
    4 => 'Collector\'s Knives',
    5 => 'Combat Knife',
    6 => 'Cutting Knife',
    7 => 'Diving Knives & Shears',
    8 => 'Fillet Knives',
    9 => 'Fixed Blade Knives',
    10 => 'Folding Knives',
    11 => 'Hunting',
    12 => 'Hunting Knives',
    13 => 'Machete',
    14 => 'Multitools',
    15 => 'Pocket Knives',
    16 => 'Saws',
    17 => 'Skinning Knife',
    18 => 'Sping-Assisted Knives',
    19 => 'Survival',
    20 => 'Swords',
    21 => 'Tactical Knives',
  ),
) ?>