<?php return array (
  'SubcategoryID' => 499,
  'SubcategoryName' => 'PortableAudio',
  'PropertyName' => 'PortableAudioColor',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '2-Tone',
    1 => 'Black',
    2 => 'Blue',
    3 => 'Brown',
    4 => 'Gold',
    5 => 'Gray',
    6 => 'Green',
    7 => 'Lavender',
    8 => 'Lime',
    9 => 'Multi',
    10 => 'Orange',
    11 => 'Pink',
    12 => 'Purple',
    13 => 'Red',
    14 => 'Silver',
    15 => 'Wheat',
    16 => 'White',
    17 => 'Yellow',
  ),
) ?>