<?php return array (
  'SubcategoryID' => 3242,
  'SubcategoryName' => 'ECPassiveComponents',
  'PropertyName' => 'ECApplication',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Audio',
    1 => 'Automotive',
    2 => 'Broadcast',
    3 => 'Energy',
    4 => 'Harsh Environment',
    5 => 'Home & Garden',
    6 => 'Home Appliances',
    7 => 'Home Automation',
    8 => 'Home Entertainment',
    9 => 'Industrial Automation',
    10 => 'Lighting',
    11 => 'Low Power',
    12 => 'Medical',
    13 => 'MEMS Technology',
    14 => 'Mobile Electronics',
    15 => 'PC Peripherals',
    16 => 'Power Supplies',
    17 => 'Robotics',
    18 => 'Sensing',
    19 => 'Smart Grid',
    20 => 'Solar',
    21 => 'Test & Measure',
    22 => 'Touch',
    23 => 'USB 3.0',
    24 => 'Weather',
    25 => 'Wireless',
    26 => 'Wireless Mesh Networking',
  ),
) ?>