<?php return array (
  'SubcategoryID' => 31,
  'SubcategoryName' => 'NetworkWirelessAdapters',
  'PropertyName' => 'WLInterface',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '16-bit PCMCIA V2.1',
    1 => '32-bit Cardbus',
    2 => '32bit PCI',
    3 => '32bit PCI 2.1',
    4 => '32bit PCI2.2',
    5 => 'CompactFlash Card',
    6 => 'Ethernet Port',
    7 => 'ExpressCard',
    8 => 'Mini Card',
    9 => 'Mini PCI',
    10 => 'Mini PCI Express',
    11 => 'PCI',
    12 => 'PCI Express',
    13 => 'PCIe Half Mini Card / M.2 (NGFF)',
    14 => 'RJ-45',
    15 => 'SDIO',
    16 => 'USB 1.0',
    17 => 'USB 1.1',
    18 => 'USB 2.0',
    19 => 'USB 3.0',
  ),
) ?>