<?php return array (
  'SubcategoryID' => 68,
  'SubcategoryName' => 'MemoryFlashMemory',
  'PropertyName' => 'FLMType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'ATA Flash',
    1 => 'CFast',
    2 => 'Compact Flash (CF)',
    3 => 'Flash Memory',
    4 => 'IDE Flash Module (40Pin Vertical)',
    5 => 'IDE Flash Module (44Pin Horizontal)',
    6 => 'IDE Flash Module (44Pin Vertical)',
    7 => 'Memory Card',
    8 => 'Memory Stick (MS)',
    9 => 'Memory Stick Duo (MS Duo)',
    10 => 'Memory Stick Micro (M2)',
    11 => 'Memory Stick Pro (MS Pro)',
    12 => 'Memory Stick Pro Duo (MS Pro Duo)',
    13 => 'Memory Stick PRO-HG Duo',
    14 => 'Memory Stick PRO-HG Duo HX',
    15 => 'MicroSD',
    16 => 'microSDHC',
    17 => 'microSDXC',
    18 => 'Mini SDHC',
    19 => 'MiniSD',
    20 => 'MultiMedia (MMC plus) Plus',
    21 => 'MultiMedia (MMC)',
    22 => 'MultiMedia Micro (MMC micro)',
    23 => 'MultiMedia Mobile (MMC mobile)',
    24 => 'P2 Card',
    25 => 'PC Card',
    26 => 'Reduced Size MultiMedia (RSMMC)',
    27 => 'SD DUO (SD + USB)',
    28 => 'SD Plus USB',
    29 => 'SDHC Plus USB',
    30 => 'Secure Digital (SD)',
    31 => 'Secure Digital Extended Capacity (SDXC)',
    32 => 'Secure Digital High-Capacity (SDHC)',
    33 => 'Wireless Flash Memory',
    34 => 'xD-Picture',
    35 => 'XQD',
  ),
) ?>