<?php return array (
  'SubcategoryID' => 68,
  'SubcategoryName' => 'MemoryFlashMemory',
  'PropertyName' => 'GroupFLMSeries',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Elite',
    1 => 'Elite Performance',
    2 => 'Elite-X',
    3 => 'Endurance',
    4 => 'Evo',
    5 => 'Extreme',
    6 => 'Extreme Pro',
    7 => 'High Performance',
    8 => 'N/A',
    9 => 'Nitro',
    10 => 'Nitro Plus',
    11 => 'Premier',
    12 => 'Pro',
    13 => 'PRO Elite',
    14 => 'Superior Pro',
    15 => 'Turbo Performance',
    16 => 'Ultra',
  ),
) ?>