<?php return array (
  'SubcategoryID' => 598,
  'SubcategoryName' => 'BluRayDrives',
  'PropertyName' => 'BRODDBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'ASUS',
    1 => 'BUSlink',
    2 => 'CyberpowerPC',
    3 => 'Generic',
    4 => 'HP',
    5 => 'I/OMagic',
    6 => 'LaCie',
    7 => 'LG',
    8 => 'LITE-ON',
    9 => 'PHILIPS',
    10 => 'Pioneer',
    11 => 'PLEXTOR',
    12 => 'PRIMERA',
    13 => 'SAMSUNG',
    14 => 'SilverStone',
    15 => 'SONY',
    16 => 'Sony Optiarc',
    17 => 'Velocity Micro',
  ),
) ?>