<?php return array (
  'SubcategoryID' => 2164,
  'SubcategoryName' => 'BeautyMakeupToolsAccessories',
  'PropertyName' => 'BeautyMakeupAccType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Blush & Bronzing Brushes',
    1 => 'Brow Brushes',
    2 => 'Brush Cleaners',
    3 => 'Brush Sets',
    4 => 'Concealer Brushes',
    5 => 'Eyelash Curlers',
    6 => 'Eyeshdow & Liner Brushes',
    7 => 'Face Tape',
    8 => 'Foundation Brushes',
    9 => 'Lash Tools',
    10 => 'Lip Brushes',
    11 => 'Mirrors',
    12 => 'Powder Brushes',
    13 => 'Refillable Compacts',
    14 => 'Shadow Shields',
    15 => 'Sharpeners',
    16 => 'Sponges & Puffs',
    17 => 'Tweezers & Scissors',
  ),
) ?>