<?php return array (
  'SubcategoryID' => 3378,
  'SubcategoryName' => 'CircuitBreakersLineProtection',
  'PropertyName' => 'CircuitBreakerType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 1,
  'PropertyValueList' => 
  array (
    0 => 'Bus Plugs',
    1 => 'Busway',
    2 => 'Busway Accessories',
    3 => 'Circuit Breaker Accessories',
    4 => 'Circuit Breaker Enclosures',
    5 => 'Circuit Breakers',
    6 => 'Circuit Protectors',
    7 => 'Hardwire Surge Protection Devices',
    8 => 'Hardwired Line Conditioners',
    9 => 'Industrial UPS & Surge Supression Device Accessori',
    10 => 'Industrial UPS Batteries',
    11 => 'Industrial UPS Systems',
    12 => 'Line Isolation Monitor Components',
    13 => 'Line Isolation Monitors',
    14 => 'Line Reactors',
    15 => 'Portable Line Conditioners',
    16 => 'Power Conditions',
    17 => 'Voltage Regulation',
  ),
) ?>