<?php return array (
  'SubcategoryID' => 2847,
  'SubcategoryName' => 'HIWallSconces',
  'PropertyName' => 'HIWallSconcesFeatures',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 1,
  'PropertyValueList' => 
  array (
    0 => '3 Way',
    1 => 'ADA Compliant',
    2 => 'Ambient Lighting',
    3 => 'Battery Operated',
    4 => 'Country French',
    5 => 'Damp Location',
    6 => 'Dimmable',
    7 => 'Down Lighting',
    8 => 'Dry Location',
    9 => 'Dusk-to-Dawn',
    10 => 'Eco-Friendly',
    11 => 'Energy Saver / Energy Efficient',
    12 => 'Fluorescent',
    13 => 'Indoor',
    14 => 'Innovative',
    15 => 'Interconnected',
    16 => 'LED',
    17 => 'Motion Sensor',
    18 => 'Photo Sensor',
    19 => 'Remote Control',
    20 => 'Solar',
    21 => 'Touch On/Off',
    22 => 'Up Lighting',
    23 => 'Wet location',
  ),
) ?>