<?php return array (
  'SubcategoryID' => 2847,
  'SubcategoryName' => 'HIWallSconces',
  'PropertyName' => 'HIWallSconcesMaterial',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Acrylic',
    1 => 'Alabaster',
    2 => 'Bamboo',
    3 => 'Beaded',
    4 => 'Ceramic',
    5 => 'Crystal',
    6 => 'Etched Glass',
    7 => 'Fabric',
    8 => 'Faux Leather',
    9 => 'Fossil Stone',
    10 => 'Glass',
    11 => 'Iron',
    12 => 'Leather',
    13 => 'Linen',
    14 => 'Metal',
    15 => 'Metal, Fabric',
    16 => 'Metal, Glass',
    17 => 'Metal, Glass, Crystal',
    18 => 'Metal, Glass, Resin',
    19 => 'Metal, Rattan',
    20 => 'Mica',
    21 => 'Mosaic',
    22 => 'Paper',
    23 => 'Rattan',
    24 => 'Reclaimed Wood',
    25 => 'Resin',
    26 => 'Silk',
    27 => 'Slate',
    28 => 'Steel',
    29 => 'Stone',
    30 => 'Tiffany Glass',
    31 => 'Wicker',
    32 => 'Wood',
  ),
) ?>