<?php return array (
  'SubcategoryID' => 2847,
  'SubcategoryName' => 'HIWallSconces',
  'PropertyName' => 'HIWallSconcesStyle',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 1,
  'PropertyValueList' => 
  array (
    0 => 'Art Deco',
    1 => 'Art Nouveau',
    2 => 'Arts-n-Crafts',
    3 => 'Asian',
    4 => 'Childrens',
    5 => 'Coastal',
    6 => 'Colonial',
    7 => 'Contemporary',
    8 => 'Cottage',
    9 => 'Country',
    10 => 'Country French',
    11 => 'Craftsman',
    12 => 'Crystal',
    13 => 'Industrial',
    14 => 'Lodge',
    15 => 'Mid Century',
    16 => 'Mission',
    17 => 'Modern',
    18 => 'Moroccan',
    19 => 'Nautical',
    20 => 'Novelty',
    21 => 'Old World',
    22 => 'Retro',
    23 => 'Rustic',
    24 => 'Shaker',
    25 => 'Southwestern',
    26 => 'Spanish Colonial',
    27 => 'Sports',
    28 => 'Tiffany',
    29 => 'Traditional',
    30 => 'Transitional',
    31 => 'Tropical',
    32 => 'Tuscan',
    33 => 'Victorian',
    34 => 'Vintage',
  ),
) ?>