<?php return array (
  'SubcategoryID' => 388,
  'SubcategoryName' => 'DigitalCameraLenses',
  'PropertyName' => 'DCLensesType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Cap & Hood',
    1 => 'Close-up',
    2 => 'Converters & Adapters',
    3 => 'Filters',
    4 => 'Fixed Length Lens',
    5 => 'Lenses Accessories',
    6 => 'Long Zoom',
    7 => 'Macro Extension Tube',
    8 => 'Macro Lens',
    9 => 'Medium Telephoto',
    10 => 'Standard & Medium Telephoto Lens',
    11 => 'Super Telephoto Lens',
    12 => 'Super Telephoto Zoom',
    13 => 'Telephoto Lens',
    14 => 'Telephoto Zoom Lens',
    15 => 'Tilt-Shift Lens',
    16 => 'Ultra Wide Angle',
    17 => 'Ultra Wide Angle Zoom',
    18 => 'Wide Angle Lens',
    19 => 'Wide Angle Zoom',
    20 => 'Wide Lens',
    21 => 'Zoom Lens',
  ),
) ?>