<?php return array (
  'SubcategoryID' => 388,
  'SubcategoryName' => 'DigitalCameraLenses',
  'PropertyName' => 'DCLensesCameraMount',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Canon EF',
    1 => 'Canon EF-M',
    2 => 'Canon EF-S',
    3 => 'Four Thirds',
    4 => 'Fujifilm X mount',
    5 => 'Micro Four Thirds',
    6 => 'Nikon 1',
    7 => 'Nikon AF',
    8 => 'Nikon F',
    9 => 'Pentax K',
    10 => 'PENTAX KAF',
    11 => 'PENTAX KAF2',
    12 => 'PENTAX KAF3',
    13 => 'Pentax Q',
    14 => 'Samsung NX',
    15 => 'Samsung NX Mount',
    16 => 'Sony',
    17 => 'Sony (E mount for NEX)',
    18 => 'Sony Alpha, Minolta AF',
    19 => 'Sony E (Full-Frame)',
  ),
) ?>