<?php return array (
  'SubcategoryID' => 133,
  'SubcategoryName' => 'ToolsNetworkPCServiceAcc',
  'PropertyName' => 'GroupNTWRKPCTOOLSOption',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'CIQ-100 Network Cable Tester',
    1 => 'CIQ-FTKSFP',
    2 => 'CIQ-KIT',
    3 => 'CIQ-KRQ',
    4 => 'Copper & Fiber Tester',
    5 => 'Copper & Fiber Tester with Tone Probe',
    6 => 'Copper Tester',
    7 => 'IntelliTone Pro200 Probe',
    8 => 'IntelliTone Pro200 Toner',
    9 => 'IntelliTone Pro200 Toner & Probe Kit',
    10 => 'LinkRunner AT & SimpliFiber Test Kit',
    11 => 'LinkRunner Holster',
    12 => 'Mat',
    13 => 'N/A',
    14 => 'Pro3000 Probe',
    15 => 'Pro3000 Tone & Probe Kit',
    16 => 'Wrist Strap',
  ),
) ?>