<?php return array (
  'SubcategoryID' => 3388,
  'SubcategoryName' => 'HVACControls',
  'PropertyName' => 'HVACControlType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Building Management Systems',
    1 => 'Combustion',
    2 => 'Draft Controls',
    3 => 'Draft Inducers',
    4 => 'Fan Controls',
    5 => 'Gas Ignition & Pilots',
    6 => 'Gas Regulators',
    7 => 'Heating Valves',
    8 => 'HVAC Controls',
    9 => 'Pressure Controls & Switches',
    10 => 'Relays',
    11 => 'Sensors',
    12 => 'Temperature Controllers',
    13 => 'Thermocouples & Thermopiles',
    14 => 'Thermostats',
    15 => 'Venting',
    16 => 'Venting Dampers',
    17 => 'Water Flow',
    18 => 'Water Heating',
    19 => 'Zoning Controls',
  ),
) ?>