<?php return array (
  'SubcategoryID' => 3185,
  'SubcategoryName' => 'HLCupSaucerSets',
  'PropertyName' => 'HLKitchenBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'American Weigh',
    1 => 'Anchor Hocking',
    2 => 'ATE',
    3 => 'BonJour',
    4 => 'Carteret',
    5 => 'Chef Buddy',
    6 => 'ChefVentions',
    7 => 'Cuisinart',
    8 => 'Drop',
    9 => 'Escali',
    10 => 'Fagor',
    11 => 'Farberware',
    12 => 'Gibson',
    13 => 'Handy Gourmet',
    14 => 'Home Basics',
    15 => 'Houdini',
    16 => 'iHealth',
    17 => 'KooLuLu',
    18 => 'Leaf & Fiber',
    19 => 'Lifetime',
    20 => 'Next Product',
    21 => 'Paula Deen',
    22 => 'Rachael Ray',
    23 => 'Rosewill',
    24 => 'Smart Weigh',
    25 => 'Starfrit',
    26 => 'Taylor',
    27 => 'Vandor',
    28 => 'Zuo Modern',
  ),
) ?>