<?php return array (
  'SubcategoryID' => 3170,
  'SubcategoryName' => 'HLPlates',
  'PropertyName' => 'HLTablewareMaterial',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Bamboo',
    1 => 'Bone China',
    2 => 'Brass',
    3 => 'Carbon Steel',
    4 => 'Ceramic',
    5 => 'Clay',
    6 => 'Crystal',
    7 => 'Earthenware',
    8 => 'Faux Leather',
    9 => 'Glass',
    10 => 'Gold-Plated',
    11 => 'Iron',
    12 => 'Ironstone',
    13 => 'Marble',
    14 => 'Melamine',
    15 => 'Palm Leaf',
    16 => 'Plastic',
    17 => 'Polypropylene',
    18 => 'Porcelain',
    19 => 'Rattan',
    20 => 'Silver-Plated',
    21 => 'Stainless Steel',
    22 => 'Steel',
    23 => 'Sterling Silver',
    24 => 'Stoneware',
    25 => 'Titanium',
    26 => 'Wood',
  ),
) ?>