<?php return array (
  'SubcategoryID' => 390,
  'SubcategoryName' => 'DigitalCameraCases',
  'PropertyName' => 'DCCaseType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Backpack',
    1 => 'Camcorder Case',
    2 => 'Camera Armor',
    3 => 'Camera Case',
    4 => 'Carrying Case',
    5 => 'Flip Cover',
    6 => 'Hard Case',
    7 => 'Holder',
    8 => 'Holster Bag',
    9 => 'Jacket',
    10 => 'Lens Case',
    11 => 'Memory Wallet',
    12 => 'Messenger',
    13 => 'Notebook Case',
    14 => 'Point & Shoot',
    15 => 'Pouch',
    16 => 'Raincover',
    17 => 'Rolling Case',
    18 => 'Screen Protector',
    19 => 'Shoulder Bag',
    20 => 'Shoulder Gear',
    21 => 'Silicon Skin',
    22 => 'Sling Bag',
    23 => 'Soft Pouch',
    24 => 'Strap',
    25 => 'Transport Case',
    26 => 'Tripod Bag',
    27 => 'Underwater Case',
    28 => 'Waterproof',
    29 => 'Wrapping Cloth',
    30 => 'Zoom Bag',
  ),
) ?>