<?php return array (
  'SubcategoryID' => 390,
  'SubcategoryName' => 'DigitalCameraCases',
  'PropertyName' => 'DCCaseSeries',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '160 Series',
    1 => '200 Series',
    2 => 'Adventura',
    3 => 'Barcelona Series',
    4 => 'Bora Series',
    5 => 'Borneo Series',
    6 => 'Classified',
    7 => 'CompuDaypack',
    8 => 'Corato Series',
    9 => 'Crest Series',
    10 => 'Digital Series',
    11 => 'Dominator Series',
    12 => 'Duo Series',
    13 => 'Easy Series',
    14 => 'Fastpack Series',
    15 => 'Gear D-Series',
    16 => 'Hawaii Series',
    17 => 'Melbourne',
    18 => 'Navi',
    19 => 'Oregon Series',
    20 => 'Pampas Series',
    21 => 'Peking Series',
    22 => 'Porto Series',
    23 => 'Pro Series',
    24 => 'Quito Series',
    25 => 'Rezo',
    26 => 'Ridge',
    27 => 'S Series',
    28 => 'Sausalito',
    29 => 'Supreme Series',
    30 => 'UP-Rise Series',
    31 => 'VGP Series',
    32 => 'WB Series',
  ),
) ?>