<?php return array (
  'SubcategoryID' => 378,
  'SubcategoryName' => 'BinocularsTelescopes',
  'PropertyName' => 'BinocularsColor',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Beige',
    1 => 'Black',
    2 => 'Black Matte',
    3 => 'Black/Blue',
    4 => 'Blue',
    5 => 'Brown',
    6 => 'Burgundy',
    7 => 'Camo',
    8 => 'Camouflage',
    9 => 'Clear',
    10 => 'Coral',
    11 => 'Dark Blue',
    12 => 'Dark Green',
    13 => 'Gold',
    14 => 'Green',
    15 => 'Grey',
    16 => 'Hammertone',
    17 => 'Ivory',
    18 => 'Khaki',
    19 => 'Light Blue',
    20 => 'Light Green',
    21 => 'Metallic',
    22 => 'Multi',
    23 => 'Multi-Color',
    24 => 'Orange',
    25 => 'Orange Camo',
    26 => 'Pink',
    27 => 'Pink Camo',
    28 => 'Platinum',
    29 => 'Purple',
    30 => 'Red',
    31 => 'Silver',
    32 => 'Silver/Black',
    33 => 'Teal',
    34 => 'White',
    35 => 'Yellow',
  ),
) ?>