<?php return array (
  'SubcategoryID' => 670,
  'SubcategoryName' => 'Cutlery',
  'PropertyName' => 'CutleryType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 1,
  'PropertyValueList' => 
  array (
    0 => 'Bagel Knives',
    1 => 'Boning Knives',
    2 => 'Bread Knives',
    3 => 'Butcher Knives',
    4 => 'Carving Forks',
    5 => 'Carving Knives',
    6 => 'Carving Sets',
    7 => 'Cheese Knives',
    8 => 'Chefs Knives',
    9 => 'Cleavers',
    10 => 'Cutlery Accessories',
    11 => 'Cutlery Sets',
    12 => 'Electric Knives',
    13 => 'Fillet Knives',
    14 => 'Flatware',
    15 => 'Fruit & Citrus Knives',
    16 => 'Kitchen Shears & Scissors',
    17 => 'Knife Blocks & Storage',
    18 => 'Knife Sharpeners',
    19 => 'Paring Knives',
    20 => 'Peeling Knives',
    21 => 'Santoku Knives',
    22 => 'Sharpening Steels',
    23 => 'Slicing Knives',
    24 => 'Specialty Cutlery',
    25 => 'Steak Knives',
    26 => 'Tomato Knives',
    27 => 'Utility Knives',
    28 => 'Vegetable Knives',
  ),
) ?>