<?php return array (
  'SubcategoryID' => 69,
  'SubcategoryName' => 'CardReaderAdapter',
  'PropertyName' => 'CardReaderInterface',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Compact Flash',
    1 => 'eSATA',
    2 => 'ExpressCard slot',
    3 => 'for OTG micro USB',
    4 => 'for OTG micro USB (cable)',
    5 => 'IEEE 1394',
    6 => 'IEEE 1394 & USB 2.0',
    7 => 'Micro USB (OTG)',
    8 => 'Micro USB (OTG) (Cable)',
    9 => 'Micro USB (OTG)Multi-Card',
    10 => 'Micro USB / USB OTG',
    11 => 'PCI',
    12 => 'PCI-Express',
    13 => 'PCMCIA',
    14 => 'PCMCIA & USB',
    15 => 'Proprietary Interface',
    16 => 'SMC / SM',
    17 => 'USB & eSATA',
    18 => 'USB & eSATA & Audio',
    19 => 'USB & SATA',
    20 => 'USB 1.1',
    21 => 'USB 2.0',
    22 => 'USB 3.0',
    23 => 'USB 3.0 (Fast Charge)',
    24 => 'USB 3.0 (Ultra-Portable)',
    25 => 'USB 3.0 (USB-C; USB-A)',
    26 => 'USB 3.0 classic',
    27 => 'USB 3.0 w/cable',
    28 => 'USB 3.0 w/Hub & Charge',
    29 => 'USB 3.0 with UHS II',
    30 => 'USB 3.1',
    31 => 'USB-C / USB-A',
  ),
) ?>