<?php return array (
  'SubcategoryID' => 1560,
  'SubcategoryName' => 'Bags',
  'PropertyName' => 'BagsColorMapping',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Beige',
    1 => 'Black',
    2 => 'Blue',
    3 => 'Brown',
    4 => 'Burgundy',
    5 => 'Gold',
    6 => 'Green',
    7 => 'Grey',
    8 => 'Khaki',
    9 => 'Multi-Color',
    10 => 'Orange',
    11 => 'Pink',
    12 => 'Purple',
    13 => 'Red',
    14 => 'Silver',
    15 => 'White',
    16 => 'Yellow',
  ),
) ?>