<?php return array (
  'SubcategoryID' => 1560,
  'SubcategoryName' => 'Bags',
  'PropertyName' => 'BagsBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '3M',
    1 => 'Acid',
    2 => 'AfterGen',
    3 => 'Antec',
    4 => 'BeSafe',
    5 => 'Built NY',
    6 => 'Case Logic',
    7 => 'Concept One by USPA Accessories',
    8 => 'Emoji',
    9 => 'Generic',
    10 => 'Goodhope Bags',
    11 => 'Hello Kitty Fab NY',
    12 => 'Hitech',
    13 => 'IGLOO',
    14 => 'JAVOedge',
    15 => 'Loqi',
    16 => 'Lowepro - Wynit',
    17 => 'Macally',
    18 => 'MKF Collection',
    19 => 'Mobile Edge',
    20 => 'OGIO',
    21 => 'Peanuts Snoopy',
    22 => 'Pickleball',
    23 => 'Piel LEATHER',
    24 => 'Pink Platinum',
    25 => 'Samsonite',
    26 => 'SmarterGarter',
    27 => 'SOLO',
    28 => 'SwissGear',
    29 => 'TRAVELERS CHOICE',
    30 => 'TUCANO',
    31 => 'Vandor',
    32 => 'Victorinox',
    33 => 'VISART',
    34 => 'Welcom',
    35 => 'Wenger',
  ),
) ?>