<?php return array (
  'SubcategoryID' => 2795,
  'SubcategoryName' => 'Dehumidifiers',
  'PropertyName' => 'DehumidifierBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Amana',
    1 => 'Amcor',
    2 => 'Arctic King',
    3 => 'Comfort-Aire',
    4 => 'Continental Electrics',
    5 => 'Delonghi',
    6 => 'Ecohouzng',
    7 => 'Excalibur',
    8 => 'Friedrich',
    9 => 'Frigidaire',
    10 => 'Haier',
    11 => 'Hanover',
    12 => 'Hisense',
    13 => 'Honeywell',
    14 => 'Hyundai',
    15 => 'Keystone',
    16 => 'Kool King',
    17 => 'LG',
    18 => 'Midea',
    19 => 'Pursonic',
    20 => 'RCA',
    21 => 'Royal',
    22 => 'SereneLife',
    23 => 'Soleus Air',
    24 => 'Sunpentown',
    25 => 'Winix',
  ),
) ?>