<?php return array (
  'SubcategoryID' => 477,
  'SubcategoryName' => 'GameCubeVideoGames',
  'PropertyName' => 'VGGenre',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Action',
    1 => 'Action / Combat',
    2 => 'Action / Horror',
    3 => 'Action / Shooter',
    4 => 'Action Adventure',
    5 => 'Adventure',
    6 => 'Compilations',
    7 => 'Family & Education',
    8 => 'Fighting',
    9 => 'Flight',
    10 => 'MMORPG',
    11 => 'Music/Rhythm',
    12 => 'Other',
    13 => 'Puzzle',
    14 => 'Racing',
    15 => 'RPG',
    16 => 'RTS',
    17 => 'Shooter',
    18 => 'Simulation',
    19 => 'Sports',
    20 => 'Strategy',
  ),
) ?>