<?php return array (
  'SubcategoryID' => 243,
  'SubcategoryName' => 'XboxAccessories',
  'PropertyName' => 'XBACCBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'C2G',
    1 => 'Conversions Technology',
    2 => 'dreamGEAR',
    3 => 'HIP GEAR',
    4 => 'Innovation',
    5 => 'Insten',
    6 => 'intec',
    7 => 'KMD',
    8 => 'Logitech',
    9 => 'Mad Catz',
    10 => 'Microsoft',
    11 => 'MONSTER',
    12 => 'Naki',
    13 => 'NUBYTECH',
    14 => 'NYKO',
    15 => 'PELICAN',
    16 => 'PLANTRONICS',
    17 => 'POLAROID',
    18 => 'QMOTIONS',
  ),
) ?>