<?php return array (
  'SubcategoryID' => 493,
  'SubcategoryName' => 'CDPlayers',
  'PropertyName' => 'CDPlayerBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'COBY',
    1 => 'Denon',
    2 => 'GEM SOUND',
    3 => 'GPX',
    4 => 'harman/kardon',
    5 => 'Jensen',
    6 => 'JVC',
    7 => 'jWIN',
    8 => 'KENWOOD',
    9 => 'Numark',
    10 => 'ONKYO',
    11 => 'Pioneer',
    12 => 'RCA',
    13 => 'Sherwood',
    14 => 'Sony',
    15 => 'Stanton',
    16 => 'SuperSonic',
    17 => 'TAO',
    18 => 'TEAC',
    19 => 'VocoPro',
    20 => 'YAMAHA',
  ),
) ?>