<?php return array (
  'SubcategoryID' => 3407,
  'SubcategoryName' => 'LightFixturesLampHolders',
  'PropertyName' => 'LightFixtureType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Floodlight Fixtures',
    1 => 'Fluorescent Light Fixtures',
    2 => 'Hazardous Location Lighting Fixtures',
    3 => 'High Abuse Fixtures',
    4 => 'High Bay & Low Bay Light Fixtures',
    5 => 'Indoor HID Fixtures',
    6 => 'Induction',
    7 => 'Lamp Holders & Accessories',
    8 => 'Landscape Lighting Fixtures',
    9 => 'LED Light Fixtures',
    10 => 'Light Bulb Related Products',
    11 => 'Light Fixture Accessories',
    12 => 'Motion Sensing Lighting & Fixtures',
    13 => 'Recessed Lighting & Downlighting Fixtures',
    14 => 'Recycling',
    15 => 'Security/Area Lighting Fixtures',
    16 => 'Track & Recessed Lighting Fixtures',
    17 => 'Wall Pack Light Fixtures',
  ),
) ?>