<?php return array (
  'SubcategoryID' => 2884,
  'SubcategoryName' => 'HICeilingFans',
  'PropertyName' => 'HICeilingFansbladefinish',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Appliance White',
    1 => 'Appliance White / Bleached Oak',
    2 => 'Appliance White / Brushed Steel',
    3 => 'Barbeque Black',
    4 => 'Black',
    5 => 'Brushed Steel',
    6 => 'Brushed Steel / Chocolate',
    7 => 'Cherry',
    8 => 'Chocolate',
    9 => 'Cocoa',
    10 => 'Dark Cherry',
    11 => 'Dark Cherry / Medium Oak',
    12 => 'Dark Mahogany',
    13 => 'Espresso',
    14 => 'Mahogany / Dark Cherry',
    15 => 'Maple',
    16 => 'Medium Cherry/Classic Walnut',
    17 => 'Medium Oak / Walnut',
    18 => 'Midnight Bordeaux',
    19 => 'Oak',
    20 => 'Oil Rubbed Bronze',
    21 => 'Oil Rubbed Bronze / Dark Cherry',
    22 => 'Pecan',
    23 => 'Pine',
    24 => 'Pink',
    25 => 'Silver',
    26 => 'Summer White / Bleached Oak',
    27 => 'Teak',
    28 => 'Toasted Oak',
    29 => 'Walnut',
    30 => 'Walnut / Medium Oak',
    31 => 'White',
    32 => 'White Washed',
  ),
) ?>