<?php return array (
  'SubcategoryID' => 2884,
  'SubcategoryName' => 'HICeilingFans',
  'PropertyName' => 'HICeilingFansCollection',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '5 Minute Fan',
    1 => 'AirPro',
    2 => 'Ashlyn',
    3 => 'Auberville',
    4 => 'Baseball',
    5 => 'Braddock',
    6 => 'Concert Breeze',
    7 => 'Curva',
    8 => 'Curva Sky',
    9 => 'Dreamland',
    10 => 'Highpointe',
    11 => 'Kensington',
    12 => 'Loft',
    13 => 'Low Profile III Plus',
    14 => 'Luxe Eco',
    15 => 'Marquette',
    16 => 'Meeting Street',
    17 => 'Midway Eco',
    18 => 'North Park',
    19 => 'Palermo',
    20 => 'Pro Series',
    21 => 'Pro Series II',
    22 => 'Sea Air',
    23 => 'The Brookline',
    24 => 'Tilo',
    25 => 'Trevina',
    26 => 'Veloce',
    27 => 'Westover Four Seasons',
  ),
) ?>