<?php return array (
  'SubcategoryID' => 577,
  'SubcategoryName' => 'HardDriveCooling',
  'PropertyName' => 'HDDCoolerBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'AeroCool',
    1 => 'Alpha and Omega',
    2 => 'asetek',
    3 => 'BGears',
    4 => 'BUFFALO',
    5 => 'COOLER MASTER',
    6 => 'COOLMAX',
    7 => 'Dynatron',
    8 => 'EVERCOOL',
    9 => 'GENERIC',
    10 => 'JETART',
    11 => 'KingWin',
    12 => 'KOOLANCE',
    13 => 'LOGISYS',
    14 => 'MASSCOOL',
    15 => 'Nexus',
    16 => 'OKGEAR',
    17 => 'PC TOYS',
    18 => 'REVOLTEC',
    19 => 'Rosewill',
    20 => 'SanMax',
    21 => 'Scythe',
    22 => 'SilenX',
    23 => 'SILVERSTONE',
    24 => 'Spire',
    25 => 'StarTech',
    26 => 'SYBA',
    27 => 'Thermaltake',
    28 => 'Titan',
    29 => 'Tuniq',
    30 => 'VANTEC',
    31 => 'VIGOR',
    32 => 'VIZO',
    33 => 'XIGMATEK',
    34 => 'ZALMAN',
  ),
) ?>