<?php return array (
  'SubcategoryID' => 3045,
  'SubcategoryName' => 'PowerAdapters',
  'PropertyName' => 'PowerAdaptersType',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '12 Volts',
    1 => '16 Port AC',
    2 => '16 Port AC (White)',
    3 => '16 Port USB',
    4 => '16 Port USB (Deep)',
    5 => '16 Port USB (White)',
    6 => '32 Port AC',
    7 => '32 Port AC Cart',
    8 => '32 Port AC Cart (White)',
    9 => '32 Port USB',
    10 => '32 Port USB Cart',
    11 => '32 Port USB Cart (White)',
    12 => '48 Port USB',
    13 => '5 Volts',
    14 => '9 Volts',
    15 => 'Lightning Car Charger',
    16 => 'Lightning Wall Charger',
    17 => 'USB Car Charger',
    18 => 'USB Wall Charger',
  ),
) ?>