<?php return array (
  'SubcategoryID' => 2880,
  'SubcategoryName' => 'HLDeskChairs',
  'PropertyName' => 'HIDeskChairstype',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Barrister',
    1 => 'BoomChair',
    2 => 'BoomPod',
    3 => 'Childrens\' Desks',
    4 => 'Computer Desks',
    5 => 'Conference Chair',
    6 => 'Corner',
    7 => 'Drafters Chair',
    8 => 'Ergonomical',
    9 => 'Executive',
    10 => 'L-Shaped Desks',
    11 => 'Lateral File Cabinets',
    12 => 'Mobile File Cabinets',
    13 => 'Office Chair',
    14 => 'Secretary Desks',
    15 => 'Set',
    16 => 'Stackable',
    17 => 'U-Shaped Desks',
    18 => 'Vertical File Cabinets',
    19 => 'Wall Mounted',
    20 => 'Writing Desks',
  ),
) ?>