<?php return array (
  'SubcategoryID' => 796,
  'SubcategoryName' => 'PresentationDevices',
  'PropertyName' => 'PresenterBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '3M',
    1 => 'ARCTIC COOLING',
    2 => 'ATEK',
    3 => 'BenQ',
    4 => 'DELL',
    5 => 'ENCORE',
    6 => 'Enhance',
    7 => 'Epson',
    8 => 'Fujitsu',
    9 => 'GEAR HEAD',
    10 => 'Genius',
    11 => 'GWC',
    12 => 'Gyration',
    13 => 'Honeywell',
    14 => 'iHome',
    15 => 'InFocus',
    16 => 'Innovera',
    17 => 'INTERLINK ELECTRONICS',
    18 => 'IOGEAR',
    19 => 'Kanguru',
    20 => 'Kensington',
    21 => 'KEYSPAN',
    22 => 'Logitech',
    23 => 'Microsoft',
    24 => 'MOBILE EDGE',
    25 => 'Quartet',
    26 => 'SMK-Link',
    27 => 'Targus',
    28 => 'Travitek',
    29 => 'TRENDnet',
    30 => 'Tripp Lite',
    31 => 'V7',
  ),
) ?>