<?php return array (
  'SubcategoryID' => 2572,
  'SubcategoryName' => 'SGFishAttractantsBaits',
  'PropertyName' => 'SGFishingBaitType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Artificial and Prepared Baits',
    1 => 'Attractants and Scents',
    2 => 'Blade Baits',
    3 => 'Buzz Baits',
    4 => 'Crank',
    5 => 'Diving Lures',
    6 => 'Jigs',
    7 => 'Natural Bait',
    8 => 'Plugs',
    9 => 'Poppers and Flies',
    10 => 'Spinners',
    11 => 'Spoons',
    12 => 'Surface Lures',
    13 => 'Traps',
    14 => 'Tube',
  ),
) ?>