<?php return array (
  'SubcategoryID' => 2791,
  'SubcategoryName' => 'MaciPad',
  'PropertyName' => 'NBTech',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '64-bit',
    1 => 'AMD HD Internet Technology',
    2 => 'HT',
    3 => 'Hyper-Threading technology',
    4 => 'Intel Centrino 2 Processor Technology',
    5 => 'Intel Centrino 2 with vPro Technology',
    6 => 'Intel Centrino Duo Mobile Technology',
    7 => 'Intel Centrino Mobile Technology',
    8 => 'Intel Centrino Pro Mobile Technology',
    9 => 'Intel Centrino Processor Technology',
    10 => 'Intel Centrino with vPro Technology',
    11 => 'PowerNow',
    12 => 'Speedstep',
    13 => 'VISION Premium Technology',
    14 => 'VISION Technology',
    15 => 'VISION Ultimate Technology',
  ),
) ?>