<?php return array (
  'SubcategoryID' => 565,
  'SubcategoryName' => 'CellPhonesBluetoothHeadsetsSpeakersAccessories',
  'PropertyName' => 'BTACCTalkTime',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Up to 10 hour(s)',
    1 => 'Up to 100 hour(s)',
    2 => 'Up to 11 hour(s)',
    3 => 'Up to 12 hour(s)',
    4 => 'Up to 13 hour(s)',
    5 => 'Up to 14 hour(s)',
    6 => 'Up to 15 hour(s)',
    7 => 'Up to 16 hour(s)',
    8 => 'Up to 17 hour(s)',
    9 => 'Up to 18 hour(s)',
    10 => 'Up to 2 hour(s)',
    11 => 'Up to 20 hour(s)',
    12 => 'Up to 21 hour(s)',
    13 => 'Up to 24 hour(s)',
    14 => 'Up to 25 hour(s)',
    15 => 'Up to 3 hour(s)',
    16 => 'Up to 3.50 hour(s)',
    17 => 'Up to 30 hour(s)',
    18 => 'Up to 32 hour(s)',
    19 => 'Up to 36 hour(s)',
    20 => 'Up to 4 hour(s)',
    21 => 'Up to 4.50 hour(s)',
    22 => 'Up to 45 hour(s)',
    23 => 'Up to 5 hour(s)',
    24 => 'Up to 5.50 hour(s)',
    25 => 'Up to 6 hour(s)',
    26 => 'Up to 6.50 hour(s)',
    27 => 'Up to 7 hour(s)',
    28 => 'Up to 7.50 hour(s)',
    29 => 'Up to 8 hour(s)',
    30 => 'Up to 9 hour(s)',
  ),
) ?>