<?php return array (
  'SubcategoryID' => 747,
  'SubcategoryName' => 'RoboticVacuums',
  'PropertyName' => 'RoboticVacuumBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'ABC',
    1 => 'Agama',
    2 => 'Ecovacs',
    3 => 'iClebo',
    4 => 'Infinuvo',
    5 => 'iRobot',
    6 => 'METAPO',
    7 => 'Mint',
    8 => 'Moneual',
    9 => 'Neato',
    10 => 'Northwest',
    11 => 'P3 International',
    12 => 'Pursonic',
    13 => 'Robomop',
    14 => 'Rollibot',
    15 => 'RolliTech',
    16 => 'Techko Maid',
    17 => 'Yujin Robot',
  ),
) ?>