<?php return array (
  'SubcategoryID' => 1881,
  'SubcategoryName' => 'OGCuttingEdgingPruning',
  'PropertyName' => 'OGCuttingBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'AMES',
    1 => 'AnySharp',
    2 => 'Barnel',
    3 => 'Black & Decker',
    4 => 'Bond',
    5 => 'Clauss',
    6 => 'Corona',
    7 => 'Dramm',
    8 => 'Easy Gardener',
    9 => 'Fiskars',
    10 => 'Flexrake',
    11 => 'Gilmour',
    12 => 'Hydrofarm',
    13 => 'Tommyco',
    14 => 'WOLF-Garten',
  ),
) ?>