<?php return array (
  'SubcategoryID' => 547,
  'SubcategoryName' => 'PS3Accessories',
  'PropertyName' => 'PS3ACCType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '3D Glasses',
    1 => 'Adapter',
    2 => 'Cable',
    3 => 'Case',
    4 => 'Charge / Battery',
    5 => 'Cleaner',
    6 => 'Controller',
    7 => 'Cooler',
    8 => 'Headset',
    9 => 'Joystick / Wheel / Gun / Dance Pad',
    10 => 'Keyboard',
    11 => 'Membership Card',
    12 => 'Memory Card',
    13 => 'Miscellaneous',
    14 => 'Move accessory',
    15 => 'Network Adapter',
    16 => 'Other',
    17 => 'Sound',
    18 => 'Sports Kit',
    19 => 'Stand',
    20 => 'Starter Kit',
    21 => 'Wired Controller',
    22 => 'Wireless Controller',
  ),
) ?>