<?php return array (
  'SubcategoryID' => 2089,
  'SubcategoryName' => 'HITubShowerParts',
  'PropertyName' => 'HITubShowerPartsType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Apron',
    1 => 'Bath Feet',
    2 => 'Bath Pillow',
    3 => 'Control Kit',
    4 => 'Flange',
    5 => 'Handles',
    6 => 'Installation Kit',
    7 => 'Overflow Plate',
    8 => 'Plug button',
    9 => 'Replacement filter cartridge',
    10 => 'Riser Tubes',
    11 => 'Rough-In Kit',
    12 => 'Shower Arm',
    13 => 'Shower Base',
    14 => 'Shower Diverter Valve',
    15 => 'Shower Hose',
    16 => 'Shower Panel',
    17 => 'Shower Supply Elbows',
    18 => 'Stopper Assembly',
    19 => 'Trim Kit',
    20 => 'Valve Trim',
    21 => 'Waste Plug',
  ),
) ?>