<?php return array (
  'SubcategoryID' => 2089,
  'SubcategoryName' => 'HITubShowerParts',
  'PropertyName' => 'HITubShowerPartsBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Alsons',
    1 => 'American Standard',
    2 => 'Chicago Faucet',
    3 => 'Cifial',
    4 => 'Culligan',
    5 => 'DELTA',
    6 => 'Elizabethan Classics',
    7 => 'FIAT',
    8 => 'Fusion',
    9 => 'Grohe',
    10 => 'Hansgrohe',
    11 => 'Jacuzzi',
    12 => 'KOHLER',
    13 => 'La Toscana',
    14 => 'LDR',
    15 => 'MOEN',
    16 => 'Opella',
    17 => 'Pegasus',
    18 => 'Pfister',
    19 => 'Plumb Craft Waxman',
    20 => 'Pollenex',
    21 => 'Swan',
    22 => 'Symmons',
    23 => 'Westbrass',
    24 => 'Zenith',
  ),
) ?>