<?php return array (
  'SubcategoryID' => 2968,
  'SubcategoryName' => 'SGBoatAnchors',
  'PropertyName' => 'SGAnchorType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Beach Anchors',
    1 => 'Chene Anchors',
    2 => 'Claw Anchors',
    3 => 'CQR Anchors',
    4 => 'Danforth Anchors',
    5 => 'Fluke Anchors',
    6 => 'Fortress Anchors',
    7 => 'Grapnel Anchors',
    8 => 'Grappling Anchors',
    9 => 'Guardian Anchors',
    10 => 'Kedge Anchors',
    11 => 'Manson Racer Anchors',
    12 => 'Mushroom Anchors',
    13 => 'Navy Anchors',
    14 => 'Plow Anchors',
    15 => 'Pyramid Anchors',
    16 => 'Quickset Anchors',
    17 => 'River Anchors',
    18 => 'Rocna Anchors',
    19 => 'Shallow Water Anchors',
    20 => 'Small Craft Anchors',
  ),
) ?>