<?php return array (
  'SubcategoryID' => 2165,
  'SubcategoryName' => 'HLHomeTextilesBedding',
  'PropertyName' => 'HLBeddingType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 1,
  'PropertyValueList' => 
  array (
    0 => 'Air Mattresses',
    1 => 'Bed Skirts and Dust Ruffles',
    2 => 'Bed Spread',
    3 => 'Bedding Accessories',
    4 => 'Bedding Pillows',
    5 => 'Blankets and Throws',
    6 => 'Comforters, Sets and Covers',
    7 => 'Daybed and Futon Bedding',
    8 => 'Decorative & Accent Pillows',
    9 => 'Duvet Covers',
    10 => 'Electric Blankets',
    11 => 'Mattress Pads and Toppers',
    12 => 'Pillow Accessories',
    13 => 'Quilts & Coverlets',
    14 => 'Sheets',
  ),
) ?>