<?php return array (
  'SubcategoryID' => 2165,
  'SubcategoryName' => 'HLHomeTextilesBedding',
  'PropertyName' => 'HLBeddingMaterial',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Bamboo',
    1 => 'Blend',
    2 => 'Canvas',
    3 => 'Cashmere',
    4 => 'Chenille',
    5 => 'Cotton',
    6 => 'Denim',
    7 => 'Elastic/Plastic',
    8 => 'Faux Fur',
    9 => 'Faux Leather',
    10 => 'Felt',
    11 => 'Flannel',
    12 => 'Jacquard',
    13 => 'Jute',
    14 => 'Leather/Suede',
    15 => 'Linen',
    16 => 'Microsuede',
    17 => 'Modal',
    18 => 'Mohair',
    19 => 'Natural/Organic Fleece',
    20 => 'Nylon',
    21 => 'Polyester',
    22 => 'Satin',
    23 => 'Silk',
    24 => 'Synthetic',
    25 => 'Wool',
  ),
) ?>