<?php return array (
  'SubcategoryID' => 2165,
  'SubcategoryName' => 'HLHomeTextilesBedding',
  'PropertyName' => 'HLBeddingStyle',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Americana',
    1 => 'Animal and Jungle',
    2 => 'Art Deco',
    3 => 'Arts-n-Crafts',
    4 => 'Asian',
    5 => 'Casual',
    6 => 'Coastal',
    7 => 'Contemporary',
    8 => 'Cottage',
    9 => 'Country',
    10 => 'Country French',
    11 => 'European',
    12 => 'Frameless',
    13 => 'Holiday / Seasonal',
    14 => 'Industrial',
    15 => 'Kids / Juvenile',
    16 => 'Lodge',
    17 => 'Mid Century',
    18 => 'Mission',
    19 => 'Moroccan',
    20 => 'Nautical',
    21 => 'Novelty',
    22 => 'Oriental and Middle Eastern',
    23 => 'Retro',
    24 => 'Rustic',
    25 => 'Shaker',
    26 => 'Southwest',
    27 => 'Spanish Colonial',
    28 => 'Sports',
    29 => 'Tiffany',
    30 => 'Traditional',
    31 => 'Transitional',
    32 => 'Tropical',
    33 => 'Tuscan',
  ),
) ?>