<?php return array (
  'SubcategoryID' => 2165,
  'SubcategoryName' => 'HLHomeTextilesBedding',
  'PropertyName' => 'HLBeddingColorMapping',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 1,
  'PropertyValueList' => 
  array (
    0 => 'Beige',
    1 => 'Black',
    2 => 'Blue',
    3 => 'Brown',
    4 => 'Cream',
    5 => 'Gold',
    6 => 'Gray',
    7 => 'Green',
    8 => 'Grey',
    9 => 'Ivory',
    10 => 'Multi',
    11 => 'Multi-Color',
    12 => 'Off-white',
    13 => 'Orange',
    14 => 'Pink',
    15 => 'Purple',
    16 => 'Red',
    17 => 'Silver',
    18 => 'White',
    19 => 'Yellow',
  ),
) ?>