<?php return array (
  'SubcategoryID' => 2165,
  'SubcategoryName' => 'HLHomeTextilesBedding',
  'PropertyName' => 'HLBeddingFilling',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '10/90 down feather',
    1 => '25/75 down feather',
    2 => '5/95 down feather',
    3 => 'Air',
    4 => 'Down',
    5 => 'Down & Feather',
    6 => 'Eco-Fill',
    7 => 'Enviroloft Polyester',
    8 => 'Fiber Fill',
    9 => 'Gel',
    10 => 'Memory Foam',
    11 => 'Organic Fiber',
    12 => 'Polyester/Polyfiber',
    13 => 'PrimaLoft Polyester',
  ),
) ?>