<?php return array (
  'SubcategoryID' => 38,
  'SubcategoryName' => 'PrinterInkjetPrinters',
  'PropertyName' => 'PrinterBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Brother',
    1 => 'Canon',
    2 => 'Canon Canada',
    3 => 'Dell',
    4 => 'EPSON',
    5 => 'Fujifilm',
    6 => 'Fujitsu',
    7 => 'G7 Productivity Systems',
    8 => 'HI TOUCH',
    9 => 'HiTi',
    10 => 'HP',
    11 => 'Kodak',
    12 => 'KONICA MINOLTA',
    13 => 'LEXMARK',
    14 => 'LG',
    15 => 'OKIDATA',
    16 => 'OLYMPUS',
    17 => 'Panasonic',
    18 => 'Penpower',
    19 => 'PENTAX',
    20 => 'PLANon',
    21 => 'Polaroid',
    22 => 'PRIMERA',
    23 => 'RICOH',
    24 => 'SAMSUNG',
    25 => 'Seiko',
    26 => 'SHARP',
    27 => 'SONY',
    28 => 'Troy',
    29 => 'VINPOWER',
    30 => 'VuPoint',
    31 => 'VuPoint Solutions',
    32 => 'XEROX',
  ),
) ?>