<?php return array (
  'SubcategoryID' => 3083,
  'SubcategoryName' => 'PS4Systems',
  'PropertyName' => 'GroupPS4Option',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Batman Bundle',
    1 => 'Batman: Arkham Knight PS4 Console Bundle',
    2 => 'Call of Duty 500GB Bundle',
    3 => 'Call of Duty Bundle',
    4 => 'Destiny Bundle',
    5 => 'Destiny: The Taken King PS4 Console Bundle',
    6 => 'Last of Us PS4 Console Bundle',
    7 => 'NHL 16 PS4 Console Bundle',
    8 => 'PS4 Batman: Arkham Knight Bundle',
    9 => 'PS4 Call of Duty: Black Ops 3 Limited Edition 1TB',
    10 => 'PS4 Destiny: The Taken King Bundle',
    11 => 'PS4 Pro 1TB',
    12 => 'PS4 Slim Uncharted 4 500GB Bundle',
    13 => 'PS4 The Star Wars Battlefront 500GB Bundle',
    14 => 'PS4 Uncharted: The Nathan Drake Collection',
    15 => 'PS4 with Free the Last of Us Remastered Bundle',
    16 => 'Star Wars Bundle',
    17 => 'Uncharted 4 Limited Edition 500GB Bundle',
    18 => 'Uncharted Bundle',
  ),
) ?>