<?php return array (
  'SubcategoryID' => 725,
  'SubcategoryName' => 'WarmingTrays',
  'PropertyName' => 'WarmingTrayBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Aroma',
    1 => 'Continental',
    2 => 'Cuisinart',
    3 => 'Deni',
    4 => 'Elite',
    5 => 'Excalibur Electronics',
    6 => 'MAXI-MATIC',
    7 => 'NOSTALGIA ELECTRICS',
    8 => 'NutriChef',
    9 => 'Oster',
    10 => 'sensio',
    11 => 'Toastess',
    12 => 'Waring Pro',
    13 => 'West Bend',
  ),
) ?>