<?php return array (
  'SubcategoryID' => 2082,
  'SubcategoryName' => 'HIMiscBathHardware',
  'PropertyName' => 'HIMiscBathHardwareBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Alsons',
    1 => 'American Standard',
    2 => 'Baldwin',
    3 => 'Croydex',
    4 => 'Decolav',
    5 => 'Delta',
    6 => 'Focus Electrics',
    7 => 'Franklin Brass',
    8 => 'Fusion',
    9 => 'Gatco',
    10 => 'Grohe',
    11 => 'Hansgrohe',
    12 => 'Home Products International',
    13 => 'Homz',
    14 => 'Hookless',
    15 => 'Jacuzzi',
    16 => 'KOHLER',
    17 => 'La Toscana',
    18 => 'Liberty Hardware',
    19 => 'LOTA',
    20 => 'MOEN',
    21 => 'Pegasus',
    22 => 'Pfister',
    23 => 'Safety First',
    24 => 'Swan',
    25 => 'Zenith',
  ),
) ?>