<?php return array (
  'SubcategoryID' => 2082,
  'SubcategoryName' => 'HIMiscBathHardware',
  'PropertyName' => 'HIMiscBathHardwareType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Arm & Flange',
    1 => 'Bath',
    2 => 'Bath Shelf',
    3 => 'Bath Waste & Overflow',
    4 => 'Cleaners',
    5 => 'Curtain',
    6 => 'Digital Interface',
    7 => 'Faucet Valves',
    8 => 'Grab Bar',
    9 => 'Handshower Holder',
    10 => 'Liners',
    11 => 'Overflow Plate',
    12 => 'Pivot Handle',
    13 => 'Robe Hook',
    14 => 'Safety Seat',
    15 => 'Shower',
    16 => 'Shower Arm',
    17 => 'Shower Curtain Rings/Hooks',
    18 => 'Shower Curtain Rod',
    19 => 'Shower Curtains',
    20 => 'Shower Speaker',
    21 => 'Shower Wall',
    22 => 'Slide Bar',
    23 => 'Splash Guards',
    24 => 'Toilet Bar',
    25 => 'Wood Frame',
  ),
) ?>