<?php return array (
  'SubcategoryID' => 500,
  'SubcategoryName' => 'HomeAudio',
  'PropertyName' => 'HomeAudioBuiltinPlayer',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '1-Disc CD  Changer',
    1 => '1-Disc DVD  Changer',
    2 => '1-Disc VCD  Changer',
    3 => '2-Disc CD Changer',
    4 => '3-Disc CD  Changer',
    5 => '4-Disc CD  Changer',
    6 => '5-Disc CD Changer',
    7 => '5-Disc DVD Changer',
    8 => '6-Disc CD Changer',
    9 => 'Audio Mixer',
    10 => 'Cassette Deck',
    11 => 'CD Player',
    12 => 'CD Player & Audio Mixer',
    13 => 'CD Player & Cassette Deck',
    14 => 'CD Player & Radio',
    15 => 'DVD Changer',
    16 => 'DVD Player & Cassette Deck',
    17 => 'Karaoke System',
    18 => 'Multimedia Player',
    19 => 'others',
    20 => 'Radio',
    21 => 'Turntable',
  ),
) ?>