<?php return array (
  'SubcategoryID' => 46,
  'SubcategoryName' => 'StorageDevicesTapeZIP',
  'PropertyName' => 'TDInterface',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '68-pin Wide Ultra SCSI',
    1 => 'Fibre Channel',
    2 => 'IDE / ATAPI',
    3 => 'IEEE 1394',
    4 => 'SAS',
    5 => 'SATA',
    6 => 'SATA II',
    7 => 'SATA to USB 2.0',
    8 => 'SCSI',
    9 => 'SCSI-2',
    10 => 'Ultra 160 SCSI',
    11 => 'Ultra 320 SCSI',
    12 => 'Ultra2 SCSI LVD',
    13 => 'USB',
    14 => 'USB 2.0',
    15 => 'USB 2.0 / eSATA',
    16 => 'USB 2.0 / IEEE 1394',
    17 => 'USB 3.0',
  ),
) ?>