<?php return array (
  'SubcategoryID' => 95,
  'SubcategoryName' => 'AccessoriesGeneral',
  'PropertyName' => 'GeneralAccColor',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '6in - Screw Mount / 100(Quantity)',
    1 => '6in / 100(Quantity)',
    2 => '6in / 1000(Quantity)',
    3 => '8in - Screw Mount / 100(Quantity)',
    4 => '8in - Screw Mount / 1000(Quantity)',
    5 => 'Black',
    6 => 'Black/Clear',
    7 => 'Blue',
    8 => 'Gray',
    9 => 'Green',
    10 => 'Orange',
    11 => 'Pink',
    12 => 'Purple',
    13 => 'Red',
    14 => 'Silver',
    15 => 'Transparent',
    16 => 'White',
    17 => 'Yellow',
  ),
) ?>