<?php return array (
  'SubcategoryID' => 3438,
  'SubcategoryName' => 'IndustrialBathroomSupplies',
  'PropertyName' => 'BathSuppliesType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 1,
  'PropertyValueList' => 
  array (
    0 => 'Baby Changing Tables',
    1 => 'Bathroom Accessories',
    2 => 'Bathroom Mats',
    3 => 'Bathroom Shelves',
    4 => 'Feminine Hygeine',
    5 => 'Grab Bars',
    6 => 'Hand Dryers',
    7 => 'Hand Sanitizers',
    8 => 'Partitions & Partition Doors',
    9 => 'Portable Restrooms',
    10 => 'Shower Seats',
    11 => 'Soap Dispensers',
    12 => 'Toilet Tissue Dispensers',
    13 => 'Towel Bars & Warmers',
    14 => 'Towel Dispensers',
    15 => 'Washroom Mirrors',
  ),
) ?>