<?php return array (
  'SubcategoryID' => 774,
  'SubcategoryName' => 'DigitalPerformanceEyewear',
  'PropertyName' => 'EyewearColor',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 1,
  'PropertyValueList' => 
  array (
    0 => 'Ash',
    1 => 'Black',
    2 => 'Black Frame/Floral Arms',
    3 => 'Black Frame/Wood Arms',
    4 => 'Brown',
    5 => 'Cloud',
    6 => 'Crimson',
    7 => 'Earth',
    8 => 'Espresso',
    9 => 'Fire',
    10 => 'Frost White',
    11 => 'Graphite',
    12 => 'Grey Tortoise Shell',
    13 => 'Gunmetal',
    14 => 'Ink',
    15 => 'Kryptonite',
    16 => 'Mercury',
    17 => 'Mint',
    18 => 'Onyx',
    19 => 'Onyx Black',
    20 => 'Snow',
    21 => 'Tortoise Frame/Black Arms',
  ),
) ?>