<?php return array (
  'SubcategoryID' => 2860,
  'SubcategoryName' => 'HIOutdoorHangingLights',
  'PropertyName' => 'HIHangingtype',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Adjustable',
    1 => 'ArcLamp',
    2 => 'Banker',
    3 => 'BatteryOperated',
    4 => 'BuffetLamp',
    5 => 'CableFixtures',
    6 => 'Cablesystems',
    7 => 'Clip-on',
    8 => 'DirectionalSpotlights',
    9 => 'FloorLampwithtable',
    10 => 'Hugger',
    11 => 'LampSets',
    12 => 'LightTherapy',
    13 => 'LineVoltage',
    14 => 'LowProfile',
    15 => 'LowVoltage',
    16 => 'Magnifier',
    17 => 'Monorail',
    18 => 'MultiDirectional',
    19 => 'MultiShade',
    20 => 'NewConstruction',
    21 => 'Outdoor',
    22 => 'PharmacyLamp',
    23 => 'Plug-in',
    24 => 'Remodel',
    25 => 'Rope',
    26 => 'SlopeHousing',
    27 => 'SwingArm',
    28 => 'Switch-PullChain',
    29 => 'TaskLamp',
    30 => 'Torchiere',
    31 => 'TrackAccessories',
    32 => 'TrackConnectors',
    33 => 'TrackSystems',
    34 => 'WithLightKit',
    35 => 'WithoutLightKit',
  ),
) ?>