<?php return array (
  'SubcategoryID' => 3173,
  'SubcategoryName' => 'HLServeware',
  'PropertyName' => 'HLServewareType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 1,
  'PropertyValueList' => 
  array (
    0 => 'Beverage Dispensers',
    1 => 'Butter Dishes',
    2 => 'Cake Stands',
    3 => 'Chafing Fuel',
    4 => 'Cheese Plates',
    5 => 'Cocktail Trays/Wine Holder Plates',
    6 => 'Condiment Organizers',
    7 => 'Condiment Sets',
    8 => 'Cream & Sugar Bowl Set',
    9 => 'Creamers',
    10 => 'Cruets',
    11 => 'Dip Trays',
    12 => 'Fruit & Dessert Bowls',
    13 => 'Gravy Boat',
    14 => 'Honey Dippers',
    15 => 'Nut Bowls',
    16 => 'Pickle/Relish Dish',
    17 => 'Pitchers',
    18 => 'Place cards/holders',
    19 => 'Platters',
    20 => 'Punch Bowls',
    21 => 'Serving Bowls',
    22 => 'Serving Pieces & Sets',
    23 => 'Serving Tools',
    24 => 'Spreaders',
    25 => 'Sugar Bowls',
    26 => 'Sushi Serving Plates',
    27 => 'Syrup Dispensers',
    28 => 'Table Ware',
    29 => 'Tiered Serving Trays',
    30 => 'Vegetable Bowl',
    31 => 'Whipped Cream Dispensers',
  ),
) ?>