<?php return array (
  'SubcategoryID' => 997,
  'SubcategoryName' => 'Rings',
  'PropertyName' => 'RingStyle',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '3-Stone',
    1 => 'Baby',
    2 => 'Bands & Sets',
    3 => 'Bezel-Set',
    4 => 'Birthstone & Zodiac',
    5 => 'Bypass',
    6 => 'Channel-Set',
    7 => 'Class',
    8 => 'Cluster',
    9 => 'Cocktail',
    10 => 'Dome',
    11 => 'Eternity',
    12 => 'Fashion',
    13 => 'Invisible-Set',
    14 => 'Matte Finish',
    15 => 'Pave',
    16 => 'Polished Finish',
    17 => 'Promise',
    18 => 'Prong-Set',
    19 => 'Puzzle',
    20 => 'Semi-Mountings',
    21 => 'Signet',
    22 => 'Solitaire',
    23 => 'Stacking',
    24 => 'Toe Rings',
    25 => 'With Side Stones',
    26 => 'Wrap',
  ),
) ?>