<?php return array (
  'SubcategoryID' => 997,
  'SubcategoryName' => 'Rings',
  'PropertyName' => 'RingBandColor',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Black',
    1 => 'Black/Gold/Silver',
    2 => 'Black/Red',
    3 => 'Black/Silver',
    4 => 'Black/White',
    5 => 'Blue',
    6 => 'Brown',
    7 => 'Gold/Silver',
    8 => 'Golden',
    9 => 'Gray',
    10 => 'Platinum',
    11 => 'Purple',
    12 => 'Red',
    13 => 'Rose',
    14 => 'Rose Gold',
    15 => 'Rose Gold/White',
    16 => 'Silver',
    17 => 'Silver/Brown',
    18 => 'Silver/Yellow',
    19 => 'White',
    20 => 'White/Rose',
    21 => 'White/Yellow',
    22 => 'Yellow',
  ),
) ?>