<?php return array (
  'SubcategoryID' => 997,
  'SubcategoryName' => 'Rings',
  'PropertyName' => 'RingOccasion',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Anniversary',
    1 => 'Birthday',
    2 => 'Christmas',
    3 => 'Communion',
    4 => 'Congratulations',
    5 => 'Engagement',
    6 => 'Father\'s Day',
    7 => 'Graduation',
    8 => 'Hanukkah',
    9 => 'Holiday',
    10 => 'Mother\'s Day',
    11 => 'New Baby',
    12 => 'Party',
    13 => 'Prom',
    14 => 'Quinceanera',
    15 => 'Seasonal',
    16 => 'Valentine\'s Day',
    17 => 'Wedding',
  ),
) ?>