<?php return array (
  'SubcategoryID' => 2992,
  'SubcategoryName' => 'SGMarineLighting',
  'PropertyName' => 'SGRLightType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Dock Lights',
    1 => 'Engine Compartment Lights',
    2 => 'Exterior Lighting',
    3 => 'Interior Lighting',
    4 => 'Laser Signaling Lights',
    5 => 'LED Strip Lights',
    6 => 'Navigation Light Pole Mounts & Accessories',
    7 => 'Navigation Light Poles',
    8 => 'Navigation Lights',
    9 => 'PFD Strobe Lights',
    10 => 'Strobe Lights',
    11 => 'Transom Lights',
    12 => 'Underwater Lights',
    13 => 'Utility Lights',
  ),
) ?>