<?php return array (
  'SubcategoryID' => 535,
  'SubcategoryName' => 'SurgeProtectors',
  'PropertyName' => 'SRGELength',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '10 Feet',
    1 => '12 Feet',
    2 => '12 Feet + TEL',
    3 => '15 Feet',
    4 => '15 Feet + TEL',
    5 => '16 Feet',
    6 => '2 Feet',
    7 => '25 Feet',
    8 => '25 Feet (Black)',
    9 => '3 Feet',
    10 => '4 Feet',
    11 => '4 Feet + TEL',
    12 => '5 Feet',
    13 => '6 Feet',
    14 => '6 Feet + TEL',
    15 => '7 Feet',
    16 => '7 Feet (Black)',
    17 => '7 Feet + Coax',
    18 => '7 Feet + TEL',
    19 => '8 Feet',
    20 => '8 Feet + Rotatable Outlets + USB',
    21 => '8 Feet + TEL',
    22 => '8 Feet + USB',
    23 => '9 Feet',
    24 => 'No',
    25 => 'Wall Mount',
  ),
) ?>