<?php return array (
  'SubcategoryID' => 535,
  'SubcategoryName' => 'SurgeProtectors',
  'PropertyName' => 'SRGEColor',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Black',
    1 => 'Black + TEL/Coax',
    2 => 'Black with Desk Clamp & USB',
    3 => 'Black with Rotating Outlets & Coax',
    4 => 'Black with Side Mounted Switch',
    5 => 'Blue',
    6 => 'Charcoal',
    7 => 'Clear White',
    8 => 'Dark Oak',
    9 => 'Gold',
    10 => 'Gray',
    11 => 'Ivory',
    12 => 'Jet Black',
    13 => 'Light Gray',
    14 => 'Light Gray + TEL',
    15 => 'Light Gray with 25 Feet Cord',
    16 => 'Light Natural',
    17 => 'Medium Cherry',
    18 => 'No',
    19 => 'Off White',
    20 => 'Off White with USB',
    21 => 'Pink',
    22 => 'Red',
    23 => 'Silver',
    24 => 'Titanium',
    25 => 'White',
    26 => 'White/Gary',
    27 => 'Yellow',
  ),
) ?>