<?php return array (
  'SubcategoryID' => 570,
  'SubcategoryName' => 'NetworkSwitchModules',
  'PropertyName' => 'SwitchModBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '3Com',
    1 => 'ACP',
    2 => 'Add-On',
    3 => 'Adtran',
    4 => 'Allied Telesis',
    5 => 'Asante',
    6 => 'Brocade',
    7 => 'Cisco',
    8 => 'D-Link',
    9 => 'Enterasys',
    10 => 'Extreme Networks',
    11 => 'HP',
    12 => 'IBM',
    13 => 'Juniper',
    14 => 'LevelOne',
    15 => 'Linksys',
    16 => 'Motorola',
    17 => 'NETGEAR',
    18 => 'SMC LG-ERICSSON',
    19 => 'SonicWall',
    20 => 'SUPERMICRO',
    21 => 'Transition Networks',
    22 => 'TRENDnet',
    23 => 'ZyXEL',
  ),
) ?>