<?php return array (
  'SubcategoryID' => 680,
  'SubcategoryName' => 'FoodProcessors',
  'PropertyName' => 'FoodProcessorGBColor',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Black',
    1 => 'Blue',
    2 => 'Contour Silver',
    3 => 'Empire Red',
    4 => 'Garnet',
    5 => 'Gray',
    6 => 'Green',
    7 => 'Gunmetal',
    8 => 'Navy',
    9 => 'Onyx',
    10 => 'Onyx Black',
    11 => 'Purple',
    12 => 'Red',
    13 => 'Rubberized Black',
    14 => 'Rubberized Blue',
    15 => 'Rubberized Orange',
    16 => 'Rubberized Pink',
    17 => 'Spray Orange',
    18 => 'Spray Pink',
    19 => 'Spray Purple',
    20 => 'Spray Yellow',
    21 => 'Teal',
    22 => 'White',
    23 => 'White and Pink',
    24 => 'White and Purple',
  ),
) ?>