<?php return array (
  'SubcategoryID' => 1042,
  'SubcategoryName' => 'PowerDistributionUnits',
  'PropertyName' => 'PDUBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'APC',
    1 => 'ATEN',
    2 => 'Avocent',
    3 => 'Belkin',
    4 => 'CISCO',
    5 => 'CyberPower',
    6 => 'db Link',
    7 => 'Delta',
    8 => 'Digi',
    9 => 'Dynapower',
    10 => 'Eaton',
    11 => 'EMERSON',
    12 => 'HP',
    13 => 'Huawei',
    14 => 'IBM',
    15 => 'Knurr',
    16 => 'Lantronix',
    17 => 'Lenovo',
    18 => 'Liebert',
    19 => 'Maruson',
    20 => 'MINUTEMAN',
    21 => 'PANDUIT',
    22 => 'Perle',
    23 => 'Powerware',
    24 => 'Raritan',
    25 => 'Server Technology',
    26 => 'SurgeX',
    27 => 'Tripp Lite',
  ),
) ?>