<?php return array (
  'SubcategoryID' => 44,
  'SubcategoryName' => 'ScannerFlatbed',
  'PropertyName' => 'ScannerSeries',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'ArtixScan',
    1 => 'CanoScan',
    2 => 'Digital Sender',
    3 => 'DocketPort',
    4 => 'DocuMate',
    5 => 'DR Series',
    6 => 'Expression Series',
    7 => 'GT Series',
    8 => 'I Series',
    9 => 'imageFORMULA',
    10 => 'OptiCard',
    11 => 'OpticBook',
    12 => 'OpticFilm',
    13 => 'OpticPro',
    14 => 'OpticSlim',
    15 => 'Patriot',
    16 => 'Perfection Series',
    17 => 'S Series',
    18 => 'ScanFront',
    19 => 'Scanjet',
    20 => 'Scanjet Enterprise',
    21 => 'ScanMaker',
    22 => 'ScanSnap',
    23 => 'SmartOffice',
    24 => 'ST Series',
    25 => 'Strobe XP',
    26 => 'TravelScan Pro',
    27 => 'V Series',
    28 => 'WorldCard',
  ),
) ?>