<?php return array (
  'SubcategoryID' => 44,
  'SubcategoryName' => 'ScannerFlatbed',
  'PropertyName' => 'ScannerBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'ADESSO',
    1 => 'Ambir',
    2 => 'AML',
    3 => 'AXIS',
    4 => 'Canon',
    5 => 'CardScan',
    6 => 'Contex',
    7 => 'EPSON',
    8 => 'Fujitsu',
    9 => 'Genius',
    10 => 'HAND HELD',
    11 => 'HP',
    12 => 'I.R.I.S',
    13 => 'iVina',
    14 => 'Kodak',
    15 => 'KONICA MINOLTA',
    16 => 'Metrologic',
    17 => 'Microtek',
    18 => 'Motorola-Symbol',
    19 => 'Mustek',
    20 => 'NEATRECEIPTS',
    21 => 'Nikon',
    22 => 'Panasonic',
    23 => 'Penpower',
    24 => 'PENTAX',
    25 => 'PLANon',
    26 => 'Plustek',
    27 => 'PSC',
    28 => 'RICOH',
    29 => 'SOCKET COMMUNICATIONS',
    30 => 'SYSCAN',
    31 => 'Targus',
    32 => 'UNITECH',
    33 => 'Visioneer',
    34 => 'Wasp',
    35 => 'WIZCOM',
    36 => 'XEROX',
  ),
) ?>