<?php return array (
  'SubcategoryID' => 3222,
  'SubcategoryName' => 'CellphoneNFCHeadsetsandSpeakers',
  'PropertyName' => 'CellphoneACCType',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '**Headset',
    1 => 'Battery',
    2 => 'Bling',
    3 => 'Cable',
    4 => 'Case & Covers',
    5 => 'Cell Phone Speaker',
    6 => 'Charger & Adapter',
    7 => 'Charm',
    8 => 'Cradle & Dock',
    9 => 'Kit',
    10 => 'Lens',
    11 => 'Misc',
    12 => 'Mobile Hotspot Devices',
    13 => 'NFC Headset',
    14 => 'NFC Speaker',
    15 => 'PC Network Card',
    16 => 'Phone Book Kit',
    17 => 'Privacy Filter',
    18 => 'Refill Card',
    19 => 'Signal Booster',
    20 => 'SIM Card',
    21 => 'Splitter',
    22 => 'Stylus',
    23 => 'Wired Headset',
  ),
) ?>