<?php return array (
  'SubcategoryID' => 3030,
  'SubcategoryName' => 'ReceiptPrinters',
  'PropertyName' => 'PrintersCutter',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Auto-Cutter',
    1 => 'Auto-Cutter with spooler',
    2 => 'Cutter',
    3 => 'Cutter w/ Catch Tray',
    4 => 'Dispenser',
    5 => 'Dispenser/Liner Rewinder',
    6 => 'Guillotine',
    7 => 'Internal Rewinder',
    8 => 'Manual',
    9 => 'N/A',
    10 => 'No',
    11 => 'Peel w/ Liner Take-up',
    12 => 'Peeler',
    13 => 'Rewind',
    14 => 'Rewind w/ Peel',
    15 => 'Rotary Cutter',
    16 => 'Tear Bar',
    17 => 'Tear Off',
    18 => 'Tear Off /w Sensor',
    19 => 'Yes',
  ),
) ?>