<?php return array (
  'SubcategoryID' => 3247,
  'SubcategoryName' => 'ECSensorsTransducers',
  'PropertyName' => 'ECSensorMeasurementFunction',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Acceleration',
    1 => 'Audio Sensors',
    2 => 'Capacitive Touch Sensors',
    3 => 'Current',
    4 => 'Encoders',
    5 => 'Environmental',
    6 => 'Fiber Optic',
    7 => 'Flow',
    8 => 'Force & Load Cell',
    9 => 'Linear Displacement',
    10 => 'Liquid Level',
    11 => 'Magnetic',
    12 => 'Motion',
    13 => 'Photo',
    14 => 'Position',
    15 => 'Pressure',
    16 => 'Proximity',
    17 => 'Radiation',
    18 => 'Safety Light Curtains',
    19 => 'Sensor Hardware & Accessories',
    20 => 'Speed',
    21 => 'Temperature',
    22 => 'Tilt',
    23 => 'Ultrasonic',
    24 => 'Vibration & Shock',
  ),
) ?>