<?php return array (
  'SubcategoryID' => 673,
  'SubcategoryName' => 'Blenders',
  'PropertyName' => 'BlenderSpeeds',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '10 speeds',
    1 => '12 speeds',
    2 => '14 speeds',
    3 => '16 speeds',
    4 => '18 speeds',
    5 => '19 speeds',
    6 => '2 speeds',
    7 => '20 speeds',
    8 => '3 speeds',
    9 => '4 speeds',
    10 => '5 speeds',
    11 => '6 speeds',
    12 => '7 speeds',
    13 => '8 speeds',
    14 => '9 speeds',
    15 => 'Mono speed',
  ),
) ?>