<?php return array (
  'SubcategoryID' => 1776,
  'SubcategoryName' => 'BabyClothingAccessories',
  'PropertyName' => 'BabyClothesAccessoriesSize',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '0-3 Months',
    1 => '0-6 Months',
    2 => '12 Months',
    3 => '12-18 Months',
    4 => '18 Months',
    5 => '18-24 Months',
    6 => '2 Toddler',
    7 => '24 Months',
    8 => '3 Toddler',
    9 => '3-6 Months',
    10 => '4 Toddler',
    11 => '6-12 Months',
    12 => '6-9 Months',
    13 => '9-12 Months',
    14 => 'Infant',
    15 => 'Newborn',
    16 => 'One Size',
    17 => 'Preemie',
  ),
) ?>