<?php return array (
  'SubcategoryID' => 2794,
  'SubcategoryName' => 'HLDoorMats',
  'PropertyName' => 'RugsConstruction',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Braided',
    1 => 'Flatweave',
    2 => 'Hand Made',
    3 => 'Hand-Hooked',
    4 => 'Hand-Knotted',
    5 => 'Hand-Loom',
    6 => 'Hand-Tufted',
    7 => 'Hand-Woven',
    8 => 'Machine Woven',
    9 => 'Machine-Made',
    10 => 'Machine-Tufted',
    11 => 'Machine-Woven',
    12 => 'Print',
    13 => 'Printed',
    14 => 'Shag',
    15 => 'Tufted',
    16 => 'Woven',
    17 => 'Woven-Printed',
    18 => 'Woven-Shag',
  ),
) ?>