<?php return array (
  'SubcategoryID' => 2181,
  'SubcategoryName' => 'HLCleaning',
  'PropertyName' => 'HLCleaningType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 1,
  'PropertyValueList' => 
  array (
    0 => 'Bathroom Cleaners',
    1 => 'Brushes',
    2 => 'Carpet Care',
    3 => 'Chimney Brushes',
    4 => 'Cleaning Accessories',
    5 => 'Cleaning Kits',
    6 => 'Cloths and Towels',
    7 => 'Cutting Board Oil',
    8 => 'Degreasers',
    9 => 'Dusting Supplies',
    10 => 'Floor Care',
    11 => 'Laundry Products',
    12 => 'Leather',
    13 => 'Linen Care',
    14 => 'Metal Cleaners',
    15 => 'Mop Head Refill',
    16 => 'Mops and Brooms',
    17 => 'Multi-Purpose Cleaners',
    18 => 'Rubber Cleaning Gloves',
    19 => 'Sanitizers',
    20 => 'Stemware Care',
    21 => 'Stone and Masonry Care',
    22 => 'Window and Glass',
    23 => 'Wood Care',
  ),
) ?>