<?php return array (
  'SubcategoryID' => 2805,
  'SubcategoryName' => 'PSVitaAccessories',
  'PropertyName' => 'PSVITAAccBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Accessory Power',
    1 => 'Ace Elite',
    2 => 'CTA Digital',
    3 => 'DreamGEAR',
    4 => 'HORI',
    5 => 'Hyperkin',
    6 => 'INSTEN',
    7 => 'KMD',
    8 => 'Mad Catz',
    9 => 'Nyko',
    10 => 'PDP',
    11 => 'Power A',
    12 => 'Sony',
    13 => 'Thrustmaster',
    14 => 'Tomee',
  ),
) ?>