<?php return array (
  'SubcategoryID' => 727,
  'SubcategoryName' => 'ProcessorsServer',
  'PropertyName' => 'ServerCPUSeries',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'AMD Opteron 4200 Series',
    1 => 'AMD Opteron 4300 Series',
    2 => 'AMD Opteron 6100 Series',
    3 => 'AMD Opteron 6200 Series',
    4 => 'AMD Opteron 6300 Series',
    5 => 'AMD Opteron 8300 Series',
    6 => 'Celeron',
    7 => 'Core i3',
    8 => 'Intel Xeon E3 Family',
    9 => 'Intel Xeon E5 Family',
    10 => 'Intel Xeon Processor 3000 Sequence',
    11 => 'Intel Xeon Processor 5000 Sequence',
    12 => 'Intel Xeon Processor 7000 Sequence',
    13 => 'Itanium',
    14 => 'Opteron',
    15 => 'Pentium',
    16 => 'Pentium III Xeon',
    17 => 'Xeon',
    18 => 'Xeon DP',
    19 => 'Xeon MP',
    20 => 'Xeon UP',
  ),
) ?>