<?php return array (
  'SubcategoryID' => 741,
  'SubcategoryName' => 'Thermometers',
  'PropertyName' => 'ThermometerBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Acurite',
    1 => 'BebeSound',
    2 => 'BIOS',
    3 => 'Braun',
    4 => 'Elgato',
    5 => 'GNC',
    6 => 'HOMEDICS',
    7 => 'Hunter',
    8 => 'Hunter Fan',
    9 => 'HYUNDAI',
    10 => 'La Crosse',
    11 => 'LUMISCOPE',
    12 => 'MASTERBUILT',
    13 => 'Maverick',
    14 => 'Mother\'s Touch',
    15 => 'Omron',
    16 => 'Oregon Scientific',
    17 => 'P3 International',
    18 => 'Porter Cable',
    19 => 'Proactive Medical',
    20 => 'PYLE',
    21 => 'RadioShack',
    22 => 'Rosewill',
    23 => 'Springfield',
    24 => 'Taylor',
    25 => 'Veridian Healthcare',
    26 => 'VICKS',
  ),
) ?>