<?php return array (
  'SubcategoryID' => 3308,
  'SubcategoryName' => 'OSTape',
  'PropertyName' => 'TapeType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 1,
  'PropertyValueList' => 
  array (
    0 => 'Anti-Slip Tape',
    1 => 'Cloth Tape',
    2 => 'Colored Tape',
    3 => 'Double Sided Tape',
    4 => 'Dry Vinyl Plating Tape',
    5 => 'Duct Tape',
    6 => 'Electrical Tape',
    7 => 'Filament Tape',
    8 => 'Film Tape',
    9 => 'Flagging Tape',
    10 => 'Foam Tape',
    11 => 'Foil Tape',
    12 => 'Invisible Tape',
    13 => 'Masking Tape',
    14 => 'Mounting Tape & Squares',
    15 => 'Packaging Tape & Dispensers',
    16 => 'Tape',
    17 => 'Tape Dispensers',
    18 => 'Transfer Tape',
    19 => 'Transparent Office Tape',
    20 => 'Velcro',
    21 => 'Water Contact Indicator Tape',
  ),
) ?>