<?php return array (
  'SubcategoryID' => 640,
  'SubcategoryName' => 'ExpansionHandsets',
  'PropertyName' => 'CNETHandsetsBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'AT&T',
    1 => 'Bell Phones by Northwestern Bell Phones',
    2 => 'Clarity',
    3 => 'ClearSounds',
    4 => 'COBY',
    5 => 'GE',
    6 => 'Jabra',
    7 => 'MOTOROLA',
    8 => 'OREGON',
    9 => 'Panasonic',
    10 => 'PHILIPS',
    11 => 'Plantronics',
    12 => 'Polycom',
    13 => 'RCA',
    14 => 'SBC',
    15 => 'SIEMENS',
    16 => 'snom',
    17 => 'Swissvoice',
    18 => 'Telex',
    19 => 'Uniden',
    20 => 'Verizon',
    21 => 'Vtech',
  ),
) ?>