<?php return array (
  'SubcategoryID' => 1910,
  'SubcategoryName' => 'HINightLights',
  'PropertyName' => 'HINightLightsBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'AGPtek',
    1 => 'COOPER',
    2 => 'Cyalume',
    3 => 'DBPOWER',
    4 => 'DealKnocks',
    5 => 'DEWALT',
    6 => 'Feit Electric',
    7 => 'GE',
    8 => 'Globe',
    9 => 'GPCT',
    10 => 'Jasco',
    11 => 'M&M',
    12 => 'Northwest',
    13 => 'P3 International',
    14 => 'Sierra Electric',
    15 => 'Sunvalley',
    16 => 'TaoTronics',
    17 => 'TOMOTOP',
    18 => 'TOMTOP',
  ),
) ?>