<?php return array (
  'SubcategoryID' => 3403,
  'SubcategoryName' => 'IndustrialFloorCareMachinesVacuums',
  'PropertyName' => 'IndustrialFloorType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Air Duct Vacuums',
    1 => 'Ash Vacuums',
    2 => 'Backpack Vacuum Cleaners',
    3 => 'Canister Vacuums',
    4 => 'Carpet Extractors',
    5 => 'Critical Area Vacuums',
    6 => 'Dust Collectors',
    7 => 'ESD Vacuums',
    8 => 'Floor Burnishers',
    9 => 'Floor Dryers & Blowers',
    10 => 'Floor Machines',
    11 => 'Handheld Vacuums',
    12 => 'HEPA Vacuums',
    13 => 'Magnetic Floor Sweepers',
    14 => 'Metalworking Coolant Vacuums',
    15 => 'Pneumatic Vacuum Cleaners',
    16 => 'Polishers & Buffers',
    17 => 'Scrubbers',
    18 => 'Steam Cleaners',
    19 => 'Sweeping',
    20 => 'Wide Area Sweepers',
    21 => 'Wide Area Vacuum Cleaners',
  ),
) ?>