<?php return array (
  'SubcategoryID' => 10,
  'SubcategoryName' => 'DesktopPC',
  'PropertyName' => 'DTColors',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Beige',
    1 => 'Black',
    2 => 'Black/Blue',
    3 => 'Black/Red',
    4 => 'Black/Silver',
    5 => 'Blue',
    6 => 'Blue/White',
    7 => 'Bronze',
    8 => 'Brown',
    9 => 'Business Black',
    10 => 'Carbonite',
    11 => 'Champagne',
    12 => 'Chrome',
    13 => 'Dark Gray',
    14 => 'Dark Gray Chrome',
    15 => 'Glossy Black',
    16 => 'Glossy Piano Black',
    17 => 'Graphite',
    18 => 'Gray',
    19 => 'Green',
    20 => 'Gun Metal/Red',
    21 => 'Magnesium Gray',
    22 => 'Modern Black',
    23 => 'Orange',
    24 => 'Piano Black',
    25 => 'Pink',
    26 => 'Purple',
    27 => 'Red',
    28 => 'Silver',
    29 => 'White',
    30 => 'White/Blue',
    31 => 'White/Pink',
    32 => 'Yellow',
  ),
) ?>