<?php return array (
  'SubcategoryID' => 10,
  'SubcategoryName' => 'DesktopPC',
  'PropertyName' => 'GlobalElectricalOutletPlugType',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Amplifier',
    1 => 'Plug Type “A” (USA, Canada, Mexico, Japan)',
    2 => 'Plug Type “B” (USA, Canada, Mexico, Japan)',
    3 => 'Plug Type “C” (China, Ireland, Greece, Spain)',
    4 => 'Plug Type “D” (India, Pakistan, Ghana, Bangladesh)',
    5 => 'Plug Type “E” (Poland, Belgium, France, Slovakia)',
    6 => 'Plug Type “F” (Netherlands, Germany, Austria)',
    7 => 'Plug Type “G” (Ireland, UK, Singapore)',
    8 => 'Plug Type “I” (Australia, New Zealand, Argentina)',
    9 => 'Plug Type “J” (Switzerland, Jordan, Rwanda)',
    10 => 'Plug Type “K” (Denmark, Greenland, Senegal)',
    11 => 'Plug Type “L” (Italy, Syria, Libya, Chile)',
    12 => 'Plug type “M” (South Africa, Swaziland)',
    13 => 'Plug type “N” (Brazil)',
    14 => 'Plug Type “O” (Thailand)',
  ),
) ?>