<?php return array (
  'SubcategoryID' => 800,
  'SubcategoryName' => 'EcoGadgets',
  'PropertyName' => 'EcoGadgetBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Blue Line Innovations',
    1 => 'Collection LED',
    2 => 'EcoStrip',
    3 => 'Hydro Flask',
    4 => 'InoSmart',
    5 => 'MEGA BRITE',
    6 => 'NatureMill',
    7 => 'Rosewill',
    8 => 'Solar Light Technologies',
    9 => 'Solarrific',
    10 => 'Southwest Windpower',
    11 => 'Stimulus Brands',
    12 => 'Sunforce',
    13 => 'TrickleStar',
    14 => 'Viatek',
  ),
) ?>