<?php return array (
  'SubcategoryID' => 496,
  'SubcategoryName' => 'AudioVideoStandsMounts',
  'PropertyName' => 'AVStandsType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'A/V STAND',
    1 => 'Accessory',
    2 => 'Audio Stand',
    3 => 'Detachable Speakers',
    4 => 'Dock',
    5 => 'Home Theater Seating',
    6 => 'In-Wall Mount',
    7 => 'Media Cabinet',
    8 => 'Media Player Bracket',
    9 => 'Projector Mount',
    10 => 'Projector Screen',
    11 => 'Projector Stand',
    12 => 'Speaker Bracket',
    13 => 'Speaker Stand',
    14 => 'TV Ceiling Mount',
    15 => 'TV Desktop Mount',
    16 => 'TV Stand',
    17 => 'TV Wall Bracket',
    18 => 'Wall Mount',
  ),
) ?>