<?php return array (
  'SubcategoryID' => 663,
  'SubcategoryName' => 'IceMakers',
  'PropertyName' => 'IceMakerBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Aficionado',
    1 => 'Amana',
    2 => 'Avanti',
    3 => 'BOSCH',
    4 => 'Chard',
    5 => 'Coleman',
    6 => 'Cuisinart',
    7 => 'Danby',
    8 => 'DeLonghi',
    9 => 'Doral Designs',
    10 => 'EMERSON',
    11 => 'Exact Replacement Parts',
    12 => 'Fujitronic',
    13 => 'GE',
    14 => 'Haier',
    15 => 'Igloo',
    16 => 'Maxi-Matic',
    17 => 'NOSTALGIA ELECTRICS',
    18 => 'NutriChef',
    19 => 'Orien',
    20 => 'Petra',
    21 => 'Poly-Flex',
    22 => 'Ragalta',
    23 => 'RIVAL',
    24 => 'Rosewill',
    25 => 'Sunpentown',
    26 => 'TAYAMA',
    27 => 'VillaWare',
    28 => 'Waring Pro',
    29 => 'Whirlpool',
    30 => 'Whynter',
  ),
) ?>