<?php return array (
  'SubcategoryID' => 3162,
  'SubcategoryName' => 'HLFoodStorage',
  'PropertyName' => 'HLFoodStorageType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 1,
  'PropertyValueList' => 
  array (
    0 => 'Bread Boxes',
    1 => 'Canisters',
    2 => 'Carrying Containers',
    3 => 'Cookie Jars',
    4 => 'Dry Food Dispensers',
    5 => 'Food Covers',
    6 => 'Food Storage & Vacuum Sealer Bags',
    7 => 'Fruit Baskets',
    8 => 'Herb Storage',
    9 => 'Jars & Terrines',
    10 => 'Picnic Baskets',
    11 => 'Porcelain Container',
    12 => 'Porcelain Food Storage',
    13 => 'Refrigerator Storage Containers',
    14 => 'Replacement Water Filters',
    15 => 'Tupperware',
    16 => 'Vegetable Crispers',
    17 => 'Water Purifier Pitchers',
  ),
) ?>