<?php return array (
  'SubcategoryID' => 630,
  'SubcategoryName' => 'PrinterLaserPrinters',
  'PropertyName' => 'LaserPrinterBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Belkin',
    1 => 'Brother',
    2 => 'Canon',
    3 => 'Dell',
    4 => 'Epson',
    5 => 'HP',
    6 => 'IBM',
    7 => 'Konica Minolta',
    8 => 'Kyocera',
    9 => 'Lexmark',
    10 => 'Oki',
    11 => 'Okidata',
    12 => 'Panasonic',
    13 => 'Pantum',
    14 => 'RICOH',
    15 => 'Samsung',
    16 => 'SHARP',
    17 => 'Tallygenicom',
    18 => 'Troy',
    19 => 'Xerox',
  ),
) ?>