<?php return array (
  'SubcategoryID' => 1571,
  'SubcategoryName' => 'ToysLearningEducational',
  'PropertyName' => 'ToysActionFiguresTheme',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Accessories',
    1 => 'Animals',
    2 => 'Anime & Manga',
    3 => 'Cartoons & Comics',
    4 => 'DC Comics',
    5 => 'Doctor Who',
    6 => 'Fantasy',
    7 => 'Game of Thrones',
    8 => 'Horror',
    9 => 'Marvel Comics',
    10 => 'Military',
    11 => 'Movies, TV & Music',
    12 => 'Other',
    13 => 'Police, Fire & Rescue',
    14 => 'Robots & Robotics',
    15 => 'Science Fiction',
    16 => 'Sports',
    17 => 'Star Trek',
    18 => 'Star Wars',
    19 => 'The Walking Dead',
    20 => 'Video Games',
    21 => 'Wrestling',
  ),
) ?>