<?php return array (
  'SubcategoryID' => 73,
  'SubcategoryName' => 'AddOnCards',
  'PropertyName' => 'AddCardExternalPorts',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '1 x Parallel Port',
    1 => '1 x SATA',
    2 => '1 x SATA 3.0',
    3 => '1 x SATA II',
    4 => '1 x Serial Port',
    5 => '1 x Serial Port + 1 x Parallel Port',
    6 => '2 port USB 3.0',
    7 => '2 x Parallel Ports',
    8 => '2 x SATA',
    9 => '2 x SATA 3.0',
    10 => '2 x SATA II',
    11 => '2 x Serial Ports',
    12 => '2 x Serial Ports + 1 x Parallel Port',
    13 => '4 port USB 3.0',
    14 => '4 x SATA',
    15 => '4 x SATA II',
    16 => '4 x Serial Ports',
    17 => '6 x Serial Ports',
    18 => '8 x Serial Ports',
  ),
) ?>