<?php return array (
  'SubcategoryID' => 73,
  'SubcategoryName' => 'AddOnCards',
  'PropertyName' => 'AddCardExternalUSBPorts',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '16x USB Ports',
    1 => '1x eSATA III, 1x SATA III',
    2 => '1x USB Port',
    3 => '2 Ext / 2 Int',
    4 => '2 Port',
    5 => '2 port USB 3.0',
    6 => '2x eSATA III',
    7 => '2x SATA III',
    8 => '2x USB Ports',
    9 => '3 Ext / 1 Int',
    10 => '3x SATA III, 1x mSATA',
    11 => '3x USB Ports',
    12 => '4 Ext',
    13 => '4 Ext Dual Bus',
    14 => '4 Ext Quad Bus',
    15 => '4 Port',
    16 => '4 port USB 3.0',
    17 => '4x SATA III',
    18 => '4x USB Ports',
    19 => '5x USB Ports',
    20 => '6x USB Ports',
    21 => '7x USB Ports',
    22 => '8 Port',
    23 => '8x USB Ports',
    24 => 'Mini PCI Express',
    25 => 'No',
    26 => 'PCI',
    27 => 'PCI Express',
    28 => 'PCI Express w Breakout Cable',
    29 => 'PCI-X',
  ),
) ?>