<?php return array (
  'SubcategoryID' => 350,
  'SubcategoryName' => 'PowerStripsInvertersandConverters',
  'PropertyName' => 'PSICCordLength',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '1.5 Feet',
    1 => '10 Feet',
    2 => '10 Feet + Drip Shield',
    3 => '12 Feet',
    4 => '15 Feet',
    5 => '15 Feet + Safety Cover',
    6 => '16 Feet',
    7 => '2 Feet',
    8 => '20 Feet',
    9 => '25 Feet',
    10 => '3 Feet',
    11 => '3 Feet Coiled Cord',
    12 => '4 Feet',
    13 => '5 Feet',
    14 => '50 Feet',
    15 => '6 Feet',
    16 => '6 Feet (Black Outlet)',
    17 => '7 Feet',
    18 => '8 Feet',
    19 => '9 Feet',
  ),
) ?>