<?php return array (
  'SubcategoryID' => 1897,
  'SubcategoryName' => 'HIElectricalBoxesEnclosures',
  'PropertyName' => 'HIElectricalBoxesType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Accessories',
    1 => 'Cabinets & Racks',
    2 => 'Electrical Box Covers',
    3 => 'Electrical Boxes',
    4 => 'Enclosure Coolers',
    5 => 'Enclosures',
    6 => 'Floor Box Covers',
    7 => 'Floor Boxes',
    8 => 'Hazardous Location Electrical Boxes',
    9 => 'Hazardous Location Enclosures',
    10 => 'Panels & Panel Accessories',
    11 => 'Plastic Boxes',
    12 => 'Pushbutton Enclosures',
    13 => 'Steel Boxes',
    14 => 'Temporary Power Panels',
    15 => 'Underground Enclosures',
    16 => 'Voice & Data Wiring Blocks',
    17 => 'Weatherproof Box Covers',
    18 => 'Weatherproof Boxes',
    19 => 'Weatherproof Outlet Boxes',
    20 => 'Wireway Enclosures',
    21 => 'Wiring Troughs',
  ),
) ?>