<?php return array (
  'SubcategoryID' => 3047,
  'SubcategoryName' => 'AudioVideoSwitch',
  'PropertyName' => 'AVSwitchPorts',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '12',
    1 => '16',
    2 => '17',
    3 => '2',
    4 => '2-Port UHD',
    5 => '3',
    6 => '3-Port',
    7 => '3-Port UHD',
    8 => '4',
    9 => '4-Port UHD',
    10 => '4x4 Matrix',
    11 => '5',
    12 => '6',
    13 => '8',
  ),
) ?>