<?php return array (
  'SubcategoryID' => 2628,
  'SubcategoryName' => 'ATAutomotiveLighting',
  'PropertyName' => 'ATLightingType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 1,
  'PropertyValueList' => 
  array (
    0 => 'Accent/Auxiliary Lighting',
    1 => 'Bulbs',
    2 => 'Corner, Bumper, Side & Parking Lights',
    3 => 'Fog Lights/Driving Lights',
    4 => 'Headlights',
    5 => 'HID & HID Kits',
    6 => 'Instrument Panel Lights',
    7 => 'Interior Lighting',
    8 => 'Light Bars',
    9 => 'Light Covers & Lenses',
    10 => 'Light Guards',
    11 => 'Off-Road Lights',
    12 => 'Other Accessories',
    13 => 'RV Awning Lights',
    14 => 'RV Exterior Lights',
    15 => 'Tail Lights',
    16 => 'Third Brake Lights',
    17 => 'Towing/Trailer Lights',
  ),
) ?>