<?php return array (
  'SubcategoryID' => 3376,
  'SubcategoryName' => 'HIFuses',
  'PropertyName' => 'HIFuseType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'British & IEC Fuses',
    1 => 'Class CC Fuses',
    2 => 'Class D Fuses',
    3 => 'Class G Fuses',
    4 => 'Class J Fuses',
    5 => 'Class L Fuses',
    6 => 'Class RK1 Fuses',
    7 => 'Class RK5 Fuses',
    8 => 'Class T Fuses',
    9 => 'Forklift & Truck Fuses',
    10 => 'Fuse Blocks & Holders',
    11 => 'Fuse Boxes & Accessories',
    12 => 'Fuse Kits',
    13 => 'Fuse Links',
    14 => 'Fuse Reducers',
    15 => 'Fuses',
    16 => 'General Purpose Fuses',
    17 => 'Minitature Glass & Ceramic Body Fuses',
    18 => 'Multimeter Fuses',
    19 => 'Pin Indication Fuses',
    20 => 'Plug Fuses',
    21 => 'Semiconductor & High-Speed Fuses',
    22 => 'Size-Rejecting & Non-Rejecting Fuses',
    23 => 'Solar Fuses',
  ),
) ?>