<?php return array (
  'SubcategoryID' => 759,
  'SubcategoryName' => 'ProcessorsMobile',
  'PropertyName' => 'MobileCPUCoreName',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Albany',
    1 => 'Arrandale',
    2 => 'Banias',
    3 => 'Barton',
    4 => 'Caspian',
    5 => 'Champlain',
    6 => 'Clarksfield',
    7 => 'ClawHammer',
    8 => 'Dothan',
    9 => 'Georgetown',
    10 => 'Haswell',
    11 => 'Ivy Bridge',
    12 => 'Keene',
    13 => 'Lancaster',
    14 => 'Lion',
    15 => 'Merom',
    16 => 'Montevina',
    17 => 'Newark',
    18 => 'Penryn',
    19 => 'Richmond',
    20 => 'Roma',
    21 => 'Sable',
    22 => 'Sandy Bridge',
    23 => 'Sonora',
    24 => 'Taylor',
    25 => 'Trinidad',
    26 => 'Tualatin',
    27 => 'Yonah',
  ),
) ?>