<?php return array (
  'SubcategoryID' => 759,
  'SubcategoryName' => 'ProcessorsMobile',
  'PropertyName' => 'MobileCPUSeries',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Athlon II',
    1 => 'Athlon XP Mobile',
    2 => 'Celeron',
    3 => 'Celeron M',
    4 => 'Core 2 Duo',
    5 => 'Core 2 Extreme',
    6 => 'Core 2 Quad',
    7 => 'Core Duo',
    8 => 'Core i3',
    9 => 'Core i5',
    10 => 'Core i7',
    11 => 'Core i7 Extreme Edition',
    12 => 'Mobile Athlon 64',
    13 => 'Mobile Athlon 64 X2',
    14 => 'Mobile Sempron',
    15 => 'Pentium Dual-Core',
    16 => 'Pentium M',
    17 => 'Phenom II',
    18 => 'Turion 64',
    19 => 'Turion 64 X2',
    20 => 'Turion 64 X2 Ultra',
    21 => 'Turion II',
  ),
) ?>