<?php return array (
  'SubcategoryID' => 2886,
  'SubcategoryName' => 'HILightKits',
  'PropertyName' => 'HILightKitsCollection',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'AirPro',
    1 => 'Alabaster Glass',
    2 => 'Ashmore',
    3 => 'Clear Prismatic Glass',
    4 => 'Guildhall',
    5 => 'Madison',
    6 => 'Meeting Street',
    7 => 'North Park',
    8 => 'Pavilion',
    9 => 'Santiago',
    10 => 'Schoolhouse',
    11 => 'Signature',
    12 => 'Trevina',
    13 => 'Trinity',
    14 => 'Universal',
    15 => 'Wisten',
  ),
) ?>