<?php return array (
  'SubcategoryID' => 517,
  'SubcategoryName' => 'Xbox360Accessories',
  'PropertyName' => 'XB360ACCType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Battery & Charger',
    1 => 'Cables & Adapters',
    2 => 'Case',
    3 => 'Cleaner',
    4 => 'Controllers',
    5 => 'Cooler',
    6 => 'Drive & Memory',
    7 => 'Essentials Pack',
    8 => 'Headset',
    9 => 'Kinect',
    10 => 'Kit',
    11 => 'Other',
    12 => 'Personalize',
    13 => 'Remote Controller',
    14 => 'Repair',
    15 => 'Screen',
    16 => 'Selector',
    17 => 'Sound',
    18 => 'Stand & Game Storage',
    19 => 'Xbox LIVE & Wireless Gear',
  ),
) ?>