<?php return array (
  'SubcategoryID' => 92,
  'SubcategoryName' => 'ExternalEnclosure',
  'PropertyName' => 'EnclosureNumberofBay',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '1',
    1 => '1:1',
    2 => '1:3',
    3 => '1:5',
    4 => '10',
    5 => '2',
    6 => '2 Bay',
    7 => '3',
    8 => '4',
    9 => '4 Bay',
    10 => '4 Bay (TB2)',
    11 => '5',
    12 => '5 Bay',
    13 => '8',
    14 => '8 Bay',
    15 => 'N/A',
  ),
) ?>