<?php return array (
  'SubcategoryID' => 92,
  'SubcategoryName' => 'ExternalEnclosure',
  'PropertyName' => 'EnclosureInternalInterface',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'IDE',
    1 => 'IDE / SAS / SATA',
    2 => 'IDE / SATA',
    3 => 'Mini-SAS',
    4 => 'mSATA',
    5 => 'mSATA III',
    6 => 'SAS / SATA',
    7 => 'SATA',
    8 => 'SATA I/II',
    9 => 'SATA I/II/III',
    10 => 'SATA II',
    11 => 'SATA III',
    12 => 'SCSI',
    13 => 'Ultra ATA',
    14 => 'Ultra ATA/100 (ATA-6)',
    15 => 'Ultra ATA/133 (ATA-7)',
    16 => 'Ultra ATA/66 (ATA-5)',
    17 => 'Ultra ATA/66/100/133',
    18 => 'Ultra320 SCSI',
  ),
) ?>