<?php return array (
  'SubcategoryID' => 92,
  'SubcategoryName' => 'ExternalEnclosure',
  'PropertyName' => 'EnclosureColor',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Banana Yellow',
    1 => 'Beige',
    2 => 'Black',
    3 => 'Black / Hairline',
    4 => 'Black / Orange',
    5 => 'Black / Silver',
    6 => 'Black / White',
    7 => 'Blue',
    8 => 'Bronze',
    9 => 'Brown',
    10 => 'Brushed Black',
    11 => 'Brushed Silver',
    12 => 'Copper',
    13 => 'Gold',
    14 => 'Gray',
    15 => 'Green',
    16 => 'Jet Black',
    17 => 'Matte Black',
    18 => 'Matte Silver',
    19 => 'Matte White',
    20 => 'Mirage Black',
    21 => 'Mirage White',
    22 => 'No',
    23 => 'Orange',
    24 => 'Pink',
    25 => 'Purple',
    26 => 'Red',
    27 => 'Silver',
    28 => 'White',
    29 => 'Yellow',
  ),
) ?>