<?php return array (
  'SubcategoryID' => 3374,
  'SubcategoryName' => 'HIHardwarePadlocks',
  'PropertyName' => 'GlobalFinish',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'ABS',
    1 => 'Armor Coat',
    2 => 'Black',
    3 => 'Black Oxide',
    4 => 'Black Phosphate',
    5 => 'Brass',
    6 => 'Bronze',
    7 => 'Brown',
    8 => 'Chrome',
    9 => 'DAC 500B',
    10 => 'Gloss',
    11 => 'Hot Dipped Galvanized',
    12 => 'Lacquer',
    13 => 'Metric Blue',
    14 => 'Natural',
    15 => 'Nickel Plated',
    16 => 'Nylon',
    17 => 'Phosphate',
    18 => 'Plain',
    19 => 'Smooth',
    20 => 'Stainless Steel',
    21 => 'Tin',
    22 => 'Ultra Coat',
    23 => 'Yellow Zinc',
    24 => 'Yellow Zinc Plated',
    25 => 'Zinc',
  ),
) ?>