<?php return array (
  'SubcategoryID' => 3374,
  'SubcategoryName' => 'HIHardwarePadlocks',
  'PropertyName' => 'PadlockType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Cable Lockouts',
    1 => 'Camlocks, Side Latches & Pawl Latches',
    2 => 'Circuit Breaker Lockouts',
    3 => 'Combination & Padlock Accessories',
    4 => 'Combination Locks',
    5 => 'Cylinders',
    6 => 'Gas Cyclinder Lockouts',
    7 => 'Group Lockout Boxes',
    8 => 'HVAC Lockouts',
    9 => 'Key Blanks & Key Machines',
    10 => 'Key Control',
    11 => 'Locking Cable & Chain',
    12 => 'Lockout Centers & Stations',
    13 => 'Lockout Hasps',
    14 => 'Lockout Padlocks',
    15 => 'Padlock Eyes',
    16 => 'Padlocks',
    17 => 'Plug & Switch Lockout Devices',
    18 => 'Pneumatic Lockouts',
    19 => 'Portable Lockout Kits',
    20 => 'Security Seals',
    21 => 'Valve Lockout Devices',
  ),
) ?>