<?php return array (
  'SubcategoryID' => 3303,
  'SubcategoryName' => 'OSSigns',
  'PropertyName' => 'SignsType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 1,
  'PropertyValueList' => 
  array (
    0 => 'Biohazard Signs',
    1 => 'Caution Signs',
    2 => 'Exit & Entry Signs',
    3 => 'Fire Signs',
    4 => 'Floor Signs',
    5 => 'Hospital Signs',
    6 => 'LED Message Displays',
    7 => 'LED Signs',
    8 => 'Letters & Numbers',
    9 => 'Neon Signs',
    10 => 'No Smoking',
    11 => 'Office & Facility',
    12 => 'Parking & Traffic Signs',
    13 => 'Restroom Signs',
    14 => 'Safety Record Signs',
    15 => 'Safety Signs',
    16 => 'Security Signs',
    17 => 'Sign Holders',
    18 => 'Signage',
    19 => 'Warning Signs',
  ),
) ?>