<?php return array (
  'SubcategoryID' => 1040,
  'SubcategoryName' => 'BathroomFaucets',
  'PropertyName' => 'BathroomFaucetBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'American Standard',
    1 => 'Belle Foret',
    2 => 'Central Brass',
    3 => 'Cifial',
    4 => 'Danze',
    5 => 'DELTA',
    6 => 'FIAT',
    7 => 'Fusion',
    8 => 'Grohe',
    9 => 'Hansgrohe',
    10 => 'Jado',
    11 => 'KOHLER',
    12 => 'La Toscana',
    13 => 'LDR',
    14 => 'Moen',
    15 => 'Mueller Industries',
    16 => 'Oatey',
    17 => 'Peerless',
    18 => 'Pegasus',
    19 => 'Pfister',
    20 => 'Symmons',
    21 => 'T&S Brass',
    22 => 'Ultra Faucets',
  ),
) ?>