<?php return array (
  'SubcategoryID' => 3431,
  'SubcategoryName' => 'PersonalProtectiveEquipment',
  'PropertyName' => 'PersonalProtectiveSizeDimensions',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '2X-Large - 3X-Large',
    1 => '3XL',
    2 => '4X-Large - 5X-Large',
    3 => '4XL',
    4 => '5XL',
    5 => 'Large',
    6 => 'Large - X-Large',
    7 => 'Medium',
    8 => 'One Size',
    9 => 'Small',
    10 => 'Small - Medium',
    11 => 'Standard',
    12 => 'X Large',
    13 => 'X Small',
    14 => 'XL',
    15 => 'XS',
    16 => 'XX Large',
    17 => 'XX Small',
    18 => 'XXL',
    19 => 'XXS',
    20 => 'XXX Large',
  ),
) ?>