<?php return array (
  'SubcategoryID' => 647,
  'SubcategoryName' => 'Refrigerators',
  'PropertyName' => 'RefrigeratorType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 1,
  'PropertyValueList' => 
  array (
    0 => 'Accessories',
    1 => 'All Refrigerator',
    2 => 'Bottom-Freezer Refrigerator',
    3 => 'Bottom-Mount Refrigerator',
    4 => 'Commercial Refrigerator',
    5 => 'Compact Refrigerator',
    6 => 'Cooler',
    7 => 'Freezer',
    8 => 'French Door Refrigerator',
    9 => 'Ice Maker',
    10 => 'Portable Refrigerator/Freezer',
    11 => 'Refrigerator',
    12 => 'Refrigerator Drawers',
    13 => 'Refrigerator/Freezer',
    14 => 'Side-By-Side Refrigerator',
    15 => 'Top-Freezer Refrigerator',
    16 => 'Top-Mount Refrigerator',
    17 => 'Vending Refrigerator',
    18 => 'Water Cooler',
    19 => 'Water Dispenser',
  ),
) ?>