<?php return array (
  'SubcategoryID' => 647,
  'SubcategoryName' => 'Refrigerators',
  'PropertyName' => 'RefrigeratorBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Aficionado',
    1 => 'Amana',
    2 => 'Avanti',
    3 => 'BebeSounds',
    4 => 'Black & Decker',
    5 => 'Coleman',
    6 => 'Continental Electric',
    7 => 'Daewoo',
    8 => 'Danby',
    9 => 'DCS',
    10 => 'Emerson',
    11 => 'Exact Replacement Parts',
    12 => 'Franklin Chef',
    13 => 'Frigidaire',
    14 => 'Frigidaire Commercial',
    15 => 'Haier',
    16 => 'Igloo',
    17 => 'Jenn-Air',
    18 => 'Kool King',
    19 => 'LG',
    20 => 'Lgloo',
    21 => 'Lorell',
    22 => 'Magic Chef',
    23 => 'Midea',
    24 => 'MyFine',
    25 => 'NOSTALGIA ELECTRICS',
    26 => 'Orien',
    27 => 'Petra',
    28 => 'Poly-Flex',
    29 => 'Sakar',
    30 => 'Samsung',
    31 => 'SANYO',
    32 => 'Sunbeam',
    33 => 'Sunpentown',
    34 => 'WAGAN',
    35 => 'Westinghouse',
    36 => 'Whirlpool',
  ),
) ?>