<?php return array (
  'SubcategoryID' => 946,
  'SubcategoryName' => 'EarringsEarCuffs',
  'PropertyName' => 'EarringDiamondColor',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Black',
    1 => 'Blue',
    2 => 'Blue-Green',
    3 => 'Champagne',
    4 => 'D',
    5 => 'D-E',
    6 => 'D-F',
    7 => 'E',
    8 => 'E-F',
    9 => 'F',
    10 => 'F-G',
    11 => 'G',
    12 => 'G-H',
    13 => 'G-J',
    14 => 'Green',
    15 => 'H',
    16 => 'H-I',
    17 => 'I',
    18 => 'I-J',
    19 => 'J',
    20 => 'J-K',
    21 => 'K',
    22 => 'K-L',
    23 => 'K-M',
    24 => 'L',
    25 => 'M',
    26 => 'N-Z',
    27 => 'Pink',
    28 => 'Purple',
    29 => 'Red',
    30 => 'White',
    31 => 'Yellow',
  ),
) ?>