<?php return array (
  'SubcategoryID' => 946,
  'SubcategoryName' => 'EarringsEarCuffs',
  'PropertyName' => 'EarringStyle',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '3-Stone',
    1 => 'Baby',
    2 => 'Ball',
    3 => 'Chandelier',
    4 => 'Clip',
    5 => 'Clip-On & Magnetic',
    6 => 'Cluster',
    7 => 'Dangle',
    8 => 'Diamond',
    9 => 'Drop',
    10 => 'Ear Cuff',
    11 => 'Earring Jackets',
    12 => 'Electroform',
    13 => 'Etruscan',
    14 => 'Half-Ball',
    15 => 'Hinged',
    16 => 'Hoop & Huggies',
    17 => 'Love Knot',
    18 => 'Pin',
    19 => 'Post',
    20 => 'Stick',
    21 => 'Studs',
    22 => 'Twisted Hoop',
  ),
) ?>