<?php return array (
  'SubcategoryID' => 3366,
  'SubcategoryName' => 'HeavyEquipmentAttachments',
  'PropertyName' => 'HeavyEquipmentType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 1,
  'PropertyValueList' => 
  array (
    0 => 'Augers',
    1 => 'Backhoe Attachments',
    2 => 'Balers',
    3 => 'Box Blades & Snow Plows',
    4 => 'Cultivators',
    5 => 'Disc Harrows',
    6 => 'Forks',
    7 => 'Grain Equipment',
    8 => 'Harvesting Equipment',
    9 => 'Hay Rakes',
    10 => 'Hitches',
    11 => 'Irrigation Equipment',
    12 => 'Manure Spreaders',
    13 => 'Material Handling Equipment',
    14 => 'Mower Decks',
    15 => 'Mowers & Mower Conditioners',
    16 => 'Planters',
    17 => 'Plows',
    18 => 'Post Hole Diggers',
    19 => 'Seeders & Spreaders',
    20 => 'Snow Blowers',
    21 => 'Sprayers',
    22 => 'Tillers',
  ),
) ?>