<?php return array (
  'SubcategoryID' => 1674,
  'SubcategoryName' => 'FieldHockeyProtectiveGear',
  'PropertyName' => 'FieldHockeyProtectiveGearSize',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Junior Large',
    1 => 'Junior Medium',
    2 => 'Junior Small',
    3 => 'Junior X-Small',
    4 => 'Junior XX-Small',
    5 => 'One Size',
    6 => 'Senior Large',
    7 => 'Senior Medium',
    8 => 'Senior Small',
    9 => 'Senior X-Large',
    10 => 'Senior X-Small',
    11 => 'Senior XX-Large',
    12 => 'Youth Large',
    13 => 'Youth Medium',
    14 => 'Youth Small',
    15 => 'Youth X-Large',
  ),
) ?>