<?php return array (
  'SubcategoryID' => 3421,
  'SubcategoryName' => 'FurnitureHospitalityFoodService',
  'PropertyName' => 'FurnitureHospitalityType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Adult Bibs & Clothing Protectors',
    1 => 'Apparel & Workwear',
    2 => 'Bakeware',
    3 => 'Breakfast Cart',
    4 => 'Bus Tubs',
    5 => 'Can Storage Racks',
    6 => 'Cashier Stand',
    7 => 'Check Racks & Wheels',
    8 => 'Coffee Kiosk',
    9 => 'Compact Mart Cart',
    10 => 'Cookware',
    11 => 'Correctional & Institutional Beds',
    12 => 'Dishwasher Racks',
    13 => 'Flatware Retrievers',
    14 => 'Food Carriers',
    15 => 'Food Service Baskets',
    16 => 'Food Service Carts',
    17 => 'Food Service Dump Buggies',
    18 => 'Food Service Furniture',
    19 => 'Food Service Storage & Transportation',
    20 => 'Guest Room Amenities',
    21 => 'Hospital Beds',
    22 => 'Hotel & Daycare Furniture',
    23 => 'Kitchen Aprons',
    24 => 'Kitchen Caps & Hats',
    25 => 'Kitchen Coats',
    26 => 'Kitchen Pants',
    27 => 'Kitchen Shirts',
    28 => 'Kitchen Supplies',
    29 => 'Laundry Service',
    30 => 'Luggage Carts & Racks',
    31 => 'Meal Delivery Carts',
    32 => 'Rollaway Beds',
    33 => 'Vending Cart',
  ),
) ?>