<?php return array (
  'SubcategoryID' => 335,
  'SubcategoryName' => 'NetworkWirelessAPBridge',
  'PropertyName' => 'WLHumidity',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '0% - 70%, Non-Condensing',
    1 => '0% - 90%, Non-Condensing',
    2 => '0% - 95%, Non-Condensing',
    3 => '10% - 80%',
    4 => '10% - 85%, Non-Condensing',
    5 => '10% - 90% (Non-Condensing)',
    6 => '10% - 90%, Non-Condensing',
    7 => '10% - 95%, Non-Condensing',
    8 => '15% - 95%, Non-Condensing',
    9 => '20% - 80%, Non-Condensing',
    10 => '20% to 90%, Non-Condensing',
    11 => '20% to 95%, Non-Condensing',
    12 => '5% - 85%, Non-Condensing',
    13 => '5% - 90%, Non-Condensing',
    14 => '5% - 95%, Non-Condensing',
    15 => '90% Maximum, Non-Condensing',
    16 => '95% Maximum, Non-Condensing',
  ),
) ?>