<?php return array (
  'SubcategoryID' => 2118,
  'SubcategoryName' => 'HIKitchenHardwareAccessories',
  'PropertyName' => 'HIKitchenAccFinish',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Almond',
    1 => 'Biscuit',
    2 => 'Black',
    3 => 'Bone',
    4 => 'Brushed Bronze',
    5 => 'Brushed Chrome',
    6 => 'Brushed Nickel',
    7 => 'Brushed Stainless',
    8 => 'Chrome',
    9 => 'Glacier',
    10 => 'Kit',
    11 => 'Metallic Black',
    12 => 'Metallic Chocolate',
    13 => 'N/A',
    14 => 'Oil-Rubbed Bronze',
    15 => 'Pearl Nickel',
    16 => 'Polished Brass',
    17 => 'Polished Chrome',
    18 => 'Polished Nickel',
    19 => 'Polished Stainless',
    20 => 'Red',
    21 => 'Rustic Bronze',
    22 => 'Sahara Stone',
    23 => 'Satin Nickel',
    24 => 'Silver',
    25 => 'Stainless Steel',
    26 => 'Steel Optik',
    27 => 'Tuscan Bronze',
    28 => 'Venetian Bronze',
    29 => 'White',
    30 => 'Wood',
  ),
) ?>