<?php return array (
  'SubcategoryID' => 3041,
  'SubcategoryName' => 'HIBedPillows',
  'PropertyName' => 'HIBedPillowsColor',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Beige',
    1 => 'Black',
    2 => 'Blue',
    3 => 'Brown',
    4 => 'Burgundy',
    5 => 'Chocolate',
    6 => 'Cream',
    7 => 'Gold',
    8 => 'Gray',
    9 => 'Green',
    10 => 'Ivory',
    11 => 'Multi Color',
    12 => 'Navy Blue',
    13 => 'Off-White',
    14 => 'Orange',
    15 => 'Pine',
    16 => 'Pink',
    17 => 'Purple',
    18 => 'Red',
    19 => 'Silver',
    20 => 'Tan',
    21 => 'Terra Cotta',
    22 => 'White',
    23 => 'Yellow',
  ),
) ?>