<?php return array (
  'SubcategoryID' => 3258,
  'SubcategoryName' => 'AccessoriesActionCamera',
  'PropertyName' => 'ACAccessoryType',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Battery',
    1 => 'Battery Charger',
    2 => 'Cable',
    3 => 'Case',
    4 => 'Cover',
    5 => 'Cradle',
    6 => 'Floatation Device',
    7 => 'Foam Pad',
    8 => 'Kit',
    9 => 'Lens',
    10 => 'Light',
    11 => 'Mic Adapter',
    12 => 'Mount',
    13 => 'Other',
    14 => 'Remote',
    15 => 'Sheet',
    16 => 'Strap',
    17 => 'Telescopic Pole',
    18 => 'Waterproof Housing',
  ),
) ?>