<?php return array (
  'SubcategoryID' => 1037,
  'SubcategoryName' => 'BabyShoes',
  'PropertyName' => 'BBShoesSport',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Aerobic',
    1 => 'Baseball',
    2 => 'Basketball',
    3 => 'Boating',
    4 => 'Bowling',
    5 => 'Boxing',
    6 => 'Camping & Hiking',
    7 => 'Canoeing & Kayaking',
    8 => 'Cycling',
    9 => 'Dance',
    10 => 'Diving',
    11 => 'Equestrian',
    12 => 'Fishing',
    13 => 'Football',
    14 => 'Golf',
    15 => 'Hockey',
    16 => 'Hunting & Archery',
    17 => 'Ice Skating',
    18 => 'Jogging & Running',
    19 => 'Martial Arts',
    20 => 'Other',
    21 => 'Pilates & Yoga',
    22 => 'Scuba & Snorkeling',
    23 => 'Skateboarding',
    24 => 'Skating',
    25 => 'Ski & Snow',
    26 => 'Soccer',
    27 => 'Softball',
    28 => 'Surfing',
    29 => 'Swimming',
    30 => 'Tennis & Racquetball',
    31 => 'Weight Training',
  ),
) ?>