<?php return array (
  'SubcategoryID' => 1037,
  'SubcategoryName' => 'BabyShoes',
  'PropertyName' => 'BBShoesMaterial',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Acrylic',
    1 => 'Angora',
    2 => 'Blend',
    3 => 'Cashmere',
    4 => 'Chiffon',
    5 => 'Corduroy',
    6 => 'Cotton',
    7 => 'Crepe',
    8 => 'Denim',
    9 => 'Fleece',
    10 => 'Gabardine',
    11 => 'Hemp',
    12 => 'Lace',
    13 => 'Leather/Suede',
    14 => 'Linen',
    15 => 'Lycra',
    16 => 'Mesh',
    17 => 'Microfiber',
    18 => 'Neoprene',
    19 => 'Nylon',
    20 => 'Other',
    21 => 'Pique',
    22 => 'Polyester',
    23 => 'Rayon',
    24 => 'Satin & Sateen',
    25 => 'Silk',
    26 => 'Terrycloth',
    27 => 'Tweed',
    28 => 'Velvet',
    29 => 'Vinyl/Latex',
    30 => 'Wool',
  ),
) ?>