<?php return array (
  'SubcategoryID' => 797,
  'SubcategoryName' => 'DigitalCameraFilters',
  'PropertyName' => 'DCFilterBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'B+W',
    1 => 'BasAcc',
    2 => 'Bower',
    3 => 'Canon',
    4 => 'Digipower',
    5 => 'DIGITAL FOX',
    6 => 'DOLICA',
    7 => 'FOTGA',
    8 => 'FUJIFILM',
    9 => 'HOYA',
    10 => 'Kenko',
    11 => 'Kodak',
    12 => 'Nikon',
    13 => 'OLYMPUS',
    14 => 'Opteka',
    15 => 'Panasonic',
    16 => 'Pixel',
    17 => 'Polaroid',
    18 => 'SANYO',
    19 => 'Schneider',
    20 => 'SIGMA',
    21 => 'SONY',
    22 => 'SUNPAK',
    23 => 'Tamron',
    24 => 'Targus',
    25 => 'TIFFEN',
    26 => 'ToCAD',
    27 => 'Vivitar',
    28 => 'XCSource',
    29 => 'ZEIKOS',
  ),
) ?>