<?php return array (
  'SubcategoryID' => 797,
  'SubcategoryName' => 'DigitalCameraFilters',
  'PropertyName' => 'DCFilterType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Close Up Lenses',
    1 => 'Color Compensating',
    2 => 'Color Conversion',
    3 => 'Contrast',
    4 => 'Enhancing & Intensifier',
    5 => 'Filters Set',
    6 => 'Fluorescent',
    7 => 'For Black & White Film',
    8 => 'Gray Graduated Density Filter',
    9 => 'Infrared',
    10 => 'Neutral Density',
    11 => 'Polarizer',
    12 => 'Skylight',
    13 => 'Soft Effect A Filter',
    14 => 'Soft Effect B Filter',
    15 => 'Soft Fantasy Filter',
    16 => 'Soft Focus Filter',
    17 => 'Underwater Filters',
    18 => 'UV, Haze & Protection',
    19 => 'White Balance',
  ),
) ?>