<?php return array (
  'SubcategoryID' => 2923,
  'SubcategoryName' => 'MIDJGrooveProduction',
  'PropertyName' => 'DJBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Akai',
    1 => 'Audio-Technica',
    2 => 'Back to the 50\'s',
    3 => 'BLACKMORE',
    4 => 'Blizzard Lighting',
    5 => 'Boytone',
    6 => 'Cakewalk',
    7 => 'CHAUVET',
    8 => 'Craig Electronics',
    9 => 'Crosley',
    10 => 'Gemini',
    11 => 'Gemini DJ',
    12 => 'Gemini Pro Audio',
    13 => 'Hercules',
    14 => 'innovative',
    15 => 'Ion',
    16 => 'Jensen',
    17 => 'Korg',
    18 => 'Monster',
    19 => 'Music Hall',
    20 => 'Native Instruments',
    21 => 'NCH',
    22 => 'Numark',
    23 => 'Onkyo',
    24 => 'Pioneer',
    25 => 'Pyle',
    26 => 'PylePro',
    27 => 'QFX',
    28 => 'SONY',
    29 => 'Stanton',
    30 => 'Steinberg',
    31 => 'Technical Pro',
  ),
) ?>