<?php return array (
  'SubcategoryID' => 2087,
  'SubcategoryName' => 'HITowelRingsBars',
  'PropertyName' => 'HITowelRingsBarsBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '3M',
    1 => 'American Standard',
    2 => 'Baldwin',
    3 => 'Belle Foret',
    4 => 'Croydex',
    5 => 'DELTA',
    6 => 'Franklin Brass',
    7 => 'Fusion',
    8 => 'Gatco',
    9 => 'Grohe',
    10 => 'Hansgrohe',
    11 => 'Jado',
    12 => 'KOHLER',
    13 => 'La Toscana',
    14 => 'Liberty Hardware',
    15 => 'MOEN',
    16 => 'Pegasus',
    17 => 'Pfister',
  ),
) ?>