<?php return array (
  'SubcategoryID' => 2099,
  'SubcategoryName' => 'HIClosetOrganizationShelving',
  'PropertyName' => 'HIClosetOrgColorFinish',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'As Shown',
    1 => 'Beige',
    2 => 'Black',
    3 => 'Blue',
    4 => 'Blue Denim:100% Cotton',
    5 => 'Brown',
    6 => 'Burgundy',
    7 => 'Camel',
    8 => 'Chrome',
    9 => 'Clear',
    10 => 'Coral',
    11 => 'Dark Blue',
    12 => 'Dark Green',
    13 => 'Gold',
    14 => 'Gray',
    15 => 'Gray Denim:100% Cotton',
    16 => 'Green',
    17 => 'Ivory',
    18 => 'Khaki',
    19 => 'Light Blue',
    20 => 'Light Green',
    21 => 'Metallic',
    22 => 'Multi-Color',
    23 => 'Natural',
    24 => 'Navy',
    25 => 'Orange',
    26 => 'Pink',
    27 => 'Pink/Green',
    28 => 'Platinum',
    29 => 'Purple',
    30 => 'Red',
    31 => 'Silver',
    32 => 'Teal',
    33 => 'White',
    34 => 'Yellow',
  ),
) ?>