<?php return array (
  'SubcategoryID' => 85,
  'SubcategoryName' => 'CPUThermalPasteGrease',
  'PropertyName' => 'ThermalCompoundBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Antec',
    1 => 'ARCTIC COOLING',
    2 => 'Arctic Silver',
    3 => 'asetek',
    4 => 'Biostar',
    5 => 'COOLER MASTER',
    6 => 'Coollaboratory',
    7 => 'Deepcool',
    8 => 'DELL',
    9 => 'EVERCOOL',
    10 => 'EVGA',
    11 => 'GeIL',
    12 => 'GELID Solutions',
    13 => 'KINGWIN',
    14 => 'Logisys Computer',
    15 => 'MASSCOOL',
    16 => 'Noctua',
    17 => 'OCZ',
    18 => 'Phanteks',
    19 => 'Prolimatech',
    20 => 'Rosewill',
    21 => 'Scythe',
    22 => 'SIIG',
    23 => 'Startech',
    24 => 'Sunbeamtech',
    25 => 'SYBA',
    26 => 'Thermaltake',
    27 => 'Tuniq',
    28 => 'XIGMATEK',
    29 => 'ZALMAN',
    30 => 'ZEROtherm',
  ),
) ?>