<?php return array (
  'SubcategoryID' => 3188,
  'SubcategoryName' => 'XboxOneAccessories',
  'PropertyName' => 'XboxOneACCBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Antec',
    1 => 'Arsenal Gaming',
    2 => 'Astro Gaming',
    3 => 'Avenger',
    4 => 'AWA',
    5 => 'CTA Digital',
    6 => 'dreamGEAR',
    7 => 'Gioteck',
    8 => 'Hori',
    9 => 'Hyperkin',
    10 => 'INSTEN',
    11 => 'Interworks',
    12 => 'KMD',
    13 => 'Logitech',
    14 => 'LucidSound',
    15 => 'MAD CATZ',
    16 => 'Microsoft',
    17 => 'Monoprice',
    18 => 'Nyko',
    19 => 'ORB',
    20 => 'PDP',
    21 => 'Plantronics',
    22 => 'Polk Audio',
    23 => 'PowerA',
    24 => 'Razer',
    25 => 'Skullcandy',
    26 => 'SquidGrip',
    27 => 'SteelSeries',
    28 => 'Thrustmaster',
    29 => 'Tomee',
    30 => 'Tosa',
    31 => 'TRITTON',
    32 => 'Turtle Beach',
  ),
) ?>