<?php return array (
  'SubcategoryID' => 3188,
  'SubcategoryName' => 'XboxOneAccessories',
  'PropertyName' => 'XboxOneACCGBColor',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Black',
    1 => 'Blue',
    2 => 'Chrome Blue',
    3 => 'Chrome Gold',
    4 => 'Chrome Gold & Black',
    5 => 'Chrome Gold & White',
    6 => 'Chrome Green',
    7 => 'Chrome Pink',
    8 => 'Chrome Purple',
    9 => 'Chrome Red',
    10 => 'Chrome Silver',
    11 => 'Green',
    12 => 'Matte Black & Gold',
    13 => 'Matte Purple & Gold',
    14 => 'Matte White & Gold',
    15 => 'Metallic Silver',
    16 => 'N/A',
    17 => 'Orange',
    18 => 'Piano White & Gold',
    19 => 'Pink',
    20 => 'Purple',
    21 => 'Red',
    22 => 'White',
    23 => 'White Camo',
    24 => 'Yellow',
  ),
) ?>