<?php return array (
  'SubcategoryID' => 2793,
  'SubcategoryName' => 'HLOutdoorRugs',
  'PropertyName' => 'RugsStyle',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Arts-n-crafts',
    1 => 'Braided',
    2 => 'Casual',
    3 => 'Children',
    4 => 'Contemporary',
    5 => 'Country',
    6 => 'Flat Weave',
    7 => 'Flokati',
    8 => 'Indoor-Outdoor',
    9 => 'Kids',
    10 => 'Kids / Juvenile',
    11 => 'Kitchen',
    12 => 'Modern',
    13 => 'Naturals',
    14 => 'Novelty',
    15 => 'Outdoor',
    16 => 'Shag',
    17 => 'Solid',
    18 => 'Southwestern',
    19 => 'Southwestern / Lodge',
    20 => 'Traditional',
    21 => 'Transitional',
    22 => 'Tropical',
  ),
) ?>