<?php return array (
  'SubcategoryID' => 521,
  'SubcategoryName' => 'CCTVAnalogCameras',
  'PropertyName' => 'NTCAMType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Baby Monitor Camera',
    1 => 'Box Camera',
    2 => 'Bullet Camera',
    3 => 'Covert Camera',
    4 => 'Cube Camera',
    5 => 'Decoy',
    6 => 'Dome Camera',
    7 => 'Eyeball Camera',
    8 => 'Fire Sprinkler Camera',
    9 => 'Fisheye Camera',
    10 => 'Infrared Camera',
    11 => 'Kit',
    12 => 'Mini Camera',
    13 => 'PTZ Camera',
    14 => 'PTZ Dome Camera',
    15 => 'Regular Camera',
    16 => 'Wedge Camera',
    17 => 'Wired Camera',
    18 => 'Wireless Camera',
  ),
) ?>