<?php return array (
  'SubcategoryID' => 3117,
  'SubcategoryName' => 'PS4VideoGames',
  'PropertyName' => 'GroupVGEdition',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Alpha Sapphire',
    1 => 'Atlas Limited',
    2 => 'Atlas Pro',
    3 => 'Batmobile',
    4 => 'Battle of Z',
    5 => 'Collector\'s',
    6 => 'Collector\'s Edition',
    7 => 'Combo breaker pack',
    8 => 'Day one',
    9 => 'Definitive',
    10 => 'Deluxe',
    11 => 'Deluxe Edition',
    12 => 'Ghost',
    13 => 'Gold',
    14 => 'Gold Edition',
    15 => 'Goliath Edition',
    16 => 'Launch Edition',
    17 => 'Legacy Edition',
    18 => 'Legend Edition',
    19 => 'Legend Edition Gold',
    20 => 'Limited',
    21 => 'Limited Edition',
    22 => 'Marineford edition',
    23 => 'MVP',
    24 => 'Omega Ruby',
    25 => 'Origins Edition',
    26 => 'Premium',
    27 => 'Premium Edition',
    28 => 'Regular',
    29 => 'Special',
    30 => 'Standard',
    31 => 'Standard Edition',
    32 => 'Ultimate Edition',
    33 => 'Ultimate Tenkaichi',
  ),
) ?>