<?php return array (
  'SubcategoryID' => 3117,
  'SubcategoryName' => 'PS4VideoGames',
  'PropertyName' => 'PS4VGGenre',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Action',
    1 => 'Action / Horror',
    2 => 'Action / Shooter',
    3 => 'Action Adventure',
    4 => 'Adventure',
    5 => 'Compilations',
    6 => 'Family and Education',
    7 => 'Fighting',
    8 => 'Flight',
    9 => 'MMO',
    10 => 'MMORPG',
    11 => 'Music / Rhythm',
    12 => 'Other',
    13 => 'Puzzle',
    14 => 'Racing',
    15 => 'RPG',
    16 => 'Shooter',
    17 => 'Simulation',
    18 => 'Sports',
    19 => 'SRPG',
    20 => 'Strategy',
  ),
) ?>