<?php return array (
  'SubcategoryID' => 717,
  'SubcategoryName' => 'WineCoolersAccessories',
  'PropertyName' => 'WineCoolerColor',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '2-Tone',
    1 => 'Antique Bronze',
    2 => 'Black',
    3 => 'Black with Stainless Steel',
    4 => 'Black/Glass',
    5 => 'Black/Mirror',
    6 => 'Black/Silver',
    7 => 'Blue',
    8 => 'Blue/Cream',
    9 => 'Brown',
    10 => 'Clear',
    11 => 'Crystal',
    12 => 'Gray',
    13 => 'Green',
    14 => 'Green/Cream',
    15 => 'Orange',
    16 => 'Pink',
    17 => 'Platinum',
    18 => 'Purple',
    19 => 'Red',
    20 => 'Silver',
    21 => 'Stainless Steel',
    22 => 'Stainless Steel/Black',
    23 => 'Tan',
    24 => 'White',
    25 => 'Yellow',
  ),
) ?>