<?php return array (
  'SubcategoryID' => 278,
  'SubcategoryName' => 'WalkyTalky',
  'PropertyName' => 'TwoWayRadioandAccessoryBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '3M',
    1 => 'AUDIOVOX',
    2 => 'Blue Star',
    3 => 'Cobra',
    4 => 'Dantona',
    5 => 'Garmin',
    6 => 'Gear Keeper',
    7 => 'GRE',
    8 => 'Honeywell',
    9 => 'Icom',
    10 => 'KENWOOD',
    11 => 'Klein Electronics',
    12 => 'Lenmar',
    13 => 'M & M',
    14 => 'Maximal Power',
    15 => 'MIDLAND',
    16 => 'MOTOROLA',
    17 => 'NABC',
    18 => 'NADY',
    19 => 'OLYMPIA',
    20 => 'Peltor',
    21 => 'Royal',
    22 => 'Sakar',
    23 => 'TecNet International',
    24 => 'TriSquare',
    25 => 'Ultralast',
    26 => 'Uniden',
    27 => 'XACT',
  ),
) ?>