<?php return array (
  'SubcategoryID' => 531,
  'SubcategoryName' => 'BluRayPlayers',
  'PropertyName' => 'BHDPlayersBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Denon',
    1 => 'Dynex',
    2 => 'Funai',
    3 => 'Generic',
    4 => 'Haier',
    5 => 'Harman Kardon',
    6 => 'INSIGNIA',
    7 => 'JVC',
    8 => 'LG',
    9 => 'Magnavox',
    10 => 'Memorex',
    11 => 'Onkyo',
    12 => 'Panasonic',
    13 => 'Philips',
    14 => 'Pioneer',
    15 => 'RCA',
    16 => 'SAMSUNG',
    17 => 'Sansui',
    18 => 'Sanyo',
    19 => 'Sharp',
    20 => 'Sherwood',
    21 => 'Sony',
    22 => 'Sylvania',
    23 => 'TOSHIBA',
    24 => 'Vizio',
    25 => 'Yamaha',
  ),
) ?>