<?php return array (
  'SubcategoryID' => 769,
  'SubcategoryName' => 'MarineElectronics',
  'PropertyName' => 'MarineBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Alpine',
    1 => 'Audiovox',
    2 => 'Bazooka',
    3 => 'Boss Audio',
    4 => 'Clarion',
    5 => 'Coleman',
    6 => 'Dual',
    7 => 'Eagle',
    8 => 'Garmin',
    9 => 'Humminbird',
    10 => 'Kicker',
    11 => 'Lowrance',
    12 => 'MB Quart',
    13 => 'Minn Kota',
    14 => 'MTX',
    15 => 'Pioneer',
    16 => 'Polk Audio',
    17 => 'Pyle',
    18 => 'SCHMITT ONGARO MARINE PRODUCTS',
    19 => 'Scosche',
    20 => 'Sony',
    21 => 'Sound Storm',
    22 => 'Spot',
    23 => 'Terk',
  ),
) ?>