<?php return array (
  'SubcategoryID' => 704,
  'SubcategoryName' => 'MobileElectronicsAccessories',
  'PropertyName' => 'MEABrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'APC',
    1 => 'AViiQ',
    2 => 'Case Logic',
    3 => 'Concept',
    4 => 'CyberPower',
    5 => 'Datexx',
    6 => 'Digital & Wireless Group',
    7 => 'Duracell',
    8 => 'HyperJuice',
    9 => 'I-Tec Electronics',
    10 => 'IC INTRACOM',
    11 => 'Innergie',
    12 => 'Jwin',
    13 => 'PC USA',
    14 => 'Rosewill',
    15 => 'Sony',
    16 => 'Tekkeon',
    17 => 'The Joy Factory',
    18 => 'Xantrex',
  ),
) ?>