<?php return array (
  'SubcategoryID' => 1017,
  'SubcategoryName' => 'MemorabiliaCollectibles',
  'PropertyName' => 'MemorabiliaMaterial',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Canvas',
    1 => 'Cardboard',
    2 => 'Clay',
    3 => 'Cotton',
    4 => 'Fiberglass',
    5 => 'Fleece',
    6 => 'Glass',
    7 => 'Leather/Suede',
    8 => 'Manmade',
    9 => 'Mesh',
    10 => 'Metal',
    11 => 'Neoprene',
    12 => 'Nylon',
    13 => 'Other',
    14 => 'Plastic',
    15 => 'Porcelain',
    16 => 'Rubber',
    17 => 'Satin',
    18 => 'Vinyl/Latex',
    19 => 'Wood',
    20 => 'Wool',
  ),
) ?>