<?php return array (
  'SubcategoryID' => 490,
  'SubcategoryName' => 'DVDRecorder',
  'PropertyName' => 'DVDRBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'APEX Digital',
    1 => 'ASTAR',
    2 => 'Buffalo',
    3 => 'Clover Electronics',
    4 => 'COBY',
    5 => 'CyberHome',
    6 => 'DAEWOO',
    7 => 'DIRECTV',
    8 => 'Funai',
    9 => 'GO VIDEO',
    10 => 'H&B',
    11 => 'Hauppauge',
    12 => 'HP',
    13 => 'Humax',
    14 => 'INOi',
    15 => 'JVC',
    16 => 'Kenwood',
    17 => 'KREISEN',
    18 => 'LASONiC',
    19 => 'LG',
    20 => 'LITE-ON',
    21 => 'MAGNAVOX',
    22 => 'MixSonic',
    23 => 'Mustek',
    24 => 'Panasonic',
    25 => 'PHILIPS',
    26 => 'Pioneer',
    27 => 'RCA',
    28 => 'RjTECH',
    29 => 'SAMSUNG',
    30 => 'Sanyo',
    31 => 'SHARP',
    32 => 'SONY',
    33 => 'SYLVANIA',
    34 => 'TiVo',
    35 => 'TOSHIBA',
    36 => 'Yamaha',
  ),
) ?>