<?php return array (
  'SubcategoryID' => 482,
  'SubcategoryName' => 'NotebookCases',
  'PropertyName' => 'NBCaseCaseType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Backpack',
    1 => 'Briefcase',
    2 => 'Carrying Case',
    3 => 'Cover Case',
    4 => 'Folio',
    5 => 'Hard Case',
    6 => 'Hard-Shell Case',
    7 => 'Keyboard/Cover Case',
    8 => 'Ladies Tote',
    9 => 'Messenger',
    10 => 'Portfolios',
    11 => 'Protection Case',
    12 => 'Shoulder / Carrying Case',
    13 => 'Sleeve',
    14 => 'Slim Shell Case',
    15 => 'Slipcase',
    16 => 'Tablet Case',
    17 => 'Travel/Luggage Case',
    18 => 'Wheel Case',
  ),
) ?>