<?php return array (
  'SubcategoryID' => 202,
  'SubcategoryName' => 'AccessoriesMouse',
  'PropertyName' => 'ACCEMouseSize',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '19.7" x 9.6"',
    1 => 'Compact',
    2 => 'Extended',
    3 => 'Full Size',
    4 => 'King',
    5 => 'Large',
    6 => 'Medium',
    7 => 'Mid',
    8 => 'Mini',
    9 => 'N/A',
    10 => 'SLIM Compact',
    11 => 'SLIM Full Size',
    12 => 'SLIM Tenkeyless',
    13 => 'Small',
    14 => 'Standard',
    15 => 'Tenkeyless',
    16 => 'Wide',
    17 => 'XL',
    18 => 'XL Heavy',
    19 => 'XXL',
    20 => 'XXXL',
  ),
) ?>