<?php return array (
  'SubcategoryID' => 202,
  'SubcategoryName' => 'AccessoriesMouse',
  'PropertyName' => 'ACCEMouseColor',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Black',
    1 => 'Blue',
    2 => 'Brown',
    3 => 'Clear',
    4 => 'Cognac',
    5 => 'Dark Brown',
    6 => 'Gold',
    7 => 'Gray',
    8 => 'Green',
    9 => 'No',
    10 => 'Orange',
    11 => 'Pink',
    12 => 'Purple',
    13 => 'Red',
    14 => 'Silver',
    15 => 'Sky Blue',
    16 => 'Transparent',
    17 => 'White',
    18 => 'Yellow',
  ),
) ?>