<?php return array (
  'SubcategoryID' => 3301,
  'SubcategoryName' => 'OSShippingMailingSupplies',
  'PropertyName' => 'ShippingMailingSuppliesType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 1,
  'PropertyValueList' => 
  array (
    0 => 'Box Moving Kits',
    1 => 'Boxes - Mailers',
    2 => 'Boxes - Shipping',
    3 => 'Bubble Wrap',
    4 => 'Catalog Envelopes',
    5 => 'Document Protection',
    6 => 'Edge Protectors',
    7 => 'Envelopes',
    8 => 'Expanded Mailroom Assortment',
    9 => 'Fasteners & Adhesives',
    10 => 'Foam Wraps',
    11 => 'Gift Wrap Supplies',
    12 => 'Kraft Paper',
    13 => 'Mailers - Bubble-lined',
    14 => 'Mailers - Cartons',
    15 => 'Mailers - Flat Corrugate',
    16 => 'Mailers - Padded',
    17 => 'Mailers - Tubes',
    18 => 'Merchandising Bag Dispensers',
    19 => 'Merchandising Bags',
    20 => 'Moisture Absorbents & Indicators',
    21 => 'Packaging and Shipping Accessories',
    22 => 'Packaging Re-Use Products',
    23 => 'Packaging Tape & Dispensers',
    24 => 'Packing List Envelopes',
    25 => 'Packing Peanuts & Fillers',
    26 => 'Rack Labeling Supplies',
    27 => 'Shipping Labels & Tags',
    28 => 'Shrink Film',
    29 => 'Stamps & Dispensers',
    30 => 'Storage Bins',
    31 => 'Strapping & Accessories',
    32 => 'Stretch Wrap Films',
    33 => 'Work Gloves',
  ),
) ?>