<?php return array (
  'SubcategoryID' => 765,
  'SubcategoryName' => 'HVACFilters',
  'PropertyName' => 'FilterACCBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '3M',
    1 => 'American Air Filter',
    2 => 'Can-Filters',
    3 => 'DeLonghi',
    4 => 'FELLOWES',
    5 => 'Filtrete',
    6 => 'Friedrich',
    7 => 'Haier',
    8 => 'Hamilton Beach',
    9 => 'Holmes',
    10 => 'Honeywell',
    11 => 'Hoover',
    12 => 'Hunter',
    13 => 'Kaz',
    14 => 'Lasko',
    15 => 'LUMISCOPE',
    16 => 'MaxPower',
    17 => 'Optimus',
    18 => 'Panasonic',
    19 => 'Protec',
    20 => 'SHARP',
    21 => 'SPT',
    22 => 'Surround Air',
    23 => 'TATUNG',
    24 => 'Tiger',
    25 => 'Vornado',
    26 => 'Winix',
  ),
) ?>