<?php return array (
  'SubcategoryID' => 2724,
  'SubcategoryName' => 'ATSwitchesRelaysReplacement',
  'PropertyName' => 'ATSwitchApplication',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Accelerator Pedal',
    1 => 'Air Conditioning',
    2 => 'Air Pressure',
    3 => 'Air Temperature',
    4 => 'Axle Shift',
    5 => 'Backup Light Switch',
    6 => 'Blower',
    7 => 'Circuit Breaker',
    8 => 'Clutch',
    9 => 'Coolant Temperature Control Vacuum',
    10 => 'Door Ajar Warning',
    11 => 'Fuel Injection Throttle',
    12 => 'Fuel Sending',
    13 => 'Fuel Tank Selector',
    14 => 'Glove Box',
  ),
) ?>