<?php return array (
  'SubcategoryID' => 675,
  'SubcategoryName' => 'CanOpeners',
  'PropertyName' => 'CanOpenerBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Ad-N-Art',
    1 => 'As Seen On TV',
    2 => 'Black & Decker',
    3 => 'Bonjour',
    4 => 'Brentwood',
    5 => 'Continental Electric',
    6 => 'Cuisinart',
    7 => 'Farberware',
    8 => 'Haier',
    9 => 'Hamilton Beach',
    10 => 'Harvest Direct',
    11 => 'Koolulu',
    12 => 'Lifetime Brands',
    13 => 'Maxi-Matic',
    14 => 'metrokane',
    15 => 'Oster',
    16 => 'OXO',
    17 => 'Proctor Silex',
    18 => 'Quirky',
    19 => 'Rival',
    20 => 'salton',
    21 => 'Starfrit',
    22 => 'Sunbeam',
    23 => 'Toastmaster',
    24 => 'West Bend',
  ),
) ?>