<?php return array (
  'SubcategoryID' => 58,
  'SubcategoryName' => 'PowerSupplies',
  'PropertyName' => 'PSUSeries',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '80 Plus',
    1 => 'AURUM XILENSER',
    2 => 'AX series',
    3 => 'AXi series',
    4 => 'Basiq power',
    5 => 'Cobra',
    6 => 'CS Series',
    7 => 'CSM Series',
    8 => 'CX series',
    9 => 'CXM series',
    10 => 'Elite',
    11 => 'Fatal1ty',
    12 => 'GS series',
    13 => 'HIVE Series',
    14 => 'NAXN',
    15 => 'NAXN Advance',
    16 => 'Nightjar',
    17 => 'Platimax',
    18 => 'ProSeries',
    19 => 'S12II',
    20 => 'SFX',
    21 => 'Silent Pro M2',
    22 => 'SuperNOVA',
    23 => 'Toughpower',
    24 => 'Triathlor',
    25 => 'TruePower Classic series',
    26 => 'Turbo-Cool Series',
    27 => 'Zippy',
  ),
) ?>