<?php return array (
  'SubcategoryID' => 205,
  'SubcategoryName' => 'ProfessionalCamcorders',
  'PropertyName' => 'CamcorderColor',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '2 Tone',
    1 => 'Black',
    2 => 'Black&Silver',
    3 => 'Blue',
    4 => 'Brown',
    5 => 'Chrome',
    6 => 'Eggplant',
    7 => 'Gold',
    8 => 'Gray',
    9 => 'Green',
    10 => 'GunMetal',
    11 => 'Maroon',
    12 => 'Orange',
    13 => 'Pink',
    14 => 'Purple',
    15 => 'Red',
    16 => 'Silver',
    17 => 'Titanium',
    18 => 'Violet',
    19 => 'White',
    20 => 'Yellow',
  ),
) ?>