<?php return array (
  'SubcategoryID' => 205,
  'SubcategoryName' => 'ProfessionalCamcorders',
  'PropertyName' => 'CamcorderType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Analog Camcorder',
    1 => 'Camera Sunglasses',
    2 => 'Digital Camcorder',
    3 => 'DVD Camcorder',
    4 => 'Full HD Camcorder',
    5 => 'Full HD DVD Camcorder',
    6 => 'Full HD HDD/Flash Memory Camcorder',
    7 => 'Full HD MiniDV Camcorder',
    8 => 'Full HD Professional Camcorder',
    9 => 'Hard Disk Drive Camcorder',
    10 => 'HD Camcorder',
    11 => 'HDD/Flash Memory Camcorder',
    12 => 'High Definition Camcorder',
    13 => 'High Definition DVD Camcorder',
    14 => 'High Definition Hard Disk Drive Camcorder',
    15 => 'High Definition HDD/Flash Memory Camcorder',
    16 => 'High Definition MiniDV Camcorder',
    17 => 'MiniDV Camcorder',
    18 => 'Pocket Camcorder',
    19 => 'Professional Camcorder',
    20 => 'Ultra HD Camcorder',
  ),
) ?>