<?php return array (
  'SubcategoryID' => 205,
  'SubcategoryName' => 'ProfessionalCamcorders',
  'PropertyName' => 'CamcorderConnectors',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'AV Ports',
    1 => 'AV Ports, HDMI',
    2 => 'AV Ports, S-Video',
    3 => 'AV Ports, USB',
    4 => 'AV Ports, USB, Component',
    5 => 'HDMI, Component',
    6 => 'HDMI, Component, Composite',
    7 => 'IEEE 1394',
    8 => 'IEEE 1394, AV ports',
    9 => 'IEEE 1394, S-Video, AV ports',
    10 => 'IEEE 1394, USB',
    11 => 'IEEE 1394, USB, AV Ports',
    12 => 'IEEE 1394, USB, S-Video',
    13 => 'IEEE 1394, USB, S-Video, AV ports',
    14 => 'USB',
    15 => 'USB, Composite',
    16 => 'USB, HDMI',
    17 => 'USB, HDMI, AV Ports',
    18 => 'USB, HDMI, AV Ports, S-Video',
    19 => 'USB, HDMI, Component, AV Ports',
    20 => 'USB, HDMI, Component, AV Ports, S-Video',
    21 => 'USB, HDMI, Component, Composite',
    22 => 'USB, HDMI, Component, Composite, S-Video',
    23 => 'USB, HDMI, Composite',
    24 => 'USB, S-Video',
    25 => 'USB, S-Video, AV Ports',
  ),
) ?>