<?php return array (
  'SubcategoryID' => 205,
  'SubcategoryName' => 'ProfessionalCamcorders',
  'PropertyName' => 'CamcorderMemoryCardSupport',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'CF Card',
    1 => 'Memory Stick / SD / SDHC / SDXC',
    2 => 'Memory Stick Duo',
    3 => 'Memory Stick Duo / PRO Duo',
    4 => 'Memory Stick Micro, microSD/HC/XC',
    5 => 'Memory Stick PRO',
    6 => 'Memory Stick PRO Duo',
    7 => 'Memory Stick PRO Duo / SD / SDHC Card',
    8 => 'microSD',
    9 => 'microSD/SDHC',
    10 => 'miniSD',
    11 => 'MS / SD / MMC Card',
    12 => 'N/A',
    13 => 'SD / MMC Card',
    14 => 'SD / SDHC / MMC Card',
    15 => 'SD / SDHC / MMC+ Card',
    16 => 'SD / SDHC / SDXC Card',
    17 => 'SD / SDHC Card',
    18 => 'SD Card',
    19 => 'SDHC / MMC+ Card',
    20 => 'SDHC Card',
    21 => 'XQD Card',
  ),
) ?>