<?php return array (
  'SubcategoryID' => 205,
  'SubcategoryName' => 'ProfessionalCamcorders',
  'PropertyName' => 'CamcorderRecordingMedia',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '8cm DVD Disc',
    1 => 'Blu-ray',
    2 => 'Blu-ray/DVD',
    3 => 'Blu-ray/HDD/DVD',
    4 => 'Built-in Memory',
    5 => 'Built-in Memory and Memory Card',
    6 => 'DVD-R/±RW',
    7 => 'DVD-R/RW',
    8 => 'DVD-RAW',
    9 => 'DVD-RAW & DVD-R/RW',
    10 => 'Flash Memory',
    11 => 'HDD/DVD',
    12 => 'HDV Cassette',
    13 => 'Hi-8',
    14 => 'Internal Hard Disk',
    15 => 'Internal Hard Disk and Memory Card',
    16 => 'Memory Card',
    17 => 'Micro MV',
    18 => 'Microdrive',
    19 => 'MiniDV Cassette',
    20 => 'SSD',
    21 => 'SSD and Memory Card',
    22 => 'VHS',
    23 => 'VHS-C',
  ),
) ?>