<?php return array (
  'SubcategoryID' => 317,
  'SubcategoryName' => 'CablesRound',
  'PropertyName' => 'CBLRNDBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'AMC',
    1 => 'Antec',
    2 => 'Cables to go',
    3 => 'CABLES UNLIMITED',
    4 => 'COOLER MASTER',
    5 => 'COOLMAX',
    6 => 'GALAXY',
    7 => 'GENERIC',
    8 => 'KINAMAX',
    9 => 'Link Depot',
    10 => 'OKGEAR',
    11 => 'ORION Pro Series',
    12 => 'Rosewill',
    13 => 'StarTech',
    14 => 'SUPER TALENT',
    15 => 'Thermaltake',
    16 => 'Unincom',
    17 => 'VANTEC',
  ),
) ?>