<?php return array (
  'SubcategoryID' => 2063,
  'SubcategoryName' => 'PatioCushionsAccessories',
  'PropertyName' => 'PatioCushionsAccessoriesColorGroup',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Beige',
    1 => 'Black',
    2 => 'Blue',
    3 => 'Brown',
    4 => 'Clear',
    5 => 'Dark Wood',
    6 => 'Green',
    7 => 'Grey',
    8 => 'Medium Brown Wood',
    9 => 'Multicolor',
    10 => 'Natural/Light Brown Wood',
    11 => 'Orange',
    12 => 'Other',
    13 => 'Pink',
    14 => 'Purple',
    15 => 'Red',
    16 => 'Silver',
    17 => 'White',
  ),
) ?>