<?php return array (
  'SubcategoryID' => 1048,
  'SubcategoryName' => 'MascotCostumes',
  'PropertyName' => 'MascotTheme',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 1,
  'PropertyValueList' => 
  array (
    0 => 'Aquatic Creatures',
    1 => 'Bears',
    2 => 'Birds & Water Fowl',
    3 => 'Cats (Domestic & Wild)',
    4 => 'Circus Animals',
    5 => 'Dogs',
    6 => 'Dragons & Dinosaurs',
    7 => 'Easter Bunny Costumes',
    8 => 'Exotic Animals',
    9 => 'Fantasy',
    10 => 'Farm Animals',
    11 => 'Food',
    12 => 'Forest Animals',
    13 => 'Fox & Wolves & Coyote',
    14 => 'Gorillas & Monkeys',
    15 => 'Humans/People',
    16 => 'Misc',
    17 => 'Monsters & Aliens',
    18 => 'Plants & Insects',
    19 => 'Rabbits & Bunnies',
    20 => 'Reptiles',
    21 => 'Seasonal & Holiday',
    22 => 'Walking Illusions',
  ),
) ?>