<?php return array (
  'SubcategoryID' => 1048,
  'SubcategoryName' => 'MascotCostumes',
  'PropertyName' => 'MascotOccasion',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '1st Birthday',
    1 => '4th of July',
    2 => 'Baby Shower',
    3 => 'Bachelorette Party',
    4 => 'Baptism/Christening',
    5 => 'Birthday',
    6 => 'Bridal Shower',
    7 => 'Christmas',
    8 => 'Cinco de Mayo',
    9 => 'Communion/Confirmation',
    10 => 'Divorce',
    11 => 'Easter',
    12 => 'Everyday',
    13 => 'Football / Superbowl',
    14 => 'Graduation',
    15 => 'Halloween',
    16 => 'Hanukkah',
    17 => 'Mardi Gras',
    18 => 'New Year\'s',
    19 => 'Purim',
    20 => 'Retirement',
    21 => 'St. Patrick\'s Day',
    22 => 'Thanksgiving',
    23 => 'Valentine\'s Day',
    24 => 'Wedding',
  ),
) ?>