<?php return array (
  'SubcategoryID' => 3177,
  'SubcategoryName' => 'HLFruitVegetableTools',
  'PropertyName' => 'HLFruitType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 1,
  'PropertyValueList' => 
  array (
    0 => 'Citrus Juicers',
    1 => 'Citrus Reamers',
    2 => 'Coring Tools',
    3 => 'Corn Holders',
    4 => 'Food Choppers',
    5 => 'French Fry Cutters',
    6 => 'Fruit & Vegetable Knives',
    7 => 'Grapefruit Spoons',
    8 => 'Mandolines',
    9 => 'Mashers',
    10 => 'Melon Ballers',
    11 => 'Nut Crackers',
    12 => 'Peelers',
    13 => 'Pineapple Slicers',
    14 => 'Pitters',
    15 => 'Pumpkin Carving Kits',
    16 => 'Salad Spinners',
    17 => 'Slicers',
    18 => 'Stem Removers',
    19 => 'Truffle Shavers',
    20 => 'Vegetable Brushes',
    21 => 'Wedgers',
    22 => 'Zesters',
  ),
) ?>