<?php return array (
  'SubcategoryID' => 803,
  'SubcategoryName' => 'ServerRacksCabinets',
  'PropertyName' => 'GroupRacksCabinetsStyle',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '2 Post',
    1 => '4 Post',
    2 => 'Adjustable Depth',
    3 => 'Assembled',
    4 => 'Fixed',
    5 => 'Flat Pack',
    6 => 'Hinged',
    7 => 'Hinged with Steel Mesh Door',
    8 => 'Hinged with Window',
    9 => 'N/A',
    10 => 'Side Mount',
    11 => 'Vertical',
    12 => 'Vertical with 2 Fans',
    13 => 'With Window',
    14 => 'With Window and Fan',
  ),
) ?>