<?php return array (
  'SubcategoryID' => 665,
  'SubcategoryName' => 'Toasters',
  'PropertyName' => 'ToasterColor',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Black',
    1 => 'Black/Chrome',
    2 => 'Blue',
    3 => 'Brushed Stainless',
    4 => 'Charcoal',
    5 => 'Chrome',
    6 => 'Copper Metallic',
    7 => 'Gray',
    8 => 'Green',
    9 => 'Orange',
    10 => 'Pink',
    11 => 'Purple',
    12 => 'Red',
    13 => 'Red/Steel',
    14 => 'Silver',
    15 => 'Stainless Steel',
    16 => 'White',
    17 => 'Yellow',
  ),
) ?>