<?php return array (
  'SubcategoryID' => 2078,
  'SubcategoryName' => 'HIBathFaucetsParts',
  'PropertyName' => 'HIBathFaucetsPartsType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Adaptors',
    1 => 'Ball Assemblies',
    2 => 'Caps',
    3 => 'Cartridges',
    4 => 'Cross Handle Insert',
    5 => 'Dishwasher Adapter',
    6 => 'Double',
    7 => 'Faucet Extension',
    8 => 'Handle Knob insert',
    9 => 'Hose lock',
    10 => 'Lever Handle Base',
    11 => 'Lever Handle Insert',
    12 => 'Lotion Dispenser',
    13 => 'Other',
    14 => 'Plug button',
    15 => 'Single',
    16 => 'Spout',
    17 => 'Sprayer Hose',
    18 => 'Sprayers',
    19 => 'Stems',
    20 => 'Valve Trim',
  ),
) ?>