<?php return array (
  'SubcategoryID' => 3417,
  'SubcategoryName' => 'RawMaterials',
  'PropertyName' => 'RawMaterialType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Alloy Steel',
    1 => 'Aluminum',
    2 => 'Assortments',
    3 => 'Brass',
    4 => 'Bronze',
    5 => 'Carbon Steel',
    6 => 'Cast Iron',
    7 => 'Cement',
    8 => 'Ceramic',
    9 => 'Concerete Cleaners & Sealers',
    10 => 'Concerete Patching & Repair',
    11 => 'Concrete Mix',
    12 => 'Copper',
    13 => 'Cork',
    14 => 'Drywall',
    15 => 'Felt',
    16 => 'Fiberglass',
    17 => 'Foam',
    18 => 'Mud',
    19 => 'Plastics',
    20 => 'Rebar',
    21 => 'Rubber',
    22 => 'Sheet Rock',
    23 => 'Stainless Steel',
    24 => 'Tin',
    25 => 'Tool Steel',
    26 => 'Vinyl',
    27 => 'Wire Cloth',
  ),
) ?>