<?php return array (
  'SubcategoryID' => 2947,
  'SubcategoryName' => 'OGPondsWaterGardens',
  'PropertyName' => 'OGPondsType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Aquatic Gardening',
    1 => 'Birdbaths',
    2 => 'Complete Kits',
    3 => 'Decorative Ponds',
    4 => 'Filter Pads',
    5 => 'Filtration',
    6 => 'Fish Food',
    7 => 'Fountains',
    8 => 'Liners',
    9 => 'Pond Care',
    10 => 'Pond Nets',
    11 => 'Press Filter',
    12 => 'Pump Accessories',
    13 => 'Pumps',
    14 => 'Tubing',
    15 => 'UV Bulbs',
    16 => 'Water Garden Kit',
    17 => 'Water Gardening Pumps',
  ),
) ?>