<?php return array (
  'SubcategoryID' => 3321,
  'SubcategoryName' => 'PaperCraftsBoards',
  'PropertyName' => 'PaperBoardPaperType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Bristol Paper',
    1 => 'Card Stock',
    2 => 'Charcoal & Pastel Paper',
    3 => 'Construction Paper',
    4 => 'Decorative Paper',
    5 => 'Drawing & Sketching Paper',
    6 => 'Easel Pads',
    7 => 'Glassine & Barrier Paper',
    8 => 'Mulberry Paper',
    9 => 'Multimedia Paper',
    10 => 'Newsprint Paper',
    11 => 'Palette Paper',
    12 => 'Parchment Paper',
    13 => 'Printer Paper',
    14 => 'Printmaking Paper',
    15 => 'Scrapbooking Paper',
    16 => 'Tissue Paper',
    17 => 'Tracing & Graph Paper',
    18 => 'Vellum Paper',
    19 => 'Washi Paper',
    20 => 'Watercolor Paper',
  ),
) ?>