<?php return array (
  'SubcategoryID' => 583,
  'SubcategoryName' => 'ScannersBarcode',
  'PropertyName' => 'BarcodeSCInterfacesSupported',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Bluetooth',
    1 => 'Full Speed USB',
    2 => 'IBM 468X/469X',
    3 => 'KBW',
    4 => 'Keyboard Wedge',
    5 => 'Keyboard WedgeKeyboard WedgeKeyboard WedgeKeyboard',
    6 => 'Laser Emulation',
    7 => 'Low Speed USB',
    8 => 'mini-DIN (PS/2)',
    9 => 'Multi-Interface',
    10 => 'No Cable',
    11 => 'PS/2',
    12 => 'RF Wireless',
    13 => 'RJ45',
    14 => 'RS-232',
    15 => 'RS-232, Keyboard Wedge',
    16 => 'RS-232C',
    17 => 'RS-485',
    18 => 'RS232 Kit',
    19 => 'RS232 Verifone Kit',
    20 => 'Serial',
    21 => 'Tailgate',
    22 => 'USB',
    23 => 'USB / Serial',
    24 => 'USB, RS-232',
    25 => 'USB, RS-232, IBM',
    26 => 'USB, RS-232, Keyboard Wedge',
    27 => 'USB, RS-232, Keyboard Wedge, IBM',
    28 => 'USB, Serial, IBM',
    29 => 'Wand Emulation',
  ),
) ?>