<?php return array (
  'SubcategoryID' => 583,
  'SubcategoryName' => 'ScannersBarcode',
  'PropertyName' => 'BarcodeSCColor',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Beige',
    1 => 'Black',
    2 => 'Blue',
    3 => 'Blue/Gray',
    4 => 'Dark Blue',
    5 => 'Dark Gray',
    6 => 'Gray',
    7 => 'Green',
    8 => 'Green/Black',
    9 => 'Ivory',
    10 => 'Light Blue',
    11 => 'Light Gray',
    12 => 'Midnight Blue',
    13 => 'Nova White',
    14 => 'Orange',
    15 => 'Red',
    16 => 'Slate Blue',
    17 => 'Teal',
    18 => 'Twilight Black',
    19 => 'White',
    20 => 'Yellow',
    21 => 'Yellow/Black',
    22 => 'Yellow/Twilight Black',
  ),
) ?>