<?php return array (
  'SubcategoryID' => 583,
  'SubcategoryName' => 'ScannersBarcode',
  'PropertyName' => 'BarcodeSCScanEngine',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '1D',
    1 => '1D 24-line Laser',
    2 => '1D CCD',
    3 => '1D Laser',
    4 => '1D Linear',
    5 => '1D Linear CCD',
    6 => '1D Linear Imager',
    7 => '1D, PDF',
    8 => '2D',
    9 => '2D Area Imager',
    10 => '2D CCD',
    11 => '2D Extended Range',
    12 => '2D High Density',
    13 => '2D High Performance',
    14 => '2D Standard Range',
    15 => '2D w/ Laser Aimer',
    16 => '2D w/ LED Aimer',
    17 => '2D/1D',
    18 => 'Laser',
    19 => 'Linear CCD',
  ),
) ?>