<?php return array (
  'SubcategoryID' => 1045,
  'SubcategoryName' => 'Costumes',
  'PropertyName' => 'CostumeTheme',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Angels & Devils',
    1 => 'Animals & Insects',
    2 => 'Around the World',
    3 => 'Biblical',
    4 => 'Careers & Occupations',
    5 => 'Disney',
    6 => 'Fairytale & Storybook',
    7 => 'Food & Beverage',
    8 => 'Games',
    9 => 'Historical',
    10 => 'Horror & Gothic',
    11 => 'Humorous',
    12 => 'Military',
    13 => 'Patriotic',
    14 => 'Pirates',
    15 => 'Pop Icons',
    16 => 'Princesses & Divas',
    17 => 'Science Fiction',
    18 => 'Seasonal & Holiday',
    19 => 'Sports',
    20 => 'Superheroes & Villains',
    21 => 'TV & Movies',
  ),
) ?>