<?php return array (
  'SubcategoryID' => 408,
  'SubcategoryName' => 'AccessoriesProjectors',
  'PropertyName' => 'ProjectorAccType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Air Filter',
    1 => 'Airflow Systems Filter',
    2 => 'Camera',
    3 => 'Ceiling Mount',
    4 => 'Desk Mount',
    5 => 'Extension Column',
    6 => 'Lift',
    7 => 'Mounting Adapter',
    8 => 'Mounting Arm',
    9 => 'Mounting Bracket',
    10 => 'Mounting Coupler',
    11 => 'Mounting Extension',
    12 => 'Mounting Pipe',
    13 => 'Others',
    14 => 'Projector Battery',
    15 => 'Projector Bracket',
    16 => 'Projector Carts',
    17 => 'Projector Cases',
    18 => 'Projector Ceiling Plate',
    19 => 'Projector Interface',
    20 => 'Projector Lamp',
    21 => 'Projector Lectern',
    22 => 'Projector Lens',
    23 => 'Projector Lock',
    24 => 'Projector Mounts',
    25 => 'Projector Remote Pointers',
    26 => 'Projector Screens',
    27 => 'Projector Shutter Glasses',
    28 => 'Projector Stands',
    29 => 'Projector Wireless Devices',
    30 => 'Remote Control',
    31 => 'Replacement Surface',
    32 => 'Security Enclosure',
    33 => 'Wall Mount',
  ),
) ?>