<?php return array (
  'SubcategoryID' => 554,
  'SubcategoryName' => 'MacAccessories',
  'PropertyName' => 'MacAccType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'AC Power / Batteries',
    1 => 'Adapter',
    2 => 'Audio',
    3 => 'Cables / Hubs',
    4 => 'Calibration System',
    5 => 'Cartridge',
    6 => 'Desktop Kit',
    7 => 'Docking Stations / Stands / Coolers',
    8 => 'Floppy Disk Drive',
    9 => 'Handle',
    10 => 'Hard Drive Accessories',
    11 => 'Internal Expansion Cards',
    12 => 'Keyboard Protector',
    13 => 'Kit',
    14 => 'KVM Switches',
    15 => 'Mac Laptop Sleeves / Bags / Covers',
    16 => 'Measurement Device',
    17 => 'Mice & Keyboards',
    18 => 'Multimedia Controller',
    19 => 'Optical Disk Drive',
    20 => 'Printer',
    21 => 'Processor Upgrade Cards',
    22 => 'Remote Control',
    23 => 'Screen Protector',
    24 => 'Switch',
    25 => 'Thunderbolt Solutions',
    26 => 'Turntable',
    27 => 'TV Tuners & Video Devices',
    28 => 'VoIP',
    29 => 'Warranties',
    30 => 'Wireless Accessory',
    31 => 'Wireless AP',
  ),
) ?>