<?php return array (
  'SubcategoryID' => 554,
  'SubcategoryName' => 'MacAccessories',
  'PropertyName' => 'MacAccColor',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Beige',
    1 => 'Black',
    2 => 'Blue',
    3 => 'Blue moon',
    4 => 'Brown',
    5 => 'Clear',
    6 => 'Dark Grey',
    7 => 'Gold',
    8 => 'Green',
    9 => 'Grey',
    10 => 'Hot Pink',
    11 => 'No',
    12 => 'Ocean Green',
    13 => 'Orange',
    14 => 'Pink',
    15 => 'Purple',
    16 => 'Red',
    17 => 'Rose Gold',
    18 => 'Silver',
    19 => 'Sky Blue',
    20 => 'Translucent Baby Blue',
    21 => 'Translucent Dark Blue',
    22 => 'Turquoise Blue',
    23 => 'White',
    24 => 'Wine Red',
    25 => 'Yellow',
  ),
) ?>