<?php return array (
  'SubcategoryID' => 2936,
  'SubcategoryName' => 'MIStandsRacks',
  'PropertyName' => 'MusicalInstrumentAccessoriesFinish',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Black',
    1 => 'Black & White Pinstripe',
    2 => 'Blue Polka Dots',
    3 => 'Burgundy Lace',
    4 => 'Cow Print',
    5 => 'Damson Lace',
    6 => 'Giraffe Print',
    7 => 'Grey Zebra',
    8 => 'Mint Lace',
    9 => 'Pink Lace',
    10 => 'Pink Polka Dots',
    11 => 'Pinstripe',
    12 => 'Purple Lace',
    13 => 'Red Ladybug',
    14 => 'White',
    15 => 'Zebra Print',
  ),
) ?>