<?php return array (
  'SubcategoryID' => 2936,
  'SubcategoryName' => 'MIStandsRacks',
  'PropertyName' => 'MusicalInstrumentAccessoriesBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Alesis',
    1 => 'Audio-Technica',
    2 => 'Avid',
    3 => 'Behringer',
    4 => 'Casio',
    5 => 'CHANNEL PLUS',
    6 => 'CHAUVET',
    7 => 'Editors Keys',
    8 => 'eMedia',
    9 => 'Fender',
    10 => 'Forearm Forklift',
    11 => 'Hosa',
    12 => 'Ion',
    13 => 'Korg',
    14 => 'M-Audio',
    15 => 'MXL',
    16 => 'Nady',
    17 => 'Numark',
    18 => 'On Stage',
    19 => 'Pyle',
    20 => 'PylePro',
    21 => 'Raxxess',
    22 => 'revolabs',
    23 => 'Rode',
    24 => 'Samson',
    25 => 'Shure',
    26 => 'SKB',
    27 => 'Spectrum',
    28 => 'Steinberg',
    29 => 'Ultimate Support',
    30 => 'Vox',
    31 => 'Woodees',
    32 => 'World Tour',
    33 => 'Yamaha',
    34 => 'Zoom',
  ),
) ?>