<?php return array (
  'SubcategoryID' => 2936,
  'SubcategoryName' => 'MIStandsRacks',
  'PropertyName' => 'MusicalInstrumentAccessoriesType',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Adapters & Plugs',
    1 => 'DI Box',
    2 => 'Fog Machine Fluid',
    3 => 'Guitar Bag',
    4 => 'Guitar Cables',
    5 => 'Guitar Foot Rest',
    6 => 'Guitar Pedal Tuner',
    7 => 'Guitar Stand',
    8 => 'Keyboard Stand',
    9 => 'Microphone Arm',
    10 => 'Microphone Cables',
    11 => 'Microphone Stand',
    12 => 'Other',
    13 => 'Piano Bench',
    14 => 'Power Supply',
    15 => 'Rack Mount Cases & Stands',
    16 => 'Snakes',
    17 => 'Software and Sheet Music',
    18 => 'Speaker Cables',
    19 => 'Speaker Stand',
  ),
) ?>