<?php return array (
  'SubcategoryID' => 1878,
  'SubcategoryName' => 'OGPestControl',
  'PropertyName' => 'OGPestControlPestType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Ants',
    1 => 'Bedbugs & Dust Mites',
    2 => 'Caterpillars',
    3 => 'Combination',
    4 => 'Fleas',
    5 => 'Flies & Gnats',
    6 => 'Grub Worms',
    7 => 'Moles',
    8 => 'Mosquitos',
    9 => 'Moths',
    10 => 'Rats & Mice',
    11 => 'Roaches',
    12 => 'Skunk',
    13 => 'Slugs & Snails',
    14 => 'Spiders',
    15 => 'Squirrels',
    16 => 'Termites',
    17 => 'Wasps, Hornets & Yellow Jackets',
  ),
) ?>