<?php return array (
  'SubcategoryID' => 1878,
  'SubcategoryName' => 'OGPestControl',
  'PropertyName' => 'OGPestControlBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Advantek',
    1 => 'AgriZap',
    2 => 'Baithub',
    3 => 'Bell  & Howell',
    4 => 'Big H Products',
    5 => 'Bird B Gone',
    6 => 'Contech',
    7 => 'Dalen',
    8 => 'Earthbox',
    9 => 'Easy Gardener',
    10 => 'Enforcer',
    11 => 'Hudson',
    12 => 'Kness',
    13 => 'Lewis',
    14 => 'Liquid Ladybug',
    15 => 'Macabee',
    16 => 'Monterey',
    17 => 'Mosquito Magnet',
    18 => 'P3 International',
    19 => 'PestNoMore',
    20 => 'Pic',
    21 => 'Prime Source',
    22 => 'RCO',
    23 => 'Repellex',
    24 => 'Rescue',
    25 => 'Senoret',
    26 => 'SereneLife',
    27 => 'Springstar',
    28 => 'St Gabriel',
    29 => 'Stinger Pest',
    30 => 'Tomcat',
    31 => 'Victor',
    32 => 'Wire Tek',
    33 => 'Woodstream',
  ),
) ?>