<?php return array (
  'SubcategoryID' => 864,
  'SubcategoryName' => 'CarriersPacks',
  'PropertyName' => 'CarrierbagMaterial',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Acrylic',
    1 => 'Aluminum',
    2 => 'Cotton & Blends',
    3 => 'Denim',
    4 => 'Faux Leather',
    5 => 'Fleece',
    6 => 'Hemp',
    7 => 'Jersey',
    8 => 'Leather',
    9 => 'Linen',
    10 => 'Lycra',
    11 => 'Manmade',
    12 => 'Nylon',
    13 => 'Plastic',
    14 => 'Polycarbonate',
    15 => 'Polyester',
    16 => 'Rayon',
    17 => 'Suede',
  ),
) ?>