<?php return array (
  'SubcategoryID' => 3369,
  'SubcategoryName' => 'IndustrialVehicleInteriorExteriorAccessories',
  'PropertyName' => 'IndustrialVehicleAccessoriesType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 1,
  'PropertyValueList' => 
  array (
    0 => 'Antenna Toppers',
    1 => 'Bumpers & Bumper Accessories',
    2 => 'Cargo Management',
    3 => 'Chrome Trim & Accessories',
    4 => 'Decals & Bumper Stickers',
    5 => 'Deflectors & Shields',
    6 => 'Fender Flares & Trim',
    7 => 'Gas Caps',
    8 => 'Gas Tank Doors',
    9 => 'Grilles & Grille Guards',
    10 => 'Hood Scoops & Vents',
    11 => 'Horns & Accessories',
    12 => 'License Plate Covers & Frames',
    13 => 'Lights & Lighting Accessories',
    14 => 'Mirrors',
    15 => 'Running Boards & Steps',
    16 => 'Snow & Ice',
    17 => 'Towing Products & Winches',
    18 => 'Trailer Accessories',
    19 => 'Truck Bed & Tailgate Accessories',
    20 => 'Vehicle Covers',
    21 => 'Window Louvers',
  ),
) ?>