<?php return array (
  'SubcategoryID' => 26,
  'SubcategoryName' => 'HubsNetworkUSBFirewire',
  'PropertyName' => 'HUBColor',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Black',
    1 => 'Blue',
    2 => 'Brown',
    3 => 'Brushed Black',
    4 => 'Brushed Silver',
    5 => 'Desktop',
    6 => 'Gold',
    7 => 'Gray',
    8 => 'Green',
    9 => 'Grey',
    10 => 'Jet Black',
    11 => 'Matte Black',
    12 => 'Matte Silver',
    13 => 'Matte White',
    14 => 'Metal',
    15 => 'Mirage Black',
    16 => 'Mirage White',
    17 => 'Orange',
    18 => 'Pink',
    19 => 'Portable',
    20 => 'Pure White',
    21 => 'Purple',
    22 => 'Red',
    23 => 'Silver',
    24 => 'White',
    25 => 'Yellow',
  ),
) ?>