<?php return array (
  'SubcategoryID' => 26,
  'SubcategoryName' => 'HubsNetworkUSBFirewire',
  'PropertyName' => 'HUBType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Docking station',
    1 => 'DVI/HDMI/USB/Audio/RJ45',
    2 => 'Firewire',
    3 => 'Network',
    4 => 'Network/Serial',
    5 => 'Parallel',
    6 => 'SATA',
    7 => 'Serial',
    8 => 'USB',
    9 => 'USB/eSATA',
    10 => 'USB/Ethernet',
    11 => 'USB/Firewire',
    12 => 'USB/Reader',
    13 => 'USB/Serial',
  ),
) ?>