<?php return array (
  'SubcategoryID' => 1687,
  'SubcategoryName' => 'YogaPilatesToning',
  'PropertyName' => 'YogaSize',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '2 oz',
    1 => '55 cm (Purple)',
    2 => '65 cm (Green)',
    3 => '75 cm (Blue)',
    4 => '8 oz',
    5 => 'Large',
    6 => 'Long 79" x 26.5"',
    7 => 'Long 85"',
    8 => 'Medium',
    9 => 'Medium/Large',
    10 => 'N/A',
    11 => 'Size 1',
    12 => 'Size 2',
    13 => 'Size 3',
    14 => 'Size 4',
    15 => 'Small',
    16 => 'Small/Medium',
    17 => 'Standard 71"',
    18 => 'Standard 72" x 26.5"',
    19 => 'X-Large',
    20 => 'X-Long 86" x 26.5"',
    21 => 'X-Small',
  ),
) ?>