<?php return array (
  'SubcategoryID' => 683,
  'SubcategoryName' => 'NintendoDSSystems',
  'PropertyName' => 'DSColor',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '2 Tone',
    1 => 'Black',
    2 => 'Blue',
    3 => 'Bronze',
    4 => 'Burgundy',
    5 => 'Coral Pink',
    6 => 'Crimson & Black',
    7 => 'Electric Blue',
    8 => 'Gold',
    9 => 'Green',
    10 => 'Metallic Rose',
    11 => 'Metallic Silver',
    12 => 'Onyx',
    13 => 'Onyx Black',
    14 => 'Platinum',
    15 => 'Polar White',
    16 => 'Red',
    17 => 'Silver',
    18 => 'Teal',
    19 => 'Titanium',
    20 => 'White',
  ),
) ?>