<?php return array (
  'SubcategoryID' => 2946,
  'SubcategoryName' => 'RangeExtenders',
  'PropertyName' => 'WLREBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Amped Wireless',
    1 => 'ARRIS',
    2 => 'ARRIS / Motorola',
    3 => 'ASUS',
    4 => 'BELKIN',
    5 => 'Buffalo',
    6 => 'Comtrend',
    7 => 'D-Link',
    8 => 'Diamond Multimedia',
    9 => 'EDIMAX',
    10 => 'ENCORE',
    11 => 'EnGenius',
    12 => 'HAWKING',
    13 => 'HooToo',
    14 => 'IOGEAR',
    15 => 'LINKSYS',
    16 => 'MANHATTAN',
    17 => 'NetComm',
    18 => 'NETGEAR',
    19 => 'Netis',
    20 => 'On Networks',
    21 => 'ReadyNet',
    22 => 'Rosewill',
    23 => 'Sabrent',
    24 => 'SIIG',
    25 => 'StarTech',
    26 => 'Tenda',
    27 => 'TP-Link',
    28 => 'TRENDnet',
    29 => 'WD',
    30 => 'ZyXEL',
  ),
) ?>