<?php return array (
  'SubcategoryID' => 2850,
  'SubcategoryName' => 'HIPictureLights',
  'PropertyName' => 'HIPictureLightsType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Adjustable',
    1 => 'Arc Lamp',
    2 => 'Banker',
    3 => 'Battery Operated',
    4 => 'Buffet Lamp',
    5 => 'Cable Fixtures',
    6 => 'Cable Systems',
    7 => 'Clip On',
    8 => 'Directional Spotlights',
    9 => 'Floor Lamp With Table',
    10 => 'Hugger',
    11 => 'Lamp Sets',
    12 => 'Light Therapy',
    13 => 'Line Voltage',
    14 => 'Low Profile',
    15 => 'Low Voltage',
    16 => 'Magnifier',
    17 => 'Monorail',
    18 => 'Multi Shade',
    19 => 'Multi-directional',
    20 => 'New Construction',
    21 => 'Outdoor',
    22 => 'Pharmacy Lamp',
    23 => 'Picture Frame',
    24 => 'Plug In',
    25 => 'Remodel',
    26 => 'Rope',
    27 => 'Sloped Housings',
    28 => 'Swing Arm',
    29 => 'Switch - Pull Chain',
    30 => 'Task Lamp',
    31 => 'Torchiere',
    32 => 'Track Accessories',
    33 => 'Track Connectors',
    34 => 'Track Systems',
    35 => 'With Light Kit',
    36 => 'Without Light Kit',
  ),
) ?>