<?php return array (
  'SubcategoryID' => 3138,
  'SubcategoryName' => 'WeddingAnniversaryRings',
  'PropertyName' => 'EWRingGemClarity',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'E1-E3',
    1 => 'Excellent',
    2 => 'Fair',
    3 => 'FI',
    4 => 'Fine',
    5 => 'Good',
    6 => 'HI1',
    7 => 'HI2',
    8 => 'I1',
    9 => 'I2-I3',
    10 => 'LI1',
    11 => 'LI2',
    12 => 'MI1',
    13 => 'MI2',
    14 => 'SI1',
    15 => 'SI2',
    16 => 'Very Good',
    17 => 'VS',
    18 => 'VVS',
  ),
) ?>