<?php return array (
  'SubcategoryID' => 3138,
  'SubcategoryName' => 'WeddingAnniversaryRings',
  'PropertyName' => 'EWRingWeddingBandStyle',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '3 Stone',
    1 => 'Beveled Edge',
    2 => 'Braided',
    3 => 'Channel',
    4 => 'Comort/EZ Fit',
    5 => 'Curved',
    6 => 'Domed',
    7 => 'Double Halo',
    8 => 'Eternity',
    9 => 'Fancy',
    10 => 'Filigree',
    11 => 'Flat',
    12 => 'Gemstones',
    13 => 'Half Round',
    14 => 'Halo',
    15 => 'Milgrain',
    16 => 'Pave',
    17 => 'Tapered',
    18 => 'Two-Toned',
  ),
) ?>