<?php return array (
  'SubcategoryID' => 3269,
  'SubcategoryName' => 'HLWindowTreatments',
  'PropertyName' => 'HLWindowTreatmentMaterial',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Bamboo',
    1 => 'Canvas',
    2 => 'Chenille',
    3 => 'Cotton',
    4 => 'Cotton Blend',
    5 => 'Denim',
    6 => 'Faux Silk',
    7 => 'Faux Wood',
    8 => 'Jute',
    9 => 'Linen',
    10 => 'Microfiber',
    11 => 'Modal',
    12 => 'Nylon',
    13 => 'Organic Cotton',
    14 => 'Plastic',
    15 => 'Polyester',
    16 => 'Polyester Blend',
    17 => 'Rattan',
    18 => 'Rayon',
    19 => 'Sateen',
    20 => 'Silk',
    21 => 'Silk Blend',
    22 => 'Synthetic',
    23 => 'Velvet',
    24 => 'Vinyl',
    25 => 'Wood',
  ),
) ?>