<?php return array (
  'SubcategoryID' => 2137,
  'SubcategoryName' => 'HWMassageRelaxation',
  'PropertyName' => 'HWMassageModel',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Adjustable',
    1 => 'Big Bend',
    2 => 'Coarse Foam',
    3 => 'Fine Foam',
    4 => 'Firm',
    5 => 'Firm Density',
    6 => 'Full Round',
    7 => 'Gentle',
    8 => 'Half Round',
    9 => 'Long',
    10 => 'N/A',
    11 => 'Non-Adjustable',
    12 => 'Pediatric',
    13 => 'Soft Density',
    14 => 'Standard',
    15 => 'Standard Density',
    16 => 'Travel',
    17 => 'w/ Professional Package',
    18 => 'w/ Respiratory Package',
  ),
) ?>