<?php return array (
  'SubcategoryID' => 357,
  'SubcategoryName' => 'GPSNavigation',
  'PropertyName' => 'CNETGPSMemoryCardCapacity',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '1.5GB SD',
    1 => '128MB microSD',
    2 => '128MB SD',
    3 => '1GB CF',
    4 => '1GB miniSD',
    5 => '1GB SD',
    6 => '256MB SD',
    7 => '2GB CF',
    8 => '2GB SD',
    9 => '32GB microSD',
    10 => '32GB miniSD',
    11 => '32MB SD',
    12 => '512MB microSD',
    13 => '64MB microSD',
  ),
) ?>