<?php return array (
  'SubcategoryID' => 357,
  'SubcategoryName' => 'GPSNavigation',
  'PropertyName' => 'CNETGPSSupportedFormats',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'AVI, MP4, OGG, ASF, Mpeg, Divx, Xvid, Mpeg1, M-JPE',
    1 => 'JPEG',
    2 => 'MP3',
    3 => 'MP3, AVI, MP4, MOV, ASF, WMV, WAV, WMA, JPEG, BMP',
    4 => 'MP3, JPEG',
    5 => 'MP3, MAV, MPEG4, AVI, GIF, JPG, PNG',
    6 => 'MP3, MPEG4',
    7 => 'MP3, MPEG4, JPEG',
    8 => 'MP3, OGG',
    9 => 'MP3, WAV, MPEG, WMV, ASF, JPEG, BMP, TXT',
    10 => 'MP3, WAV, WMA, ASF, AVI, MID, JPEG, BMP',
    11 => 'MP3, WKA, WKV, MP4, AVI, ASF, OGG, OGM and JPEG',
    12 => 'MP3, WMA, JPEG',
    13 => 'MP3, WMA, JPEG, BMP',
    14 => 'MP3, WMA, MAV, OGG, MPEG4, AVI, GIF, JPG, TIFF',
    15 => 'MP3, WMA, WMV, MPEG, AVI, JPEG, BMP',
    16 => 'MP3, WMA, WMV, MPEG4 and JPEG',
    17 => 'MP3, WMA, WMV, MPEG4, AVI, and JPEG',
    18 => 'MP3, WMA, WMV, MPEG4, DIVX, XVID, MPEG2, JPG, GIF,',
    19 => 'WMA,MP3, AVI, WMV, ASF, DAT, MPEG, MPG, MOV, TXT,',
    20 => 'WMA,MP3, WMV, MPEG 2 , JPG, GIF, BMP,  PNG, TXT',
    21 => 'WMV, WMA, MP3',
  ),
) ?>