<?php return array (
  'SubcategoryID' => 357,
  'SubcategoryName' => 'GPSNavigation',
  'PropertyName' => 'CNETGPSReceiver',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '12 channel GPS receiver',
    1 => '14 channel GPS receiver',
    2 => '16 channel GPS receiver',
    3 => '18 channel GPS receiver',
    4 => '20 channel GPS receiver',
    5 => '22 channel GPS receiver',
    6 => '24 channel GPS receiver',
    7 => '32 channel GPS receiver',
    8 => '42 channel GPS receiver',
    9 => '8 channel GPS receiver',
    10 => 'Centrality Atlas III',
    11 => 'High-sensitivity receiver',
    12 => 'MTK',
    13 => 'MTK MT3318',
    14 => 'RDS-TMC',
    15 => 'SiRF Atlas IV',
    16 => 'SiRF InstantFix II',
    17 => 'SiRFstarII',
    18 => 'SiRFstarIII',
    19 => 'TrueFix',
  ),
) ?>