<?php return array (
  'SubcategoryID' => 1548,
  'SubcategoryName' => 'ChildrensSocksTights',
  'PropertyName' => 'ChildrensSocksColor',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 1,
  'IsRequired' => 1,
  'PropertyValueList' => 
  array (
    0 => 'Army Green',
    1 => 'Beige',
    2 => 'Black',
    3 => 'Blue',
    4 => 'Brown',
    5 => 'Burgundy',
    6 => 'Clear',
    7 => 'Coral',
    8 => 'Dark Blue',
    9 => 'Dark Green',
    10 => 'Gold',
    11 => 'Green',
    12 => 'Grey',
    13 => 'Ivory',
    14 => 'Khaki',
    15 => 'Light Blue',
    16 => 'Light Green',
    17 => 'Light Pink',
    18 => 'Metallic',
    19 => 'Multi-Color',
    20 => 'Navy Blue',
    21 => 'Orange',
    22 => 'Pink',
    23 => 'Platinum',
    24 => 'Purple',
    25 => 'Red',
    26 => 'Silver',
    27 => 'Skull',
    28 => 'Strawberry',
    29 => 'Taupe',
    30 => 'Teal',
    31 => 'White',
    32 => 'Yellow',
  ),
) ?>