<?php return array (
  'SubcategoryID' => 749,
  'SubcategoryName' => 'VacuumFloorCareAccessories',
  'PropertyName' => 'FloorCareAccType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Battery',
    1 => 'Brushroll',
    2 => 'Carpet Extractor Accessories',
    3 => 'Cleaning Kit',
    4 => 'Cleaning Pad',
    5 => 'Clutch Plates & Pad Holders',
    6 => 'Concrete Preparation Tools',
    7 => 'Drum-Top Vacuum Heads',
    8 => 'Floor Machine Accessories',
    9 => 'Floor Machine Pads',
    10 => 'Part',
    11 => 'Rotary Brushes & Pad Drivers',
    12 => 'Vacuum Accessory Kits',
    13 => 'Vacuum Attachments & Accessories',
    14 => 'Vacuum Bag',
    15 => 'Vacuum Belt',
    16 => 'Vacuum Blower Motors',
    17 => 'Vacuum Filter',
    18 => 'Vacuum Hoses',
  ),
) ?>