<?php return array (
  'SubcategoryID' => 3223,
  'SubcategoryName' => 'GolfElectronics',
  'PropertyName' => 'CNETGPSOperatingSystem',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Garmin',
    1 => 'Linux',
    2 => 'maemo Linux based OS2008',
    3 => 'OS 2.6.x Linux',
    4 => 'Palm OS 5.0',
    5 => 'Palm OS 5.2.1',
    6 => 'Windows CE 4.2',
    7 => 'Windows CE.5.0',
    8 => 'Windows CE.6.0',
    9 => 'Windows CE.NET',
    10 => 'Windows CE.NET 4.2',
    11 => 'Windows CE.NET 5.0',
    12 => 'Windows CE.NET 6.0',
    13 => 'Windows Mobile 2003',
    14 => 'Windows Mobile 2003 Premium Edition',
    15 => 'Windows Mobile 2003 Second Edition',
    16 => 'Windows Mobile 5.0',
    17 => 'Windows MobileTM Pocket PC operating system',
    18 => 'Windows XP',
  ),
) ?>