<?php return array (
  'SubcategoryID' => 3223,
  'SubcategoryName' => 'GolfElectronics',
  'PropertyName' => 'GolfElectronicsColor',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Beige',
    1 => 'Black',
    2 => 'Black/Red',
    3 => 'Blue',
    4 => 'Brown',
    5 => 'Burgundy',
    6 => 'Camo and Brown',
    7 => 'Charcoal',
    8 => 'Clear',
    9 => 'Coral',
    10 => 'Dark Blue',
    11 => 'Dark Green',
    12 => 'Gold',
    13 => 'GPS',
    14 => 'Green',
    15 => 'Grey',
    16 => 'Ivory',
    17 => 'Khaki',
    18 => 'Light Blue',
    19 => 'Light Green',
    20 => 'Metallic',
    21 => 'Multi-Color',
    22 => 'Orange',
    23 => 'Pink',
    24 => 'Platinum',
    25 => 'Purple',
    26 => 'Red',
    27 => 'Silver',
    28 => 'Teal',
    29 => 'White',
    30 => 'White/Blue',
    31 => 'White/Gold',
    32 => 'Yellow',
  ),
) ?>