<?php return array (
  'SubcategoryID' => 421,
  'SubcategoryName' => 'PCCardsPCMCIAAddonCards',
  'PropertyName' => 'PCMCIACardType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Accessories',
    1 => 'eSATA ExpressCard',
    2 => 'ExpressCard Reader',
    3 => 'ExpressCard to CardBus',
    4 => 'ExpressCard to PCMCIA Card',
    5 => 'IEEE 1394 ExpressCard',
    6 => 'IEEE 1394 PCMCIA Card',
    7 => 'LAN ExpressCard',
    8 => 'Paralle Port ExpressCard',
    9 => 'Parallel Ports PCMCIA Card',
    10 => 'PCMCIA Card Reader',
    11 => 'PCMCIA Sound Card',
    12 => 'PCMCIA to ExpressCard',
    13 => 'SATA PCMCIA Card',
    14 => 'SATAII ExpressCard',
    15 => 'SCSI CardBus PC Card',
    16 => 'Serial + Paralle Ports ExpressCard',
    17 => 'Serial + Paralle Ports PCMCIA Card',
    18 => 'Serial Ports CompactFlash Card',
    19 => 'Serial Ports ExpressCard',
    20 => 'Serial Ports PCMCIA Card',
    21 => 'TV Tuner PCMCIA Card',
    22 => 'USB + LAN PCMCIA Card',
    23 => 'USB / IEEE 1394 ExpressCard',
    24 => 'USB / IEEE 1394 PCMCIA Card',
    25 => 'USB / SATA ExpressCard',
    26 => 'USB / SATA PCMCIA Card',
    27 => 'USB ExpressCard',
    28 => 'USB PCMCIA Card',
  ),
) ?>