<?php return array (
  'SubcategoryID' => 538,
  'SubcategoryName' => 'NotebookBatteriesACAdapters',
  'PropertyName' => 'NBBATTBatteryType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '12 Cell Lithium-Ion',
    1 => '2 Cell Lithium-Ion',
    2 => '3 Cell Lithium Polymer',
    3 => '3 Cell Lithium-Ion',
    4 => '4 Cell Lithium-Ion',
    5 => '6 Cell Lithium Polymer',
    6 => '6 Cell Lithium-Ion',
    7 => '7 Cell Lithium-Ion',
    8 => '8 Cell Lithium-Ion',
    9 => '9 Cell Lithium Polymer',
    10 => '9 Cell Lithium-Ion',
    11 => 'Lithium Polymer',
    12 => 'Lithium-Ion',
    13 => 'Nickel-Metal Hydride',
  ),
) ?>