<?php return array (
  'SubcategoryID' => 1761,
  'SubcategoryName' => 'NurseryFurniture',
  'PropertyName' => 'NurseryFurnitureType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Bassinets & Cradles',
    1 => 'Bean Bags',
    2 => 'Bookcases & Hutches',
    3 => 'Changing Tables',
    4 => 'Chests & Nightstands',
    5 => 'Cribs',
    6 => 'Dressers',
    7 => 'Furniture Accessories',
    8 => 'Gliders & Ottomans',
    9 => 'Hampers & Laundry Sorters',
    10 => 'Kids\' Rockers & Recliners',
    11 => 'Kids\' Workspaces, Desks & Chairs',
    12 => 'Mattresses',
    13 => 'Sleepers & Soothers',
    14 => 'Toddler Bed',
    15 => 'Twin & Full Beds',
    16 => 'Vanities & Mirrors',
  ),
) ?>