<?php return array (
  'SubcategoryID' => 733,
  'SubcategoryName' => 'HairStylingTools',
  'PropertyName' => 'HairCareBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'andis',
    1 => 'Babyliss',
    2 => 'Babyliss For Men',
    3 => 'BaBylissPro',
    4 => 'Bed Head',
    5 => 'Braun',
    6 => 'Carteret',
    7 => 'CONAIR',
    8 => 'Helen of Troy',
    9 => 'impress',
    10 => 'John Frieda',
    11 => 'Journey\'s Edge',
    12 => 'Laila Ali',
    13 => 'Matrix Men',
    14 => 'Michael Mercier',
    15 => 'Norelco',
    16 => 'Panasonic',
    17 => 'PHILIPS',
    18 => 'Philips Norelco',
    19 => 'Pro Beauty',
    20 => 'Pursonic',
    21 => 'Ragalta',
    22 => 'REMINGTON',
    23 => 'REVLON',
    24 => 'Roman',
    25 => 'Rosewill',
    26 => 'Toni & Guy',
    27 => 'Topstyler',
    28 => 'Verilux',
    29 => 'Viatek',
    30 => 'VIDAL SASSOON',
    31 => 'WAHL',
  ),
) ?>