<?php return array (
  'SubcategoryID' => 1982,
  'SubcategoryName' => 'OGGardenDecorStatues',
  'PropertyName' => 'OGGardenDecorType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Decorative Urns',
    1 => 'Gazing Balls & Stands',
    2 => 'Hanging Décor',
    3 => 'Pagodas',
    4 => 'Pedestals',
    5 => 'Rain Gauges',
    6 => 'Rainbow Makers',
    7 => 'Statues',
    8 => 'Stepping Stones',
    9 => 'Sun Dials',
    10 => 'Tree People & Doors',
    11 => 'Wall Décor',
    12 => 'Weathervanes',
    13 => 'Wind Chimes',
    14 => 'Wind Socks',
    15 => 'Yard Signs & Plaques',
  ),
) ?>