<?php return array (
  'SubcategoryID' => 851,
  'SubcategoryName' => 'HomeAutomationSmartSensorsAccessories',
  'PropertyName' => 'SURHAColor',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Almond',
    1 => 'Antique Brass',
    2 => 'Black',
    3 => 'Black/Brass',
    4 => 'Black/Nickled Brass',
    5 => 'Blue',
    6 => 'Bright Brass',
    7 => 'Bronze',
    8 => 'Brown',
    9 => 'Champagne',
    10 => 'Chrome',
    11 => 'Dark Gray',
    12 => 'Gray',
    13 => 'Green',
    14 => 'Ivory',
    15 => 'Light Almond',
    16 => 'N/A',
    17 => 'Oil-Rubbed Bronze',
    18 => 'Orange',
    19 => 'Pink',
    20 => 'Polished Brass',
    21 => 'Red',
    22 => 'RGB',
    23 => 'Satin Nickel',
    24 => 'Silver',
    25 => 'Venetian Bronze',
    26 => 'White',
    27 => 'Yellow',
  ),
) ?>