<?php return array (
  'SubcategoryID' => 2838,
  'SubcategoryName' => 'CablesUSBCables',
  'PropertyName' => 'USBCableConnectorType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Lighting Connector to USB A',
    1 => 'Micro USB to Mini USB',
    2 => 'Micro USB to USB A',
    3 => 'Micro USB to USB B',
    4 => 'Mini USB to Micro USB',
    5 => 'Mini USB to USB A',
    6 => 'Mini USB to USB B',
    7 => 'USB A to Micro USB',
    8 => 'USB A to Micro USB & Mini USB',
    9 => 'USB A to Mini USB',
    10 => 'USB A to USB A',
    11 => 'USB A to USB B',
    12 => 'USB A to USB C',
    13 => 'USB B to Micro USB',
    14 => 'USB B to Mini USB',
    15 => 'USB B to USB A',
    16 => 'USB B to USB B',
    17 => 'USB C to Micro USB',
    18 => 'USB C to USB A',
    19 => 'USB C to USB B',
    20 => 'USB C to USB C',
  ),
) ?>