<?php return array (
  'SubcategoryID' => 1659,
  'SubcategoryName' => 'CycleParts',
  'PropertyName' => 'CyclePartsType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Bearings',
    1 => 'Brakes',
    2 => 'Cables',
    3 => 'Drivetrain Components',
    4 => 'Forks & Shocks',
    5 => 'Frames',
    6 => 'Freewheels & Cassettes',
    7 => 'Handle Bars',
    8 => 'Hub',
    9 => 'Pedal',
    10 => 'Rims',
    11 => 'Saddles, Seats & Seat Posts',
    12 => 'Spokes',
    13 => 'Stands',
    14 => 'Stems',
    15 => 'Tires',
    16 => 'Track Cogs',
    17 => 'Tubes',
    18 => 'Wheels',
  ),
) ?>