<?php return array (
  'SubcategoryID' => 714,
  'SubcategoryName' => 'PressureCookers',
  'PropertyName' => 'PressureCookerBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Big Boss',
    1 => 'Black & Decker',
    2 => 'Brentwood',
    3 => 'Cuisinart',
    4 => 'Deni',
    5 => 'Elite',
    6 => 'Emson',
    7 => 'Fagor',
    8 => 'HOMEIMAGE',
    9 => 'Imusa',
    10 => 'Instant Pot',
    11 => 'Magefesa',
    12 => 'Master Chef',
    13 => 'MAXI-MATIC',
    14 => 'Midea',
    15 => 'Mirro',
    16 => 'Nesco',
    17 => 'NutriChef',
    18 => 'Oster',
    19 => 'PRESTO',
    20 => 'Rosewill',
    21 => 'SilverStone',
    22 => 'T-fal',
    23 => 'TATUNG',
    24 => 'Tayama',
    25 => 'Tristar',
    26 => 'Vasconia',
    27 => 'West Bend',
  ),
) ?>