<?php return array (
  'SubcategoryID' => 411,
  'SubcategoryName' => 'LCDTV',
  'PropertyName' => 'LCDTVCabinetColor',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Berry',
    1 => 'Black',
    2 => 'Black/White',
    3 => 'Blue',
    4 => 'Brown',
    5 => 'Charcoal Black',
    6 => 'Dark Java Brown',
    7 => 'Glossy Piano Black',
    8 => 'Gray',
    9 => 'Green',
    10 => 'High Gloss Black',
    11 => 'Matte Black',
    12 => 'Orange',
    13 => 'Piano Black',
    14 => 'Pink',
    15 => 'Red',
    16 => 'Rose Black',
    17 => 'Silver',
    18 => 'Silver / Black',
    19 => 'White',
  ),
) ?>