<?php return array (
  'SubcategoryID' => 2849,
  'SubcategoryName' => 'HISwingArms',
  'PropertyName' => 'HISwingArmsType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Adjustable',
    1 => 'Arc Lamp',
    2 => 'Banker',
    3 => 'Bathroom',
    4 => 'Battery Operated',
    5 => 'Clip On',
    6 => 'Directional Spotlights',
    7 => 'Multi Shade',
    8 => 'Multi-Directional',
    9 => 'Outdoor',
    10 => 'Pharmacy Lamp',
    11 => 'Plug In',
    12 => 'Switch - Pull Chain',
    13 => 'Task Lamp',
  ),
) ?>