<?php return array (
  'SubcategoryID' => 2170,
  'SubcategoryName' => 'HLCookware',
  'PropertyName' => 'HLCookwareType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 1,
  'PropertyValueList' => 
  array (
    0 => 'Braisers & Paella Pans',
    1 => 'Casseroles',
    2 => 'Chef\'s Pan',
    3 => 'Chefs Pans',
    4 => 'Cocotte',
    5 => 'Deep Fry Pan',
    6 => 'Double Broilers',
    7 => 'Dutch Ovens',
    8 => 'French Oven',
    9 => 'Fry Pan',
    10 => 'Frying Pans & Skillets',
    11 => 'Griddle Pans',
    12 => 'Grill Pan',
    13 => 'Kettle',
    14 => 'Lasagna Pans',
    15 => 'Low Stockpot',
    16 => 'Meatloaf Pans',
    17 => 'Microwave Cookware',
    18 => 'Mixed Sets',
    19 => 'Pasta Inserts',
    20 => 'Pizza Pans',
    21 => 'Quiche Pans',
    22 => 'Roasting Pans',
    23 => 'Saucepan',
    24 => 'Saucepans',
    25 => 'Sauciers',
    26 => 'Saute Pans',
    27 => 'Sauteuses',
    28 => 'Sets',
    29 => 'Soup & Stock Pots',
    30 => 'Specialty Cookware',
    31 => 'Steamer Baskets',
    32 => 'Stockpot',
    33 => 'Terrines',
    34 => 'Woks & Stir Fry Pans',
  ),
) ?>