<?php return array (
  'SubcategoryID' => 3240,
  'SubcategoryName' => 'ECCircuitProtection',
  'PropertyName' => 'ECTerminationStyle',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Axial',
    1 => 'Axial Ribbon',
    2 => 'Cartridge',
    3 => 'Chassis',
    4 => 'Clip',
    5 => 'Disk',
    6 => 'Knife Blade',
    7 => 'Lug',
    8 => 'Microstrip',
    9 => 'Pin',
    10 => 'Plate',
    11 => 'Quick Connect',
    12 => 'Radial',
    13 => 'Radial Blade Plug In',
    14 => 'Screw',
    15 => 'SIP',
    16 => 'SMD/SMT',
    17 => 'Snap In',
    18 => 'Soldering Star',
    19 => 'Tab',
  ),
) ?>