<?php return array (
  'SubcategoryID' => 1510,
  'SubcategoryName' => 'ScarvesShawls',
  'PropertyName' => 'ScarvesShawlsColorMapping',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 1,
  'PropertyValueList' => 
  array (
    0 => 'Beige',
    1 => 'Beige / Brown / Pink',
    2 => 'Black',
    3 => 'Blue',
    4 => 'Blue / White',
    5 => 'Blue / White / Yellow',
    6 => 'Brown',
    7 => 'Burgundy',
    8 => 'Clear',
    9 => 'Coral',
    10 => 'Dark Blue',
    11 => 'Dark Green',
    12 => 'Gold',
    13 => 'Green',
    14 => 'Grey',
    15 => 'Ivory',
    16 => 'Khaki',
    17 => 'Light Blue',
    18 => 'Light Green',
    19 => 'Maroon',
    20 => 'Metallic',
    21 => 'Multi-Color',
    22 => 'Orange',
    23 => 'Pink',
    24 => 'Pink / Orange',
    25 => 'Pink / Red / Burgundy',
    26 => 'Platinum',
    27 => 'Purple',
    28 => 'Red',
    29 => 'Silver',
    30 => 'Teal',
    31 => 'White',
    32 => 'Yellow',
  ),
) ?>