<?php return array (
  'SubcategoryID' => 2094,
  'SubcategoryName' => 'HIFasteners',
  'PropertyName' => 'HIFastenersHeadType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Bugle',
    1 => 'Combo Round Head',
    2 => 'Combo Truss Head',
    3 => 'Countersinking',
    4 => 'Cupped',
    5 => 'Flat',
    6 => 'Phillips Flat Head',
    7 => 'Phillips Oval Head',
    8 => 'Phillips Pan Head',
    9 => 'Phillips Truss Head',
    10 => 'Round',
    11 => 'Slotted Flat Head',
    12 => 'Slotted Hex Washer Head Type F',
    13 => 'Slotted Oval Head',
    14 => 'Slotted Round Head',
    15 => 'Slotted Truss Head',
    16 => 'Square',
    17 => 'Torx Flat Head Type F',
    18 => 'Torx Pan Head Type F',
    19 => 'Trim',
  ),
) ?>