<?php return array (
  'SubcategoryID' => 2094,
  'SubcategoryName' => 'HIFasteners',
  'PropertyName' => 'HIFastenersType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Anchors',
    1 => 'Assortment & Kits',
    2 => 'Bolts',
    3 => 'Collars & Couplings',
    4 => 'End Caps & Screw Protectors',
    5 => 'Hook & Loop Fasteners',
    6 => 'Nails',
    7 => 'Nuts',
    8 => 'Pins',
    9 => 'Rivets',
    10 => 'Screw Pins',
    11 => 'Screws',
    12 => 'Specialty Fasteners',
    13 => 'Spikes',
    14 => 'Tacks',
    15 => 'Threaded Rods',
    16 => 'Turnbuckles',
    17 => 'Velcro',
    18 => 'Washers',
  ),
) ?>