<?php return array (
  'SubcategoryID' => 1789,
  'SubcategoryName' => 'HISoldering',
  'PropertyName' => 'HISolderingType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Cleaning',
    1 => 'Flux',
    2 => 'Flux Dispensers',
    3 => 'Flux Removers',
    4 => 'Gun',
    5 => 'Iron',
    6 => 'Pencil',
    7 => 'Solder',
    8 => 'Solder Elements',
    9 => 'Soldering & Desoldering Stations',
    10 => 'Soldering Accessories',
    11 => 'Soldering Flux',
    12 => 'Soldering Guns, Irons & Stations',
    13 => 'Soldering Iron Testers',
    14 => 'Soldering Kits',
    15 => 'Soldering Tips',
    16 => 'Swabs & Applicators',
    17 => 'Wood Burning Tool',
  ),
) ?>