<?php return array (
  'SubcategoryID' => 674,
  'SubcategoryName' => 'BreadMakers',
  'PropertyName' => 'BreadmakerBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Black & Decker',
    1 => 'BONJOUR',
    2 => 'Breadman',
    3 => 'Conair',
    4 => 'Cuisinart',
    5 => 'DeLonghi',
    6 => 'Emeril',
    7 => 'Hamilton Beach',
    8 => 'NESCO',
    9 => 'Oster',
    10 => 'Panasonic',
    11 => 'RIVAL',
    12 => 'Rosewill',
    13 => 'Salton',
    14 => 'Sunbeam',
    15 => 'T-Fal',
    16 => 'VillaWare',
    17 => 'West Bend',
    18 => 'ZOJIRUSHI',
  ),
) ?>