<?php return array (
  'SubcategoryID' => 244,
  'SubcategoryName' => 'GameBoyAccessories',
  'PropertyName' => 'GBACCType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Adapter',
    1 => 'Armored Case',
    2 => 'Battery',
    3 => 'Case',
    4 => 'Charging Station',
    5 => 'Clip',
    6 => 'Face Plates',
    7 => 'Game Cases',
    8 => 'Grip',
    9 => 'Kit',
    10 => 'Light & Magnifier',
    11 => 'Link Cable',
    12 => 'Miscellaneous',
    13 => 'Other',
    14 => 'Power Cable',
    15 => 'Protector',
    16 => 'Screen Protector',
    17 => 'Sound',
    18 => 'Starter Kit',
    19 => 'Stylus',
  ),
) ?>