<?php return array (
  'SubcategoryID' => 1562,
  'SubcategoryName' => 'Games',
  'PropertyName' => 'GamesType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Action & Reflex',
    1 => 'Arcade',
    2 => 'Badminton & Volleyball',
    3 => 'Billiards',
    4 => 'Board Games',
    5 => 'Bocce',
    6 => 'Bowling',
    7 => 'Card Games',
    8 => 'Casino Games',
    9 => 'Checkers, Chess & Backgammon',
    10 => 'Cricket & Croquet ',
    11 => 'Darts',
    12 => 'Dice & Marbles',
    13 => 'Dominoes & Tiles',
    14 => 'Floor Games',
    15 => 'Foreign Language',
    16 => 'Game Tables',
    17 => 'Horseshoes ',
    18 => 'Kickball',
    19 => 'Learning & Educational',
    20 => 'Mystery',
    21 => 'Paddleball & Ping Pong',
    22 => 'Paintball',
    23 => 'Party Games',
    24 => 'Puzzles & Logic Games',
    25 => 'Replacement Parts & Upgrades',
    26 => 'Role Playing Games',
    27 => 'Sets',
    28 => 'Skill Games',
    29 => 'Sports',
    30 => 'Television & DVD Games',
    31 => 'Tetherball ',
  ),
) ?>