<?php return array (
  'SubcategoryID' => 3225,
  'SubcategoryName' => 'PrinterInkCartridgesAftermarket',
  'PropertyName' => 'CartridgesReplacementBrand',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Brother',
    1 => 'Canon',
    2 => 'Dell',
    3 => 'Dell, IBM',
    4 => 'Dell, IBM, Unisys',
    5 => 'Dell, Lexmark',
    6 => 'Dell, Lexmark, Sharp',
    7 => 'Epson',
    8 => 'Fujitsu',
    9 => 'HP',
    10 => 'HP, Canon',
    11 => 'HP, Troy',
    12 => 'IBM',
    13 => 'Imagistics',
    14 => 'Infoprint',
    15 => 'Infoprint, Dell',
    16 => 'Kodak',
    17 => 'Konica Minolta',
    18 => 'Kyocera',
    19 => 'Lexmark',
    20 => 'Listics',
    21 => 'Muratec',
    22 => 'Neopost',
    23 => 'Oki Data',
    24 => 'Panasonic',
    25 => 'Pantum',
    26 => 'Pitney Bowes',
    27 => 'Ricoh',
    28 => 'Samsung',
    29 => 'Sharp',
    30 => 'Source Technologies',
    31 => 'Toshiba',
    32 => 'Troy',
    33 => 'Xerox',
  ),
) ?>