<?php return array (
  'SubcategoryID' => 998,
  'SubcategoryName' => 'FloralArrangement',
  'PropertyName' => 'CraftTheme',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Alphabets',
    1 => 'Angels',
    2 => 'Animals/Pets',
    3 => 'Baby / Nursery',
    4 => 'Culture/International',
    5 => 'Fall/Harvest',
    6 => 'Family Milestones',
    7 => 'Family/Friends',
    8 => 'Fantasy/Fairies',
    9 => 'Flowers/Garden',
    10 => 'Holiday',
    11 => 'Kids/Juvenile',
    12 => 'Kitchen/Food',
    13 => 'Landscapes/Scenic',
    14 => 'Love/Romance',
    15 => 'Masculine',
    16 => 'Musical',
    17 => 'Samplers',
  ),
) ?>