<?php return array (
  'SubcategoryID' => 998,
  'SubcategoryName' => 'FloralArrangement',
  'PropertyName' => 'FloralType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 1,
  'PropertyValueList' => 
  array (
    0 => 'Artificial Birds & Nesting',
    1 => 'Baskets',
    2 => 'Bushes & Bouquets',
    3 => 'Containers & Wrappers',
    4 => 'Corsage & Boutonniere Supplies',
    5 => 'Drieds',
    6 => 'Floral Design Accessories',
    7 => 'Floral Picks, Sprays & Stems',
    8 => 'Fruits & Vegetables',
    9 => 'Garlands',
    10 => 'Greenery',
    11 => 'Leaves & Rose Petals',
    12 => 'Natural Grapevine',
    13 => 'Other Accessories',
    14 => 'Pip Berries',
    15 => 'Plants',
    16 => 'Roses',
    17 => 'Storage & Carriers',
    18 => 'Styrofoam & Floral Foam',
    19 => 'Treatments',
    20 => 'Trees',
    21 => 'Vase Fillers & Table Scatters',
    22 => 'Wreath Stands & Hangers',
    23 => 'Wreaths',
  ),
) ?>