<?php return array (
  'SubcategoryID' => 998,
  'SubcategoryName' => 'FloralArrangement',
  'PropertyName' => 'FloralMaterial',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Acrylic',
    1 => 'Angora',
    2 => 'Artificial',
    3 => 'Blend',
    4 => 'Cashmere',
    5 => 'Corduroy',
    6 => 'Cotton',
    7 => 'Crepe',
    8 => 'Denim',
    9 => 'Fleece',
    10 => 'Foam',
    11 => 'Gabardine',
    12 => 'Hemp',
    13 => 'Lace',
    14 => 'Leather/Suede',
    15 => 'Linen',
    16 => 'Lycra',
    17 => 'Mesh',
    18 => 'Microfiber',
    19 => 'Neoprene',
    20 => 'Nylon',
    21 => 'Other',
    22 => 'Paper',
    23 => 'Pique',
    24 => 'Plastic',
    25 => 'Polyester',
    26 => 'Rayon',
    27 => 'Satin',
    28 => 'Satin & Sateen',
    29 => 'Silk',
    30 => 'Terrycloth',
    31 => 'Tweed',
    32 => 'Velvet',
    33 => 'Vinyl/Latex',
    34 => 'Wood',
    35 => 'Wool',
  ),
) ?>