<?php return array (
  'SubcategoryID' => 277,
  'SubcategoryName' => 'SurveillanceAccessories',
  'PropertyName' => 'SCRTYSEQPMTType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Audio & Power Cable',
    1 => 'Audio Extension Card',
    2 => 'Audio/Video & Power Cable',
    3 => 'Audio/Video Extension Card',
    4 => 'Bag',
    5 => 'Camera Stand',
    6 => 'Connector',
    7 => 'Housing',
    8 => 'Inductive Sensor',
    9 => 'IR Illuminator',
    10 => 'Lens',
    11 => 'Management System',
    12 => 'Management System with Camera',
    13 => 'Monitor',
    14 => 'Mounting',
    15 => 'NVR',
    16 => 'Other',
    17 => 'Password Manager',
    18 => 'PoE Midspan',
    19 => 'PoE Splitter',
    20 => 'Power Adapter',
    21 => 'Power Convertor',
    22 => 'Power Extension Cable',
    23 => 'Power Supply',
    24 => 'Protective Housing',
    25 => 'Room Monitor',
    26 => 'Sensor Extender Cable',
    27 => 'Temperature Sensor',
    28 => 'Theft Deterrent Imitation Cam',
    29 => 'USB Cable',
    30 => 'USB Repeater Cable',
    31 => 'Video & Power Cable',
    32 => 'Video Cable',
    33 => 'Video Converter',
    34 => 'Video Encoder',
  ),
) ?>