<?php return array (
  'SubcategoryID' => 2116,
  'SubcategoryName' => 'HIWaterHeaterPartsAccessories',
  'PropertyName' => 'HIWaterHeaterPartsAccType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Anode Rod',
    1 => 'Blanket',
    2 => 'Connector',
    3 => 'Connector Kit',
    4 => 'Connectors',
    5 => 'Drain Kit',
    6 => 'Drain Pan',
    7 => 'Elbow',
    8 => 'Electric',
    9 => 'Elements',
    10 => 'Expansion Tank',
    11 => 'Pipe',
    12 => 'Power Vent Kit',
    13 => 'Rain Cap',
    14 => 'Relief Valve',
    15 => 'Roof Flashing',
    16 => 'Storm Collar',
    17 => 'Straps',
    18 => 'Tankless',
    19 => 'Thermostat',
    20 => 'Washing Machine Drip Pan',
    21 => 'Water Detectors',
    22 => 'Water Filter',
    23 => 'Water Heater Controls',
    24 => 'Water Heater Vents',
  ),
) ?>