<?php return array (
  'SubcategoryID' => 1888,
  'SubcategoryName' => 'OGFertilizersTreatments',
  'PropertyName' => 'OGFertilizersTreatmentsBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Akro Mills',
    1 => 'Austram',
    2 => 'Biobizz',
    3 => 'BioSafe Systems',
    4 => 'Black Gold',
    5 => 'Botanicare',
    6 => 'Contech',
    7 => 'Crystal Clear',
    8 => 'Dalen',
    9 => 'Danner',
    10 => 'DeWitt',
    11 => 'Earth Juice',
    12 => 'EarthBox',
    13 => 'Easy Gardener',
    14 => 'Gilmour',
    15 => 'Hudson',
    16 => 'Humboldt Nutrients',
    17 => 'Hydro Organics',
    18 => 'Hydrofarm',
    19 => 'Jiffy',
    20 => 'Lilly Miller',
    21 => 'Liquid Fence',
    22 => 'Luster Leaf',
    23 => 'Mars Fishcare',
    24 => 'Master Mark Plastics',
    25 => 'Mat',
    26 => 'Nutriculture',
    27 => 'Parker Mccrory',
    28 => 'RTI',
    29 => 'Sprayco',
    30 => 'Tetra Pond',
    31 => 'Xtreme Gardening',
  ),
) ?>