<?php return array (
  'SubcategoryID' => 1781,
  'SubcategoryName' => 'JewelryAccessories',
  'PropertyName' => 'JewelryAccessoriesOccasion',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Anniversary',
    1 => 'Birthday',
    2 => 'Christmas & Hanukkah',
    3 => 'Communion',
    4 => 'Congratulations',
    5 => 'Everyday',
    6 => 'Fathers Day',
    7 => 'Graduation',
    8 => 'Holiday',
    9 => 'Mothers Day',
    10 => 'New Baby',
    11 => 'Party',
    12 => 'Prom',
    13 => 'Quinceanera',
    14 => 'Seasonal',
    15 => 'Valentines Day',
    16 => 'Wedding',
  ),
) ?>