<?php return array (
  'SubcategoryID' => 3108,
  'SubcategoryName' => 'MTEnginePartsAccessories',
  'PropertyName' => 'MTEngineType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Air-Oil Separators',
    1 => 'Cams',
    2 => 'Covers & Protectors',
    3 => 'Crank Cases',
    4 => 'Cylinders & Pistons',
    5 => 'Engine Cooling Fans',
    6 => 'Engine Hardware',
    7 => 'Engine Performance Parts',
    8 => 'Flush Kits',
    9 => 'Gaskets & Seals',
    10 => 'Internal Motor Parts',
    11 => 'Lifts & Tappets',
    12 => 'Motor Mounts',
    13 => 'Oil Coolers',
    14 => 'Oil Filter Housings',
    15 => 'Oil Filter Mounting Hardware',
    16 => 'Oil Filters',
    17 => 'Oil Lines',
    18 => 'Oil Pumps',
    19 => 'Oil Seals',
    20 => 'Oil System Covers',
    21 => 'Oil System Gaskets',
    22 => 'Oil Valves & Plugs',
    23 => 'Other Accessories',
    24 => 'Pushrods',
    25 => 'Radiator Cap Covers',
    26 => 'Radiators',
    27 => 'Rocker Arms',
    28 => 'Water Pump',
  ),
) ?>