<?php return array (
  'SubcategoryID' => 644,
  'SubcategoryName' => 'ShelfSystems',
  'PropertyName' => 'CNETShelfSystemBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'ASTAR',
    1 => 'AUDIOVOX',
    2 => 'auvi',
    3 => 'Boston Acoustics',
    4 => 'Buslink',
    5 => 'COBY',
    6 => 'CROSLEY',
    7 => 'Denon',
    8 => 'Dual',
    9 => 'EMERSON',
    10 => 'Fisher',
    11 => 'Gemini',
    12 => 'GPX',
    13 => 'iLive',
    14 => 'Iluv',
    15 => 'iSymphony',
    16 => 'JENSEN',
    17 => 'JVC',
    18 => 'LASONIC',
    19 => 'LG',
    20 => 'MAGNAVOX',
    21 => 'Memorex',
    22 => 'NAKAMICHI',
    23 => 'ONKYO',
    24 => 'Panasonic',
    25 => 'PHILIPS',
    26 => 'Pioneer',
    27 => 'Polk Audio',
    28 => 'Pyle',
    29 => 'RCA',
    30 => 'RjTECH',
    31 => 'SAMSUNG',
    32 => 'SHARP',
    33 => 'SONY',
    34 => 'SUPERSONIC',
    35 => 'TEAC',
    36 => 'Yamaha',
  ),
) ?>