<?php return array (
  'SubcategoryID' => 3204,
  'SubcategoryName' => 'HLDiningTablesChairsSets',
  'PropertyName' => 'HLFurnitureMaterial',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Alder Wood',
    1 => 'Aluminum',
    2 => 'Ash Wood',
    3 => 'Bamboo',
    4 => 'Birch Wood',
    5 => 'Cast Iron',
    6 => 'Cherry Wood',
    7 => 'Fabric',
    8 => 'Faux Leather',
    9 => 'Glass',
    10 => 'HDF / Particle Board',
    11 => 'Iron',
    12 => 'Leather',
    13 => 'Light Density / Particle Board',
    14 => 'Linen',
    15 => 'Maple Wood',
    16 => 'Marble',
    17 => 'MDF / Particle Board',
    18 => 'Metal',
    19 => 'Metal & Glass',
    20 => 'Microfiber',
    21 => 'Natural Fiber',
    22 => 'Oak Wood',
    23 => 'Pine Wood',
    24 => 'Poplar Wood',
    25 => 'Rattan',
    26 => 'Reclaimed Wood',
    27 => 'Stainless Steel',
    28 => 'Stone',
    29 => 'Vinyl',
    30 => 'Wicker',
    31 => 'Wood',
    32 => 'Wood & Metal',
  ),
) ?>