<?php return array (
  'SubcategoryID' => 3204,
  'SubcategoryName' => 'HLDiningTablesChairsSets',
  'PropertyName' => 'HLFurnitureUpholsteryMaterial',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Cedar',
    1 => 'Chenille',
    2 => 'Chrome',
    3 => 'Cotton',
    4 => 'Fabric',
    5 => 'Faux Leather',
    6 => 'Foam',
    7 => 'Leather',
    8 => 'Linen',
    9 => 'Mahogany',
    10 => 'MDF',
    11 => 'Metal',
    12 => 'Microfiber',
    13 => 'Microsuede',
    14 => 'N/A',
    15 => 'Oak',
    16 => 'Pine',
    17 => 'Plastic',
    18 => 'Poly Synthetic Fiber',
    19 => 'Polyester',
    20 => 'Polyester Blend',
    21 => 'Polyester Linen Blend',
    22 => 'Polypropylene',
    23 => 'Softino Polyurethane',
    24 => 'Steel',
    25 => 'Suede',
    26 => 'Synthetic',
    27 => 'Synthetic Fiber',
    28 => 'Upholstered',
    29 => 'Velvet',
    30 => 'Veneer',
    31 => 'Vinyl',
    32 => 'Wood',
  ),
) ?>