<?php return array (
  'SubcategoryID' => 781,
  'SubcategoryName' => 'PortableCDPlayers',
  'PropertyName' => 'PortableCDPlayerBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'AUDIOVOX',
    1 => 'Auvi',
    2 => 'COBY',
    3 => 'Emerson',
    4 => 'Fisher',
    5 => 'GPX',
    6 => 'iriver',
    7 => 'Jensen',
    8 => 'JS Karaoke',
    9 => 'JVC',
    10 => 'jWIN',
    11 => 'Lasonic',
    12 => 'Magnavox',
    13 => 'Memorex',
    14 => 'Naxa',
    15 => 'Panasonic',
    16 => 'Philips',
    17 => 'QFX',
    18 => 'RCA',
    19 => 'SONY',
    20 => 'Supersonic',
    21 => 'TEAC',
  ),
) ?>