<?php return array (
  'SubcategoryID' => 730,
  'SubcategoryName' => 'OralCare',
  'PropertyName' => 'OralCareColor',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Amethyst',
    1 => 'Autism Speaks Edition',
    2 => 'Black',
    3 => 'Blue',
    4 => 'Candy Stripes',
    5 => 'Green',
    6 => 'Lavender',
    7 => 'Leopard',
    8 => 'Orange',
    9 => 'Pink',
    10 => 'Purple',
    11 => 'Red',
    12 => 'Rose Gold',
    13 => 'Silver',
    14 => 'Sky',
    15 => 'Twilight',
    16 => 'White',
    17 => 'Yellow',
  ),
) ?>