<?php return array (
  'SubcategoryID' => 730,
  'SubcategoryName' => 'OralCare',
  'PropertyName' => 'OralCareBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Acteh',
    1 => 'As Seen on TV',
    2 => 'Conair',
    3 => 'Dazzlepro',
    4 => 'germguardian',
    5 => 'GNC',
    6 => 'Great Smile Store',
    7 => 'kissMe',
    8 => 'METAPO',
    9 => 'O\'Nano',
    10 => 'Oral-B',
    11 => 'Panasonic',
    12 => 'PHILIPS',
    13 => 'Philips Sonicare',
    14 => 'Pursonic',
    15 => 'PYLE',
    16 => 'Ragalta',
    17 => 'Sonicare',
    18 => 'Verilux',
    19 => 'Viatek',
    20 => 'Vivitar',
    21 => 'Waterpik',
    22 => 'Watts Dental',
    23 => 'Watts Power',
  ),
) ?>