<?php return array (
  'SubcategoryID' => 2827,
  'SubcategoryName' => 'CablesPowerExtensionCords',
  'PropertyName' => 'AVCableType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Cable Connectors',
    1 => 'Cable Kits',
    2 => 'Cable Splitters',
    3 => 'Coax Cables',
    4 => 'DisplayPort Cable',
    5 => 'DVI Cables',
    6 => 'DVI to HDMI Cable',
    7 => 'DVI to VGA Cables',
    8 => 'Extension Cable',
    9 => 'HDMI Cables',
    10 => 'Others',
    11 => 'RCA Component',
    12 => 'RCA Composite',
    13 => 'S-Video Cables',
    14 => 'S-Video to BNC',
    15 => 'S-Video to Composite',
    16 => 'Speaker Wires',
    17 => 'Stereo Cables',
    18 => 'Subwoofer Cables',
    19 => 'Toslink Cables',
    20 => 'USB to HDMI',
    21 => 'VGA Cables',
    22 => 'XLR Cable',
  ),
) ?>