<?php return array (
  'SubcategoryID' => 537,
  'SubcategoryName' => 'NotebookPortReplicatorsDockingStations',
  'PropertyName' => 'GroupNBPortOption',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '2x DVI/HDMI/VGA',
    1 => 'Dual 4K Monitor - DP /TB3(USB-C)',
    2 => 'Dual Display',
    3 => 'Dual Monitor - 2xDP',
    4 => 'Dual Monitor - 2xDVI + HDMI / VGA Adapters',
    5 => 'Dual Monitor - 4K DP / HDMI',
    6 => 'Dual Monitor - 4K DP / HDMI - 2 Laptop KVM',
    7 => 'Dual Monitor - HDMI / DVI + VGA Adapter',
    8 => 'Dual Monitor - HDMI / DVI / VGA',
    9 => 'Dual Monitor - HDMI/TB2',
    10 => 'Dual Monitor – DVI/HDMI(4K)',
    11 => 'DVI',
    12 => 'HDMI/DVI',
    13 => 'HDMI/DVI/VGA',
    14 => 'Single Display',
    15 => 'Single HDMI + GbE',
    16 => 'Single HDMI or VGA +  USB 3.0 + GbE',
    17 => 'Single Monitor - 4K DP',
    18 => 'Single Monitor - DVI',
    19 => 'Single Monitor - HDMI',
    20 => 'Single VGA +  USB 3.0 + GbE',
    21 => 'Single VGA + GbE',
    22 => 'Triple Monitor - 2 x DP / HDMI',
    23 => 'TUD-300',
    24 => 'TUD-3000',
    25 => 'Ultrabook',
    26 => 'Windows 8 Tablet',
  ),
) ?>