<?php return array (
  'SubcategoryID' => 1887,
  'SubcategoryName' => 'OGSpecialtyGardenHandTools',
  'PropertyName' => 'OGSpecialtyToolsBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Ames',
    1 => 'Barnel',
    2 => 'Black & Decker',
    3 => 'Bond',
    4 => 'Corona',
    5 => 'Danner',
    6 => 'DeWitt',
    7 => 'Dramm',
    8 => 'Dynamic Design',
    9 => 'Fiskars',
    10 => 'Flexrake',
    11 => 'Garden Groom',
    12 => 'Jackson',
    13 => 'Picnic Pack',
    14 => 'Radius',
    15 => 'Stalwart',
    16 => 'TerraTrade',
    17 => 'True Temper',
    18 => 'Yard Butler',
  ),
) ?>