<?php return array (
  'SubcategoryID' => 738,
  'SubcategoryName' => 'BloodPressureMonitors',
  'PropertyName' => 'BPMonitorBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'A&D Medical',
    1 => 'Acteh',
    2 => 'Braun',
    3 => 'CITIZEN',
    4 => 'Drive Medical',
    5 => 'GNC',
    6 => 'HOMEDICS',
    7 => 'LUMISCOPE',
    8 => 'MARK OF FITNESS',
    9 => 'Medline',
    10 => 'North American Health + Wellness',
    11 => 'Omron',
    12 => 'Oregon Scientific',
    13 => 'Panasonic',
    14 => 'Proactive Medical',
    15 => 'PYLE',
    16 => 'QARDIO',
    17 => 'Rosewill',
    18 => 'Veridian',
    19 => 'Veridian Healthcare',
    20 => 'Withings',
    21 => 'WrisTech',
  ),
) ?>