<?php return array (
  'SubcategoryID' => 735,
  'SubcategoryName' => 'StraighteningIrons',
  'PropertyName' => 'HairStraightenerBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Andis',
    1 => 'BaBylissPro',
    2 => 'BED HEAD',
    3 => 'Cleaning Pad',
    4 => 'CONAIR',
    5 => 'EMSON',
    6 => 'Farouk CHI',
    7 => 'GHD',
    8 => 'Helen of Troy',
    9 => 'HOT TOOLS',
    10 => 'impress',
    11 => 'Laila Ali',
    12 => 'One \'n Only',
    13 => 'Pursonic',
    14 => 'REMINGTON',
    15 => 'REVLON',
    16 => 'SANYO',
    17 => 'VIDAL SASSOON',
    18 => 'Wahl',
  ),
) ?>