<?php return array (
  'SubcategoryID' => 552,
  'SubcategoryName' => 'MacStorage',
  'PropertyName' => 'MacStorageBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '3ware',
    1 => 'acomdata',
    2 => 'ADATA',
    3 => 'AKiTiO',
    4 => 'Apple',
    5 => 'APRICORN',
    6 => 'BUFFALO',
    7 => 'CalDigit',
    8 => 'Cavalry',
    9 => 'EZQUEST',
    10 => 'Fantom Drives',
    11 => 'FREECOM',
    12 => 'G-Technology',
    13 => 'HGST',
    14 => 'iomega',
    15 => 'ioSafe',
    16 => 'LACIE',
    17 => 'Macally',
    18 => 'Maxtor',
    19 => 'POCKETEC',
    20 => 'rocstor',
    21 => 'SANS DIGITAL',
    22 => 'Seagate',
    23 => 'SimpleTech',
    24 => 'SMARTDISK',
    25 => 'SoNNeT',
    26 => 'Toshiba',
    27 => 'Verbatim',
    28 => 'VOX',
    29 => 'WD',
  ),
) ?>