<?php return array (
  'SubcategoryID' => 1699,
  'SubcategoryName' => 'BallRacksStorage',
  'PropertyName' => 'BallRacksColor',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Beige',
    1 => 'Black',
    2 => 'Blue',
    3 => 'Brown',
    4 => 'Burgundy',
    5 => 'Cherrywood',
    6 => 'Clear',
    7 => 'Coral',
    8 => 'Dark Blue',
    9 => 'Dark Brown Maple',
    10 => 'Dark Green',
    11 => 'Gold',
    12 => 'Green',
    13 => 'Grey',
    14 => 'Ivory',
    15 => 'Khaki',
    16 => 'Light Blue',
    17 => 'Light Green',
    18 => 'Metallic',
    19 => 'Multi-Color',
    20 => 'Orange',
    21 => 'Pink',
    22 => 'Platinum',
    23 => 'Purple',
    24 => 'Red',
    25 => 'Silver',
    26 => 'Teal',
    27 => 'White',
    28 => 'Yellow',
  ),
) ?>