<?php return array (
  'SubcategoryID' => 2878,
  'SubcategoryName' => 'HLKitchenIslandsServingCarts',
  'PropertyName' => 'HIKitchenIslandscartsfinish',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Ash',
    1 => 'Birch',
    2 => 'Black',
    3 => 'Blue',
    4 => 'Brown',
    5 => 'Cherry',
    6 => 'Chestnut',
    7 => 'Chrome',
    8 => 'Clear',
    9 => 'Cream',
    10 => 'Distressed',
    11 => 'Espresso',
    12 => 'Gray',
    13 => 'Green',
    14 => 'Handpainted',
    15 => 'Honey',
    16 => 'Ivory',
    17 => 'Mahogany',
    18 => 'Maple',
    19 => 'Oak',
    20 => 'Orange',
    21 => 'Patina',
    22 => 'Pecan',
    23 => 'Pewter',
    24 => 'Pine',
    25 => 'Red',
    26 => 'Silver',
    27 => 'Stainless Steel',
    28 => 'Unfinished',
    29 => 'Walnut',
    30 => 'Weathered',
    31 => 'Wenge',
    32 => 'White',
    33 => 'Yellow',
  ),
) ?>