<?php return array (
  'SubcategoryID' => 2591,
  'SubcategoryName' => 'HLEntrywayHalls',
  'PropertyName' => 'HLEntrywayColorFinish',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 1,
  'IsRequired' => 1,
  'PropertyValueList' => 
  array (
    0 => 'As Shown',
    1 => 'Beige',
    2 => 'Black',
    3 => 'Blue',
    4 => 'Bronze',
    5 => 'Brown',
    6 => 'Burgundy',
    7 => 'Charcoal',
    8 => 'Clear',
    9 => 'Concrete',
    10 => 'Coral',
    11 => 'Dark Blue',
    12 => 'Dark Green',
    13 => 'Gold',
    14 => 'Gray',
    15 => 'Green',
    16 => 'Grey',
    17 => 'Ivory',
    18 => 'Kalahari Desert',
    19 => 'Khaki',
    20 => 'Light Blue',
    21 => 'Light Green',
    22 => 'Metallic',
    23 => 'Mount Olympus',
    24 => 'Multi-Color',
    25 => 'Orange',
    26 => 'Pink',
    27 => 'Platinum',
    28 => 'Purple',
    29 => 'Red',
    30 => 'Silver',
    31 => 'Slate Stone',
    32 => 'Tan',
    33 => 'Teal',
    34 => 'White',
    35 => 'Yellow',
  ),
) ?>