<?php return array (
  'SubcategoryID' => 3226,
  'SubcategoryName' => 'SportsActionCamcorders',
  'PropertyName' => 'ACType',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Bike pack',
    1 => 'Black Edition',
    2 => 'Body Only',
    3 => 'Bundle',
    4 => 'Close-Up Lens + Screen Package',
    5 => 'Close-Up Lens Package',
    6 => 'Golf pack',
    7 => 'No',
    8 => 'Pet pack',
    9 => 'Sea Dragon 1200 with Float Strap',
    10 => 'Sea Dragon 2000 Duo Kit Package',
    11 => 'Sea Dragon 2000 with Float Strap',
    12 => 'Sea Dragon 600 Micro Kit Package',
    13 => 'Sea Dragon Duo 2100 Dual Light Package',
    14 => 'Sea Dragon Duo 2500 Dual Light Package',
    15 => 'Sea Dragon Duo 5000 Light Package',
    16 => 'Sea Dragon Mini 650 Light Package',
    17 => 'Silver Edition',
    18 => 'White Edition',
    19 => 'with Screen Protector',
  ),
) ?>