<?php return array (
  'SubcategoryID' => 2159,
  'SubcategoryName' => 'BeautyEyes',
  'PropertyName' => 'BeautyEyesColor',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'As Shown',
    1 => 'Black',
    2 => 'Black Brown',
    3 => 'Charcoal',
    4 => 'Clear',
    5 => 'Cocoa',
    6 => 'Deep Brown',
    7 => 'Indigo Blue',
    8 => 'Lust',
    9 => 'Mink',
    10 => 'Not Just Nudes',
    11 => 'Orion',
    12 => 'Pink Chiffon',
    13 => 'Pure Black',
    14 => 'Purple',
    15 => 'Soft Blond',
    16 => 'Soft Gray',
    17 => 'Sterling Blue',
    18 => 'True Taupe',
  ),
) ?>