<?php return array (
  'SubcategoryID' => 2999,
  'SubcategoryName' => 'HLChairs',
  'PropertyName' => 'HIChairsCollection',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Andromeda',
    1 => 'Baby Spire',
    2 => 'Bounce',
    3 => 'Carbon',
    4 => 'Carnival',
    5 => 'Draper',
    6 => 'Drop',
    7 => 'Drop Lumen',
    8 => 'Fortress',
    9 => 'Game',
    10 => 'Neptune',
    11 => 'Phante',
    12 => 'Prospect Park',
    13 => 'Pup',
    14 => 'Singular',
    15 => 'Unico',
    16 => 'Union Jack',
    17 => 'Vital',
    18 => 'Xert',
  ),
) ?>