<?php return array (
  'SubcategoryID' => 2999,
  'SubcategoryName' => 'HLChairs',
  'PropertyName' => 'HIChairsmaterial',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'ABS',
    1 => 'Acrylic',
    2 => 'Aluminum',
    3 => 'Bamboo',
    4 => 'Bonded Leather',
    5 => 'Bycast Leather',
    6 => 'Fabric',
    7 => 'Faux Leather',
    8 => 'Fiberglass',
    9 => 'Laminate',
    10 => 'Leather',
    11 => 'Leatherette',
    12 => 'Mesh',
    13 => 'Metal',
    14 => 'Microfiber',
    15 => 'PE plastic',
    16 => 'Plastic',
    17 => 'Rattan',
    18 => 'Reclaimed Wood',
    19 => 'Seagrass',
    20 => 'Vinyl',
    21 => 'Wicker',
    22 => 'Wood',
    23 => 'Wood and Metal',
    24 => 'Wood Composites',
  ),
) ?>