<?php return array (
  'SubcategoryID' => 2999,
  'SubcategoryName' => 'HLChairs',
  'PropertyName' => 'HIChairstype',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 1,
  'PropertyValueList' => 
  array (
    0 => 'Accent Chairs',
    1 => 'Bean Bags',
    2 => 'Chaises',
    3 => 'Corner Chairs',
    4 => 'Director Chairs',
    5 => 'Folding',
    6 => 'Futons',
    7 => 'Gliders',
    8 => 'Height-Adjustable Chair',
    9 => 'Leather Chairs',
    10 => 'Parsons Chairs',
    11 => 'Rocking Chairs',
    12 => 'Settees',
    13 => 'Slipcovered',
    14 => 'Slipper Chairs',
    15 => 'Upholstered Chairs',
    16 => 'Video Gaming Chairs',
    17 => 'Wing Chairs',
  ),
) ?>