<?php return array (
  'SubcategoryID' => 1949,
  'SubcategoryName' => 'OGPlaysets',
  'PropertyName' => 'OGPlaysetsColor',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Black',
    1 => 'Blue',
    2 => 'Chocolate',
    3 => 'Cinnabar',
    4 => 'Cocoa',
    5 => 'Green',
    6 => 'Kiwi',
    7 => 'Natural/Light Brown Wood',
    8 => 'Navy',
    9 => 'Pink',
    10 => 'Purple',
    11 => 'Purple/Green',
    12 => 'Red',
    13 => 'Royal Blue',
    14 => 'Strawberry',
    15 => 'Tan',
    16 => 'White',
    17 => 'Yellow',
  ),
) ?>