<?php return array (
  'SubcategoryID' => 1951,
  'SubcategoryName' => 'OGPoolEquipmentSupplies',
  'PropertyName' => 'OGPoolAccType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Automatic Cleaners',
    1 => 'Boilers',
    2 => 'Filter',
    3 => 'Filter Replacement Cartridges',
    4 => 'Flotation Devices',
    5 => 'Hangers & Clips',
    6 => 'Ladders & Steps',
    7 => 'Pool & Spa Accessories',
    8 => 'Pool & Spa Covers',
    9 => 'Pool & Spa Filters',
    10 => 'Pool & Spa Fittings',
    11 => 'Pool & Spa Skimmers',
    12 => 'Pool Cleaner Pumps',
    13 => 'Pool Cover Pumps',
    14 => 'Pool Covers',
    15 => 'Pool Drain Covers',
    16 => 'Pool Heaters',
    17 => 'Pool Lifts',
    18 => 'Pool Light Fixtures',
    19 => 'Pool Light Junction Boxes',
    20 => 'Pool Liners',
    21 => 'Pool Maintenance Tools',
    22 => 'Pool Pump Motors',
    23 => 'Pool Pump/Filter Systems',
    24 => 'Pool Safety',
    25 => 'Public Pool Accessories',
    26 => 'Slide Spray Kits',
    27 => 'Spa & Hot Tub Heaters',
    28 => 'Spa Caddies',
    29 => 'Spa Replacement Parts',
    30 => 'Spa Steps',
    31 => 'Strainer',
  ),
) ?>