<?php return array (
  'SubcategoryID' => 3174,
  'SubcategoryName' => 'HLCuttingBoards',
  'PropertyName' => 'HLCuttingBoardMaterial',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Acacia Wood',
    1 => 'Bamboo',
    2 => 'Bamboo, TPE',
    3 => 'Cherry',
    4 => 'Composite',
    5 => 'Edge-Grain Wood',
    6 => 'Glass',
    7 => 'Hard Rock Maple',
    8 => 'Hardwood',
    9 => 'Maple',
    10 => 'Marble',
    11 => 'Marble/Granite',
    12 => 'Melamine',
    13 => 'Natural Wood Fibre Composite',
    14 => 'Polyethylene',
    15 => 'Polypropylene, TPE',
    16 => 'Slate',
    17 => 'Solid Hard Rock Maple',
    18 => 'Teak',
    19 => 'Tpe And Arkshell',
    20 => 'Walnut',
  ),
) ?>