<?php return array (
  'SubcategoryID' => 1918,
  'SubcategoryName' => 'HIRangeHoods',
  'PropertyName' => 'HIRangeHoodsColorFinish',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Almond',
    1 => 'Aluminum',
    2 => 'Antique Brushed Nickel',
    3 => 'Beige Granite',
    4 => 'Beige Quarry',
    5 => 'Biscuit',
    6 => 'Bisque',
    7 => 'Black',
    8 => 'Black Granite',
    9 => 'Blacksmith',
    10 => 'Brown',
    11 => 'Burnt Sienna',
    12 => 'Chestnut Bronze',
    13 => 'Chocolate Linen',
    14 => 'Copper Bronze Patina',
    15 => 'Estate Bronze',
    16 => 'Galvanized',
    17 => 'Glass',
    18 => 'Gray',
    19 => 'Heirloom Bronze',
    20 => 'Lace Circle',
    21 => 'Montero Granite',
    22 => 'Montesol Granite',
    23 => 'Napoli Granite',
    24 => 'Oil Rubbed Bronze',
    25 => 'Polished Brass',
    26 => 'Rapids',
    27 => 'Restoration Bronze',
    28 => 'Russell Square',
    29 => 'Silver Metallic',
    30 => 'Stainless Steel',
    31 => 'Tempered Glass',
    32 => 'Terra Cotta',
    33 => 'Terra Cotta Granite',
    34 => 'Triple Wave',
    35 => 'White',
    36 => 'White Linen',
  ),
) ?>