<?php return array (
  'SubcategoryID' => 3266,
  'SubcategoryName' => 'HLWallArtCoverings',
  'PropertyName' => 'HLWallArtStyle',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Art Deco',
    1 => 'Asian',
    2 => 'Coastal',
    3 => 'Contemporary',
    4 => 'Country',
    5 => 'Frameless',
    6 => 'Frameless Textile',
    7 => 'Holiday / Seasonal',
    8 => 'Impressionism',
    9 => 'Kids / Juvenile',
    10 => 'Lodge',
    11 => 'Retro',
    12 => 'Rustic',
    13 => 'Southwest',
    14 => 'Sports',
    15 => 'Traditional',
    16 => 'Transitional',
    17 => 'Tropical',
    18 => 'Vintage',
  ),
) ?>