<?php return array (
  'SubcategoryID' => 3266,
  'SubcategoryName' => 'HLWallArtCoverings',
  'PropertyName' => 'HLWallArtSubject',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Abstract',
    1 => 'Animals',
    2 => 'Architecture',
    3 => 'Children',
    4 => 'Cityscape',
    5 => 'Coca-Cola',
    6 => 'Figures',
    7 => 'Florals & Plants',
    8 => 'Food & Beverage',
    9 => 'Holiday / Seasonal',
    10 => 'Kitchen Art',
    11 => 'Landscapes / Scenery',
    12 => 'Maps',
    13 => 'Movies / Entertainment',
    14 => 'Music',
    15 => 'Nautical / Beach',
    16 => 'Patriotic',
    17 => 'People',
    18 => 'Places',
    19 => 'Spiritual',
    20 => 'Sports',
    21 => 'Still Life',
    22 => 'Transportation',
    23 => 'Typography',
    24 => 'Vintage',
  ),
) ?>