<?php return array (
  'SubcategoryID' => 3266,
  'SubcategoryName' => 'HLWallArtCoverings',
  'PropertyName' => 'HLWallArtColorMapping',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Beige',
    1 => 'Black',
    2 => 'Blue',
    3 => 'Brown',
    4 => 'Dark Blue',
    5 => 'Dark Green',
    6 => 'Gold',
    7 => 'Green',
    8 => 'Khaki',
    9 => 'Light Blue',
    10 => 'Light Green',
    11 => 'Metal',
    12 => 'Navy',
    13 => 'Olive',
    14 => 'Orange',
    15 => 'Pink',
    16 => 'Purple',
    17 => 'Red',
    18 => 'Silver',
    19 => 'Turquoise',
    20 => 'White',
    21 => 'Yellow',
  ),
) ?>