<?php return array (
  'SubcategoryID' => 3266,
  'SubcategoryName' => 'HLWallArtCoverings',
  'PropertyName' => 'HLWallArtType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 1,
  'PropertyValueList' => 
  array (
    0 => 'Acrylic',
    1 => 'Architectural Fragments',
    2 => 'Batik',
    3 => 'Canvas Art',
    4 => 'Indoor Flags & Banners',
    5 => 'Metal Wall Art',
    6 => 'Oil & Giclee',
    7 => 'Photography',
    8 => 'Plaques and Panels',
    9 => 'Posters',
    10 => 'Prints',
    11 => 'Signs',
    12 => 'Stained Glass',
    13 => 'Tapestries',
    14 => 'Wall Decals',
    15 => 'Wallpaper',
  ),
) ?>