<?php return array (
  'SubcategoryID' => 2148,
  'SubcategoryName' => 'HWSleepSnoringAids',
  'PropertyName' => 'HWSleepAidsModel',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '5" Lobe',
    1 => '6" Lobe',
    2 => '7" Lobe',
    3 => 'California King',
    4 => 'Dual CA King',
    5 => 'Dual King',
    6 => 'Dual Queen',
    7 => 'Full',
    8 => 'Gentle Support',
    9 => 'High Profile',
    10 => 'King',
    11 => 'Lumbar',
    12 => 'Marpac Pool Keeper',
    13 => 'N/A',
    14 => 'Neck',
    15 => 'Neck/Pelvic',
    16 => 'One Sided Gel Layer',
    17 => 'Pillow Pad',
    18 => 'Queen',
    19 => 'Single',
    20 => 'Standard No Gel',
    21 => 'Standard Support',
    22 => 'Twin',
    23 => 'Twin XL',
    24 => 'Two Sided Gel Layer',
  ),
) ?>