<?php return array (
  'SubcategoryID' => 143,
  'SubcategoryName' => 'KVMKeyboardVideoMouseSwitches',
  'PropertyName' => 'KVMType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Accessories',
    1 => 'D-Sub',
    2 => 'D-Sub, DVI',
    3 => 'D-Sub, DVI, USB',
    4 => 'D-Sub, PS/2',
    5 => 'D-Sub, USB',
    6 => 'D-Sub, USB, PS/2',
    7 => 'D-Sub, USB, RJ-45, Stereo Jack',
    8 => 'DisplayPort, USB',
    9 => 'DVI',
    10 => 'DVI, PS/2',
    11 => 'DVI, PS/2, USB',
    12 => 'DVI, USB',
    13 => 'HDMI',
    14 => 'HDMI, USB',
    15 => 'PS/2',
    16 => 'RJ-45',
    17 => 'Serial',
    18 => 'USB',
    19 => 'USB, PS/2',
  ),
) ?>