<?php return array (
  'SubcategoryID' => 1041,
  'SubcategoryName' => 'KitchenFaucets',
  'PropertyName' => 'KitchenFaucetBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'American Standard',
    1 => 'Belle Foret',
    2 => 'Blanco',
    3 => 'Central Brass',
    4 => 'Cifial',
    5 => 'Danze',
    6 => 'DELTA',
    7 => 'Elkay',
    8 => 'FIAT',
    9 => 'Fusion',
    10 => 'GROHE',
    11 => 'Hansgrohe',
    12 => 'Ideaworks',
    13 => 'InSinkErator',
    14 => 'KOHLER',
    15 => 'La Toscana',
    16 => 'LDR',
    17 => 'MOEN',
    18 => 'PEERLESS',
    19 => 'Pfister',
    20 => 'T&S Brass',
    21 => 'Ultra Faucets',
  ),
) ?>