<?php return array (
  'SubcategoryID' => 2885,
  'SubcategoryName' => 'HIOutdoorFans',
  'PropertyName' => 'HIOutdoorFansfeatures',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '3 Way',
    1 => 'Dimmable',
    2 => 'Eco Friendly',
    3 => 'Energy Saver/Energy Efficient',
    4 => 'Fluorescent',
    5 => 'Hugger',
    6 => 'Innovative',
    7 => 'Interconnected',
    8 => 'LED',
    9 => 'Low Profile',
    10 => 'Multi Directional',
    11 => 'Remote Control',
    12 => 'Sloped Ceiling',
    13 => 'Switch - Pull Chain',
    14 => 'Wet Location',
  ),
) ?>