<?php return array (
  'SubcategoryID' => 3429,
  'SubcategoryName' => 'FacilityTrafficSafetyEquipment',
  'PropertyName' => 'FacilitySafetyType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Anti-Static & ESD Equipment',
    1 => 'Asbestos Abatement',
    2 => 'Blade Disposals',
    3 => 'Confined Space Equipment',
    4 => 'Emergency Eyewash & Shower Equipment',
    5 => 'Emergency Preparedness',
    6 => 'Fall Protection',
    7 => 'Fire Protection',
    8 => 'Gas Detection',
    9 => 'Guard Rails, Railings & Rail Fittings',
    10 => 'Knee Protection',
    11 => 'Machine Guards & Shields',
    12 => 'Matting & Anti-Slip',
    13 => 'Noise Control',
    14 => 'Other',
    15 => 'Replacement Parts',
    16 => 'Safety Alarms & Warnings',
    17 => 'Safety Storage',
    18 => 'Safety Training Materials',
    19 => 'Spill Control Supplies',
    20 => 'Switchmats & Controllers',
    21 => 'Traffic & Parking Lot',
    22 => 'Wall & Hand Rail Accessories',
    23 => 'Wall & Hand Rails',
    24 => 'Weather Detection',
  ),
) ?>