<?php return array (
  'SubcategoryID' => 3327,
  'SubcategoryName' => 'AccessoriesNotebooksTabletPCs',
  'PropertyName' => 'GroupNBAccOption',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Arizona Cardinals',
    1 => 'Atlanta Falcons',
    2 => 'Baltimore Ravens',
    3 => 'Buffalo Bills',
    4 => 'Carolina Panthers',
    5 => 'Chicago Bears',
    6 => 'Cincinnati Bengals',
    7 => 'Cleveland Browns',
    8 => 'Dallas Cowboys',
    9 => 'Denver Broncos',
    10 => 'Detroit Lions',
    11 => 'Full-Size',
    12 => 'Green Bay Packers',
    13 => 'Houston Texans',
    14 => 'Indianapolis Colts',
    15 => 'Jacksonville Jaguars',
    16 => 'Kansas City Chiefs',
    17 => 'LA Rams',
    18 => 'Miami Dolphins',
    19 => 'Minnesota Vikings',
    20 => 'N/A',
    21 => 'New England Patriots',
    22 => 'New Orleans Saints',
    23 => 'New York Giants',
    24 => 'New York Jets',
    25 => 'Oakland Raiders',
    26 => 'Philadelphia Eagles',
    27 => 'Pittsburgh Steelers',
    28 => 'Portable',
    29 => 'San Diego Chargers',
    30 => 'San Francisco 49er\'s',
    31 => 'Seattle Seahawks',
    32 => 'Tampa Bay Buccaneers',
    33 => 'Tennessee Titans',
    34 => 'Washington Redskins',
  ),
) ?>