<?php return array (
  'SubcategoryID' => 739,
  'SubcategoryName' => 'ActivityTrackers',
  'PropertyName' => 'HeartRateMonitorColor',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Berry',
    1 => 'Black',
    2 => 'Black/Berry',
    3 => 'Black/Blue',
    4 => 'Black/Gold',
    5 => 'Black/Grey',
    6 => 'Black/Orange',
    7 => 'Black/Purple',
    8 => 'Black/Red',
    9 => 'Black/Volt',
    10 => 'Blue',
    11 => 'Burgundy',
    12 => 'Dark Blue',
    13 => 'Gold',
    14 => 'Gray',
    15 => 'Green',
    16 => 'Hot Pink',
    17 => 'Indigo',
    18 => 'Light Blue',
    19 => 'Orange',
    20 => 'Pink',
    21 => 'Prasinous',
    22 => 'Purple',
    23 => 'Red',
    24 => 'Sand',
    25 => 'Silver',
    26 => 'Slate',
    27 => 'Tangerine',
    28 => 'Teal',
    29 => 'White',
    30 => 'Yellow',
  ),
) ?>