<?php return array (
  'SubcategoryID' => 739,
  'SubcategoryName' => 'ActivityTrackers',
  'PropertyName' => 'HeartRateMonitorBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '4iiii',
    1 => 'Acer',
    2 => 'Amazfit',
    3 => 'BebeSounds',
    4 => 'Fitbit',
    5 => 'Garmin',
    6 => 'GNC',
    7 => 'Gofit',
    8 => 'Healbe',
    9 => 'Huami',
    10 => 'iHealth',
    11 => 'Jawbone',
    12 => 'LG',
    13 => 'Microsoft',
    14 => 'Mio Global',
    15 => 'Misfit Wearables',
    16 => 'Moov',
    17 => 'MyKronoz',
    18 => 'Omron',
    19 => 'Oregon Scientific',
    20 => 'Ovente',
    21 => 'Philips',
    22 => 'Polar',
    23 => 'PYLE',
    24 => 'Rosewill',
    25 => 'Runtastic',
    26 => 'SAMSUNG',
    27 => 'Skechers',
    28 => 'Sportline',
    29 => 'Striiv',
    30 => 'Suunto',
    31 => 'ZFIT',
  ),
) ?>