<?php return array (
  'SubcategoryID' => 767,
  'SubcategoryName' => 'Airpurifier',
  'PropertyName' => 'AirPurifierColor',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '2-tone',
    1 => 'Black',
    2 => 'Blue',
    3 => 'Brown',
    4 => 'Carbon',
    5 => 'Cherry Wood',
    6 => 'Espresso',
    7 => 'Gold',
    8 => 'Graphite Black',
    9 => 'Gray',
    10 => 'Green',
    11 => 'Grey',
    12 => 'Leaf Green',
    13 => 'Maple',
    14 => 'Midnight Blue',
    15 => 'Moss Green',
    16 => 'Oak',
    17 => 'Orange',
    18 => 'Pink',
    19 => 'Polar White',
    20 => 'Purple',
    21 => 'Red',
    22 => 'Ruby Red',
    23 => 'Sandstone',
    24 => 'Silver',
    25 => 'Warm Grey',
    26 => 'White',
    27 => 'Yellow',
  ),
) ?>