<?php return array (
  'SubcategoryID' => 767,
  'SubcategoryName' => 'Airpurifier',
  'PropertyName' => 'AirPurifierPurifyTechnology',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Activated Carbon',
    1 => 'Carbon Mat',
    2 => 'Electrostatic',
    3 => 'HEPA',
    4 => 'HEPA, Activated Carbon',
    5 => 'HEPA, Active Carbon, Ionizer',
    6 => 'HEPA, Active Carbon, Ionizer, PreFilter',
    7 => 'HEPA, Ionizer',
    8 => 'HEPA, Ionizer, Electrostatic',
    9 => 'HEPA, Ionizer, PreFilter',
    10 => 'HEPA, PreFilter',
    11 => 'HEPA, UV',
    12 => 'HEPA, UV, Active Carbon',
    13 => 'HEPA, UV, Active Carbon, Ionizer',
    14 => 'HEPA, UV, Active Carbon, Ionizer, Electrostatic',
    15 => 'HEPA, UV, Active Carbon, Ionizer, Ozone',
    16 => 'HEPA, UV, Active Carbon, Ionizer, Ozone, PreFilter',
    17 => 'HEPA, UV, Ionizer, PreFilter',
    18 => 'HEPA, UV, PreFilter',
    19 => 'Ionizer',
    20 => 'Ionizer, Ozone',
    21 => 'Ionizer, UV',
    22 => 'Ionizer, UV, Electrostatic',
    23 => 'Ionizer, UV, Ozone',
    24 => 'Ionizer, UV, PreFilter',
    25 => 'Ozone',
    26 => 'Plasma, HEPA, CARBON',
    27 => 'Plasmacluster Ion',
    28 => 'PlasmaTrue',
    29 => 'PlasmaWave',
    30 => 'UV',
  ),
) ?>