<?php return array (
  'SubcategoryID' => 2858,
  'SubcategoryName' => 'HIOutdoorPorchWallLanterns',
  'PropertyName' => 'HIPorchWalllanternmaterial',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Acrylic',
    1 => 'Alabaster',
    2 => 'Aluminum',
    3 => 'Bamboo',
    4 => 'Beaded',
    5 => 'Brass',
    6 => 'Ceramic',
    7 => 'Copper',
    8 => 'Crystal',
    9 => 'EtchedGlass',
    10 => 'Fabric',
    11 => 'FauxLeather',
    12 => 'FossilStone',
    13 => 'Glass',
    14 => 'Iron',
    15 => 'Leather',
    16 => 'Linen',
    17 => 'Metal',
    18 => 'Mica',
    19 => 'Mosaic',
    20 => 'Paper',
    21 => 'Rattan',
    22 => 'ReclaimedWood',
    23 => 'Resin',
    24 => 'Silk',
    25 => 'Slate',
    26 => 'Steel',
    27 => 'Stone',
    28 => 'TiffanyGlass',
    29 => 'Wicker',
    30 => 'Wood',
    31 => 'Zinc',
  ),
) ?>