<?php return array (
  'SubcategoryID' => 2955,
  'SubcategoryName' => 'CellPhoneMountsHolders',
  'PropertyName' => 'CellphoneACCModel',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Blackberry Q10',
    1 => 'Galaxy Note 4',
    2 => 'Galaxy S6 Edge',
    3 => 'Galaxy S6 Edge Plus',
    4 => 'HTC Desire 816',
    5 => 'HTC One',
    6 => 'HTC One M7',
    7 => 'HTC One M8',
    8 => 'Huawei Ascend G6',
    9 => 'iPhone 4s',
    10 => 'iPhone 5',
    11 => 'iPhone 5 / 5s',
    12 => 'iPhone 5, iPhone 5S',
    13 => 'iPhone 5C',
    14 => 'iPhone 5s',
    15 => 'iPhone 6',
    16 => 'iPhone 6 Plus',
    17 => 'LG G2',
    18 => 'LG G2 Mini',
    19 => 'LG G3',
    20 => 'LG Pro 2',
    21 => 'Motorola Moto X',
    22 => 'Nexus 5',
    23 => 'Nokia Lumia 630/635',
    24 => 'Nokia Lumia 930',
    25 => 'Nokia Lumina 1020',
    26 => 'Nokia XL',
    27 => 'Samgsung S4',
    28 => 'Samsung Galaxy Note 3',
    29 => 'Samsung S3',
    30 => 'Samsung S5',
    31 => 'Sony Xperia M2',
    32 => 'Sony Xperia Z1S',
    33 => 'Sony Xperia Z2',
    34 => 'YotaPhone 2',
    35 => 'ZTE Grand Memo II',
  ),
) ?>