<?php return array (
  'SubcategoryID' => 374,
  'SubcategoryName' => 'DigitalVoiceRecorders',
  'PropertyName' => 'VRECBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Alesis',
    1 => 'Aluratek',
    2 => 'AmpliVox',
    3 => 'COBY',
    4 => 'Datexx',
    5 => 'DENPA',
    6 => 'HIKVISION',
    7 => 'Iluv',
    8 => 'Jensen',
    9 => 'jWIN',
    10 => 'M-AUDIO',
    11 => 'Memorex',
    12 => 'Native Union',
    13 => 'OLYMPUS',
    14 => 'Oregon Scientific',
    15 => 'Panasonic',
    16 => 'Philips',
    17 => 'PYLE AUDIO',
    18 => 'PylePro',
    19 => 'RCA',
    20 => 'Sangean',
    21 => 'Sanyo',
    22 => 'SONY',
    23 => 'TEAC',
    24 => 'WHISTLER',
    25 => 'Zoom',
  ),
) ?>