<?php return array (
  'SubcategoryID' => 374,
  'SubcategoryName' => 'DigitalVoiceRecorders',
  'PropertyName' => 'VRECRecordingMedia',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '128MB',
    1 => '16MB',
    2 => '1GB',
    3 => '256MB',
    4 => '2GB',
    5 => '32MB',
    6 => '4GB',
    7 => '512MB',
    8 => '64MB',
    9 => '8GB',
    10 => '8MB',
    11 => 'Cassette',
    12 => 'Depending on SM Card',
    13 => 'Flash Memory',
    14 => 'Microcassette',
    15 => 'microSD Card',
    16 => 'Mini Disc',
    17 => 'SD/SDHC media',
  ),
) ?>