<?php return array (
  'SubcategoryID' => 1586,
  'SubcategoryName' => 'DogsTravelOutdoors',
  'PropertyName' => 'DogTravelOutdoorsColor',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Beige',
    1 => 'Black',
    2 => 'Blue',
    3 => 'Blue/Grey',
    4 => 'Brown',
    5 => 'Burgundy',
    6 => 'Clear',
    7 => 'Cloudburst Gray',
    8 => 'Coral',
    9 => 'Dark Blue',
    10 => 'Dark Green',
    11 => 'Gold',
    12 => 'Green',
    13 => 'Green/Khaki',
    14 => 'Grey',
    15 => 'Ivory',
    16 => 'Khaki',
    17 => 'Khaki/Grey',
    18 => 'Light Blue',
    19 => 'Light Green',
    20 => 'Metallic',
    21 => 'Multi-Color',
    22 => 'Orange',
    23 => 'Paw Print',
    24 => 'Pink',
    25 => 'Pink/Grey',
    26 => 'Platinum',
    27 => 'Purple',
    28 => 'Red',
    29 => 'Red/Black',
    30 => 'Silver',
    31 => 'Stripes',
    32 => 'Teal',
    33 => 'White',
    34 => 'Yellow',
  ),
) ?>