<?php return array (
  'SubcategoryID' => 3054,
  'SubcategoryName' => 'ToysRCEngineParts',
  'PropertyName' => 'RCEnginePartsType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 1,
  'PropertyValueList' => 
  array (
    0 => 'Air Cleaners & Filters',
    1 => 'Air Pressure Line',
    2 => 'Carburetors',
    3 => 'Cooling Fans',
    4 => 'Engine Mounting Gear',
    5 => 'Engine Starters',
    6 => 'External Fuel Filter',
    7 => 'Flywheels',
    8 => 'Fuel Lines',
    9 => 'Fuel Pumps',
    10 => 'Fuel Tank',
    11 => 'Gears & Chains',
    12 => 'Glow Plug Accessories',
    13 => 'Glow Plugs',
    14 => 'Glow Starters',
    15 => 'Mufflers & Pipe Systems',
    16 => 'On Board Glows',
    17 => 'Other Accessories',
    18 => 'Power Panels',
    19 => 'Primers',
    20 => 'Propeller Rotors',
    21 => 'Propeller Spinners & Cones',
    22 => 'Pull-start mechanisms',
    23 => 'Pumps & Smoke Systems',
    24 => 'Secondary Silencer',
    25 => 'Silencers',
    26 => 'Silencers (in cowl)',
    27 => 'Tuned Pipes',
    28 => 'Venturi Tubes',
  ),
) ?>