<?php return array (
  'SubcategoryID' => 1645,
  'SubcategoryName' => 'BasketballProtectiveGear',
  'PropertyName' => 'BasketballProtectiveGearSize',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Large',
    1 => 'Medium',
    2 => 'One Size',
    3 => 'Regular',
    4 => 'Small',
    5 => 'X-Large',
    6 => 'X-Small',
    7 => 'XX-Large',
    8 => 'XX-Small',
    9 => 'XXX-Large',
    10 => 'Youth Large',
    11 => 'Youth Medium',
    12 => 'Youth Regular',
    13 => 'Youth Small',
    14 => 'Youth X-Large',
    15 => 'Youth X-Small',
    16 => 'Youth XX-Large',
    17 => 'Youth XX-Small',
    18 => 'Youth XXX-Large',
  ),
) ?>