<?php return array (
  'SubcategoryID' => 2864,
  'SubcategoryName' => 'HISpotLights',
  'PropertyName' => 'HISpotlightsMaterial',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Acrylic',
    1 => 'Alabaster',
    2 => 'Bamboo',
    3 => 'Beaded',
    4 => 'Ceramic',
    5 => 'Crystal',
    6 => 'EtchedGlass',
    7 => 'Fabric',
    8 => 'FauxLeather',
    9 => 'FossilStone',
    10 => 'Glass',
    11 => 'Iron',
    12 => 'Leather',
    13 => 'Linen',
    14 => 'Metal',
    15 => 'Mica',
    16 => 'Mosaic',
    17 => 'Paper',
    18 => 'Plastic',
    19 => 'Rattan',
    20 => 'ReclaimedWood',
    21 => 'Resin',
    22 => 'Silk',
    23 => 'Slate',
    24 => 'Stone',
    25 => 'TiffanyGlass',
    26 => 'Wicker',
    27 => 'Wood',
  ),
) ?>