<?php return array (
  'SubcategoryID' => 2864,
  'SubcategoryName' => 'HISpotLights',
  'PropertyName' => 'HISpotlightsFeatures',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '3Way',
    1 => 'BatteryOperated',
    2 => 'Dimmable',
    3 => 'Dusk-to-Dawn',
    4 => 'Eco-Friendly',
    5 => 'EnergySaver/EnergyEfficient',
    6 => 'Fluorescent',
    7 => 'Indoor',
    8 => 'Innovative',
    9 => 'Interconnected',
    10 => 'LED',
    11 => 'MotionSensor',
    12 => 'PhotoSensor',
    13 => 'RemoteControl',
    14 => 'Solar',
    15 => 'TouchOn/Off',
    16 => 'WetLocation',
  ),
) ?>