<?php return array (
  'SubcategoryID' => 1935,
  'SubcategoryName' => 'HIPowerPlugsConnectors',
  'PropertyName' => 'HIStraightBladePlugsType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Hazardoud Location Plugs',
    1 => 'IEC Pin & Sleeve Plugs, Connectors & Interlocks',
    2 => 'International Plug Adapters',
    3 => 'Marine Wiring Accessories',
    4 => 'Mechanical Interlock Devices',
    5 => 'Midget Locking Devices',
    6 => 'Pin & Sleeve Boxes',
    7 => 'Pin & Sleeve Device Accessories',
    8 => 'Plug & Connector Boots',
    9 => 'Plug Adapters',
    10 => 'Receptacle & Switch Wiring Modules',
    11 => 'Single Pole Connector Accessories',
    12 => 'Single Pole Connectors',
    13 => 'Straight Blade',
    14 => 'Straight Blade Connectors',
    15 => 'Straight Blade Device Accessories',
    16 => 'Straight Blade Plugs',
    17 => 'Twist Lock Connectors',
    18 => 'Twist Lock Power Plugs',
    19 => 'Twist Lock Safety Enclosures',
    20 => 'Twist Lock Safety Shrouds, Inlets & Receptacles',
  ),
) ?>