<?php return array (
  'SubcategoryID' => 2842,
  'SubcategoryName' => 'HLTableLamps',
  'PropertyName' => 'HITablelampsStyle',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Art Deco',
    1 => 'Arts-n-Crafts',
    2 => 'Asian',
    3 => 'Botanical',
    4 => 'Childrens',
    5 => 'Coastal',
    6 => 'Contemporary',
    7 => 'Cottage',
    8 => 'Country',
    9 => 'Country French',
    10 => 'Industrial',
    11 => 'Lodge',
    12 => 'Mid Century',
    13 => 'Mission',
    14 => 'Modern',
    15 => 'Moroccan',
    16 => 'Nautical',
    17 => 'Novelty',
    18 => 'Old World',
    19 => 'Retro',
    20 => 'Rustic',
    21 => 'Shaker',
    22 => 'Southwestern',
    23 => 'Spanish Colonial',
    24 => 'Sports',
    25 => 'Tiffany',
    26 => 'Traditional',
    27 => 'Transitional',
    28 => 'Tropical',
    29 => 'Tuscan',
    30 => 'Vintage',
  ),
) ?>