<?php return array (
  'SubcategoryID' => 2842,
  'SubcategoryName' => 'HLTableLamps',
  'PropertyName' => 'HITablelampsFeatures',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '3 Way',
    1 => 'Battery Operated',
    2 => 'Country',
    3 => 'Dimmable',
    4 => 'Dusk-to-Dawn',
    5 => 'Eco-Friendly',
    6 => 'Energy Saver/Energy Efficient',
    7 => 'Fluorescent',
    8 => 'Height Adjustable',
    9 => 'In-Line Switch',
    10 => 'Innovative',
    11 => 'Interconnected',
    12 => 'LED',
    13 => 'Line Switch',
    14 => 'Motion Sensor',
    15 => 'Photo Sensor',
    16 => 'Pull Chain',
    17 => 'Remote Control',
    18 => 'Removable Cord',
    19 => 'Rotary Switch',
    20 => 'Rotory Switch',
    21 => 'Solar',
    22 => 'Touch On/Off',
    23 => 'UL Rated',
    24 => 'UL Rated - Dry Location',
    25 => 'Wet Location',
  ),
) ?>