<?php return array (
  'SubcategoryID' => 3515,
  'SubcategoryName' => 'GamingChairs',
  'PropertyName' => 'GamingChairPrimaryColor',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Azure',
    1 => 'Black',
    2 => 'Black / Blue',
    3 => 'Black / Green',
    4 => 'Black / Red',
    5 => 'Blue',
    6 => 'Bronze Brown',
    7 => 'Dark Brown',
    8 => 'Deep Lavender',
    9 => 'Dusty Blue',
    10 => 'Green',
    11 => 'Grey',
    12 => 'Moss Gray',
    13 => 'Orange',
    14 => 'Parrot Green',
    15 => 'Pink',
    16 => 'Red',
    17 => 'Silver',
    18 => 'Violet',
    19 => 'White',
    20 => 'Yellow',
  ),
) ?>