<?php return array (
  'SubcategoryID' => 3515,
  'SubcategoryName' => 'GamingChairs',
  'PropertyName' => 'GamingChairAccentColor',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Black',
    1 => 'Black/Grey',
    2 => 'Black/Red',
    3 => 'Blue',
    4 => 'Blue/White',
    5 => 'Brown',
    6 => 'Coffee',
    7 => 'Dark Blue',
    8 => 'Green',
    9 => 'Grey',
    10 => 'Indigo',
    11 => 'No',
    12 => 'Orange',
    13 => 'Pink',
    14 => 'PU Black',
    15 => 'PU Blue',
    16 => 'PU Gold',
    17 => 'PU Green',
    18 => 'PU Red',
    19 => 'PU White',
    20 => 'PU Yellow',
    21 => 'Purple/White',
    22 => 'Real Leather Black',
    23 => 'Real Leather White',
    24 => 'Red',
    25 => 'Red/White',
    26 => 'Silver',
    27 => 'Violet',
    28 => 'White',
    29 => 'Yellow',
    30 => 'Yellow/White',
  ),
) ?>