<?php return array (
  'SubcategoryID' => 2959,
  'SubcategoryName' => 'CellPhoneUnlockedCellPhones',
  'PropertyName' => 'MWBuilt-inStorage',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 1,
  'IsRequired' => 1,
  'PropertyValueList' => 
  array (
    0 => '128GB',
    1 => '16GB',
    2 => '1GB',
    3 => '256GB',
    4 => '2GB',
    5 => '32GB',
    6 => '3GB',
    7 => '40GB',
    8 => '4GB',
    9 => '512 MB ROM, 256 MB RAM',
    10 => '64GB',
    11 => '8GB',
    12 => 'Card slot: microSD, up to 32GB',
    13 => 'n/a',
    14 => 'Under 1GB',
  ),
) ?>