<?php return array (
  'SubcategoryID' => 2959,
  'SubcategoryName' => 'CellPhoneUnlockedCellPhones',
  'PropertyName' => 'MWCompatibleCarrierService',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'AT&T',
    1 => 'AT&T / T-Mobile',
    2 => 'AT&T 2G, AT&T 3G',
    3 => 'AT&T 2G, AT&T 3G, T-Mobile 2G',
    4 => 'AT&T 2G, Rogers, Fido',
    5 => 'AT&T 2G, T-Mobile 2G',
    6 => 'AT&T 2G, T-Mobile 2G, Rogers, Fido',
    7 => 'AT&T 2G, T-Mobile 2G, Rogers, Fido, Red Pocket',
    8 => 'AT&T 2G, T-Mobile 2G/3G',
    9 => 'AT&T 2G, T-Mobile 2G/3G, Rogers, Fido',
    10 => 'AT&T 2G, T-Mobile 2G/3G, Rogers/Fido/SimpleMobile',
    11 => 'AT&T 2G, Verizon',
    12 => 'AT&T 2G/3G, T-Mobile 2G, Rogers, Fido',
    13 => 'AT&T 2G/3G, T-Mobile 2G, Verizon, Rogers, Fido',
    14 => 'AT&T 2G/3G, T-Mobile 2G/3G',
    15 => 'AT&T 2G/3G, T-Mobile 2G/3G, Rogers, Fido',
    16 => 'AT&T/T-Mobile 2G, Sprint/Verizon 3G, Rogers, Fido',
    17 => 'Boost Mobile',
    18 => 'GigSky',
    19 => 'GoSmart Mobile',
    20 => 'H2O Wireless',
    21 => 'Net10',
    22 => 'Red Pocket',
    23 => 'Rogers, Fido',
    24 => 'Simple Mobile',
    25 => 'Sprint',
    26 => 'Sprint Prepaid',
    27 => 'Sprint, Verizon',
    28 => 'T-Mobile',
    29 => 'T-Mobile 2G, T-Mobile 3G',
    30 => 'TracFone',
    31 => 'Verizon',
    32 => 'Verizon / Sprint',
    33 => 'Virgin Mobile',
  ),
) ?>