<?php return array (
  'SubcategoryID' => 658,
  'SubcategoryName' => 'CoffeeGrinders',
  'PropertyName' => 'CoffeeGrinderBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'AROMA',
    1 => 'ascaso',
    2 => 'Better Chef',
    3 => 'Black & Decker',
    4 => 'BOSCH',
    5 => 'BRAUN',
    6 => 'Breville',
    7 => 'Bunn-O-Matic Corporation',
    8 => 'Continental Electric',
    9 => 'Cuisinart',
    10 => 'DeLonghi',
    11 => 'Espressione',
    12 => 'Gaggia',
    13 => 'Hamilton Beach',
    14 => 'Jura-Capresso',
    15 => 'KitchenAid',
    16 => 'KRUPS',
    17 => 'MAXI-MATIC',
    18 => 'Melitta',
    19 => 'MR. COFFEE',
    20 => 'NESCO',
    21 => 'Proctor Silex',
    22 => 'Saeco',
    23 => 'SALTON',
    24 => 'Solis',
    25 => 'Solofill',
    26 => 'TOASTESS',
    27 => 'Toastmaster',
  ),
) ?>