<?php return array (
  'SubcategoryID' => 410,
  'SubcategoryName' => 'HardDriveControllersRAIDCards',
  'PropertyName' => 'HDControllerInterface',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'DIMM Socket',
    1 => 'ISA',
    2 => 'N/A',
    3 => 'PCI',
    4 => 'PCI Express',
    5 => 'PCI-Express 2.0',
    6 => 'PCI-Express 2.0 x1',
    7 => 'PCI-Express 2.0 x16',
    8 => 'PCI-Express 2.0 x2',
    9 => 'PCI-Express 2.0 x4',
    10 => 'PCI-Express 2.0 x8',
    11 => 'PCI-Express 3.0',
    12 => 'PCI-Express 3.0 x8',
    13 => 'PCI-Express x1',
    14 => 'PCI-Express x4',
    15 => 'PCI-Express x8',
    16 => 'PCI-X',
    17 => 'PCMCIA',
    18 => 'SAS/SATA 6Gb/s',
    19 => 'SATA 6Gb/s',
  ),
) ?>