<?php return array (
  'SubcategoryID' => 799,
  'SubcategoryName' => 'Solar',
  'PropertyName' => 'SolarBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'ALLSOP',
    1 => 'Anker',
    2 => 'Athenatech',
    3 => 'Brinkmann',
    4 => 'Coleman',
    5 => 'EnerPlex',
    6 => 'GearIt',
    7 => 'Goal Zero',
    8 => 'i.Tech',
    9 => 'Lenmar',
    10 => 'Malibu Lighting Corporation',
    11 => 'MANGO',
    12 => 'Maxsa',
    13 => 'Nature Power',
    14 => 'OLYMPIA',
    15 => 'Revolve',
    16 => 'Ritek',
    17 => 'Rosewill',
    18 => 'Royal',
    19 => 'Solar Light Technologies',
    20 => 'Solarrific',
    21 => 'Solio',
    22 => 'Solpro',
    23 => 'Sunforce',
    24 => 'Sunpak',
    25 => 'Wagan',
    26 => 'WakaWaka',
  ),
) ?>