<?php return array (
  'SubcategoryID' => 484,
  'SubcategoryName' => 'NetworkDigitalMediaPlayers',
  'PropertyName' => 'NetplayerBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '4XEM',
    1 => 'AIS',
    2 => 'AMX',
    3 => 'AOpen',
    4 => 'Asus',
    5 => 'AVS Gear',
    6 => 'Belkin',
    7 => 'BrightSign',
    8 => 'BUFFALO',
    9 => 'Cisco',
    10 => 'Creative',
    11 => 'D-Link',
    12 => 'Galaxy METAL GEAR',
    13 => 'GeoVision',
    14 => 'Intel',
    15 => 'LACIE',
    16 => 'LG',
    17 => 'Linear',
    18 => 'LINKSKEY',
    19 => 'LINKSYS',
    20 => 'Masscool',
    21 => 'MediaGate',
    22 => 'Mitsubishi',
    23 => 'NETGEAR',
    24 => 'NEX',
    25 => 'Pinnacle',
    26 => 'Planar',
    27 => 'PLANET',
    28 => 'PRISMIQ',
    29 => 'Roku',
    30 => 'SLIM DEVICES',
    31 => 'SMC LG-ERICSSON',
    32 => 'ViewSonic',
    33 => 'Vodality',
    34 => 'ZyXEL',
  ),
) ?>