<?php return array (
  'SubcategoryID' => 3373,
  'SubcategoryName' => 'HIHardwareDoorWindowHardware',
  'PropertyName' => 'DoorHardwareType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Access Doors',
    1 => 'Automatic & Magnetic Door Holders',
    2 => 'Concealed Door Closers',
    3 => 'Door Bottoms',
    4 => 'Door Closer Accessories',
    5 => 'Door Closers',
    6 => 'Door Cover Plates',
    7 => 'Door Edge',
    8 => 'Door Guards',
    9 => 'Door Holders',
    10 => 'Door Knob Wall Guards',
    11 => 'Door Knockers',
    12 => 'Door Reinforces',
    13 => 'Door Sensors',
    14 => 'Door Stops',
    15 => 'Door Viewers',
    16 => 'Door Wedges',
    17 => 'Dummy Door Knobs',
    18 => 'Dummy Door Levers',
    19 => 'Electric Strikes',
    20 => 'Exit Devices',
    21 => 'Handles',
    22 => 'Hanging Door Hardware',
    23 => 'Kick Plates',
    24 => 'Latches, Hasps & Hinges',
    25 => 'Passage Door Knobs',
    26 => 'Passage Door Levers',
    27 => 'Pet Doors',
    28 => 'Screen Door Hardware',
    29 => 'Weatherstripping',
    30 => 'Window & Door Seals',
    31 => 'Window Insulation Kits',
    32 => 'Window Locks & Hardware',
  ),
) ?>