<?php return array (
  'SubcategoryID' => 637,
  'SubcategoryName' => 'PhoneConferencingDevices',
  'PropertyName' => 'CNETConferenceBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Adtran',
    1 => 'AT&T',
    2 => 'Barco',
    3 => 'Basyx',
    4 => 'Biscotti',
    5 => 'Brother',
    6 => 'Cisco',
    7 => 'ClearOne',
    8 => 'GN Netcom',
    9 => 'InFocus',
    10 => 'inPerson',
    11 => 'Jabra',
    12 => 'Konftel',
    13 => 'Kramer',
    14 => 'LifeSize',
    15 => 'Logitech',
    16 => 'MXL',
    17 => 'NEC',
    18 => 'Oklahoma',
    19 => 'Panasonic',
    20 => 'Phoenix Audio Technologies',
    21 => 'Plantronics',
    22 => 'POLYCOM',
    23 => 'RCA',
    24 => 'Revolabs',
    25 => 'Sennheiser',
    26 => 'Sony',
    27 => 'Spracht',
    28 => 'Vtech',
    29 => 'Yealink',
    30 => 'ZTE',
  ),
) ?>