<?php return array (
  'SubcategoryID' => 3483,
  'SubcategoryName' => 'CablesLightningCables',
  'PropertyName' => 'CellphoneACCChargerLength',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '< 1 Feet',
    1 => '1 Feet',
    2 => '1.3 Feet',
    3 => '10 Feet',
    4 => '12 Feet',
    5 => '16 Feet',
    6 => '2 Feet',
    7 => '3 Feet',
    8 => '3.3 Feet',
    9 => '4 Feet',
    10 => '4"',
    11 => '5 Feet',
    12 => '6 Feet',
    13 => '6.5 Feet',
    14 => '7 Feet',
    15 => '8 Feet',
    16 => '9 Feet',
    17 => 'No',
  ),
) ?>