<?php return array (
  'SubcategoryID' => 3358,
  'SubcategoryName' => 'RacquetSportsAccessories',
  'PropertyName' => 'RSAccessoriesBallType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Advanced',
    1 => 'All Court',
    2 => 'Beginner',
    3 => 'Clay Court',
    4 => 'Doubles',
    5 => 'Foam',
    6 => 'Grass Court',
    7 => 'Hard Court',
    8 => 'Hardball',
    9 => 'High Altitude',
    10 => 'Indoor',
    11 => 'Intermediate',
    12 => 'Low Compression',
    13 => 'Outdoor',
    14 => 'Practice',
    15 => 'Premium',
    16 => 'Pressureless',
    17 => 'Shuttlecocks',
    18 => 'Singles',
    19 => 'Softball',
    20 => 'Two-Tone',
  ),
) ?>