<?php return array (
  'SubcategoryID' => 562,
  'SubcategoryName' => 'MacNotebooks',
  'PropertyName' => 'NBDisplayType',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Full HD',
    1 => 'HD+',
    2 => 'QHD',
    3 => 'Retina Display',
    4 => 'SVGA',
    5 => 'SXGA',
    6 => 'SXGA+',
    7 => 'UHD',
    8 => 'UXGA',
    9 => 'Wide SVGA',
    10 => 'Wide SXGA',
    11 => 'Wide SXGA+',
    12 => 'Wide UXGA',
    13 => 'Wide VGA',
    14 => 'Wide XGA',
    15 => 'Wide XGA+',
    16 => 'XGA',
  ),
) ?>