<?php return array (
  'SubcategoryID' => 1639,
  'SubcategoryName' => 'ChildrensActivewear',
  'PropertyName' => 'SportsGlobalCompositeSportsType',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Baseball & Softball',
    1 => 'Basketball',
    2 => 'Bowling',
    3 => 'Cross-Training',
    4 => 'Cycling',
    5 => 'Diving',
    6 => 'Fishing',
    7 => 'Football',
    8 => 'Golf',
    9 => 'Hiking',
    10 => 'Hockey',
    11 => 'Hunting',
    12 => 'Lacrosse',
    13 => 'Mountaineering',
    14 => 'Multi-Sport',
    15 => 'Racing',
    16 => 'Skateboarding',
    17 => 'Soccer',
    18 => 'Surfing',
    19 => 'Swimming',
    20 => 'Track & Field',
    21 => 'Winter Sports',
  ),
) ?>