<?php return array (
  'SubcategoryID' => 1890,
  'SubcategoryName' => 'OGTimers',
  'PropertyName' => 'OGTimersBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Blossom',
    1 => 'BlueSpray',
    2 => 'Claber',
    3 => 'Dramm',
    4 => 'Gilmour',
    5 => 'Insteon',
    6 => 'Nelson',
    7 => 'Orbit',
    8 => 'Rachio',
    9 => 'Rain Bird',
    10 => 'Raindrip',
    11 => 'RainMachine',
    12 => 'Ray Padula',
    13 => 'SkyDrop',
    14 => 'Smartenit',
  ),
) ?>