<?php return array (
  'SubcategoryID' => 2574,
  'SubcategoryName' => 'SGFishingTackleBoxes',
  'PropertyName' => 'SGTackleColor',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'As Shown',
    1 => 'Beige',
    2 => 'Black',
    3 => 'Blue',
    4 => 'Brown',
    5 => 'Burgundy',
    6 => 'Clear',
    7 => 'Coral',
    8 => 'Dark Blue',
    9 => 'Dark Green',
    10 => 'Gold',
    11 => 'Green',
    12 => 'Grey',
    13 => 'Ivory',
    14 => 'Khaki',
    15 => 'Light Blue',
    16 => 'Light Green',
    17 => 'Metallic',
    18 => 'Multi',
    19 => 'Multi-Color',
    20 => 'Orange',
    21 => 'Pink',
    22 => 'Platinum',
    23 => 'Purple',
    24 => 'Red',
    25 => 'Silver',
    26 => 'Teal',
    27 => 'White',
    28 => 'Yellow',
  ),
) ?>