<?php return array (
  'SubcategoryID' => 737,
  'SubcategoryName' => 'Massagers',
  'PropertyName' => 'MassagerType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Accessories',
    1 => 'Belt Massager',
    2 => 'Electric Throw',
    3 => 'Foot Massager',
    4 => 'Foot Spa',
    5 => 'Gym Equipment',
    6 => 'Hand-held Massager',
    7 => 'Heated Blanket',
    8 => 'Heated Comforter',
    9 => 'Heated Mattress Pad',
    10 => 'Heating Pad',
    11 => 'Light Therapy',
    12 => 'Magnetic Therapy Massager',
    13 => 'Manicure / Pedicure',
    14 => 'Massage Lounger',
    15 => 'Massage Mat',
    16 => 'Massaging Seat Cushion',
    17 => 'Neck Massager',
    18 => 'Paraffin Bath',
    19 => 'Pulse Massager',
    20 => 'Skin Care',
  ),
) ?>