<?php return array (
  'SubcategoryID' => 3241,
  'SubcategoryName' => 'ECChemicalsAdhesives',
  'PropertyName' => 'ECColorFinish',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Amber',
    1 => 'Black',
    2 => 'Blue',
    3 => 'Bronze',
    4 => 'Brown',
    5 => 'Brushed Stainless',
    6 => 'Clear',
    7 => 'Dark Grey',
    8 => 'Gray',
    9 => 'Hazy Off-White',
    10 => 'Ligh Grey/Off-White',
    11 => 'Light Tan',
    12 => 'Milky Translucent',
    13 => 'Satin Nickel',
    14 => 'Silver',
    15 => 'Slight Haze/Slight Straw',
    16 => 'Steel',
    17 => 'Steel Grey',
    18 => 'Tan',
    19 => 'White',
  ),
) ?>