<?php return array (
  'SubcategoryID' => 2129,
  'SubcategoryName' => 'WasherDryerAccessories',
  'PropertyName' => 'WasherDryerAccessoriesBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Avanti',
    1 => 'Brasscraft',
    2 => 'Calflex',
    3 => 'Certified Appliance',
    4 => 'Conair',
    5 => 'Daewoo',
    6 => 'Deflecto',
    7 => 'Dormont',
    8 => 'GE',
    9 => 'Haier',
    10 => 'LG',
    11 => 'Petra',
    12 => 'Samsung',
    13 => 'SANYO',
  ),
) ?>