<?php return array (
  'SubcategoryID' => 8,
  'SubcategoryName' => 'ServerBarebone',
  'PropertyName' => 'BBRackCPUType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'AMD',
    1 => 'AMD Athlon 64 FX / Athlon 64 / Sempron',
    2 => 'AMD Athlon 64 FX / Athlon 64 / X2 / Opteron 100',
    3 => 'AMD Athlon XP / Athlon / Sempron / Duron',
    4 => 'AMD Opteron',
    5 => 'Dual AMD Opteron',
    6 => 'Dual Intel Xeon',
    7 => 'Eight AMD Opteron',
    8 => 'Eight Intel Xeon',
    9 => 'Four AMD Opteron',
    10 => 'Four Intel Itanium',
    11 => 'Four Intel Xeon',
    12 => 'Intel Atom',
    13 => 'Intel Core 2 / Core 2 Extreme / Core 2 Quad',
    14 => 'Intel Core 2 / Xeon',
    15 => 'Intel Core i5',
    16 => 'Intel Core i7',
    17 => 'Intel Core i7 / i5 / i3',
    18 => 'Intel Core i7 / i5 / i3 / Pentium / Celeron',
    19 => 'Intel Core i7 / Xeon',
    20 => 'Intel Pentium 4 / Celeron',
    21 => 'Intel Pentium 4 / Pentium D',
    22 => 'Intel Pentium 4 / Pentium D / Celeron',
    23 => 'Intel Pentium 4 / Pentium D / Celeron M',
    24 => 'Intel Pentium D / Pentium EE / Celeron',
    25 => 'Intel Pentium M',
    26 => 'Intel Tualatin / Coppermine / Celeron',
    27 => 'Intel Xeon',
    28 => 'Intel Xeon / Core i3 / Pentium',
    29 => 'VIA',
  ),
) ?>