<?php return array (
  'SubcategoryID' => 8,
  'SubcategoryName' => 'ServerBarebone',
  'PropertyName' => 'BBRackBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'ASRock',
    1 => 'ASUS',
    2 => 'Biostar',
    3 => 'Cisco',
    4 => 'Dell',
    5 => 'GIGABYTE',
    6 => 'Habey',
    7 => 'HP',
    8 => 'Huawei',
    9 => 'Intel',
    10 => 'MSI',
    11 => 'NORCO',
    12 => 'OEM Production',
    13 => 'PROMISE',
    14 => 'Quanta',
    15 => 'SUPERMICRO',
    16 => 'TYAN',
    17 => 'UNIWIDE',
    18 => 'VIA',
    19 => 'WYSE',
  ),
) ?>