<?php return array (
  'SubcategoryID' => 2062,
  'SubcategoryName' => 'GazebosCanopies',
  'PropertyName' => 'GazebosCanopiesColorGroup',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Beige',
    1 => 'Black',
    2 => 'Blue',
    3 => 'Brown',
    4 => 'Burgundy',
    5 => 'Clear',
    6 => 'Dark Wood',
    7 => 'Forest green',
    8 => 'Gold',
    9 => 'Green',
    10 => 'Grey',
    11 => 'Kelly green',
    12 => 'Medium Brown Wood',
    13 => 'Multicolor',
    14 => 'Natural/Light Brown Wood',
    15 => 'Navy blue',
    16 => 'Orange',
    17 => 'Other',
    18 => 'Pink',
    19 => 'Purple',
    20 => 'Red',
    21 => 'Silver',
    22 => 'Stripe Black/White',
    23 => 'Stripe Blue/White',
    24 => 'Stripe Green/White',
    25 => 'Stripe Red/White',
    26 => 'Turquoise',
    27 => 'White',
    28 => 'Yellow',
  ),
) ?>