<?php return array (
  'SubcategoryID' => 3372,
  'SubcategoryName' => 'CaulksSealantsApplicators',
  'PropertyName' => 'CaulkType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 1,
  'PropertyValueList' => 
  array (
    0 => 'Accessories',
    1 => 'Asphalt Patching & Repair Compounds',
    2 => 'Castable Rubber',
    3 => 'Caulk Guns',
    4 => 'Caulks',
    5 => 'Cleaners & Primers',
    6 => 'Coolants & Soldering',
    7 => 'Cutting Oils & Lubricants',
    8 => 'Dispensing Needles & Syringes',
    9 => 'Expoxy Applicators',
    10 => 'Filler/Repair Compound',
    11 => 'Foam',
    12 => 'Gasket Sealant',
    13 => 'Glue Guns',
    14 => 'Joint Sealant',
    15 => 'Lubricants & Rust Protection',
    16 => 'Patching & Repairing Compounds',
    17 => 'Pipe Sealant Tape',
    18 => 'Pipe Sealants',
    19 => 'Putties',
    20 => 'Sealing Compound',
    21 => 'Threaded Pipe Sealant',
    22 => 'Threadlockers',
    23 => 'Valve Sealants',
  ),
) ?>