<?php return array (
  'SubcategoryID' => 1950,
  'SubcategoryName' => 'OGOutdoorFurnitureAccessories',
  'PropertyName' => 'OGOutdFurnAccColor',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'As Shown',
    1 => 'Black',
    2 => 'BLACK JEAN',
    3 => 'Black/Tan',
    4 => 'Blue',
    5 => 'Cocoa Cosmos Brown',
    6 => 'Copper Mosaic Gold',
    7 => 'Eggplant',
    8 => 'ENGLISH',
    9 => 'Floral',
    10 => 'GERRYS JUBILEE',
    11 => 'Gray',
    12 => 'Green',
    13 => 'GREEN PAISLEY',
    14 => 'HOUNDSTOOTH',
    15 => 'Khaki',
    16 => 'Mint Chip',
    17 => 'Multi',
    18 => 'PINK DESIRE',
    19 => 'PROVENCE FLAIR',
    20 => 'Purple',
    21 => 'PURPLE MOSAIC',
    22 => 'Red',
    23 => 'Sea Stripe',
    24 => 'Tapestry',
    25 => 'TOOLED GOLD',
    26 => 'White',
  ),
) ?>