<?php return array (
  'SubcategoryID' => 2020,
  'SubcategoryName' => 'VanitieswithTops',
  'PropertyName' => 'VanitieswithTopsFinish',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Antique Bisque',
    1 => 'Antique White',
    2 => 'Black',
    3 => 'Cherry',
    4 => 'Cherry Wood',
    5 => 'Dark Cherry',
    6 => 'Dark Walnut',
    7 => 'Dark Wood',
    8 => 'Espresso',
    9 => 'Heirloom Bronze',
    10 => 'Light Wood',
    11 => 'Maple',
    12 => 'Medium Walnut',
    13 => 'Other',
    14 => 'Rich Mahogany',
    15 => 'Tahiti Desert',
    16 => 'Walnut',
    17 => 'Warm Cinnamon',
    18 => 'Warm Walnut',
    19 => 'White',
  ),
) ?>