<?php return array (
  'SubcategoryID' => 2902,
  'SubcategoryName' => 'MIBassAmplifiers',
  'PropertyName' => 'ReceiversChannels',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '10-Channel',
    1 => '11.2-Channel',
    2 => '12-Channel',
    3 => '2.1-Channel',
    4 => '3-Channel',
    5 => '4-Channel',
    6 => '5-Channel',
    7 => '5.1-Channel',
    8 => '5.2-Channel',
    9 => '6-Channel',
    10 => '6.1-Channel',
    11 => '7-Channel',
    12 => '7.1-Channel',
    13 => '7.2-Channel',
    14 => '8-Channel',
    15 => '9.2-Channel',
    16 => '9.3-Channel',
    17 => 'Single',
    18 => 'Stereo',
  ),
) ?>