<?php return array (
  'SubcategoryID' => 944,
  'SubcategoryName' => 'BeautyGiftSets',
  'PropertyName' => 'BeautyGiftColor',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Beige',
    1 => 'Black',
    2 => 'Blue',
    3 => 'Brown',
    4 => 'Burgundy',
    5 => 'Clear',
    6 => 'Coral',
    7 => 'DarkBlue',
    8 => 'DarkGreen',
    9 => 'Gold',
    10 => 'Green',
    11 => 'Grey',
    12 => 'Ivory',
    13 => 'Khaki',
    14 => 'LightBlue',
    15 => 'LightGreen',
    16 => 'Metallic',
    17 => 'Multi-Color',
    18 => 'Orange',
    19 => 'Pink',
    20 => 'Platinum',
    21 => 'Purple',
    22 => 'Red',
    23 => 'Silver',
    24 => 'Teal',
    25 => 'White',
    26 => 'Yellow',
  ),
) ?>