<?php return array (
  'SubcategoryID' => 573,
  'SubcategoryName' => 'CaseFans',
  'PropertyName' => 'CaseFanLED',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Black',
    1 => 'Blue',
    2 => 'Blue/Red',
    3 => 'Blue/Red/Green',
    4 => 'Blue/Red/Green/White',
    5 => 'Green',
    6 => 'HD RGB',
    7 => 'Multi-Color',
    8 => 'No',
    9 => 'No LED',
    10 => 'Orange',
    11 => 'Pink',
    12 => 'Purple',
    13 => 'Red',
    14 => 'Silver',
    15 => 'Smoke',
    16 => 'SP RGB',
    17 => 'White',
    18 => 'Yellow',
  ),
) ?>