<?php return array (
  'SubcategoryID' => 573,
  'SubcategoryName' => 'CaseFans',
  'PropertyName' => 'CaseFanColor',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '2-Tone',
    1 => 'Black',
    2 => 'Black/White',
    3 => 'Blue',
    4 => 'Blue/White',
    5 => 'Brown',
    6 => 'Clear',
    7 => 'Gold',
    8 => 'Gray',
    9 => 'Green',
    10 => 'No',
    11 => 'Orange',
    12 => 'Purple',
    13 => 'Red',
    14 => 'Silver',
    15 => 'Transparent',
    16 => 'White',
    17 => 'Yellow',
  ),
) ?>