<?php return array (
  'SubcategoryID' => 573,
  'SubcategoryName' => 'CaseFans',
  'PropertyName' => 'CaseFanBearingType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '1 Ball, 1 Sleeve',
    1 => '2 Ball',
    2 => 'ARCTIC Ceramic',
    3 => 'Ball',
    4 => 'Barometric',
    5 => 'Barometric Oilless Bearing (BOL)',
    6 => 'Ceramic',
    7 => 'Enter',
    8 => 'Ever Lubricate',
    9 => 'EverLasting Quiet',
    10 => 'Fluid Circulative Bearing',
    11 => 'Fluid Dynamic',
    12 => 'Hydraulic',
    13 => 'Hydro Bearing',
    14 => 'Hydro Wave',
    15 => 'Hyper-spin',
    16 => 'Liquid state',
    17 => 'Loop Dynamic Bearing (LDB)',
    18 => 'Magnetic Barometric',
    19 => 'Nanoflux Bearing (NFB)',
    20 => 'Oil System Bearing',
    21 => 'Powder Copper Fluid (P.C.F.)',
    22 => 'Rifle',
    23 => 'Sleeve',
    24 => 'SSO',
    25 => 'SSO2',
    26 => 'SuperFlo',
    27 => 'Teflon Nano Bearing',
    28 => 'TMD (Tip-Magnetic Driving)',
    29 => 'Twister',
    30 => 'UFB (Updraft Floating Balance)',
    31 => 'UFO',
    32 => 'Vapo Bearing',
    33 => 'Z-AXIS',
  ),
) ?>