<?php return array (
  'SubcategoryID' => 486,
  'SubcategoryName' => 'SatelliteRadioReceiversAccessories',
  'PropertyName' => 'SatelliteRadioType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 1,
  'PropertyValueList' => 
  array (
    0 => 'Antenna Cable',
    1 => 'Boombox',
    2 => 'Control System',
    3 => 'FM Modular Kit',
    4 => 'FM Modulator',
    5 => 'FM Switch Box',
    6 => 'Home Docking Kit',
    7 => 'Home/Car Radio Kit',
    8 => 'Marine Kit',
    9 => 'Outdoor Wearable Kit',
    10 => 'Radio Car Kit',
    11 => 'Radio Home Kit',
    12 => 'Repeater Antenna',
    13 => 'Satellite Radio Antennas & Adapters',
    14 => 'Satellite Radio Docks & Cradles',
    15 => 'Satellite Radio Interfaces',
    16 => 'Satellite Radio Tuners',
    17 => 'Satellite Receivers',
    18 => 'Sirius XM Radio Accessories',
    19 => 'XM Extension Kit',
  ),
) ?>