<?php return array (
  'SubcategoryID' => 486,
  'SubcategoryName' => 'SatelliteRadioReceiversAccessories',
  'PropertyName' => 'SatelliteRadioBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'AGT',
    1 => 'ALTEC LANSING',
    2 => 'ARKON',
    3 => 'AUDIOVOX',
    4 => 'BELKIN',
    5 => 'Browning',
    6 => 'Cisco',
    7 => 'Clarion',
    8 => 'Creative',
    9 => 'Dantona',
    10 => 'DELPHI',
    11 => 'eton',
    12 => 'HD Frequency',
    13 => 'iLuv',
    14 => 'Jeep ELECTRONICS',
    15 => 'Jensen',
    16 => 'JVC',
    17 => 'KENWOOD',
    18 => 'Lenmar',
    19 => 'MONSTER',
    20 => 'Panasonic',
    21 => 'Pioneer',
    22 => 'SAMSUNG',
    23 => 'SIRIUS',
    24 => 'Speck Products',
    25 => 'TAO',
    26 => 'TERK',
    27 => 'Tram',
    28 => 'XACT',
    29 => 'YAMAHA',
  ),
) ?>