<?php return array (
  'SubcategoryID' => 2823,
  'SubcategoryName' => 'CablesNetworkEthernetCables',
  'PropertyName' => 'NetworkCableColor',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Aqua',
    1 => 'Aqua Blue',
    2 => 'Beige',
    3 => 'Black',
    4 => 'Blue',
    5 => 'Brown',
    6 => 'Clear',
    7 => 'Dark Blue',
    8 => 'Gray',
    9 => 'Green',
    10 => 'Grey',
    11 => 'Hot Pink',
    12 => 'Ivory',
    13 => 'Light Blue',
    14 => 'Light Gray',
    15 => 'Light Green',
    16 => 'Multi-Color',
    17 => 'Navy Blue',
    18 => 'Orange',
    19 => 'Pink',
    20 => 'Purple',
    21 => 'Red',
    22 => 'Royal Blue',
    23 => 'Silver',
    24 => 'Teal',
    25 => 'Violet',
    26 => 'White',
    27 => 'Yellow',
  ),
) ?>