<?php return array (
  'SubcategoryID' => 3078,
  'SubcategoryName' => 'ProfessionalVideoDevices',
  'PropertyName' => 'PVDInterface',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Analog to SDI',
    1 => 'Audio to SDI',
    2 => 'DVI',
    3 => 'DVI to HDMI',
    4 => 'HDMI',
    5 => 'HDMI to SDI',
    6 => 'PCI-Express',
    7 => 'SDI',
    8 => 'SDI to Analog',
    9 => 'SDI to Audio',
    10 => 'SDI to HDMI',
    11 => 'Thunderbolt',
    12 => 'USB 2.0',
    13 => 'USB 3.0',
    14 => 'Wireless',
  ),
) ?>