<?php return array (
  'SubcategoryID' => 3078,
  'SubcategoryName' => 'ProfessionalVideoDevices',
  'PropertyName' => 'videoaddType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '3D Glasses',
    1 => 'Digital Media Streamer',
    2 => 'External TV Tuner Box',
    3 => 'For Mac',
    4 => 'Media Player',
    5 => 'Media Transfer',
    6 => 'PC to TV',
    7 => 'Professional Video Devices',
    8 => 'Professional Video Editing',
    9 => 'PVR',
    10 => 'Satellite Receiving',
    11 => 'Signal Generator',
    12 => 'Terminal/Repeater',
    13 => 'Tuner for Laptop',
    14 => 'TV Tuner Accessory',
    15 => 'TV Tuner Cards',
    16 => 'USB TV Tuner Stick',
    17 => 'Video Adapter/Converter',
    18 => 'Video Capture & Editing',
    19 => 'Video Emulator',
    20 => 'Video Extender',
    21 => 'Video Splitter',
    22 => 'Video Switch',
  ),
) ?>