<?php return array (
  'SubcategoryID' => 2654,
  'SubcategoryName' => 'ATKeyChains',
  'PropertyName' => 'KeyChainColor',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Beige',
    1 => 'Black',
    2 => 'Blue',
    3 => 'Brown',
    4 => 'Brushed Nickel',
    5 => 'Burgundy',
    6 => 'Chrome',
    7 => 'Clear',
    8 => 'Cognac',
    9 => 'Coral',
    10 => 'Dark Blue',
    11 => 'Dark Brown',
    12 => 'Dark Green',
    13 => 'Gold',
    14 => 'Green',
    15 => 'Grey',
    16 => 'Ivory',
    17 => 'Khaki',
    18 => 'Light Blue',
    19 => 'Light Green',
    20 => 'Magenta',
    21 => 'Metallic',
    22 => 'Multi-Color',
    23 => 'Oil Rubbed Bronze',
    24 => 'Orange',
    25 => 'Pink',
    26 => 'Platinum',
    27 => 'Purple',
    28 => 'Red',
    29 => 'Silver',
    30 => 'Teal',
    31 => 'White',
    32 => 'Yellow',
  ),
) ?>