<?php return array (
  'SubcategoryID' => 2654,
  'SubcategoryName' => 'ATKeyChains',
  'PropertyName' => 'KeyChainTheme',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Animals & Insects',
    1 => 'Around the World',
    2 => 'Biblical',
    3 => 'Careers & Occupations',
    4 => 'Cartoon',
    5 => 'Couples',
    6 => 'Disney',
    7 => 'Easter Bunny Costumes',
    8 => 'Fairytale & Storybook',
    9 => 'Food & Beverage',
    10 => 'Historical',
    11 => 'Holiday',
    12 => 'Horror & Gothic',
    13 => 'Humorous',
    14 => 'Military',
    15 => 'Pet Costumes',
    16 => 'Princesses & Divas',
    17 => 'Santa Suits',
    18 => 'Science Fiction',
    19 => 'Seasonal & Holiday',
    20 => 'Sports',
    21 => 'Superheroes',
    22 => 'Traditional',
    23 => 'TV & Movies',
  ),
) ?>