<?php return array (
  'SubcategoryID' => 3270,
  'SubcategoryName' => 'HLPartySupplies',
  'PropertyName' => 'HLPartySuppliesType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 1,
  'PropertyValueList' => 
  array (
    0 => 'Aluminum Pans',
    1 => 'Balloons',
    2 => 'Banners & Signs',
    3 => 'Cake Toppers',
    4 => 'Candles',
    5 => 'Candy Favors',
    6 => 'Coffee Cups',
    7 => 'Confetti',
    8 => 'Favor Bags',
    9 => 'Favor Boxes',
    10 => 'Gift Bags',
    11 => 'Headbands & Tiaras',
    12 => 'Invitations & Cards',
    13 => 'Noise Makers',
    14 => 'Paper Napkins',
    15 => 'Party Decorations',
    16 => 'Party Favors',
    17 => 'Party Hats',
    18 => 'Party Lights',
    19 => 'Pitchers & Ice Buckets',
    20 => 'Place Cards & Holders',
    21 => 'Plastic & Paper Bowls',
    22 => 'Plastic & Paper Cups',
    23 => 'Plastic & Paper Plates',
    24 => 'Plastic & Paper Table Runners',
    25 => 'Plastic & Paper Tablecloths',
    26 => 'Plastic Cutlery',
    27 => 'Serving Trays',
    28 => 'Stickers & Decals',
    29 => 'Straws, Stirrers and Picks',
    30 => 'Streamers',
    31 => 'Wrapping Paper & Tissue & Bows',
  ),
) ?>