<?php return array (
  'SubcategoryID' => 3270,
  'SubcategoryName' => 'HLPartySupplies',
  'PropertyName' => 'HLPartySuppliesColorFinish',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Black',
    1 => 'Blue',
    2 => 'Brass',
    3 => 'Bronze',
    4 => 'Brown',
    5 => 'Brushed Steel',
    6 => 'Cherry',
    7 => 'Chrome',
    8 => 'Copper',
    9 => 'Espresso',
    10 => 'Gold',
    11 => 'Green',
    12 => 'N/A',
    13 => 'Nickel',
    14 => 'Oak',
    15 => 'Pewter',
    16 => 'Purple',
    17 => 'Red',
    18 => 'Silver',
    19 => 'Walnut',
    20 => 'White',
  ),
) ?>