<?php return array (
  'SubcategoryID' => 3270,
  'SubcategoryName' => 'HLPartySupplies',
  'PropertyName' => 'HLPartySuppliesTheme',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '50s',
    1 => '60s',
    2 => '70s',
    3 => '80s',
    4 => '90s',
    5 => 'Action / Super Heroes',
    6 => 'Animals',
    7 => 'Baby',
    8 => 'Beach',
    9 => 'Butterflies & Bugs',
    10 => 'Camouflage',
    11 => 'Carnival',
    12 => 'Cartoons',
    13 => 'Casino',
    14 => 'Disco',
    15 => 'Disney',
    16 => 'Fiesta',
    17 => 'Generic',
    18 => 'Hello Kitty',
    19 => 'Hollywood / Movies / TV',
    20 => 'Luau',
    21 => 'Monsters',
    22 => 'Noahs Ark',
    23 => 'Outer Space',
    24 => 'Patriotic',
    25 => 'Pirate',
    26 => 'Pixar',
    27 => 'Princess',
    28 => 'Religious',
    29 => 'Rock n Roll',
    30 => 'Sci Fi',
    31 => 'Sesame Street',
    32 => 'Sports',
    33 => 'Star Wars',
    34 => 'Transportation',
    35 => 'Video Games',
    36 => 'Western',
  ),
) ?>