<?php return array (
  'SubcategoryID' => 2088,
  'SubcategoryName' => 'HITubShowerFaucets',
  'PropertyName' => 'HITubShowerFaucetsBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Alsons',
    1 => 'American Standard',
    2 => 'Belle Foret',
    3 => 'Central Brass',
    4 => 'Cifial',
    5 => 'DELTA',
    6 => 'FIAT',
    7 => 'Focus Electrics',
    8 => 'Grohe',
    9 => 'Hansgrohe',
    10 => 'Jado',
    11 => 'KOHLER',
    12 => 'La Toscana',
    13 => 'MOEN',
    14 => 'PEERLESS',
    15 => 'Pegasus',
    16 => 'Pfister',
    17 => 'Swan',
    18 => 'Symmons',
    19 => 'Westbrass',
  ),
) ?>