<?php return array (
  'SubcategoryID' => 528,
  'SubcategoryName' => 'CDDVDFlashDuplicators',
  'PropertyName' => 'ODDType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Blu-Ray / DVD / CD Duplicator',
    1 => 'Blu-ray Burner',
    2 => 'Blu-ray DVD Burner',
    3 => 'Blu-ray DVD Duplicator',
    4 => 'Blu-ray DVD-ROM Drive',
    5 => 'CD Burner',
    6 => 'CD Duplicator',
    7 => 'CD-ROM Drive',
    8 => 'Combo Drive',
    9 => 'Combo Drive with Card Reader',
    10 => 'Compact Flash Duplicator',
    11 => 'Copier',
    12 => 'Dataplay',
    13 => 'DVD Burner',
    14 => 'DVD Duplicator',
    15 => 'DVD-ROM Drive',
    16 => 'DVD/CD Duplicator',
    17 => 'Hard Drive Duplicator',
    18 => 'HD DVD-ROM Drive',
    19 => 'Publisher',
    20 => 'Reader',
    21 => 'SD Duplicator',
    22 => 'SD/MicroSD Duplicator',
    23 => 'Slim Blu-ray Combo Drive',
    24 => 'Slim CD Burner',
    25 => 'Slim CD-ROM Drive',
    26 => 'Slim Combo Drive',
    27 => 'Slim DVD Burner',
    28 => 'Slim DVD Drive',
    29 => 'Slim DVD-ROM Drive',
    30 => 'USB Flash Drive Duplicator',
    31 => 'Writer',
  ),
) ?>