<?php return array (
  'SubcategoryID' => 3060,
  'SubcategoryName' => 'ToysGameTables',
  'PropertyName' => 'HIGameTablesmaterial',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'ABS',
    1 => 'Acrylic',
    2 => 'Aluminum',
    3 => 'Bamboo',
    4 => 'Bonded Leather',
    5 => 'Bycast Leather',
    6 => 'Ceramic',
    7 => 'Faux Leather',
    8 => 'Fiberglass',
    9 => 'Glass',
    10 => 'Glass and Metal',
    11 => 'Glass and Wood',
    12 => 'Laminate',
    13 => 'Leather',
    14 => 'Metal',
    15 => 'Plastic',
    16 => 'Rattan',
    17 => 'Reclaimed Wood',
    18 => 'Slate',
    19 => 'Stone',
    20 => 'tile',
    21 => 'Tile and metal',
    22 => 'Tile and Wood',
    23 => 'Vinyl',
    24 => 'Wicker',
    25 => 'Wood',
    26 => 'Wood and Metal',
    27 => 'Wood Composites',
  ),
) ?>