<?php return array (
  'SubcategoryID' => 2938,
  'SubcategoryName' => 'HLHomeEntertainment',
  'PropertyName' => 'HIHomeEntertainmentType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 1,
  'PropertyValueList' => 
  array (
    0 => 'Ceiling Mount',
    1 => 'Coffee and Side Table',
    2 => 'Component Racks',
    3 => 'Corner',
    4 => 'Entertainment Center',
    5 => 'Fireplace TV Stand',
    6 => 'Gaming Console',
    7 => 'Media Console',
    8 => 'Media Storage',
    9 => 'Open Shelving TV Stand',
    10 => 'Pier Cabinet',
    11 => 'Plasma Lift',
    12 => 'Sliding Unit',
    13 => 'TV Carts',
    14 => 'TV Stand with mount',
    15 => 'TV Stands',
    16 => 'Wall Mount',
    17 => 'Wall Unit',
  ),
) ?>