<?php return array (
  'SubcategoryID' => 3319,
  'SubcategoryName' => 'FabricCraftsSewingAccessories',
  'PropertyName' => 'CraftStyle',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Americana',
    1 => 'Animal & Jungle',
    2 => 'Art Deco',
    3 => 'Asian',
    4 => 'Casual',
    5 => 'Coastal',
    6 => 'Contemporary',
    7 => 'Cottage',
    8 => 'Country',
    9 => 'Country French',
    10 => 'European',
    11 => 'Holiday / Seasonal',
    12 => 'Industrial',
    13 => 'Lodge',
    14 => 'Masculine',
    15 => 'Mid Century',
    16 => 'Mission',
    17 => 'Moroccan',
    18 => 'Musical',
    19 => 'Nautical',
    20 => 'Novelty',
    21 => 'Oriental & Middle Eastern',
    22 => 'Retro',
    23 => 'Rustic',
    24 => 'Shaker',
    25 => 'Southwest',
    26 => 'Spanish Colonial',
    27 => 'Sports',
    28 => 'Tiffany',
    29 => 'Traditional',
    30 => 'Transitional',
    31 => 'Tropical',
    32 => 'Tuscan',
  ),
) ?>