<?php return array (
  'SubcategoryID' => 3319,
  'SubcategoryName' => 'FabricCraftsSewingAccessories',
  'PropertyName' => 'FabricPatternDesign',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Animal Print',
    1 => 'Checkered',
    2 => 'Floral',
    3 => 'Geometric',
    4 => 'Graphic',
    5 => 'Ikat',
    6 => 'Paisley',
    7 => 'Patchwork',
    8 => 'Patterned',
    9 => 'Plaid',
    10 => 'Polka Dot',
    11 => 'Solid',
    12 => 'Striped',
    13 => 'Toile',
  ),
) ?>