<?php return array (
  'SubcategoryID' => 3319,
  'SubcategoryName' => 'FabricCraftsSewingAccessories',
  'PropertyName' => 'FabricFabricContent',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '100% Acetate',
    1 => '100% Acrylic',
    2 => '100% Cotton',
    3 => '100% Linen',
    4 => '100% Lyocell',
    5 => '100% Nylon',
    6 => '100% Poly Filament',
    7 => '100% Polyester',
    8 => '100% Ramie',
    9 => '100% Rayon',
    10 => '100% Silk',
    11 => '100% Wool',
    12 => 'Acetate Blend',
    13 => 'Acrylic Blend',
    14 => 'Cotton Blend',
    15 => 'Linen Blend',
    16 => 'Metallic Blend',
    17 => 'Metallic Polyester Blend',
    18 => 'Nylon Blend',
    19 => 'Nylon Polyester',
    20 => 'Organic Cotton',
    21 => 'Polyester',
    22 => 'Polyester Blend',
    23 => 'Rayon Blend',
    24 => 'Silk Blend',
    25 => 'Wool Blend',
  ),
) ?>