<?php return array (
  'SubcategoryID' => 734,
  'SubcategoryName' => 'CurlingIrons',
  'PropertyName' => 'HairCurlerBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Andis',
    1 => 'babyliss',
    2 => 'Babyliss Pro',
    3 => 'BED HEAD',
    4 => 'Bibasque',
    5 => 'BRAUN',
    6 => 'Carteret',
    7 => 'CONAIR',
    8 => 'Helen of Troy',
    9 => 'HOT TOOLS',
    10 => 'John Frieda',
    11 => 'Laila Ali',
    12 => 'One \'n Only',
    13 => 'Ovente',
    14 => 'Panasonic',
    15 => 'Pro Beauty',
    16 => 'Remington',
    17 => 'REVLON',
    18 => 'Roman',
    19 => 'Sunbeam',
    20 => 'VIDAL SASSOON',
  ),
) ?>