<?php return array (
  'SubcategoryID' => 3385,
  'SubcategoryName' => 'Relays',
  'PropertyName' => 'RelayType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Alternating Relays',
    1 => 'Current Sensor Relays',
    2 => 'IEC & NEMA Style Relays',
    3 => 'Power Relays',
    4 => 'Prewired Relays',
    5 => 'Relay Accessories',
    6 => 'Relay Sockets',
    7 => 'Relays',
    8 => 'Safety Monitoring Relays',
    9 => 'Solid State Relays',
    10 => 'Solid State Timer Relays',
    11 => 'Time Delay Relays',
    12 => 'Voltage Sensor Relays',
    13 => 'Wireless Relays & Transmitters',
  ),
) ?>