<?php return array (
  'SubcategoryID' => 1769,
  'SubcategoryName' => 'Playards',
  'PropertyName' => 'PlayardsColor',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Assorted',
    1 => 'Beige',
    2 => 'Black',
    3 => 'Blue',
    4 => 'Brown',
    5 => 'Burgundy',
    6 => 'Clear',
    7 => 'Coral',
    8 => 'Gold',
    9 => 'Green',
    10 => 'Grey',
    11 => 'Ivory',
    12 => 'Metallic',
    13 => 'Multi',
    14 => 'Orange',
    15 => 'Pink',
    16 => 'Platinum',
    17 => 'Prints',
    18 => 'Purple',
    19 => 'Red',
    20 => 'Silver',
    21 => 'Teal',
    22 => 'White',
    23 => 'Yellow',
  ),
) ?>