<?php return array (
  'SubcategoryID' => 1505,
  'SubcategoryName' => 'Hats',
  'PropertyName' => 'HatsType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 1,
  'PropertyValueList' => 
  array (
    0 => 'Baseball Caps',
    1 => 'Beanies',
    2 => 'Berets',
    3 => 'Bowlers',
    4 => 'Bucket Hats',
    5 => 'Cadet Hats',
    6 => 'Cowboy Hats',
    7 => 'Earmuffs',
    8 => 'Fedoras',
    9 => 'Homburgs',
    10 => 'Newsboy Hats',
    11 => 'Panama Hats',
    12 => 'Porkpie Hats',
    13 => 'Slouch Hats',
    14 => 'Sun Hats',
    15 => 'Top Hats',
    16 => 'Trapper Hats',
    17 => 'Trilby Hats',
    18 => 'Trucker Hats',
    19 => 'Visors',
  ),
) ?>