<?php return array (
  'SubcategoryID' => 2789,
  'SubcategoryName' => 'WaterSportsGearAccessories',
  'PropertyName' => 'WSGearType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 1,
  'PropertyValueList' => 
  array (
    0 => 'Bags & Storage',
    1 => 'Books & Videos',
    2 => 'Buoyancy Compensators',
    3 => 'Clips, Reels & Handles',
    4 => 'Fins',
    5 => 'Fitness & Exercise Gear',
    6 => 'Floating Beverage Cooler',
    7 => 'Floating Lounge',
    8 => 'Gauges & Gadgets',
    9 => 'Goggles & Masks',
    10 => 'Oars',
    11 => 'Other Accessories',
    12 => 'Paddles',
    13 => 'Safety & Training Equipment',
    14 => 'Scuba',
    15 => 'Scuba Tanks',
    16 => 'Ski Tows & Pylons',
    17 => 'Snorkels',
    18 => 'Spray Skirts',
    19 => 'Surfing',
    20 => 'Swimming',
    21 => 'Tow Ropes & Harnesses',
    22 => 'Toys & Games',
    23 => 'Water Tube',
    24 => 'Weights & Belts',
    25 => 'Whistles',
  ),
) ?>