<?php return array (
  'SubcategoryID' => 1015,
  'SubcategoryName' => 'Watches',
  'PropertyName' => 'WatchBandMaterial',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Aluminum',
    1 => 'Brass',
    2 => 'Ceramic',
    3 => 'Cloth',
    4 => 'Cobalt Chrome',
    5 => 'Copper',
    6 => 'Crocodile Leather',
    7 => 'Felt',
    8 => 'Genuine Leather - Black',
    9 => 'Genuine Leather - Bone Color',
    10 => 'Genuine Leather - Light Purple',
    11 => 'Genuine Leather - White',
    12 => 'Glass',
    13 => 'Gold',
    14 => 'Gold Plated',
    15 => 'Leather',
    16 => 'Metal',
    17 => 'Nylon',
    18 => 'Padium',
    19 => 'Plastic',
    20 => 'Platinum',
    21 => 'Polymer',
    22 => 'Polyurethane',
    23 => 'Rose Gold',
    24 => 'Rubber',
    25 => 'Silicone',
    26 => 'Silver',
    27 => 'Silver Plated',
    28 => 'Stainless Steel',
    29 => 'Steel',
    30 => 'Sterling Silver',
    31 => 'Titanium',
    32 => 'Tungsten',
    33 => 'White Gold',
    34 => 'Wood',
  ),
) ?>