<?php return array (
  'SubcategoryID' => 1015,
  'SubcategoryName' => 'Watches',
  'PropertyName' => 'WatchDesign',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Animals',
    1 => 'Birthstone & Zodiac',
    2 => 'Classical',
    3 => 'Family',
    4 => 'Feminine',
    5 => 'Flowers',
    6 => 'Food & Beverages',
    7 => 'Gemstone',
    8 => 'Hobby',
    9 => 'Holidays',
    10 => 'Insects',
    11 => 'Luxury',
    12 => 'Military',
    13 => 'Musical',
    14 => 'Names, ID\'s & Initials',
    15 => 'Nautical',
    16 => 'Novelty',
    17 => 'Oversized',
    18 => 'Plain/Engravable',
    19 => 'Professions',
    20 => 'Religious',
    21 => 'Retro',
    22 => 'Skeleton Watch',
    23 => 'Sports',
    24 => 'Sun, Moon & Stars',
    25 => 'Symbols',
    26 => 'Team & School',
    27 => 'Themed',
  ),
) ?>