<?php return array (
  'SubcategoryID' => 412,
  'SubcategoryName' => 'ServerChassis',
  'PropertyName' => 'CaseCaseMaterial',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'ABS / Aluminum / Steel',
    1 => 'ABS / Iron / SGCC',
    2 => 'ABS / Mesh',
    3 => 'Aluminum',
    4 => 'Aluminum / Plastic',
    5 => 'Aluminum / Steel',
    6 => 'Aluminum / Tempered Glass',
    7 => 'Chrome',
    8 => 'Clear Acrylic',
    9 => 'SECC',
    10 => 'SGCC',
    11 => 'SPCC',
    12 => 'Steel',
    13 => 'Steel / Plastic',
  ),
) ?>