<?php return array (
  'SubcategoryID' => 412,
  'SubcategoryName' => 'ServerChassis',
  'PropertyName' => 'CaseExpansionSlots',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '1',
    1 => '10',
    2 => '11',
    3 => '12',
    4 => '13',
    5 => '14',
    6 => '2',
    7 => '3',
    8 => '4',
    9 => '5',
    10 => '6',
    11 => '7',
    12 => '8',
    13 => '9',
  ),
) ?>