<?php return array (
  'SubcategoryID' => 1678,
  'SubcategoryName' => 'FootballProtectiveGear',
  'PropertyName' => 'FBProtectiveGearSize',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Adult',
    1 => 'Adult Large',
    2 => 'Adult Medium',
    3 => 'Adult One Size Fits All',
    4 => 'Adult Small',
    5 => 'Adult X-Large',
    6 => 'Adult X-Small',
    7 => 'Adult XX-Large',
    8 => 'Adult XX-Small',
    9 => 'Adult XXX-Large',
    10 => 'Adult XXXX-Large',
    11 => 'Regular',
    12 => 'Youth',
    13 => 'Youth Large',
    14 => 'Youth Medium',
    15 => 'Youth One Size Fits All',
    16 => 'Youth Small',
    17 => 'Youth X-Large',
    18 => 'Youth X-Small',
    19 => 'Youth XX-Large',
    20 => 'Youth XX-Small',
  ),
) ?>