<?php return array (
  'SubcategoryID' => 2079,
  'SubcategoryName' => 'HIBathwares',
  'PropertyName' => 'HIBathwaresBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '3M',
    1 => 'Amerec Steam',
    2 => 'American Standard',
    3 => 'Baldwin',
    4 => 'Blanco',
    5 => 'Bobrick',
    6 => 'Croydex',
    7 => 'DELTA',
    8 => 'Drive Medical',
    9 => 'Franklin Brass',
    10 => 'Fusion',
    11 => 'Gatco',
    12 => 'Grohe',
    13 => 'Hansgrohe',
    14 => 'KOHLER',
    15 => 'La Toscana',
    16 => 'Liberty Hardware',
    17 => 'LOTA',
    18 => 'Moen',
    19 => 'Pegasus',
    20 => 'Rosewill',
    21 => 'Swanstone',
    22 => 'Zenith',
  ),
) ?>