<?php return array (
  'SubcategoryID' => 1802,
  'SubcategoryName' => 'HILightBulbs',
  'PropertyName' => 'HILightBulbsType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '3 Way Light',
    1 => 'Circline',
    2 => 'Compact Fluorescent Bulbs',
    3 => 'Decorative',
    4 => 'Flood Light',
    5 => 'Fluorescent Specialty Bulbs',
    6 => 'Fluorescent Tube Light Bulbs',
    7 => 'Halogen Light Bulbs',
    8 => 'Halogen Quarts Bulbs',
    9 => 'Halogen Reflector Flood Bulbs',
    10 => 'Halogen Spot Light Bulbs',
    11 => 'Heat Lamps',
    12 => 'High Intensity Discharge Bulbs',
    13 => 'High Pressure Sodium',
    14 => 'Incandescent Light Bulbs',
    15 => 'Mercury Vapor',
    16 => 'Motion',
    17 => 'Omni Type Bulbs',
    18 => 'Reflector Flood Light Bulbs',
    19 => 'Reflector PAR Flood Bulbs',
    20 => 'Reflectors',
    21 => 'Spiral',
    22 => 'Spot Light',
    23 => 'Torchier',
    24 => 'Tube',
  ),
) ?>