<?php return array (
  'SubcategoryID' => 715,
  'SubcategoryName' => 'ElectricSkilletsWoks',
  'PropertyName' => 'ElectricSkilletBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'AROMA',
    1 => 'Bella',
    2 => 'Black & Decker',
    3 => 'Breville',
    4 => 'Char-Broil',
    5 => 'CHI CUISINE',
    6 => 'Cuisinart',
    7 => 'DeLonghi',
    8 => 'Deni',
    9 => 'Elite',
    10 => 'FARBERWARE',
    11 => 'Hamilton Beach',
    12 => 'MAXI-MATIC',
    13 => 'Mondial',
    14 => 'NOSTALGIA ELECTRICS',
    15 => 'Oster',
    16 => 'PRESTO',
    17 => 'Proctor Silex',
    18 => 'Ragalta USA',
    19 => 'RIVAL',
    20 => 'Sunpentown',
    21 => 'Tiger',
    22 => 'Toastess',
    23 => 'VillaWare',
    24 => 'West Bend',
    25 => 'Zojirush',
  ),
) ?>