<?php return array (
  'SubcategoryID' => 2019,
  'SubcategoryName' => 'BathStorage',
  'PropertyName' => 'BathStorageFinish',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Antique Brass',
    1 => 'Antique Copper',
    2 => 'Antique White',
    3 => 'Black Walnut',
    4 => 'Chrome',
    5 => 'English Bronze',
    6 => 'Espresso',
    7 => 'Forever Brass',
    8 => 'French Gold',
    9 => 'Hand Relieved Oil Rubbed Bronze',
    10 => 'Matte White',
    11 => 'Metal',
    12 => 'Nickel',
    13 => 'Polished Chrome',
    14 => 'Venetian Bronze',
    15 => 'Warm Cinnamon',
    16 => 'White',
    17 => 'White Oak',
  ),
) ?>