<?php return array (
  'SubcategoryID' => 581,
  'SubcategoryName' => 'NotebookCasesForHer',
  'PropertyName' => 'NBCase4herColor',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Beige',
    1 => 'Black',
    2 => 'Blue',
    3 => 'Brown',
    4 => 'Gray',
    5 => 'Green',
    6 => 'Pink',
    7 => 'Purple',
    8 => 'Red',
    9 => 'Scarlet',
    10 => 'Silver',
    11 => 'Striped',
    12 => 'White',
    13 => 'Yellow',
  ),
) ?>