<?php return array (
  'SubcategoryID' => 581,
  'SubcategoryName' => 'NotebookCasesForHer',
  'PropertyName' => 'NBCase4herBrand',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Athenatech',
    1 => 'BELKIN',
    2 => 'Brenthaven',
    3 => 'Built NY',
    4 => 'Case Logic',
    5 => 'Choiix',
    6 => 'Decode',
    7 => 'Eccessories',
    8 => 'ECO TREND',
    9 => 'HP',
    10 => 'inland',
    11 => 'Kensington',
    12 => 'Lowepro',
    13 => 'MANGO TANGO',
    14 => 'MetStyle',
    15 => 'Microsoft',
    16 => 'MOBILE EDGE',
    17 => 'MSI',
    18 => 'pacific DESIGN',
    19 => 'PC Treasures',
    20 => 'Samsonite',
    21 => 'SOLO',
    22 => 'SONY VAIO',
    23 => 'STM',
    24 => 'SUMDEX',
    25 => 'Targus',
    26 => 'TRAVELERS CHOICE',
    27 => 'Tucano',
    28 => 'VANGUARD',
    29 => 'Wenger',
    30 => 'WIB',
  ),
) ?>