<?php return array (
  'SubcategoryID' => 3315,
  'SubcategoryName' => 'AdhesivesFasteners',
  'PropertyName' => 'AdhesiveFastenerGlueType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '2-Way Glue',
    1 => 'Art Paste & Wheat Paste',
    2 => 'Clear Lacquer',
    3 => 'Decoupage Glue',
    4 => 'Dimensional Paints',
    5 => 'Epoxy',
    6 => 'Fabric Glue',
    7 => 'Framing Glue & Adhesives',
    8 => 'Glitter Glue',
    9 => 'Glue Pens & Applicators',
    10 => 'Glue Sticks',
    11 => 'Hot Glue',
    12 => 'Instant Glue',
    13 => 'Jewelry Glue',
    14 => 'Paper Glue',
    15 => 'Plastic Cement',
    16 => 'Resin Glue',
    17 => 'Rubber Cement',
    18 => 'Tacky Glue',
    19 => 'White Glue',
    20 => 'Wood & Modeling Glue',
  ),
) ?>