<?php return array (
  'SubcategoryID' => 3315,
  'SubcategoryName' => 'AdhesivesFasteners',
  'PropertyName' => 'AdhesiveFastenerType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 1,
  'PropertyValueList' => 
  array (
    0 => 'Adhesive Dispensers',
    1 => 'Adhesive Foam',
    2 => 'Adhesive Removers',
    3 => 'Adhesive Sheets, Strips  & Dots',
    4 => 'Adhesive Sprays',
    5 => 'Adhesive Tapes',
    6 => 'Archival Adhesives',
    7 => 'Brads',
    8 => 'Ceiling & Window Hooks',
    9 => 'Clamps',
    10 => 'Clips',
    11 => 'Glues',
    12 => 'Hook & Loop Fasteners',
    13 => 'Magnets & Magnetic Sheets',
    14 => 'Mounting Systems',
    15 => 'Photo Corners',
  ),
) ?>