<?php return array (
  'SubcategoryID' => 708,
  'SubcategoryName' => 'CarSubwoofers',
  'PropertyName' => 'CarSubwoofersSeries',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'ANARCHY',
    1 => 'Atrend Series',
    2 => 'AXIS',
    3 => 'B Box Series',
    4 => 'Big Bang',
    5 => 'Blue Wave',
    6 => 'BT Series',
    7 => 'Champion Series',
    8 => 'Champion Series PRO',
    9 => 'Competition',
    10 => 'Force',
    11 => 'JackHammer',
    12 => 'Okur',
    13 => 'Okur K1 Series',
    14 => 'Okur K3 Series',
    15 => 'Okur K5 Series',
    16 => 'Okur K7 Series',
    17 => 'Okur K9 Series',
    18 => 'Onyx Series',
    19 => 'PHANTOM',
    20 => 'Picasso',
    21 => 'PylePro',
    22 => 'Road Thunder',
    23 => 'Xplod Slim Series',
  ),
) ?>