<?php return array (
  'SubcategoryID' => 662,
  'SubcategoryName' => 'CappuccinoEspressoMachines',
  'PropertyName' => 'EspressoBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'ascaso',
    1 => 'Bialetti',
    2 => 'BONJOUR',
    3 => 'BOSCH',
    4 => 'Breville',
    5 => 'BRIEL',
    6 => 'Bugatti',
    7 => 'Continental Electric',
    8 => 'Cuisinart',
    9 => 'DeLonghi',
    10 => 'Dolce Gusto',
    11 => 'Espressione',
    12 => 'FARBERWARE',
    13 => 'Gaggia',
    14 => 'Haier',
    15 => 'Hamilton Beach',
    16 => 'Jura-Capresso',
    17 => 'Kalorik',
    18 => 'KRUPS',
    19 => 'Melitta',
    20 => 'MR. COFFEE',
    21 => 'Nespresso',
    22 => 'Nostalgia Electrics',
    23 => 'Oster',
    24 => 'Philips',
    25 => 'Philips Saeco',
    26 => 'Premium',
    27 => 'Primula',
    28 => 'Saeco',
    29 => 'Salton',
    30 => 'Solis',
    31 => 'VillaWare',
    32 => 'Waring Pro',
  ),
) ?>