<?php return array (
  'SubcategoryID' => 729,
  'SubcategoryName' => 'MensShaversandTrimmers',
  'PropertyName' => 'MensShaverBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Andis',
    1 => 'BRAUN',
    2 => 'Carteret',
    3 => 'CONAIR',
    4 => 'Eltron',
    5 => 'Emjoi',
    6 => 'Gillette',
    7 => 'GNC',
    8 => 'Maxi-Matic',
    9 => 'Norelco',
    10 => 'Northwest',
    11 => 'Optimus',
    12 => 'Panasonic',
    13 => 'PHILIPS',
    14 => 'Philips Norelco',
    15 => 'Procter & Gamble',
    16 => 'RAGALTA',
    17 => 'REMINGTON',
    18 => 'Sakar',
    19 => 'SANYO',
    20 => 'Schick',
    21 => 'Vivitar',
    22 => 'WAHL',
    23 => 'Zadro',
  ),
) ?>