<?php return array (
  'SubcategoryID' => 678,
  'SubcategoryName' => 'VacuumSealersCanisters',
  'PropertyName' => 'CanisterBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Anchor Hocking',
    1 => 'Aroa Marketing',
    2 => 'ARY',
    3 => 'Chard',
    4 => 'Chef Buddy',
    5 => 'Cookpro',
    6 => 'Cuisinart',
    7 => 'Daewoo',
    8 => 'Deni',
    9 => 'Fit & Fresh',
    10 => 'FoodSaver',
    11 => 'freshvac',
    12 => 'frye international',
    13 => 'Glad',
    14 => 'Ideaworks',
    15 => 'Lipper',
    16 => 'Lock&Lock',
    17 => 'Metrokane',
    18 => 'MOSQUITO MAGNET',
    19 => 'NESCO',
    20 => 'Oliso',
    21 => 'OXO',
    22 => 'Ragalta',
    23 => 'RIVAL',
    24 => 'Rosewill',
    25 => 'Smart Planet',
    26 => 'Sunbeam',
    27 => 'Technosonic',
    28 => 'Thermos',
    29 => 'Tiger',
    30 => 'Typhoon',
    31 => 'VacMaster',
    32 => 'Vacu-Seal',
    33 => 'Waring Pro',
    34 => 'Weston',
    35 => 'ZOJIRUSHI',
  ),
) ?>