<?php return array (
  'SubcategoryID' => 779,
  'SubcategoryName' => 'Boomboxes',
  'PropertyName' => 'BoomboxBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'AKAI',
    1 => 'Aluratek',
    2 => 'auvi',
    3 => 'COBY',
    4 => 'Craig Electronics',
    5 => 'Emerson',
    6 => 'Excalibur Electronics',
    7 => 'GPX',
    8 => 'Grace Digital',
    9 => 'iLive',
    10 => 'JENSEN',
    11 => 'JVC',
    12 => 'jWIN',
    13 => 'LASONIC',
    14 => 'Logitech',
    15 => 'Magnasonic',
    16 => 'Margaritaville',
    17 => 'Memorex',
    18 => 'Moki',
    19 => 'Naxa',
    20 => 'Panasonic',
    21 => 'Philips',
    22 => 'RCA',
    23 => 'Sony',
    24 => 'SUPERSONIC',
    25 => 'Sylvania',
    26 => 'TDK',
    27 => 'Visual Land',
  ),
) ?>