<?php return array (
  'SubcategoryID' => 3294,
  'SubcategoryName' => 'OSOfficeFurniture',
  'PropertyName' => 'GroupOFSOption',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '1,000/Carton',
    1 => '1/pack',
    2 => '100 Sheets Capacity',
    3 => '2/pack',
    4 => '48" Top, Black',
    5 => '48" Top, Espresso',
    6 => '50/Pack',
    7 => '6/pack',
    8 => '60 Sheets Capacity',
    9 => '60" Contoured Top, Black',
    10 => '60" Contoured Top, Espresso',
    11 => '60" Contoured Top, White',
    12 => '65 Sheets Capacity',
    13 => '72" Top, Black',
    14 => '72" Top, Espresso',
    15 => 'Base, Black',
    16 => 'Base, Gray',
    17 => 'Base, White',
    18 => 'Desk-Clamp Work Station',
    19 => 'Desk-Clamp Work Station w/ Display Mount',
    20 => 'Full Strip',
    21 => 'Half Strip',
    22 => 'N/A',
    23 => 'Workstation',
  ),
) ?>