<?php return array (
  'SubcategoryID' => 3294,
  'SubcategoryName' => 'OSOfficeFurniture',
  'PropertyName' => 'OfficeFurnitureType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 1,
  'PropertyValueList' => 
  array (
    0 => 'Bin Cabinets',
    1 => 'Bookcases & Hutches',
    2 => 'Bridge',
    3 => 'Cabinet Accessories',
    4 => 'Cabinet Bench Accessoires',
    5 => 'Cabinet Benches',
    6 => 'Cabinets',
    7 => 'Carts & Stands',
    8 => 'Chair & Furniture Accessories',
    9 => 'Chairmats',
    10 => 'Chairs',
    11 => 'Clock',
    12 => 'Commercial Office Furniture',
    13 => 'Cubicles, Partitions & Dividers',
    14 => 'Desk Accessories & Organizers',
    15 => 'Desks & Laptop Stands',
    16 => 'Drawer Cabinets',
    17 => 'File Cabinets & Accessories',
    18 => 'Home & Small Office Furniture',
    19 => 'Lighting',
    20 => 'Medical & Maintenance Carts',
    21 => 'Medical Cabinets',
    22 => 'Mobile Storage Cabinets',
    23 => 'Modular Drawer Cabinets',
    24 => 'Modular Shelf Cabinets',
    25 => 'Office Decor',
    26 => 'Panel',
    27 => 'Paper Shredder',
    28 => 'Reception & Conference Room Furniture',
    29 => 'Service Counters',
    30 => 'Stand',
    31 => 'Storage & Shelving',
    32 => 'Storage Cabinets',
    33 => 'Tables',
    34 => 'Wall Cabinets',
    35 => 'Warming Cabinets',
    36 => 'Work Table Cabinets',
  ),
) ?>