<?php return array (
  'SubcategoryID' => 2609,
  'SubcategoryName' => 'ATCarElectronicsAccessories',
  'PropertyName' => 'CEAccessoriesType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 1,
  'PropertyValueList' => 
  array (
    0 => 'Amplifier & Processor Remotes',
    1 => 'Amplifier Bridging Modules',
    2 => 'Amplifier Cooling Fans',
    3 => 'Amplifier Housings',
    4 => 'Bass Blockers',
    5 => 'Capacitor',
    6 => 'Car Kit Speakerphone',
    7 => 'Car Stereo Add-Ons',
    8 => 'Charger Mount',
    9 => 'Dash Installation Kits',
    10 => 'DC Adapters',
    11 => 'Face Cases & Covers',
    12 => 'Firewall Bushings',
    13 => 'Ground Loop Isolators',
    14 => 'Headunit Replacement Converter',
    15 => 'Installation Tools',
    16 => 'Noise Filters',
    17 => 'Overhead Monitor Trim',
    18 => 'Pad',
    19 => 'Pre-Amps & Line Drivers',
    20 => 'Radio Transmitter',
    21 => 'Rearview Monitor',
    22 => 'Remote Controls',
    23 => 'Sound Dampners',
    24 => 'Speaker Baffles',
    25 => 'Speaker Brackets',
    26 => 'Speaker Grilles',
    27 => 'Speaker Spacers',
    28 => 'Test Disks & Lens Cleaners',
    29 => 'Trigger Output Modules',
    30 => 'Vehicle Headrest Mounts',
    31 => 'Vehicle Laptop Mounts',
    32 => 'Vehicle Mount',
    33 => 'Wire Harness',
  ),
) ?>