<?php return array (
  'SubcategoryID' => 173,
  'SubcategoryName' => 'TelephonyAccessories',
  'PropertyName' => 'DevicecasesAccType',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Adapter',
    1 => 'Alert Device',
    2 => 'Battery',
    3 => 'Bluetooth Gateway',
    4 => 'Cable',
    5 => 'Call ID Box',
    6 => 'Call Recorder',
    7 => 'Camera/Intercom',
    8 => 'Case',
    9 => 'Charger',
    10 => 'Dial pad',
    11 => 'Dock',
    12 => 'Expansion Module',
    13 => 'Extended Microphone',
    14 => 'Handset',
    15 => 'Headset',
    16 => 'Headset Amplifier',
    17 => 'Indicator Light',
    18 => 'Memory Card',
    19 => 'Speaker Phone',
    20 => 'Switch',
    21 => 'Telephone System',
    22 => 'Upgrade Kit',
    23 => 'Wall Plates & Jacks',
  ),
) ?>