<?php return array (
  'SubcategoryID' => 3191,
  'SubcategoryName' => 'Chromebooks',
  'PropertyName' => 'NBBOperatingSystem',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Chrome OS',
    1 => 'Linux',
    2 => 'Mac OS X v10.10 Yosemite',
    3 => 'Mac OS X v10.11 El Capitan',
    4 => 'Mac OS X v10.12 Sierra',
    5 => 'Mac OS X v10.3 Panther',
    6 => 'Mac OS X v10.4 Tiger',
    7 => 'Mac OS X v10.5 Leopard',
    8 => 'Mac OS X v10.6 Snow Leopard',
    9 => 'Mac OS X v10.7 Lion',
    10 => 'Mac OS X v10.8 Mountain Lion',
    11 => 'Mac OS X v10.9 Mavericks',
    12 => 'Windows 10 Home',
    13 => 'Windows 10 Pro',
    14 => 'Windows 7 Enterprise',
    15 => 'Windows 7 Home Premium',
    16 => 'Windows 7 Professional',
    17 => 'Windows 7 Starter',
    18 => 'Windows 7 Ultimate',
    19 => 'Windows 8',
    20 => 'Windows 8 Pro',
    21 => 'Windows 8 RT',
    22 => 'Windows 8.1',
    23 => 'Windows 8.1 Pro',
    24 => 'Windows Embedded Standard',
    25 => 'Windows Vista Business',
    26 => 'Windows Vista Home Basic',
    27 => 'Windows Vista Home Premium',
    28 => 'Windows Vista Ultimate',
    29 => 'Windows XP Embedded',
    30 => 'Windows XP Home',
    31 => 'Windows XP Media Center Edition',
    32 => 'Windows XP Professional',
    33 => 'Windows XP Tablet PC Edition',
  ),
) ?>