<?php return array (
  'SubcategoryID' => 1655,
  'SubcategoryName' => 'BowlingBallsAccessories',
  'PropertyName' => 'BowlingBallsSize',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '10 Pounds',
    1 => '11 Pounds',
    2 => '12 Pounds',
    3 => '13 Pounds',
    4 => '14 Pounds',
    5 => '15 Pounds',
    6 => '16 Pounds',
    7 => '17 Pounds',
    8 => '18 Pounds',
    9 => '4 Pounds',
    10 => '5 Pounds',
    11 => '6 Pounds',
    12 => '7 Pounds',
    13 => '8 Pounds',
    14 => '9 Pounds',
    15 => 'Large',
    16 => 'Medium',
    17 => 'One Size Fits All',
    18 => 'Small',
    19 => 'X-Large',
    20 => 'X-Small',
    21 => 'XX-Large',
    22 => 'XXX-Large',
    23 => 'XXXX-Large',
  ),
) ?>