<?php return array (
  'SubcategoryID' => 3118,
  'SubcategoryName' => 'PS4Accessories',
  'PropertyName' => 'PS4ACCColor',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Black',
    1 => 'Black/Blue',
    2 => 'Blue',
    3 => 'Blue Urban',
    4 => 'Brown',
    5 => 'Glacier White',
    6 => 'Gold',
    7 => 'Green',
    8 => 'Grey',
    9 => 'N/A',
    10 => 'Orange',
    11 => 'Pink',
    12 => 'Red',
    13 => 'Sliver',
    14 => 'Sticker Bomb',
    15 => 'Urban Camouflage',
    16 => 'Wave Blue',
    17 => 'White',
    18 => 'White Nightmare',
    19 => 'Yellow',
  ),
) ?>