<?php return array (
  'SubcategoryID' => 3118,
  'SubcategoryName' => 'PS4Accessories',
  'PropertyName' => 'PS4ACCBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Arsenal',
    1 => 'Astro Gaming',
    2 => 'Avenger',
    3 => 'AWA',
    4 => 'CTA Digital',
    5 => 'dreamGEAR',
    6 => 'GAEMS',
    7 => 'Gioteck',
    8 => 'HORI',
    9 => 'Hydra Performance',
    10 => 'Hyperkin',
    11 => 'INSTEN',
    12 => 'KMD',
    13 => 'LucidSound',
    14 => 'Mad Catz',
    15 => 'Nyko',
    16 => 'ORB',
    17 => 'PDP',
    18 => 'Plantronics',
    19 => 'PowerA',
    20 => 'Razer',
    21 => 'RDS',
    22 => 'Sony',
    23 => 'SquidGrip',
    24 => 'SteelSeries',
    25 => 'TekNmotion',
    26 => 'Thrustmaster',
    27 => 'Tomee',
    28 => 'Tosa',
    29 => 'TRITTON',
    30 => 'Turtle Beach',
    31 => 'Worldnect',
  ),
) ?>