<?php return array (
  'SubcategoryID' => 20,
  'SubcategoryName' => 'MonitorsLCDFlatPanel',
  'PropertyName' => 'MonitorConvenienceStandAdjustments',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Height',
    1 => 'Height & Pivot',
    2 => 'Height & Swivel',
    3 => 'Height & Tilt',
    4 => 'Height, Pivot, Swivel',
    5 => 'Height, Pivot, Swivel, Tilt',
    6 => 'Height, Pivot, Tilt',
    7 => 'Height, Swivel, Tilt',
    8 => 'No',
    9 => 'Pivot',
    10 => 'Pivot & Swivel',
    11 => 'Pivot & Tilt',
    12 => 'Pivot, Swivel & Tilt',
    13 => 'Round',
    14 => 'Swivel',
    15 => 'Swivel & Tilt',
    16 => 'Tilt',
  ),
) ?>