<?php return array (
  'SubcategoryID' => 20,
  'SubcategoryName' => 'MonitorsLCDFlatPanel',
  'PropertyName' => 'MonitorDisplayDisplayType',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '8" Back LCD',
    1 => 'Full HD',
    2 => 'HD',
    3 => 'HD 1080',
    4 => 'HD 720',
    5 => 'HD+',
    6 => 'MDA',
    7 => 'No Rear Display',
    8 => 'QFHD',
    9 => 'QSXGA',
    10 => 'QVGA',
    11 => 'QXGA',
    12 => 'SVGA',
    13 => 'SXGA',
    14 => 'SXGA+',
    15 => 'UD',
    16 => 'UHD',
    17 => 'UXGA',
    18 => 'VFD',
    19 => 'VGA',
    20 => 'WQHD',
    21 => 'WQXGA',
    22 => 'WSXGA',
    23 => 'WSXGA+',
    24 => 'WUXGA',
    25 => 'WVGA',
    26 => 'WXGA',
    27 => 'WXGA+',
    28 => 'XGA',
  ),
) ?>