<?php return array (
  'SubcategoryID' => 553,
  'SubcategoryName' => 'MacDisplay',
  'PropertyName' => 'MacDisplayAdjustableStand',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Height & Pivot Adjustments',
    1 => 'Height & Swivel Adjustments',
    2 => 'Height & Tilt Adjustments',
    3 => 'Height Adjustments',
    4 => 'Height, Pivot, Swivel Adjustments',
    5 => 'Height, Pivot, Swivel, Tilt Adjustments',
    6 => 'Height, Pivot, Tilt Adjustments',
    7 => 'Height, Swivel, Tilt Adjustments',
    8 => 'No',
    9 => 'Pivot & Swivel Adjustments',
    10 => 'Pivot & Tilt Adjustments',
    11 => 'Pivot Adjustments',
    12 => 'Swivel & Tilt Adjustments',
    13 => 'Swivel Adjustments',
    14 => 'Tilt Adjustments',
  ),
) ?>