<?php return array (
  'SubcategoryID' => 553,
  'SubcategoryName' => 'MacDisplay',
  'PropertyName' => 'MacDisplayConnectors',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'D-Sub',
    1 => 'D-Sub, BNC',
    2 => 'D-Sub, DVI',
    3 => 'D-Sub, DVI, S-Video',
    4 => 'D-Sub, DVI, S-Video, BNC',
    5 => 'D-Sub, DVI, S-Video, Component',
    6 => 'D-Sub, DVI, S-Video, Composite',
    7 => 'D-Sub, DVI, S-Video, Composite, Component, RCA',
    8 => 'D-Sub, DVI, S-Video, Composite, RCA',
    9 => 'D-Sub, DVI, TV',
    10 => 'D-Sub, DVI, USB',
    11 => 'D-Sub, DVI, Video, USB',
    12 => 'D-Sub, DVI-D',
    13 => 'D-Sub, DVI-I',
    14 => 'D-Sub, S-Video, Composite',
    15 => 'D-Sub, S-Video, Composite, Component, RCA',
    16 => 'D-Sub, S-Video, Composite, RCA',
    17 => 'D-Sub, S-Video, RCA',
    18 => 'Dual D-Sub',
    19 => 'DVI',
    20 => 'S-Video, Composite, Component',
  ),
) ?>