<?php return array (
  'SubcategoryID' => 2084,
  'SubcategoryName' => 'HIShowerHeads',
  'PropertyName' => 'HIShowerHeadsBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Alsons',
    1 => 'American Standard',
    2 => 'Aroma Sense',
    3 => 'DELTA',
    4 => 'Fusion',
    5 => 'Grohe',
    6 => 'Hansgrohe',
    7 => 'Home Basics',
    8 => 'KOHLER',
    9 => 'La Toscana',
    10 => 'MOEN',
    11 => 'Opus',
    12 => 'Pegasus',
    13 => 'Pfister',
    14 => 'Pollenex',
    15 => 'Sunbeam',
    16 => 'Symmons',
    17 => 'T&S Brass',
    18 => 'Westbrass',
  ),
) ?>