<?php return array (
  'SubcategoryID' => 600,
  'SubcategoryName' => 'BluRayBurners',
  'PropertyName' => 'BWODDBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Addonics',
    1 => 'Aluratek',
    2 => 'ASUS',
    3 => 'BenQ',
    4 => 'BUFFALO',
    5 => 'CyberpowerPC',
    6 => 'Generic',
    7 => 'HornetTek',
    8 => 'HP',
    9 => 'I/OMAGIC',
    10 => 'Kanguru',
    11 => 'LACIE',
    12 => 'LENOVO',
    13 => 'LG',
    14 => 'LITE-ON',
    15 => 'Memorex',
    16 => 'PHILIPS',
    17 => 'Pioneer',
    18 => 'PLDS',
    19 => 'PLEXTOR',
    20 => 'SAMSUNG',
    21 => 'SilverStone',
    22 => 'SONY',
    23 => 'Sony Optiarc',
    24 => 'Vinpower',
  ),
) ?>