<?php return array (
  'SubcategoryID' => 242,
  'SubcategoryName' => 'PlaystationPlaystation2Accessories',
  'PropertyName' => 'PS2ACCBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'ACTIVISION',
    1 => 'Arsenal',
    2 => 'AVB',
    3 => 'C2G',
    4 => 'dreamGEAR',
    5 => 'eDimensional',
    6 => 'Genius',
    7 => 'HIP GEAR',
    8 => 'i-con',
    9 => 'Innovation',
    10 => 'Insten',
    11 => 'intec',
    12 => 'JOYTECH',
    13 => 'Katana',
    14 => 'KMD',
    15 => 'KYE',
    16 => 'Logitech',
    17 => 'Mad Catz',
    18 => 'MONSTER',
    19 => 'MOTOROLA',
    20 => 'Naki',
    21 => 'NYKO',
    22 => 'PELICAN',
    23 => 'Psyclone',
    24 => 'QMOTIONS',
    25 => 'RADICA',
    26 => 'RedBeard',
    27 => 'redoctane',
    28 => 'Sakar',
    29 => 'SONY',
    30 => 'split fish GAMEWARE',
    31 => 'TAC',
    32 => 'THRUSTMASTER',
    33 => 'Xploder',
  ),
) ?>