<?php return array (
  'SubcategoryID' => 451,
  'SubcategoryName' => 'KVMCables',
  'PropertyName' => 'KVMCableColor',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '2-Tone',
    1 => 'Beige',
    2 => 'Black',
    3 => 'Blue',
    4 => 'Charcoal',
    5 => 'Dark Gray',
    6 => 'Gray',
    7 => 'Green',
    8 => 'Ivory',
    9 => 'Light Gray',
    10 => 'Multi-Color',
    11 => 'Off White',
    12 => 'Pink',
    13 => 'Red',
    14 => 'Silver',
    15 => 'White',
    16 => 'Yellow',
  ),
) ?>