<?php return array (
  'SubcategoryID' => 1490,
  'SubcategoryName' => 'Handbags',
  'PropertyName' => 'HandbagsBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Blue Avocado',
    1 => 'Christian Siriano',
    2 => 'Concept One by USPA Accessories',
    3 => 'Haiku',
    4 => 'iPurse',
    5 => 'Joe\'s Jeans',
    6 => 'Kipling',
    7 => 'MLine',
    8 => 'Mobile Edge',
    9 => 'pacific DESIGN',
    10 => 'Piel LEATHER',
    11 => 'Rogue Wallets',
    12 => 'Shorebags',
    13 => 'Vagabond Traveler',
    14 => 'Vandor',
    15 => 'Visconti',
  ),
) ?>