<?php return array (
  'SubcategoryID' => 3197,
  'SubcategoryName' => 'HLBeds',
  'PropertyName' => 'HLBedType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 1,
  'IsRequired' => 1,
  'PropertyValueList' => 
  array (
    0 => 'Adjustable Beds',
    1 => 'Air Beds',
    2 => 'Bunk & Loft Beds',
    3 => 'Canopy Beds',
    4 => 'Captain Beds',
    5 => 'Daybeds & Trundle Beds',
    6 => 'Folding Beds',
    7 => 'Headboards & Footboards',
    8 => 'Low Profile Beds',
    9 => 'Metal Beds',
    10 => 'Platform Beds',
    11 => 'Poster Beds',
    12 => 'Sleigh Beds',
    13 => 'Storage Beds',
    14 => 'Underbed Storage',
    15 => 'Upholstered Bed',
    16 => 'Wall/Murphy Beds',
    17 => 'Waterbeds',
  ),
) ?>