<?php return array (
  'SubcategoryID' => 3197,
  'SubcategoryName' => 'HLBeds',
  'PropertyName' => 'HLFurnitureHardwareFinish',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Biscotti',
    1 => 'Biscotti & Black',
    2 => 'Black & Ebony',
    3 => 'Black & White',
    4 => 'Cappuccino',
    5 => 'Ebony',
    6 => 'Ivory & Maple',
    7 => 'Maple & white',
    8 => 'Matte Black',
    9 => 'Moka',
    10 => 'Moka & Black',
    11 => 'Truffle',
    12 => 'Walnut & Black',
    13 => 'Walnut & Charcoal',
    14 => 'Walnut & White',
    15 => 'White & Ebony',
    16 => 'White & Walnut',
    17 => 'White & Yellow',
  ),
) ?>