<?php return array (
  'SubcategoryID' => 63,
  'SubcategoryName' => 'Keyboards',
  'PropertyName' => 'GroupKBStyle',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '3-Color LED',
    1 => '7-Color LED',
    2 => 'Android Hot Keys',
    3 => 'Blue LED',
    4 => 'Chroma',
    5 => 'Green LED',
    6 => 'ios Hot Keys',
    7 => 'Multi-color LED',
    8 => 'No',
    9 => 'POSEIDON Z',
    10 => 'POSEIDON ZX',
    11 => 'Red LED',
    12 => 'RGB',
    13 => 'Standard',
    14 => 'Standard Stealth',
    15 => 'Tenkeyless',
    16 => 'Tournament',
    17 => 'Tournament  Stealth',
    18 => 'Ultimate',
    19 => 'Ultimate Stealth',
    20 => 'White LED',
  ),
) ?>