<?php return array (
  'SubcategoryID' => 63,
  'SubcategoryName' => 'Keyboards',
  'PropertyName' => 'KBTrackingMethod',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Ball',
    1 => 'BlueTrack',
    2 => 'HulaPoint',
    3 => 'HulaPoint II',
    4 => 'Joystick',
    5 => 'Laser',
    6 => 'Optical',
    7 => 'Pointing Stick',
    8 => 'Scroll Wheel',
    9 => 'Thumb Stick',
    10 => 'Touch Scroll',
    11 => 'TouchPad',
    12 => 'TrackBall',
    13 => 'Trackpoint',
    14 => 'UltraNav',
  ),
) ?>