<?php return array (
  'SubcategoryID' => 546,
  'SubcategoryName' => 'NintendoWiiAccessories',
  'PropertyName' => 'WiiACCType',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Adapter',
    1 => 'Armored Case',
    2 => 'Battery',
    3 => 'Battery Pack',
    4 => 'Cable',
    5 => 'Case',
    6 => 'Charging Station',
    7 => 'Clip',
    8 => 'Controller',
    9 => 'Cooler',
    10 => 'Face Plates',
    11 => 'Fit kit',
    12 => 'Game Cases',
    13 => 'Headset',
    14 => 'Light & Magnifier',
    15 => 'Link Cable',
    16 => 'Memory Card',
    17 => 'Point Card',
    18 => 'Power Adaptor',
    19 => 'Remote',
    20 => 'Repair',
    21 => 'Screen Protector',
    22 => 'Sensor Bar',
    23 => 'Sound',
    24 => 'Stand',
    25 => 'Starter Kit',
    26 => 'Stylus',
    27 => 'Wireless Adapter',
  ),
) ?>