<?php return array (
  'SubcategoryID' => 35,
  'SubcategoryName' => 'PDAHandheldPCs',
  'PropertyName' => 'PDABrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'ASUS',
    1 => 'Cherry',
    2 => 'COMPAQ',
    3 => 'DELL',
    4 => 'ECTACO',
    5 => 'Franklin',
    6 => 'HP',
    7 => 'Intermec',
    8 => 'Lingo',
    9 => 'Mio',
    10 => 'Motorola',
    11 => 'NOKIA',
    12 => 'palm',
    13 => 'Pepper Pad',
    14 => 'PHAROS',
    15 => 'Royal',
    16 => 'SHARP',
    17 => 'Socket',
    18 => 'SONY',
    19 => 'SVAT',
    20 => 'Tapwave',
    21 => 'TOSHIBA',
  ),
) ?>