<?php return array (
  'SubcategoryID' => 679,
  'SubcategoryName' => 'Steamers',
  'PropertyName' => 'SteamersBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'BACK TO BASICS',
    1 => 'Bella',
    2 => 'Black & Decker',
    3 => 'Breville',
    4 => 'CONAIR',
    5 => 'Cuisinart',
    6 => 'CuiZen',
    7 => 'Deni',
    8 => 'E-Ware',
    9 => 'Hamilton Beach',
    10 => 'Home Image',
    11 => 'M.E.Heuck CO.',
    12 => 'Master Chef',
    13 => 'NESCO',
    14 => 'NutriChef',
    15 => 'Oreck',
    16 => 'Oster',
    17 => 'Ovente',
    18 => 'Reliable',
    19 => 'RIVAL',
    20 => 'Rosewill',
    21 => 'SteamFast',
    22 => 'T-Fal',
    23 => 'TATUNG',
    24 => 'Tayama',
    25 => 'Taylor',
    26 => 'Toastess',
    27 => 'TYPHOON',
    28 => 'West Bend',
  ),
) ?>