<?php return array (
  'SubcategoryID' => 1585,
  'SubcategoryName' => 'DogsTreats',
  'PropertyName' => 'DogTreatsType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Biscuits',
    1 => 'Canned Food',
    2 => 'Chew Toys',
    3 => 'Cookies & Cupcakes',
    4 => 'Dental Treats',
    5 => 'Dry Food',
    6 => 'Food Pouches',
    7 => 'Food Toppers',
    8 => 'Fortified Treats',
    9 => 'Meat Treats',
    10 => 'Natural Food',
    11 => 'Pill Pockets',
    12 => 'Rings',
    13 => 'Smoothie Treats',
    14 => 'Stuffers',
    15 => 'Supplements',
    16 => 'Training Treats',
    17 => 'Treat Dispensers',
  ),
) ?>