<?php return array (
  'SubcategoryID' => 646,
  'SubcategoryName' => 'Dishwashers',
  'PropertyName' => 'DishwasherBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Amana',
    1 => 'Avanti',
    2 => 'BROAN',
    3 => 'Danby',
    4 => 'Frigidaire',
    5 => 'GE',
    6 => 'Haier',
    7 => 'Jenn-Air',
    8 => 'KitchenAid',
    9 => 'LG',
    10 => 'Magic Chef',
    11 => 'Midea',
    12 => 'Petra',
    13 => 'SAMSUNG',
    14 => 'Sunpentown',
    15 => 'True & Tidy',
    16 => 'Watts',
    17 => 'Whirlpool',
  ),
) ?>