<?php return array (
  'SubcategoryID' => 668,
  'SubcategoryName' => 'WaterDispensers',
  'PropertyName' => 'WaterDispenserBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '3M',
    1 => 'Aqua-Pure',
    2 => 'Avanti',
    3 => 'Black & Decker',
    4 => 'Brita',
    5 => 'Brondell',
    6 => 'Cuisinart',
    7 => 'ELKAY',
    8 => 'FARBERWARE',
    9 => 'Fujitronic',
    10 => 'Haier',
    11 => 'Homedics',
    12 => 'Kohler',
    13 => 'NARITA',
    14 => 'NOSTALGIA ELECTRICS',
    15 => 'Panasonic',
    16 => 'PELONIS',
    17 => 'PUR',
    18 => 'Pursonic',
    19 => 'Ragalta',
    20 => 'Rosewill',
    21 => 'Samsung',
    22 => 'SodaStream',
    23 => 'Soleus Air',
    24 => 'Sunbeam',
    25 => 'Sunpentown',
    26 => 'TATUNG',
    27 => 'TIGER',
    28 => 'Toastess',
    29 => 'Whynter',
    30 => 'Zero Water',
    31 => 'ZOJIRUSHI',
  ),
) ?>