<?php return array (
  'SubcategoryID' => 2180,
  'SubcategoryName' => 'HLHolidayDecor',
  'PropertyName' => 'HLHolidayDecorOccasion',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '4th of July',
    1 => 'Birthday',
    2 => 'Christmas',
    3 => 'Easter',
    4 => 'Father\'s Day',
    5 => 'Graduation',
    6 => 'Halloween',
    7 => 'Hanukkah',
    8 => 'Mother\'s Day',
    9 => 'New Baby',
    10 => 'New Year\'s Eve',
    11 => 'Retirement',
    12 => 'St. Patrick\'s Day',
    13 => 'Thanksgiving',
    14 => 'Valentine\'s Day',
    15 => 'Wedding & Anniversary',
    16 => 'Welcome Home',
  ),
) ?>