<?php return array (
  'SubcategoryID' => 2180,
  'SubcategoryName' => 'HLHolidayDecor',
  'PropertyName' => 'HLHolidayDecorTheme',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Angels',
    1 => 'Animals & Insects',
    2 => 'Baby',
    3 => 'Beach & Tropical',
    4 => 'Beer',
    5 => 'Boats & Ships',
    6 => 'Box Sets',
    7 => 'Careers & Occupations',
    8 => 'Cartoons',
    9 => 'Christmas Classics',
    10 => 'Disney',
    11 => 'Divas',
    12 => 'Fairytale & Storybook',
    13 => 'Food & Beverage',
    14 => 'Historical',
    15 => 'Hunting',
    16 => 'Military',
    17 => 'Musical Instruments',
    18 => 'Religious',
    19 => 'Santa Clause',
    20 => 'Snowmen',
    21 => 'Sports',
    22 => 'Sports Teams',
    23 => 'Superheros',
    24 => 'TV & Movies',
    25 => 'Wedding & Anniversary',
    26 => 'Western',
  ),
) ?>