<?php return array (
  'SubcategoryID' => 2180,
  'SubcategoryName' => 'HLHolidayDecor',
  'PropertyName' => 'HLHolidayDecorType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 1,
  'PropertyValueList' => 
  array (
    0 => 'Christmas Trees',
    1 => 'Collectibles',
    2 => 'Decorations',
    3 => 'Lawn & Yard',
    4 => 'Lighted Yard Art & Displays',
    5 => 'Lights',
    6 => 'Nativity Pieces',
    7 => 'Ornaments',
    8 => 'Other Accessories',
    9 => 'Stockings',
    10 => 'Table Top Decorations',
    11 => 'Tree Skirts',
    12 => 'Tree Stands',
    13 => 'Tree Toppers',
    14 => 'Window Decor',
    15 => 'Wreaths & Garlands',
  ),
) ?>