<?php return array (
  'SubcategoryID' => 2120,
  'SubcategoryName' => 'HIKitchenSinks',
  'PropertyName' => 'HIKitchenSinksBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'American Standard',
    1 => 'Astracast',
    2 => 'Blanco',
    3 => 'Bootz',
    4 => 'DELTA',
    5 => 'Elkay',
    6 => 'FIAT',
    7 => 'Franke',
    8 => 'Griffin',
    9 => 'Kindred',
    10 => 'KOHLER',
    11 => 'Magnus',
    12 => 'MOEN',
    13 => 'Pegasus',
    14 => 'Swan',
    15 => 'Whitehaus',
  ),
) ?>