<?php return array (
  'SubcategoryID' => 2844,
  'SubcategoryName' => 'HLDeskLamps',
  'PropertyName' => 'HIDesklampsBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '4D Concepts',
    1 => 'Bell + Howell',
    2 => 'ENHANCE',
    3 => 'Grandrich',
    4 => 'Lavish Home',
    5 => 'Ledu',
    6 => 'LumiSource',
    7 => 'Normande Lighting',
    8 => 'Northwest',
    9 => 'NTW',
    10 => 'Rosewill',
    11 => 'SALAV',
    12 => 'Trademark',
    13 => 'Trademark Home',
    14 => 'Uttermost',
    15 => 'Verilux',
    16 => 'Zuo Modern',
  ),
) ?>