<?php return array (
  'SubcategoryID' => 764,
  'SubcategoryName' => 'Heater',
  'PropertyName' => 'HeaterColor',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '2-Tone',
    1 => 'Almond',
    2 => 'Black',
    3 => 'Black Iron',
    4 => 'Blue',
    5 => 'Brown',
    6 => 'Coffee',
    7 => 'Copper/Iron',
    8 => 'Espresso',
    9 => 'Gray',
    10 => 'Medium Oak',
    11 => 'Metal',
    12 => 'Orange',
    13 => 'Purple',
    14 => 'Red',
    15 => 'Silver',
    16 => 'Tan',
    17 => 'Tuscan Walnut',
    18 => 'White',
    19 => 'White - Silver',
    20 => 'Wood',
    21 => 'Yellow',
  ),
) ?>