<?php return array (
  'SubcategoryID' => 495,
  'SubcategoryName' => 'HomeElectronicsAccessories',
  'PropertyName' => 'HECablesColor',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '2-Tone',
    1 => 'Almond',
    2 => 'Aluminum',
    3 => 'Beige',
    4 => 'Black',
    5 => 'Black and White',
    6 => 'Blue',
    7 => 'Brown',
    8 => 'Caramel',
    9 => 'Charcoal',
    10 => 'Chocolat',
    11 => 'Clear',
    12 => 'Copper',
    13 => 'Glacier',
    14 => 'Glow',
    15 => 'Gold',
    16 => 'Golden',
    17 => 'Gray',
    18 => 'Green',
    19 => 'Ivory',
    20 => 'Mesh',
    21 => 'Multi-Color',
    22 => 'Onyx',
    23 => 'Orange',
    24 => 'Pink',
    25 => 'Purple',
    26 => 'Red',
    27 => 'Silver',
    28 => 'Translucent',
    29 => 'Translucent & Glow',
    30 => 'Transparent',
    31 => 'White',
    32 => 'Wood',
    33 => 'Yellow',
  ),
) ?>