<?php return array (
  'SubcategoryID' => 3268,
  'SubcategoryName' => 'HLHomeAccents',
  'PropertyName' => 'HLHomeAccentMaterial',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Canvas',
    1 => 'Cotton',
    2 => 'Glass',
    3 => 'Leather / Faux leather',
    4 => 'Metal',
    5 => 'Mirrored',
    6 => 'Paper',
    7 => 'Plastic/Chrome Metal',
    8 => 'Reclaimed Wood',
    9 => 'Recycled Cotton',
    10 => 'Recycled Plastics',
    11 => 'Resin',
    12 => 'Wood',
    13 => 'Wood / Metal',
  ),
) ?>