<?php return array (
  'SubcategoryID' => 3268,
  'SubcategoryName' => 'HLHomeAccents',
  'PropertyName' => 'HLHomeAccentType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 1,
  'PropertyValueList' => 
  array (
    0 => 'Baskets',
    1 => 'Bookends',
    2 => 'Candle Holders',
    3 => 'Candles',
    4 => 'Decorative Bowls',
    5 => 'Decorative Boxes',
    6 => 'Decorative Plates',
    7 => 'Decorative Trays',
    8 => 'Faux Florals & Plants',
    9 => 'Folding Screens',
    10 => 'Globes',
    11 => 'Indoor Floor Fountains',
    12 => 'Indoor Tabletop Fountains',
    13 => 'Keepsakes',
    14 => 'Photo Albums',
    15 => 'Picture Frames',
    16 => 'Piggy Banks & Money Jars',
    17 => 'Sand Timers',
    18 => 'Sculptures & Figurines',
    19 => 'Vases',
    20 => 'Wall Hooks',
    21 => 'Window Magnets',
  ),
) ?>