<?php return array (
  'SubcategoryID' => 3179,
  'SubcategoryName' => 'HLMeatPoultrySeafoodTools',
  'PropertyName' => 'HLMeatType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 1,
  'PropertyValueList' => 
  array (
    0 => 'Basters & Brushes',
    1 => 'Bone Scrapers',
    2 => 'Carving Gloves',
    3 => 'Caviar Spoons',
    4 => 'Clam & Oyster Knives',
    5 => 'Crab & Lobster Cracker',
    6 => 'Cutlet Frills',
    7 => 'Egg Tools',
    8 => 'Fish Scalers',
    9 => 'Fish Spatulas',
    10 => 'Fish Tweezers',
    11 => 'Flavor Injectors',
    12 => 'Hamburger Molds',
    13 => 'Hammers & Mallets',
    14 => 'Meat Pounder',
    15 => 'Meat Presses',
    16 => 'Meat Slicers',
    17 => 'Meatballers',
    18 => 'Roast Lifters',
    19 => 'Seafood Picks & Forks',
    20 => 'Seafood Scissors',
    21 => 'Shrimp Deveiner',
    22 => 'Tenderizers',
    23 => 'Trussing Needles',
  ),
) ?>