<?php return array (
  'SubcategoryID' => 3277,
  'SubcategoryName' => 'OSBusinessTaxForms',
  'PropertyName' => 'BusinessTaxFormsType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 1,
  'PropertyValueList' => 
  array (
    0 => '1099 Envelopes',
    1 => '1099 Forms',
    2 => 'Columnar Pads & Ledgers',
    3 => 'Contractor Forms',
    4 => 'Form Holders',
    5 => 'Healthcare Insurance Forms',
    6 => 'Human Resources Forms',
    7 => 'Labor Law & Safety Posters',
    8 => 'Legal Forms',
    9 => 'Other Forms',
    10 => 'Receipts Books',
    11 => 'Sales & Ordering Forms',
    12 => 'Shipping & Receiving Forms',
    13 => 'Tax Forms',
  ),
) ?>