<?php return array (
  'SubcategoryID' => 1925,
  'SubcategoryName' => 'HIElectricalIndustrialWire',
  'PropertyName' => 'HIElecIndWiresType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Aluminum Building Wire',
    1 => 'Automotive Wire & Cable',
    2 => 'Battery Cable',
    3 => 'Bonding & Grounding Wire',
    4 => 'Bonding & Grounding Wire Accessories',
    5 => 'Building Cable',
    6 => 'Building Wire',
    7 => 'Bus Drop & Tray Cable',
    8 => 'Central Office Power Cable',
    9 => 'Continuous Flexing Cable',
    10 => 'Copper Building Wire',
    11 => 'Diesel Locomotive',
    12 => 'High Temperature Lead Wire',
    13 => 'Hookup Wire',
    14 => 'Industrial Cable',
    15 => 'Jumper Cable',
    16 => 'Lamp Cord',
    17 => 'Low Volt',
    18 => 'Machine Tool Wire',
    19 => 'Metal Clad Whips',
    20 => 'Portable Cord',
    21 => 'Power Supply Cord',
    22 => 'Specialty Wire & Cable',
    23 => 'Sprinkler Wire & Irrigation Cable',
    24 => 'Stage Lighting Cable',
    25 => 'Submersible Pump Cable',
    26 => 'Thermocouple Wire',
    27 => 'Thermostat Cable',
    28 => 'Type G Cable',
    29 => 'Type G-GC Cable',
    30 => 'Type MC',
    31 => 'Type W Cable',
    32 => 'Type W Magnet Crane',
    33 => 'Underground',
    34 => 'Welding Cables',
    35 => 'Wire Wrapping Wire',
  ),
) ?>