<?php return array (
  'SubcategoryID' => 716,
  'SubcategoryName' => 'PopcornPoppers',
  'PropertyName' => 'PopcornPopperBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'BACK TO BASICS',
    1 => 'Bella',
    2 => 'Chard',
    3 => 'Chef Buddy',
    4 => 'Cuisinart',
    5 => 'Culinair',
    6 => 'Elite',
    7 => 'Epoca',
    8 => 'Hamilton Beach',
    9 => 'Hello Kitty',
    10 => 'Holstein Housewares',
    11 => 'Kalorik',
    12 => 'MAXI-MATIC',
    13 => 'None',
    14 => 'NOSTALGIA ELECTRICS',
    15 => 'Ovente',
    16 => 'PRESTO',
    17 => 'Rosewill',
    18 => 'Sensio',
    19 => 'Smart Planet',
    20 => 'Sunbeam',
    21 => 'Toastess',
    22 => 'Waring Pro',
    23 => 'West Bend',
  ),
) ?>