<?php return array (
  'SubcategoryID' => 23,
  'SubcategoryName' => 'MP3MP4Players',
  'PropertyName' => 'CNETMP3CompatibleOperatingSystems',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Windows 2000/XP',
    1 => 'Windows 2000/XP/ME/Mac OS',
    2 => 'Windows 98/2000/XP/Vista, Apple Mac OS',
    3 => 'Windows 98SE/2000/ME/XP/MAC OS X v10.2 or higher',
    4 => 'Windows 98SE/ME/2000/XP',
    5 => 'Windows 98SE/ME/2000/XP Home/XP Pro',
    6 => 'Windows 98SE/ME/2000/XP/Mac OS 9.0 or higher',
    7 => 'Windows ME/2000/XP',
    8 => 'Windows ME/2000/XP/Meida Center/Vista',
    9 => 'Windows ME/2000/XP/Vista',
    10 => 'Windows ME/2000/XP/Vista/OS X or higher',
    11 => 'Windows ME/2000/XP/Vista/OS X or higher/Linux',
    12 => 'Windows XP',
    13 => 'Windows XP SP2 / Mac OS X 10.3 / Linux',
    14 => 'Windows XP/ Vista',
    15 => 'Windows XP/ Vista / Windows 7',
    16 => 'Windows XP/ Vista / Windows 7/ Mac OS/ Linux',
    17 => 'Windows XP/ Vista/Mac OS/Linux',
  ),
) ?>