<?php return array (
  'SubcategoryID' => 23,
  'SubcategoryName' => 'MP3MP4Players',
  'PropertyName' => 'CNETMP3AudioRecording',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'IMA ADPCM',
    1 => 'MP3',
    2 => 'MP3/WAV',
    3 => 'MP3/WAV/ACT',
    4 => 'TVF',
    5 => 'Voice',
    6 => 'Voice, FM',
    7 => 'Voice, FM, Line-in',
    8 => 'Voice, Line-in',
    9 => 'WAV',
    10 => 'WAV/ACT',
    11 => 'WAV/ADPCM',
    12 => 'WMA',
    13 => 'WMA/FLAC',
    14 => 'Yes',
  ),
) ?>