<?php return array (
  'SubcategoryID' => 23,
  'SubcategoryName' => 'MP3MP4Players',
  'PropertyName' => 'CNETMP3ImagesFormats',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'BMP',
    1 => 'BMP/JPEG',
    2 => 'BMP/JPEG/GIF',
    3 => 'BMP/JPEG/GIF/PNG/TIFF',
    4 => 'BMP/JPEG/GIF/TIFF',
    5 => 'BMP/JPEG/GIF/TIFF/PNG/RAW',
    6 => 'BMP/JPEG/JIF',
    7 => 'BMP/JPEG/PNG',
    8 => 'BMP/JPEG/PNG/GIF',
    9 => 'BMP/JPEG/PNG/NEF',
    10 => 'BMP/JPEG/PNG/RAW',
    11 => 'BMP/JPEG/TIFF',
    12 => 'JPEG',
    13 => 'JPEG/BMP/GIF/TIFF/PSD/PNG',
    14 => 'JPEG/GIF',
    15 => 'JPEG/GIF/SWF',
    16 => 'JPEG/MPG',
    17 => 'JPEG/PNG',
    18 => 'JPEG/RAW',
  ),
) ?>