<?php return array (
  'SubcategoryID' => 2800,
  'SubcategoryName' => 'HLBarstools',
  'PropertyName' => 'BarstoolsStyle',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Art Deco',
    1 => 'Arts-N-Crafts',
    2 => 'Asian',
    3 => 'Casual',
    4 => 'Coastal',
    5 => 'Contemporary',
    6 => 'Cottage',
    7 => 'Country',
    8 => 'Country French',
    9 => 'Industrial',
    10 => 'Lodge',
    11 => 'Mid Century',
    12 => 'Mission',
    13 => 'Modern',
    14 => 'Nautical',
    15 => 'Old World',
    16 => 'Retro',
    17 => 'Rustic',
    18 => 'Shaker',
    19 => 'Southwestern',
    20 => 'Sports',
    21 => 'Tiffany',
    22 => 'Traditional',
    23 => 'Transitional',
    24 => 'Tropical',
    25 => 'Tuscan',
    26 => 'Vintage',
  ),
) ?>