<?php return array (
  'SubcategoryID' => 2175,
  'SubcategoryName' => 'HLCookingUtensilsAccessories',
  'PropertyName' => 'HLCookingType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 1,
  'PropertyValueList' => 
  array (
    0 => 'Bread Slicers',
    1 => 'Carving Gloves',
    2 => 'Cheese Slicers',
    3 => 'Cheesecloths',
    4 => 'Cookbook Holders',
    5 => 'Cooking Torches',
    6 => 'Cooking Twine & Twine Dispensers',
    7 => 'Flour Sifters',
    8 => 'Food Scoops',
    9 => 'Garlic Peelers',
    10 => 'Garlic Presses',
    11 => 'Garlic Roasters',
    12 => 'Garlic Slicers',
    13 => 'Ice Cream Scoops',
    14 => 'Ice Pop Maker',
    15 => 'Ice Trays',
    16 => 'Jello Molds',
    17 => 'Ladles',
    18 => 'Lids & Splatter Screens',
    19 => 'Pizza Cutters',
    20 => 'Pot & Pan Handles',
    21 => 'Pot Clip',
    22 => 'Pot Holders & Mitts',
    23 => 'Pressure Cooker Accessories',
    24 => 'Roasting Bags',
    25 => 'Rolling Pins',
    26 => 'Seasoning & Spice Tools',
    27 => 'Skimmers',
    28 => 'Spatulas & Turners',
    29 => 'Spoons',
    30 => 'Tongs',
    31 => 'Tortilla Presses',
    32 => 'Utensil Crocks',
    33 => 'Utensil Holders, Crocks & Racks',
    34 => 'Utensil Sets',
    35 => 'Whisks',
  ),
) ?>