<?php return array (
  'SubcategoryID' => 309,
  'SubcategoryName' => 'BareboneSystemsMiniBooksize',
  'PropertyName' => 'BBMBBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '4XEM',
    1 => 'AOpen',
    2 => 'ASRock',
    3 => 'ASUS',
    4 => 'Avatar',
    5 => 'Biostar',
    6 => 'CasEdge',
    7 => 'CybertronPC',
    8 => 'ECS',
    9 => 'Foxconn',
    10 => 'Giada',
    11 => 'GIGABYTE',
    12 => 'HIPER',
    13 => 'Intel',
    14 => 'JEHE',
    15 => 'Jetway',
    16 => 'Kangaroo',
    17 => 'MINIX',
    18 => 'MSI',
    19 => 'OCZ',
    20 => 'OEM Production',
    21 => 'PC Rides',
    22 => 'SAPPHIRE',
    23 => 'Shuttle',
    24 => 'Vigor Gaming',
    25 => 'Zotac',
  ),
) ?>