<?php return array (
  'SubcategoryID' => 309,
  'SubcategoryName' => 'BareboneSystemsMiniBooksize',
  'PropertyName' => 'BBMBCPUType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'AMD APU',
    1 => 'AMD Athlon II',
    2 => 'AMD Athlon II / Sempron',
    3 => 'AMD Athlon Neo',
    4 => 'AMD Athlon X2 / Athlon 64 FX / Athlon 64',
    5 => 'AMD C-50 APU',
    6 => 'AMD E-350 APU (1.6 GHz, dual core)',
    7 => 'AMD E-450 APU (1.65 GHz, dual core)',
    8 => 'AMD Phenom / Opteron',
    9 => 'AMD PhenomII / AthlonII',
    10 => 'Intel 2nd Generation Core i7/i5/i3 (1155)',
    11 => 'Intel Atom',
    12 => 'Intel Atom D2500 (1.86 GHz, dual core)',
    13 => 'Intel Atom D2550 (1.86 GHz, dual core)',
    14 => 'Intel Atom D2700 (2.13 GHz, dual core)',
    15 => 'Intel Atom D410 (1.66 GHz, single core)',
    16 => 'Intel Atom D425 (1.8 GHz, single core)',
    17 => 'Intel Atom D510 (1.8 GHz, dual core)',
    18 => 'Intel Atom D525 (1.8 GHz, dual core)',
    19 => 'Intel Celeron',
    20 => 'Intel Celeron M',
    21 => 'Intel Core 2 Duo / Celeron',
    22 => 'Intel Core 2 Duo / Celeron M',
    23 => 'Intel Core 2 Duo / Core 2 Duo Extreme',
    24 => 'Intel Core 2 Duo / Core Duo / Core Solo Mobile',
    25 => 'Intel Core 2 Duo / Pentium D / Pentium 4 / Celeron',
    26 => 'Intel Core 2 Duo Mobile Processor',
    27 => 'Intel Core i3 / i5 (LGA1156)',
    28 => 'Intel Core i7 / i5 / i3 Desktop Processor',
    29 => 'Intel Core i7 / i5 / i3 Mobile Processor',
    30 => 'Intel Pentium 4 / Celeron',
    31 => 'Intel Pentium M',
    32 => 'Other',
    33 => 'VIA C3',
    34 => 'VIA C7',
    35 => 'VIA Eden',
    36 => 'VIA Nano',
  ),
) ?>