<?php return array (
  'SubcategoryID' => 3238,
  'SubcategoryName' => 'Filament',
  'PropertyName' => 'FilamentBrand',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '3D Printlife',
    1 => '3D Systems',
    2 => '3Doodler',
    3 => 'BotFeeder',
    4 => 'BuMat',
    5 => 'CreoPop',
    6 => 'FlashForge',
    7 => 'Leapfrog',
    8 => 'Makerbot',
    9 => 'Mywerkz',
    10 => 'OK International',
    11 => 'Print Rite',
    12 => 'ROBO 3D',
    13 => 'Robox',
    14 => 'Rosewill',
    15 => 'Solidoodle',
    16 => 'Tiertime',
    17 => 'Verbatim',
    18 => 'XYZprinting',
    19 => 'Zeepro',
  ),
) ?>