<?php return array (
  'SubcategoryID' => 2879,
  'SubcategoryName' => 'HLDesks',
  'PropertyName' => 'HIDeskstype',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Accessory',
    1 => 'Barrister',
    2 => 'Childrens\' Desks',
    3 => 'Computer Desks',
    4 => 'Corner',
    5 => 'Desk return',
    6 => 'Ergonomical',
    7 => 'Executive',
    8 => 'L-Shaped Desks',
    9 => 'Lateral File Cabinets',
    10 => 'Mobile File Cabinets',
    11 => 'Pedestal Desks',
    12 => 'Secretary Desks',
    13 => 'Stackable',
    14 => 'Student Desks',
    15 => 'U-Shaped Desks',
    16 => 'Vertical File Cabinets',
    17 => 'Wall Mounted',
    18 => 'Writing Desks',
  ),
) ?>