<?php return array (
  'SubcategoryID' => 1530,
  'SubcategoryName' => 'ScienceNature',
  'PropertyName' => 'ScienceNatureType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Action Figures',
    1 => 'Amateur Radio',
    2 => 'Astronomy',
    3 => 'Bird Watching',
    4 => 'Books & Videos',
    5 => 'Chemistry',
    6 => 'Display Cases & Stands',
    7 => 'Geocaching',
    8 => 'Geology',
    9 => 'Kits',
    10 => 'Magnetism',
    11 => 'Medical Science',
    12 => 'Metallurgy',
    13 => 'Optics',
    14 => 'Paints & Decals',
    15 => 'Physics & Electricity',
    16 => 'Radio Controlled & Robotics',
    17 => 'Tools & Accessories',
    18 => 'Weather',
  ),
) ?>