<?php return array (
  'SubcategoryID' => 3004,
  'SubcategoryName' => 'NintendoWiiUAccessories',
  'PropertyName' => 'WIIUAccType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Adapter',
    1 => 'Battery',
    2 => 'Battery Pack',
    3 => 'Cable',
    4 => 'Case',
    5 => 'Charger',
    6 => 'Controller',
    7 => 'Figure',
    8 => 'Game Cases',
    9 => 'Grip',
    10 => 'Headset',
    11 => 'Memory Card',
    12 => 'Microphone',
    13 => 'Other',
    14 => 'Power Adaptor',
    15 => 'Protector',
    16 => 'Screen Filter',
    17 => 'Stand',
    18 => 'Starter Kit',
    19 => 'Stylus',
  ),
) ?>