<?php return array (
  'SubcategoryID' => 42,
  'SubcategoryName' => 'Projectors',
  'PropertyName' => 'GroupProjectorOption',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '1080p',
    1 => '1080p Rec.709 Lens Shift',
    2 => '1080p Short Throw',
    3 => '3200 Lumens',
    4 => '3500 Lumens',
    5 => '4000 Lumens and 10W Speaker',
    6 => '4000 Lumens and 16W Speaker',
    7 => 'Black',
    8 => 'SVGA',
    9 => 'SVGA Black',
    10 => 'SVGA White',
    11 => 'SVGA with HDMI',
    12 => 'White',
    13 => 'WXGA 3500 Lumens',
    14 => 'WXGA Short Throw',
    15 => 'WXGA with HDMI',
    16 => 'WXGA with Short Throw + HDMI',
    17 => 'XGA 3300 Lumens',
    18 => 'XGA 3500 Lumens',
    19 => 'XGA Black',
    20 => 'XGA Short Throw',
    21 => 'XGA White',
    22 => 'XGA with HDMI',
    23 => 'XGA with Short Throw + HDMI',
  ),
) ?>