<?php return array (
  'SubcategoryID' => 42,
  'SubcategoryName' => 'Projectors',
  'PropertyName' => 'MonitorConnectivityInputVideoConnectors',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Composite',
    1 => 'D-Sub',
    2 => 'D-Sub, Composite',
    3 => 'D-Sub, Composite, Component',
    4 => 'D-Sub, DVI',
    5 => 'D-Sub, DVI, Composite',
    6 => 'D-Sub, DVI, HDMI, Composite, Component, S-Video',
    7 => 'D-Sub, DVI, HDMI, Composite, S-Video',
    8 => 'D-Sub, DVI, S-Video',
    9 => 'D-Sub, DVI, S-Video, Composite, Component, RCA',
    10 => 'D-Sub, DVI, S-Video, Composite, RCA',
    11 => 'D-Sub, HDMI',
    12 => 'D-Sub, HDMI, Component, S-Video',
    13 => 'D-Sub, HDMI, Composite',
    14 => 'D-Sub, HDMI, Composite, Component',
    15 => 'D-Sub, HDMI, Composite, Component, S-Video',
    16 => 'D-Sub, HDMI, Composite, S-Video',
    17 => 'D-Sub, HDMI, S-Video, RCA',
    18 => 'D-Sub, S-Video, Composite',
    19 => 'D-Sub, S-Video, Composite, Component',
    20 => 'D-Sub, S-Video, Composite, RCA',
    21 => 'D-Sub, S-Video, RCA',
    22 => 'HDMI',
  ),
) ?>