<?php return array (
  'SubcategoryID' => 655,
  'SubcategoryName' => 'RotisserieOvens',
  'PropertyName' => 'RotisserieOvensBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Avanti',
    1 => 'Black & Decker',
    2 => 'Coleman',
    3 => 'Cuisinart',
    4 => 'DeLonghi',
    5 => 'Deni',
    6 => 'Doral Designs',
    7 => 'Fujitronic',
    8 => 'George Foreman',
    9 => 'Haier',
    10 => 'LIFETIME BRANDS',
    11 => 'MEYER',
    12 => 'MorningWare',
    13 => 'NARITA',
    14 => 'NutriChef',
    15 => 'NuWave',
    16 => 'RIVAL',
    17 => 'Ronco',
    18 => 'Sunpentown',
    19 => 'Tayama',
    20 => 'ZOJIRUSHI',
  ),
) ?>