<?php return array (
  'SubcategoryID' => 3100,
  'SubcategoryName' => 'MTSeats',
  'PropertyName' => 'MTVehicleType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 1,
  'PropertyValueList' => 
  array (
    0 => 'Any except automotive',
    1 => 'ATV',
    2 => 'Automotive',
    3 => 'Cruiser/V-Twin',
    4 => 'Dirt Bike  ',
    5 => 'Go-Kart',
    6 => 'Golf Cart',
    7 => 'Mini Bike/Pit Bike',
    8 => 'Personal Watercraft',
    9 => 'Scooter',
    10 => 'Side x Side',
    11 => 'Snowmobile',
    12 => 'Sportbike',
    13 => 'Street Bike/Sport Bike',
    14 => 'Universal Cruiser',
    15 => 'UTV',
  ),
) ?>