<?php return array (
  'SubcategoryID' => 359,
  'SubcategoryName' => 'Flashlights',
  'PropertyName' => 'FLColor',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Aluminum',
    1 => 'Aqua',
    2 => 'Army Green',
    3 => 'Black',
    4 => 'Blue',
    5 => 'Bronze',
    6 => 'Camouflage',
    7 => 'Dark Green',
    8 => 'Green',
    9 => 'Grey',
    10 => 'Gun Metal Grey',
    11 => 'Multi',
    12 => 'Neon Green',
    13 => 'Orange',
    14 => 'Pewter',
    15 => 'Pink',
    16 => 'Purple',
    17 => 'Red',
    18 => 'Silver',
    19 => 'White',
    20 => 'Yellow',
  ),
) ?>