<?php return array (
  'SubcategoryID' => 359,
  'SubcategoryName' => 'Flashlights',
  'PropertyName' => 'FLType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '6 VOLT',
    1 => 'Barbecue Light',
    2 => 'Book Light',
    3 => 'Bulb',
    4 => 'Cap Light',
    5 => 'Clip',
    6 => 'Combination Kits',
    7 => 'D CELL',
    8 => 'Emergency Light',
    9 => 'Flameless Candle',
    10 => 'Flashlight',
    11 => 'Hand Held',
    12 => 'Head Lamp',
    13 => 'Head Torch',
    14 => 'Headlight',
    15 => 'Keychain Light',
    16 => 'Lantern',
    17 => 'LED',
    18 => 'Pen Light',
    19 => 'Reading Light',
    20 => 'Solar Powered',
    21 => 'Spotlight',
    22 => 'TRAFFIC',
    23 => 'Tripod',
    24 => 'UPGRADE',
    25 => 'UTILITY',
    26 => 'Work Light',
  ),
) ?>