<?php return array (
  'SubcategoryID' => 3102,
  'SubcategoryName' => 'MTFuelSystemAirIntake',
  'PropertyName' => 'MTFuelType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Air Cut-Off Valves',
    1 => 'Air Filters',
    2 => 'Air Injection Kits',
    3 => 'Boost Bottles',
    4 => 'Carburetor Covers',
    5 => 'Carburetors',
    6 => 'Check Valves',
    7 => 'Choke Controls',
    8 => 'Cold Air Kits',
    9 => 'Crankcase Breathers',
    10 => 'Dust Covers',
    11 => 'ECU Software',
    12 => 'Enrichers',
    13 => 'Flame Arresters',
    14 => 'Flange Adapters',
    15 => 'Fuel Filters',
    16 => 'Fuel Injection',
    17 => 'Fuel Injection Mapping',
    18 => 'Fuel Lines',
    19 => 'Fuel Pumps',
    20 => 'Fuel Valves',
    21 => 'Hose Fittings',
    22 => 'Hoses & Clamps',
    23 => 'Hyperchargers',
    24 => 'Intake Manifolds',
    25 => 'Intakes & Reeds',
    26 => 'Jet Kits',
    27 => 'Jet Needles',
    28 => 'Jets',
    29 => 'Manifold Accessories',
    30 => 'Nitrous Oxide Systems',
    31 => 'Petcocks',
  ),
) ?>