<?php return array (
  'SubcategoryID' => 2596,
  'SubcategoryName' => 'SGAirsoftTacticalGearSafetyAccessories',
  'PropertyName' => 'SGTactGearColor',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'A-TACS-AU',
    1 => 'As Shown',
    2 => 'Beige',
    3 => 'Black',
    4 => 'Blue',
    5 => 'Brown',
    6 => 'Burgundy',
    7 => 'Clear',
    8 => 'Coral',
    9 => 'Coyote',
    10 => 'Coyote Tan',
    11 => 'Dark Blue',
    12 => 'Dark Green',
    13 => 'Gold',
    14 => 'Green',
    15 => 'Grey',
    16 => 'Ivory',
    17 => 'Khaki',
    18 => 'Light Blue',
    19 => 'Light Green',
    20 => 'Metallic',
    21 => 'Multi-Color',
    22 => 'MULTICAM',
    23 => 'Navy',
    24 => 'Orange',
    25 => 'Pink',
    26 => 'Platinum',
    27 => 'Purple',
    28 => 'Red',
    29 => 'Silver',
    30 => 'Teal',
    31 => 'White',
    32 => 'Yellow',
  ),
) ?>