<?php return array (
  'SubcategoryID' => 643,
  'SubcategoryName' => 'GameGuides',
  'PropertyName' => 'SWDRM',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Battle.NET',
    1 => 'ByteShield',
    2 => 'Desura',
    3 => 'Digital e-Guide',
    4 => 'EA Core',
    5 => 'EA Origin',
    6 => 'Game Download',
    7 => 'Origin',
    8 => 'PlayStation',
    9 => 'PlayStation 3',
    10 => 'PlayStation 4',
    11 => 'PlayStation Network',
    12 => 'Rockstar Games Social Club',
    13 => 'SecuROM',
    14 => 'SolidShield',
    15 => 'StarForce',
    16 => 'Steam',
    17 => 'Uniloc',
    18 => 'Uplay',
    19 => 'XBOX 360',
    20 => 'XBOX Live',
    21 => 'XBOX One',
  ),
) ?>