<?php return array (
  'SubcategoryID' => 1651,
  'SubcategoryName' => 'BaseballSoftballGlovesMitts',
  'PropertyName' => 'BBSBGlovesColor',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Beige',
    1 => 'Black',
    2 => 'Blue',
    3 => 'Brown',
    4 => 'Brown/Tan',
    5 => 'Burgundy',
    6 => 'Clear',
    7 => 'Coral',
    8 => 'Dark Blue',
    9 => 'Dark Green',
    10 => 'Gold',
    11 => 'Green',
    12 => 'Grey',
    13 => 'Grey/Royal',
    14 => 'Ivory',
    15 => 'Khaki',
    16 => 'Left Handed Throw',
    17 => 'Light Blue',
    18 => 'Light Green',
    19 => 'Metallic',
    20 => 'Multi',
    21 => 'Multi-Color',
    22 => 'Navy',
    23 => 'Orange',
    24 => 'Pink',
    25 => 'Platinum',
    26 => 'Purple',
    27 => 'Red',
    28 => 'Right Handed Throw',
    29 => 'Silver',
    30 => 'Tan/Black',
    31 => 'Teal',
    32 => 'White',
    33 => 'Yellow',
  ),
) ?>