<?php return array (
  'SubcategoryID' => 3008,
  'SubcategoryName' => 'CompactMirrorlessSystemCamera',
  'PropertyName' => 'DSLRBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Canon',
    1 => 'Cobra Digital',
    2 => 'FUJIFILM',
    3 => 'General Imaging',
    4 => 'Intova',
    5 => 'Kodak',
    6 => 'KONICA MINOLTA',
    7 => 'Nikon',
    8 => 'OLYMPUS',
    9 => 'Panasonic',
    10 => 'PENTAX',
    11 => 'Polaroid',
    12 => 'Sakar',
    13 => 'SAMSUNG',
    14 => 'SIGMA',
    15 => 'SONY',
    16 => 'Vivitar',
  ),
) ?>