<?php return array (
  'SubcategoryID' => 2086,
  'SubcategoryName' => 'HIToiletPaperHolders',
  'PropertyName' => 'HIToiletPaperHoldersBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'American Standard',
    1 => 'Baldwin',
    2 => 'Bobrick',
    3 => 'Croydex',
    4 => 'DELTA',
    5 => 'Fusion',
    6 => 'Gatco',
    7 => 'Grohe',
    8 => 'Hansgrohe',
    9 => 'Jado',
    10 => 'KOHLER',
    11 => 'La Toscana',
    12 => 'Liberty Hardware',
    13 => 'MOEN',
    14 => 'Onyx',
    15 => 'Pegasus',
    16 => 'Pfister',
    17 => 'Trademark',
    18 => 'Zenith',
  ),
) ?>