<?php return array (
  'SubcategoryID' => 2086,
  'SubcategoryName' => 'HIToiletPaperHolders',
  'PropertyName' => 'HIToiletPaperHoldersFinish',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Aged Pewter',
    1 => 'Antique Nickel',
    2 => 'Black',
    3 => 'Brushed Bronze',
    4 => 'Brushed Chrome',
    5 => 'Brushed Nickel',
    6 => 'Brushed Nickel/Brass',
    7 => 'Brushed Nickel/Chrome',
    8 => 'Chrome',
    9 => 'Chrome/Brass',
    10 => 'Chrome/Polished Brass',
    11 => 'French Gold',
    12 => 'Hammered Nickel',
    13 => 'Heritage Bronze',
    14 => 'Oil Rubbed Bronze',
    15 => 'Polished Brass',
    16 => 'Polished Chrome',
    17 => 'Polished Nickel',
    18 => 'Polyester',
    19 => 'Rustic Bronze',
    20 => 'Satin Nickel',
    21 => 'Satin/Chrome',
    22 => 'Stainless Steel',
    23 => 'StarLight Chrome',
    24 => 'Tuscan Bronze',
    25 => 'Venetian Bronze',
    26 => 'White',
    27 => 'Wrought Iron',
  ),
) ?>