<?php return array (
  'SubcategoryID' => 2101,
  'SubcategoryName' => 'HLDecorativeShelving',
  'PropertyName' => 'HIDecorativeShelvingmaterial',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'ABS',
    1 => 'Bonded Leather',
    2 => 'Bycast Leather',
    3 => 'Fabric',
    4 => 'Faux Leather',
    5 => 'Glass',
    6 => 'Laminate',
    7 => 'Leather',
    8 => 'Mesh',
    9 => 'Metal',
    10 => 'Metal and Glass',
    11 => 'Microfiber',
    12 => 'Plastic',
    13 => 'Reclaimed Wood',
    14 => 'Vinyl',
    15 => 'Wood',
    16 => 'Wood and Glass',
    17 => 'Wood and Metal',
  ),
) ?>