<?php return array (
  'SubcategoryID' => 3089,
  'SubcategoryName' => 'MTControls',
  'PropertyName' => 'MTControlType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Brake Levers',
    1 => 'Brake Pedal Accessories',
    2 => 'Brake Pedal Mount Plates',
    3 => 'Brake Pedals',
    4 => 'Clutch Levers',
    5 => 'Foot Pedals',
    6 => 'Forward Control Accessories',
    7 => 'Forward Controls',
    8 => 'Hot Start Levers',
    9 => 'Kick Starters',
    10 => 'Lever Sets',
    11 => 'Pedal Accessories',
    12 => 'Perches',
    13 => 'Recoil Handles',
    14 => 'Reverse Controls',
    15 => 'Shift Levers',
    16 => 'Shift Pegs',
    17 => 'Shifters',
    18 => 'Steering Bearings',
    19 => 'Steering Dampeners',
    20 => 'Steering Systems',
    21 => 'Tether Switches',
    22 => 'Throttles',
  ),
) ?>