<?php return array (
  'SubcategoryID' => 2575,
  'SubcategoryName' => 'SGFishingToolsAccessories',
  'PropertyName' => 'SGFishToolsSizeDimensions',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '1.8M',
    1 => '2.1M',
    2 => '2.7M',
    3 => '2XL',
    4 => '3.0M',
    5 => '3.3M',
    6 => '3.6M',
    7 => '8',
    8 => '9',
    9 => 'L',
    10 => 'M',
    11 => 'ML',
    12 => 'S',
    13 => 'UL',
    14 => 'XL',
  ),
) ?>