<?php return array (
  'SubcategoryID' => 2167,
  'SubcategoryName' => 'HLBakewarePansSheets',
  'PropertyName' => 'HLBakewareType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 1,
  'PropertyValueList' => 
  array (
    0 => 'Au Gratin Dishes',
    1 => 'Bakeware Sets',
    2 => 'Baking Liners',
    3 => 'Baking Molds',
    4 => 'Baking Sheets',
    5 => 'Bread & Loaf Pans',
    6 => 'Brotforms',
    7 => 'Brownie Pans',
    8 => 'Cake Pans',
    9 => 'Cupcake Pans',
    10 => 'Kids\' Baking Supplies',
    11 => 'Mixed Sets',
    12 => 'Muffin & Popover Pans',
    13 => 'Novelty Pans',
    14 => 'Paper Baking Cups',
    15 => 'Pie Dishes & Tart Pans',
    16 => 'Ramekins & Souffle Dishes',
    17 => 'Specialty Bakeware',
    18 => 'Springform & Cheesecake Pans',
  ),
) ?>