<?php return array (
  'SubcategoryID' => 2167,
  'SubcategoryName' => 'HLBakewarePansSheets',
  'PropertyName' => 'HLKitchenStyle',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Art Deco',
    1 => 'Arts-n-Crafts',
    2 => 'Asian',
    3 => 'Casual',
    4 => 'Classic',
    5 => 'Coastal',
    6 => 'Contemporary',
    7 => 'Cottage',
    8 => 'Country',
    9 => 'Country French',
    10 => 'Formal',
    11 => 'Industrial',
    12 => 'Kids / Juvenile',
    13 => 'Lodge',
    14 => 'Mid Century',
    15 => 'Mission',
    16 => 'Modern',
    17 => 'Moroccan',
    18 => 'Nautical',
    19 => 'Novelty',
    20 => 'Old World',
    21 => 'Professional/Gourmet',
    22 => 'Retro',
    23 => 'Rustic',
    24 => 'Shaker',
    25 => 'Southwestern',
    26 => 'Spanish Colonial',
    27 => 'Specialty',
    28 => 'Sports',
    29 => 'Tiffany',
    30 => 'Traditional',
    31 => 'Transitional',
    32 => 'Tropical',
    33 => 'Tuscan',
    34 => 'Vintage',
  ),
) ?>