<?php return array (
  'SubcategoryID' => 395,
  'SubcategoryName' => 'CameraCablesRemotes',
  'PropertyName' => 'DCCablesBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Accessory Power',
    1 => 'Aiptek',
    2 => 'Atlona',
    3 => 'Bower',
    4 => 'Cables Unlimited',
    5 => 'Canon',
    6 => 'CASIO',
    7 => 'Cisco',
    8 => 'CREATIVE',
    9 => 'Flip video',
    10 => 'FUJIFILM',
    11 => 'KODAK',
    12 => 'MyMyk',
    13 => 'Nikon',
    14 => 'NXG Technology',
    15 => 'OLYMPUS',
    16 => 'Panasonic',
    17 => 'PENTAX',
    18 => 'PocketWizard',
    19 => 'POLYCOM',
    20 => 'Samsung',
    21 => 'Scosche',
    22 => 'SIGMA',
    23 => 'SONY',
    24 => 'Steren',
    25 => 'SWITRONIX, INC',
    26 => 'Tamrac',
    27 => 'Targus',
    28 => 'Ubiquiti Networks',
    29 => 'ZEIKOS',
  ),
) ?>