<?php return array (
  'SubcategoryID' => 3085,
  'SubcategoryName' => 'iPadAccessoriesOEM',
  'PropertyName' => 'iPadAccCompatibility',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'For Apple',
    1 => 'iPad 1',
    2 => 'iPad 2',
    3 => 'iPad 2, iPad 3, iPad 4',
    4 => 'iPad 2, iPad 3, iPad 4th Gen',
    5 => 'iPad 2, iPad 3, iPad 4th gen.',
    6 => 'iPad 2/3/4',
    7 => 'iPad 3',
    8 => 'iPad 4',
    9 => 'iPad 4/Air/mini/mini 2',
    10 => 'iPad Air',
    11 => 'iPad Air 2',
    12 => 'iPad Air 2, iPad Pro 9.7-inch',
    13 => 'iPad Air, iPad Air 2',
    14 => 'iPad Air, iPad Air 2, iPad Pro 9.7-inch',
    15 => 'iPad Air, iPad mini 2, iPad 4th gen., iPad mini',
    16 => 'iPad Air/Mini',
    17 => 'iPad Mini',
    18 => 'iPad Mini 1/2',
    19 => 'iPad Mini 2',
    20 => 'iPad Mini 3',
    21 => 'iPad Mini 4',
    22 => 'iPad mini with Retina Display',
    23 => 'iPad mini with Retina display, iPad mini',
    24 => 'iPad mini, iPad mini 2, iPad mini 3',
    25 => 'iPad Mini, iPad Mini 2, iPad Mini 3, iPad Mini 4',
    26 => 'iPad mini, iPad mini with Retina display',
    27 => 'iPad mini/iPad mini with Retina display',
    28 => 'iPad Pro',
    29 => 'iPad Pro 9.7-inch',
    30 => 'iPad, iPad 2, iPad 3',
    31 => 'iPad, iPad 2, iPad 3, iPad 4th gen.',
    32 => 'IPad, iPhone',
    33 => 'Universal',
  ),
) ?>