<?php return array (
  'SubcategoryID' => 1702,
  'SubcategoryName' => 'SportsProtectiveGear',
  'PropertyName' => 'ProtectiveGearSize',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '28',
    1 => '30',
    2 => '32',
    3 => '34',
    4 => '36',
    5 => '38',
    6 => '40',
    7 => '42',
    8 => '44',
    9 => '46',
    10 => 'Adult',
    11 => 'Adult Convertible',
    12 => 'Large',
    13 => 'Medium',
    14 => 'One Size',
    15 => 'Pee Wee',
    16 => 'Regular',
    17 => 'Small',
    18 => 'X-Large',
    19 => 'X-Small',
    20 => 'XX-Large',
    21 => 'XX-Small',
    22 => 'XXX-Large',
    23 => 'Youth',
    24 => 'Youth Convertible',
    25 => 'Youth Large',
    26 => 'Youth Regular',
  ),
) ?>