<?php return array (
  'SubcategoryID' => 1642,
  'SubcategoryName' => 'BasketballAccessories',
  'PropertyName' => 'BasketballAccessoriesSize',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '22 Inch',
    1 => 'Large',
    2 => 'Medium',
    3 => 'One Size',
    4 => 'Regular',
    5 => 'Small',
    6 => 'X-Large',
    7 => 'X-Small',
    8 => 'XX-Large',
    9 => 'XX-Small',
    10 => 'XXX-Large',
    11 => 'Youth Large',
    12 => 'Youth Medium',
    13 => 'Youth Regular',
    14 => 'Youth Small',
    15 => 'Youth X-Large',
    16 => 'Youth X-Small',
    17 => 'Youth XX-Large',
    18 => 'Youth XX-Small',
    19 => 'Youth XXX-Large',
  ),
) ?>