<?php return array (
  'SubcategoryID' => 634,
  'SubcategoryName' => 'ScannersDocument',
  'PropertyName' => 'DocumentScannerBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Addmaster',
    1 => 'Adesso',
    2 => 'Ambir',
    3 => 'Brother',
    4 => 'Canon',
    5 => 'CardScan',
    6 => 'Contex',
    7 => 'CSSN',
    8 => 'DocketPORT',
    9 => 'EPSON',
    10 => 'Fujitsu',
    11 => 'Genius',
    12 => 'HP',
    13 => 'I.R.I.S',
    14 => 'INUVIO',
    15 => 'ION',
    16 => 'iVina',
    17 => 'Kodak',
    18 => 'Microtek',
    19 => 'Mustek',
    20 => 'Neat',
    21 => 'Panasonic',
    22 => 'Pandigital',
    23 => 'PenPower',
    24 => 'Pentax',
    25 => 'Plustek',
    26 => 'Ricoh',
    27 => 'SimpleScan',
    28 => 'Visioneer',
    29 => 'VuPoint Solutions',
    30 => 'XEROX',
  ),
) ?>