<?php return array (
  'SubcategoryID' => 634,
  'SubcategoryName' => 'ScannersDocument',
  'PropertyName' => 'DocumentScannerSeries',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'ArtixScan',
    1 => 'CanoScan',
    2 => 'Designjet',
    3 => 'DocketPort',
    4 => 'DocuMate',
    5 => 'DR Series',
    6 => 'Dsmobile',
    7 => 'fi Series',
    8 => 'GT Series',
    9 => 'ImageCenter',
    10 => 'imageFORMULA',
    11 => 'ImageScan',
    12 => 'IRISCan',
    13 => 'IRISCard',
    14 => 'Ngenuity',
    15 => 'Patriot',
    16 => 'Perfection',
    17 => 'Scan Station',
    18 => 'ScanFront',
    19 => 'Scanjet',
    20 => 'ScanMaker',
    21 => 'ScanMate',
    22 => 'ScanShell',
    23 => 'ScanSnap',
    24 => 'Sidekick',
    25 => 'SmartOffice',
    26 => 'Strobe XP',
    27 => 'TravelScan Pro',
    28 => 'Truper',
    29 => 'WorkForce',
  ),
) ?>