<?php return array (
  'SubcategoryID' => 1635,
  'SubcategoryName' => 'PetHousingCratesTravelOutdoors',
  'PropertyName' => 'PetHousingColor',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Beige',
    1 => 'Black',
    2 => 'Black/Orange',
    3 => 'Black/Purple',
    4 => 'Blue',
    5 => 'Brown',
    6 => 'Burgundy',
    7 => 'Clear',
    8 => 'Coral',
    9 => 'Cream',
    10 => 'Dark Blue',
    11 => 'Dark Green',
    12 => 'Gold',
    13 => 'Green',
    14 => 'Grey',
    15 => 'Hot Pink',
    16 => 'Ivory',
    17 => 'Khaki',
    18 => 'Light Blue',
    19 => 'Light Green',
    20 => 'Metallic',
    21 => 'Multi-Color',
    22 => 'Orange',
    23 => 'Pink',
    24 => 'Platinum',
    25 => 'Purple',
    26 => 'Red',
    27 => 'Red Plaid',
    28 => 'Silver',
    29 => 'Teal',
    30 => 'White',
    31 => 'Yellow',
  ),
) ?>