<?php return array (
  'SubcategoryID' => 3058,
  'SubcategoryName' => 'ToysRCBatteriesChargers',
  'PropertyName' => 'RCBatteriesType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 1,
  'PropertyValueList' => 
  array (
    0 => 'Balance Lead Converters',
    1 => 'Balance Lead Extensions',
    2 => 'Battery Balancers',
    3 => 'Battery Chargers',
    4 => 'Battery Monitors & Testers',
    5 => 'Battery Protectors',
    6 => 'Battery Voltage Regulators',
    7 => 'Bullet Connectors',
    8 => 'Charge Cords',
    9 => 'Charger Accessories',
    10 => 'Connectors',
    11 => 'Deans / T-plug Connectors',
    12 => 'LiPo Safe Charge Bags',
    13 => 'Power Packs',
    14 => 'Power Supply / AC Adapters',
    15 => 'Receiver Batteries',
    16 => 'Switches',
    17 => 'Transmitter Batteries',
  ),
) ?>