<?php return array (
  'SubcategoryID' => 692,
  'SubcategoryName' => 'SurveillanceWireless',
  'PropertyName' => 'CCTVBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '4XEM',
    1 => 'ABS',
    2 => 'Aposonic',
    3 => 'Asante',
    4 => 'Astak',
    5 => 'Axis',
    6 => 'Cisco Small Business',
    7 => 'Clover',
    8 => 'CNet',
    9 => 'CP TECHNOLOGIES',
    10 => 'D-Link',
    11 => 'EDIMAX',
    12 => 'Encore',
    13 => 'Ezonics',
    14 => 'First Alert',
    15 => 'GE',
    16 => 'Graco',
    17 => 'Hawking',
    18 => 'LevelOne',
    19 => 'LINKSYS',
    20 => 'Lorex',
    21 => 'LTS',
    22 => 'Macally',
    23 => 'MOBI',
    24 => 'Panasonic',
    25 => 'PLANET',
    26 => 'Q-See',
    27 => 'SecurityMan',
    28 => 'SMC',
    29 => 'Sony',
    30 => 'SVAT',
    31 => 'Swann',
    32 => 'Toshiba',
    33 => 'TRENDnet',
    34 => 'Zonet',
  ),
) ?>