<?php return array (
  'SubcategoryID' => 2896,
  'SubcategoryName' => 'MIAcousticElectricGuitars',
  'PropertyName' => 'GuitarsBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Arcadia',
    1 => 'Behringer',
    2 => 'Bryant',
    3 => 'Casio',
    4 => 'eMedia',
    5 => 'Epiphone',
    6 => 'Fretlight',
    7 => 'Korg',
    8 => 'Nady',
    9 => 'Peavey',
    10 => 'Pyle',
    11 => 'PylePro',
    12 => 'Samson',
    13 => 'Silvertone',
    14 => 'Spectrum',
    15 => 'Stagg',
    16 => 'Vox',
    17 => 'Zoom',
  ),
) ?>