<?php return array (
  'SubcategoryID' => 664,
  'SubcategoryName' => 'ToasterOvens',
  'PropertyName' => 'ToasterOvenColor',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Black',
    1 => 'Charcoal',
    2 => 'Cherry Blossom Pink',
    3 => 'Chrome',
    4 => 'Copper',
    5 => 'Coral Red',
    6 => 'Forget Me Not Blue',
    7 => 'Lilac Mauve',
    8 => 'Lime Green',
    9 => 'Mint Green',
    10 => 'Orange',
    11 => 'Peach Orange',
    12 => 'Pink',
    13 => 'Purple',
    14 => 'Red',
    15 => 'Rose',
    16 => 'Silver',
    17 => 'Snowdrop White',
    18 => 'Stainless Steel',
    19 => 'Sunflower Yellow',
    20 => 'Turquoise',
    21 => 'Violet',
    22 => 'White',
    23 => 'Yellow',
  ),
) ?>