<?php return array (
  'SubcategoryID' => 2683,
  'SubcategoryName' => 'ATAutomotivePaintsCoatings',
  'PropertyName' => 'AutoPaintType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '2K Aero-Spray Paints',
    1 => 'Airbrushing',
    2 => 'Basecoats',
    3 => 'Bedliner Coatings',
    4 => 'Candy Paints',
    5 => 'Clear Coats',
    6 => 'ElastiWrap',
    7 => 'Hi Temp & Engine Paints',
    8 => 'Interior Paints',
    9 => 'Paint Guns & Equipment',
    10 => 'Paint Strippers & Cleaners',
    11 => 'Pinstriping',
    12 => 'Plating & Chrome',
    13 => 'Powder Coating',
    14 => 'Primers',
    15 => 'Rat Pod Paints',
    16 => 'Reducers & Activators',
    17 => 'Rubber Coatings',
    18 => 'Rust Solutions',
    19 => 'Shop Floor Coatings',
    20 => 'Single Stage Urethane',
    21 => 'Trunk Spatter Paints',
    22 => 'Under Car Coatings',
    23 => 'Underhood Paints',
    24 => 'Water Based Paints',
    25 => 'Wheel Paints',
  ),
) ?>