<?php return array (
  'SubcategoryID' => 3265,
  'SubcategoryName' => 'HLMirrors',
  'PropertyName' => 'HLMirrorFrameColorMapping',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Beige',
    1 => 'Black',
    2 => 'Blue',
    3 => 'Brown',
    4 => 'Clear',
    5 => 'Dark Blue',
    6 => 'Dark Green',
    7 => 'Gold',
    8 => 'Gray',
    9 => 'Green',
    10 => 'Khaki',
    11 => 'Light Blue',
    12 => 'Light Green',
    13 => 'Metallic',
    14 => 'Multi-Color',
    15 => 'Navy',
    16 => 'Olive',
    17 => 'Orange',
    18 => 'Pink',
    19 => 'Purple',
    20 => 'Red',
    21 => 'Silver',
    22 => 'Turquoise',
    23 => 'White',
    24 => 'Yellow',
  ),
) ?>