<?php return array (
  'SubcategoryID' => 2171,
  'SubcategoryName' => 'HLTableLinens',
  'PropertyName' => 'HLTableType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 1,
  'PropertyValueList' => 
  array (
    0 => 'Aprons',
    1 => 'Cloth Napkins',
    2 => 'Cocktail Napkins',
    3 => 'Dining Chair Covers',
    4 => 'Dining Chair Pads',
    5 => 'Dish Towels & Cloths',
    6 => 'Mixed Sets',
    7 => 'Napkin Rings',
    8 => 'Placemats and Runners',
    9 => 'Table Liners',
    10 => 'Table Skirts',
    11 => 'Table Toppers',
    12 => 'Tablecloths',
    13 => 'Trivets & Coasters',
  ),
) ?>