<?php return array (
  'SubcategoryID' => 2171,
  'SubcategoryName' => 'HLTableLinens',
  'PropertyName' => 'HLTableMaterial',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '100% Cotton',
    1 => 'Acrylic',
    2 => 'Bamboo',
    3 => 'Blend',
    4 => 'Cotton',
    5 => 'Damask',
    6 => 'Felt',
    7 => 'Lace',
    8 => 'Linen',
    9 => 'Plastic',
    10 => 'Polyester',
    11 => 'Satin',
    12 => 'Silk',
    13 => 'Sunbrella',
    14 => 'Vinyl',
  ),
) ?>