<?php return array (
  'SubcategoryID' => 700,
  'SubcategoryName' => 'ProjectorLamps',
  'PropertyName' => 'ProjectorLampBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Acer',
    1 => 'Advanced',
    2 => 'BenQ',
    3 => 'BTI',
    4 => 'CHIEF MANUFACTURING',
    5 => 'Dell',
    6 => 'Diamond',
    7 => 'EPSON',
    8 => 'eReplacements',
    9 => 'GO Lamps',
    10 => 'HITACHI',
    11 => 'InFocus',
    12 => 'Leaf Imaging Supplies',
    13 => 'Marvel',
    14 => 'Mitsubishi',
    15 => 'NEC',
    16 => 'OPTOMA',
    17 => 'OSR',
    18 => 'Panasonic',
    19 => 'Peerless',
    20 => 'Premium Power',
    21 => 'Projectiondesign',
    22 => 'Sanyo',
    23 => 'Sharp',
    24 => 'Sony',
    25 => 'Total Micro Technologies',
    26 => 'V7',
    27 => 'ViewSonic',
    28 => 'Vivitek',
  ),
) ?>