<?php return array (
  'SubcategoryID' => 3316,
  'SubcategoryName' => 'StudioSupplies',
  'PropertyName' => 'CraftColorFamily',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Barn Red',
    1 => 'Beige',
    2 => 'Black',
    3 => 'Blue',
    4 => 'Brown',
    5 => 'Clear',
    6 => 'Coral',
    7 => 'Gold',
    8 => 'Green',
    9 => 'Grey',
    10 => 'Hunter Green',
    11 => 'Khaki',
    12 => 'Light Blue',
    13 => 'Metallic',
    14 => 'Multi-Color',
    15 => 'Natural Gray',
    16 => 'Orange',
    17 => 'Oyster',
    18 => 'Pink',
    19 => 'Purple',
    20 => 'Red',
    21 => 'Turquoise',
    22 => 'White',
    23 => 'Yellow',
  ),
) ?>