<?php return array (
  'SubcategoryID' => 1024,
  'SubcategoryName' => 'WatchAccessories',
  'PropertyName' => 'WatchaccMaterial',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '18K Gold Plated',
    1 => '925 Silver with Rhodium Plated',
    2 => 'Aluminum',
    3 => 'Brass',
    4 => 'Copper',
    5 => 'Copper Alloy',
    6 => 'Glass',
    7 => 'Gold',
    8 => 'Gold Plated',
    9 => 'Leather',
    10 => 'Plastic',
    11 => 'Platinum',
    12 => 'Polymer',
    13 => 'Rhodium Plated',
    14 => 'Rose Gold',
    15 => 'Rubber',
    16 => 'Silver',
    17 => 'Silver Plated',
    18 => 'Stainless Steel',
    19 => 'Steel',
    20 => 'Sterling Silver',
    21 => 'Titanium',
    22 => 'Tungsten',
    23 => 'White Gold',
    24 => 'Wood',
  ),
) ?>