<?php return array (
  'SubcategoryID' => 3096,
  'SubcategoryName' => 'MTBumpers',
  'PropertyName' => 'MTPosition',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'External',
    1 => 'Forward',
    2 => 'Front',
    3 => 'Front & Rear',
    4 => 'Front Left',
    5 => 'Front Right',
    6 => 'Internal',
    7 => 'Left',
    8 => 'Left & Right',
    9 => 'Mid-Body',
    10 => 'Rear Left',
    11 => 'Rear Right',
    12 => 'Right',
    13 => 'Universal',
    14 => 'Upper Front',
  ),
) ?>