<?php return array (
  'SubcategoryID' => 2865,
  'SubcategoryName' => 'HIHolidayStringLights',
  'PropertyName' => 'HIHolidayStringlightslightcolor',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Amber',
    1 => 'Aqua',
    2 => 'Blue',
    3 => 'Clear',
    4 => 'Cool White',
    5 => 'Crystal Clear',
    6 => 'Gold',
    7 => 'Green',
    8 => 'Multi-Color',
    9 => 'Multicolor',
    10 => 'Orange',
    11 => 'Pink',
    12 => 'Pure White',
    13 => 'Purple',
    14 => 'Red',
    15 => 'Warm White',
    16 => 'White',
    17 => 'Yellow',
  ),
) ?>