<?php return array (
  'SubcategoryID' => 2865,
  'SubcategoryName' => 'HIHolidayStringLights',
  'PropertyName' => 'HIHolidayStringlightscolor',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Amber',
    1 => 'As Shown',
    2 => 'Black',
    3 => 'Blue',
    4 => 'Brown',
    5 => 'Ceramic Multi-Color',
    6 => 'Clear',
    7 => 'Cool White',
    8 => 'Frosted',
    9 => 'Frosted White',
    10 => 'Gold',
    11 => 'Gold / Amber',
    12 => 'Gold Glitter',
    13 => 'Green',
    14 => 'Holiday White',
    15 => 'Multi-Color',
    16 => 'Multi-Color Tinsel / Clear Globe',
    17 => 'N/A',
    18 => 'Orange',
    19 => 'Pearl White',
    20 => 'Pink',
    21 => 'Polar White',
    22 => 'Pure White',
    23 => 'Purple',
    24 => 'Red',
    25 => 'Red & Yellow',
    26 => 'Red / Blue / Green',
    27 => 'Red / White',
    28 => 'Red / White / Blue',
    29 => 'Silver',
    30 => 'Sugared Multi-Color',
    31 => 'Teal',
    32 => 'Transparent Multi-Color',
    33 => 'Warm White',
    34 => 'White',
    35 => 'White & Blue',
    36 => 'Yellow',
  ),
) ?>