<?php return array (
  'SubcategoryID' => 3414,
  'SubcategoryName' => 'ElectricalStartersContactors',
  'PropertyName' => 'StarterType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Auxiliary Contacts',
    1 => 'Combination Starters',
    2 => 'Contactor Accessories',
    3 => 'Contactor Repair Kits',
    4 => 'Definite Purpose Magnetic Contactors',
    5 => 'Definite Purpose Magnetic Motor Starters',
    6 => 'Drum Switches',
    7 => 'Hazardous Location Manual Motor Switches & Starter',
    8 => 'Hazardous Location Motor Starters',
    9 => 'Hoist Magnetic Contactors',
    10 => 'IEC Delay Timers',
    11 => 'IEC Magnetic Contactors',
    12 => 'Lighting Magnetic Contactors',
    13 => 'Magnetic Starters with Electronic Overload',
    14 => 'Magnetic Starters with Thermal Overlaod',
    15 => 'Manual Motor Protectors',
    16 => 'Manual Motor Switches & Starters',
    17 => 'Manual Starter Accessory',
    18 => 'Mercury Displacement Contactors',
    19 => 'Motor Starter Enclosures',
    20 => 'NEMA Magnetic Contactors',
    21 => 'NEMA Motor Pilot Lights',
    22 => 'Overcurrent Modules',
    23 => 'Overload Relays',
    24 => 'Replacement Coils',
    25 => 'Starter Control Kit',
    26 => 'Thermal Units',
    27 => 'Vibration Sensors',
  ),
) ?>