<?php return array (
  'SubcategoryID' => 3276,
  'SubcategoryName' => 'OSBreakroomCleaning',
  'PropertyName' => 'BrkroomCleaningFlavor',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Adrenaline Explosion',
    1 => 'Breakfast Blend',
    2 => 'Caramel',
    3 => 'Chai Latte',
    4 => 'Chai Tea',
    5 => 'Chamomile',
    6 => 'Columbian',
    7 => 'Columbian Roast',
    8 => 'Costa Rica',
    9 => 'Earl Grey',
    10 => 'English Breakfast',
    11 => 'French Roast',
    12 => 'French Vanilla',
    13 => 'Green',
    14 => 'Green Citron',
    15 => 'Guatemala',
    16 => 'Hazelnut Creme',
    17 => 'Hibiscus Mint',
    18 => 'Hot Chocolate',
    19 => 'Italiano',
    20 => 'Kenya',
    21 => 'Kona',
    22 => 'Lemon',
    23 => 'Passion Fruit',
    24 => 'Raspberry',
    25 => 'Signature Blend',
    26 => 'Sumatra',
    27 => 'Tropical Breeze',
    28 => 'Valencia Orange',
    29 => 'Vanilla Bean',
    30 => 'Variety',
    31 => 'White Lavender',
  ),
) ?>