<?php return array (
  'SubcategoryID' => 3073,
  'SubcategoryName' => 'Ultrabooks',
  'PropertyName' => 'GroupNBOption',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '5200U (2.2 GHz)',
    1 => '5300U (2.3 GHz)',
    2 => '5600U (2.6 GHz)',
    3 => 'Bundle w/Pen',
    4 => 'Dock Included',
    5 => 'English',
    6 => 'External DVD±R/RW',
    7 => 'French',
    8 => 'French Bilingual',
    9 => 'No',
    10 => 'No Optical Drive',
    11 => 'Notebook Only',
    12 => 'Tablet and Dock',
    13 => 'Tablet Only',
  ),
) ?>