<?php return array (
  'SubcategoryID' => 3073,
  'SubcategoryName' => 'Ultrabooks',
  'PropertyName' => 'NBOpticalDriveType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'BD Combo',
    1 => 'BD-ROM',
    2 => 'Blu-Ray Burner',
    3 => 'Blu-ray Disc / Super Multi',
    4 => 'Blu-ray Reader/DVD-Writer',
    5 => 'CD-ROM',
    6 => 'Dual layer DVD Burner',
    7 => 'DVD Super Multi',
    8 => 'DVD+R/RW',
    9 => 'DVD-R/RW',
    10 => 'DVD-ROM',
    11 => 'DVD/CD-RW Combo',
    12 => 'DVD±R/RW',
    13 => 'DVD±RW',
    14 => 'HD DVD-ROM / Super Multi',
    15 => 'HD DVD-RW / Super Multi',
    16 => 'Multi-Format DVD Recorder',
    17 => 'No',
    18 => 'Yes',
  ),
) ?>