<?php return array (
  'SubcategoryID' => 852,
  'SubcategoryName' => 'EBookAccessories',
  'PropertyName' => 'eBookAccType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'App Supported Accessories',
    1 => 'Bluetooth Handset',
    2 => 'Camera',
    3 => 'Case & Stand',
    4 => 'Cases / Overlays / Light',
    5 => 'Clean Tools',
    6 => 'Dock',
    7 => 'Keyboard',
    8 => 'Kit',
    9 => 'Parts',
    10 => 'Power / Batteries / Cables',
    11 => 'Screen Protectors',
    12 => 'Security',
    13 => 'Skin',
    14 => 'Stand',
    15 => 'Strip',
    16 => 'Stylus',
    17 => 'Wall Bracket / Wall Mount',
  ),
) ?>