<?php return array (
  'SubcategoryID' => 3046,
  'SubcategoryName' => 'AudioVideoConverters',
  'PropertyName' => 'ADPTCHNGERStyle',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Acer Aspire S7',
    1 => 'CBL-MDDVI',
    2 => 'CBL-MDHDMI',
    3 => 'HP Pavilion Chromebook 14',
    4 => 'Lenovo X1 Carbon',
    5 => 'Lenovo X1 Carbon 2',
    6 => 'Macbook Air',
    7 => 'MacBook Pro',
    8 => 'Microsoft Surface Pro 2',
    9 => 'Microsoft Surface Pro 3',
    10 => 'Microsoft Surface3',
    11 => 'No',
    12 => 'Samsung Chromebook 2',
    13 => 'Samsung XE303 Chromebook',
  ),
) ?>