<?php return array (
  'SubcategoryID' => 3046,
  'SubcategoryName' => 'AudioVideoConverters',
  'PropertyName' => 'AVConvertersType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Analog to Digital',
    1 => 'Audio Signal Converters',
    2 => 'Capture Devices',
    3 => 'Component to HDMI',
    4 => 'Component to VGA',
    5 => 'Composite to VGA',
    6 => 'Digital to Analog',
    7 => 'DP to DVI',
    8 => 'DP to HDMI',
    9 => 'DP to VGA',
    10 => 'DP to VGA / DVI /HDMI',
    11 => 'DVI Converters',
    12 => 'DVI to HDMI',
    13 => 'DVI to Mini DP',
    14 => 'DVI to VGA',
    15 => 'HDMI / DVI to DP',
    16 => 'HDMI / VGA / Mini DP to HDMI',
    17 => 'HDMI Converters',
    18 => 'HDMI to Composite',
    19 => 'HDMI to DP',
    20 => 'HDMI to DVI',
    21 => 'HDMI to HDMI',
    22 => 'HDMI to VGA',
    23 => 'Mini DisplayPort Converters',
    24 => 'Mini DP to DP',
    25 => 'Mini DP to DP / DVI / HDMI',
    26 => 'Mini DP to DVI',
    27 => 'Mini DP to HDMI',
    28 => 'Mini DP to VGA',
    29 => 'Mini DP to VGA / HDMI',
    30 => 'Mini DP to VGA / HDMI / DVI',
    31 => 'Nintendo Wii to HDMI',
    32 => 'No',
    33 => 'VGA Converters',
    34 => 'VGA to Composite',
    35 => 'VGA to DVI',
    36 => 'VGA to HDMI',
  ),
) ?>