<?php return array (
  'SubcategoryID' => 978,
  'SubcategoryName' => 'NecklacesPendants',
  'PropertyName' => 'NecklaceDesign',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Angel',
    1 => 'Animals',
    2 => 'Birthstone & Zodiac',
    3 => 'Bow',
    4 => 'Butterfly',
    5 => 'Circle',
    6 => 'Coin',
    7 => 'Cross',
    8 => 'Cushion',
    9 => 'Family',
    10 => 'Flower',
    11 => 'Gemstone',
    12 => 'Geometric',
    13 => 'Heart',
    14 => 'Hobby',
    15 => 'Initials',
    16 => 'Insects',
    17 => 'Key',
    18 => 'Leaf',
    19 => 'Lockets',
    20 => 'Love',
    21 => 'Lucky Charm',
    22 => 'Military',
    23 => 'Names, ID\'s & Initials',
    24 => 'Novelty',
    25 => 'Peace Sign',
    26 => 'Photo',
    27 => 'Plain/Engravable',
    28 => 'Professions',
    29 => 'Religious',
    30 => 'Sports',
    31 => 'Square',
    32 => 'Star',
    33 => 'Symbols',
    34 => 'Team & School',
    35 => 'Themed',
    36 => 'Zodiac',
  ),
) ?>