<?php return array (
  'SubcategoryID' => 978,
  'SubcategoryName' => 'NecklacesPendants',
  'PropertyName' => 'NecklaceStyle',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Chains',
    1 => 'Choker',
    2 => 'Collar',
    3 => 'Double Strands',
    4 => 'Gem-Set',
    5 => 'Lariat',
    6 => 'Lockets',
    7 => 'Long Strands',
    8 => 'Matinee',
    9 => 'Opera',
    10 => 'Pearl Strands',
    11 => 'Pendants',
    12 => 'Princess',
    13 => 'Rope',
    14 => 'Single Strand',
    15 => 'Stampato',
    16 => 'Station',
    17 => 'Torsade',
    18 => 'Triple Strands',
    19 => 'Y Necklaces',
  ),
) ?>