<?php return array (
  'SubcategoryID' => 978,
  'SubcategoryName' => 'NecklacesPendants',
  'PropertyName' => 'NecklaceStoneShape',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Asscher',
    1 => 'Beads',
    2 => 'Briolette',
    3 => 'Button',
    4 => 'Cabochon',
    5 => 'Coin',
    6 => 'Cushion',
    7 => 'Cushion Checkerboard',
    8 => 'Drop',
    9 => 'Emerald',
    10 => 'Emerald Cut',
    11 => 'Fancy',
    12 => 'Heart',
    13 => 'Inlay',
    14 => 'Marquise',
    15 => 'Octagonal',
    16 => 'Off Round',
    17 => 'Oval',
    18 => 'Oval Cabochon',
    19 => 'Pear',
    20 => 'Potato',
    21 => 'Princess',
    22 => 'Radiant',
    23 => 'Rice',
    24 => 'Round',
    25 => 'Round Cabochon',
    26 => 'Square',
    27 => 'Square Cabochon',
    28 => 'Triangle',
    29 => 'Trillion',
  ),
) ?>