<?php return array (
  'SubcategoryID' => 669,
  'SubcategoryName' => 'RiceCookers',
  'PropertyName' => 'RiceCookersColor',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Black',
    1 => 'Black & Rose Brown',
    2 => 'Black/Stainless Steel',
    3 => 'Blue',
    4 => 'Champagne',
    5 => 'Gray/Black',
    6 => 'Gray/Stainless Steel',
    7 => 'Green',
    8 => 'Grey',
    9 => 'Pink',
    10 => 'Red',
    11 => 'Silver',
    12 => 'Silver/White',
    13 => 'Stainless Steel',
    14 => 'White',
    15 => 'White & Rose Pink',
    16 => 'Yellow',
  ),
) ?>