<?php return array (
  'SubcategoryID' => 3120,
  'SubcategoryName' => 'CombinationMachines',
  'PropertyName' => 'CoffeeMakersColor',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 1,
  'IsRequired' => 1,
  'PropertyValueList' => 
  array (
    0 => 'Black',
    1 => 'Black/Steel',
    2 => 'Blue',
    3 => 'Bronze',
    4 => 'Brushed Stainless Steel',
    5 => 'Champagne',
    6 => 'Chrome',
    7 => 'Clear',
    8 => 'Copper',
    9 => 'Espresso',
    10 => 'Gray',
    11 => 'Green',
    12 => 'Grey',
    13 => 'Mocha',
    14 => 'Orange',
    15 => 'Pearl',
    16 => 'Pink',
    17 => 'Platinum',
    18 => 'Purple',
    19 => 'Purple Clay',
    20 => 'Red',
    21 => 'Rhubarb',
    22 => 'Silver',
    23 => 'Smoke',
    24 => 'Stainless steel',
    25 => 'Stainless-Steel',
    26 => 'Strawberry Red',
    27 => 'Titanium Silver',
    28 => 'Torquoise',
    29 => 'Violet',
    30 => 'White',
    31 => 'White/Steel',
    32 => 'Yellow',
  ),
) ?>