<?php return array (
  'SubcategoryID' => 1528,
  'SubcategoryName' => 'TravelAccessories',
  'PropertyName' => 'TravelAccessoriesBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Aqua Teal',
    1 => 'Beach Handbags',
    2 => 'Cabeau',
    3 => 'Carbon Sesto',
    4 => 'Celestron',
    5 => 'ChargeIt',
    6 => 'Collar Perfect',
    7 => 'CTA Digital',
    8 => 'DENY Designs',
    9 => 'En Route Travelware',
    10 => 'Genexa',
    11 => 'Germ Guardian',
    12 => 'Goodhope Bags',
    13 => 'J.L. Childress',
    14 => 'Loqi',
    15 => 'Lowepro - Wynit',
    16 => 'Lyrix',
    17 => 'Nicole Lee',
    18 => 'NJ Croce',
    19 => 'Northwest',
    20 => 'Olympia',
    21 => 'Pelican',
    22 => 'PowerCube',
    23 => 'QVS',
    24 => 'SKITS',
    25 => 'Symtec',
  ),
) ?>