<?php return array (
  'SubcategoryID' => 696,
  'SubcategoryName' => 'TVBrackets',
  'PropertyName' => 'TVBracketColor',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Aluminum',
    1 => 'Beige',
    2 => 'Black',
    3 => 'Blue',
    4 => 'Brown',
    5 => 'Clear',
    6 => 'Espresso',
    7 => 'Gloss Black',
    8 => 'Gold',
    9 => 'Gray',
    10 => 'Green',
    11 => 'Ivory',
    12 => 'Metallic',
    13 => 'Multi-colored',
    14 => 'Piano Black',
    15 => 'Platinum',
    16 => 'Polished Aluminum',
    17 => 'Purple',
    18 => 'Red',
    19 => 'Silver',
    20 => 'White',
    21 => 'Yellow',
  ),
) ?>