<?php return array (
  'SubcategoryID' => 696,
  'SubcategoryName' => 'TVBrackets',
  'PropertyName' => 'TVBracketMountStyle',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Antenna Mount',
    1 => 'Articulating/Full Motion',
    2 => 'Cabinet',
    3 => 'Ceiling Mount',
    4 => 'Clamp Mount',
    5 => 'Crossbar',
    6 => 'Desk Mount',
    7 => 'Extension Column',
    8 => 'Fixed Mount',
    9 => 'Flat',
    10 => 'Full Motion',
    11 => 'Mounting Adapter',
    12 => 'Mounting Adapter Kit',
    13 => 'Mounting Arm',
    14 => 'Mounting Bracket',
    15 => 'Mounting Coupler',
    16 => 'Mounting Pole',
    17 => 'Mounting Post',
    18 => 'Mounting Shelf',
    19 => 'Pole Mount',
    20 => 'Rack Mount',
    21 => 'Rail Kit',
    22 => 'Swiveling',
    23 => 'Table',
    24 => 'Tilt',
    25 => 'Tilting Low-Profile',
    26 => 'Tilting Low-Profile/Swiveling',
    27 => 'Tower Conversion Kit',
    28 => 'Ultra Low Profile Articulating Mounts',
    29 => 'Ultra Thin',
    30 => 'Ultra Thin/Fixed Mount',
    31 => 'Universal Flush Mounts',
    32 => 'Vehicle Mount',
    33 => 'Wall',
    34 => 'Wall Mount',
  ),
) ?>