<?php return array (
  'SubcategoryID' => 3331,
  'SubcategoryName' => 'WirelessStreamingAudio',
  'PropertyName' => 'HomeAudioSpeakersColor',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Black',
    1 => 'Blue',
    2 => 'Brown',
    3 => 'Cherry',
    4 => 'Coral',
    5 => 'Dark Apple',
    6 => 'Ebony',
    7 => 'Gloss Black',
    8 => 'Gloss Teal',
    9 => 'Gloss White',
    10 => 'Glossy Gray',
    11 => 'Gold',
    12 => 'Granite',
    13 => 'Green',
    14 => 'Grey',
    15 => 'Maple',
    16 => 'Matte Grey',
    17 => 'N/A',
    18 => 'Pink',
    19 => 'Purple',
    20 => 'Red',
    21 => 'Rosenut',
    22 => 'Sandstone',
    23 => 'Shale',
    24 => 'Silver',
    25 => 'Slate',
    26 => 'Speckled Granite',
    27 => 'Titanium',
    28 => 'White',
    29 => 'Yellow',
  ),
) ?>