<?php return array (
  'SubcategoryID' => 3128,
  'SubcategoryName' => 'MTHelmetsAccessories',
  'PropertyName' => 'MTHelmetSizeDimensions',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '16.5” L x 11.5” W x 11.5” D',
    1 => '2X-Large',
    2 => '2X-Small',
    3 => '3X-Large',
    4 => '4X-Large',
    5 => '5X-Large',
    6 => 'Adult 2XL',
    7 => 'Adult 3XL',
    8 => 'Adult 4XL',
    9 => 'Adult 5XL',
    10 => 'Adult Large',
    11 => 'Adult M/L',
    12 => 'Adult Medium',
    13 => 'Adult S/M',
    14 => 'Adult Small',
    15 => 'Adult XL',
    16 => 'Adult XL/2XL',
    17 => 'Adult XS',
    18 => 'Adult XS/Small',
    19 => 'Large',
    20 => 'Large/X-Large',
    21 => 'Large/X-Large/2X-Large',
    22 => 'Medium',
    23 => 'One Size',
    24 => 'Small',
    25 => 'Small/Medium',
    26 => 'X-Large',
    27 => 'X-Small',
    28 => 'X-Small/Small',
    29 => 'X-Small/Small/Medium',
    30 => 'XX-Large',
    31 => 'XX-Small',
    32 => 'XXX-Large',
    33 => 'Youth Large',
    34 => 'Youth Medium',
    35 => 'Youth Small',
    36 => 'Youth XL',
  ),
) ?>