<?php return array (
  'SubcategoryID' => 3128,
  'SubcategoryName' => 'MTHelmetsAccessories',
  'PropertyName' => 'MTHelmetType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 1,
  'PropertyValueList' => 
  array (
    0 => 'Anti-fog',
    1 => 'Dual Sport Helmets',
    2 => 'Full Face Helmets',
    3 => 'Half Helmets',
    4 => 'Helmet Accents',
    5 => 'Helmet Bags',
    6 => 'Helmet Base Plate Covers',
    7 => 'Helmet Breath Guards',
    8 => 'Helmet Liners',
    9 => 'Helmet Locks',
    10 => 'Helmet Pads',
    11 => 'Helmet Pivot Kits',
    12 => 'Helmet Tear-Offs',
    13 => 'Helmet Vents',
    14 => 'Intercoms/Communication Devices',
    15 => 'Modular Helmets',
    16 => 'Motocross Helmets',
    17 => 'Open Face Helmets',
    18 => 'Shields & Visors',
  ),
) ?>