<?php return array (
  'SubcategoryID' => 558,
  'SubcategoryName' => 'CarSpeakers',
  'PropertyName' => 'CarSpeakersSeries',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'A-Series',
    1 => 'ANARCHY',
    2 => 'AXIS',
    3 => 'Big Bang',
    4 => 'Blue Label',
    5 => 'Chaos Series',
    6 => 'Drive Series',
    7 => 'DRVN XX',
    8 => 'Gear X Series',
    9 => 'Okur',
    10 => 'ONYX NX',
    11 => 'PHANTOM SKULL',
    12 => 'Picasso',
    13 => 'PRO Audio',
    14 => 'Pro Audio Series',
    15 => 'Rubicon',
    16 => 'Speed Series',
    17 => 'Tarantula',
    18 => 'Terminator',
    19 => 'Xplod W Series',
  ),
) ?>