<?php return array (
  'SubcategoryID' => 2157,
  'SubcategoryName' => 'BeautySkinCare',
  'PropertyName' => 'BeautySkinCareColor',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Aqua',
    1 => 'Black',
    2 => 'Black and Purple',
    3 => 'Blue',
    4 => 'Gold',
    5 => 'Gold and Black',
    6 => 'Golden',
    7 => 'Golden and Black',
    8 => 'Gray',
    9 => 'Lavender',
    10 => 'Light Green',
    11 => 'N/A',
    12 => 'Pale Yellow',
    13 => 'Pink',
    14 => 'Pink Frost',
    15 => 'Purple',
    16 => 'Red',
    17 => 'Silver',
    18 => 'Silver and Black',
    19 => 'White',
    20 => 'White and Purple',
    21 => 'White and Purple',
  ),
) ?>