<?php return array (
  'SubcategoryID' => 2157,
  'SubcategoryName' => 'BeautySkinCare',
  'PropertyName' => 'BeautySkinCareType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Acne Treatments',
    1 => 'Anti-Aging Treatments',
    2 => 'Antiperspirants & Deodorants',
    3 => 'Body Skin Care Products',
    4 => 'Cotton Balls & Swabs',
    5 => 'Eye Treatments',
    6 => 'Face Cleaners',
    7 => 'Facial Exfoliators',
    8 => 'Facial Moisturizers',
    9 => 'Facial Treatments',
    10 => 'Hand & Body Lotions',
    11 => 'Men\'s Skin Care',
    12 => 'Skin Care Kits',
    13 => 'Skin Care Tools',
    14 => 'Soaps & Bodywash',
    15 => 'Sun Care',
    16 => 'Toners',
  ),
) ?>