<?php return array (
  'SubcategoryID' => 3368,
  'SubcategoryName' => 'IndustrialVehiclePartsAccessories',
  'PropertyName' => 'IndustrialVehiclePartsType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 1,
  'PropertyValueList' => 
  array (
    0 => 'Aero & Body Parts',
    1 => 'Air Brake System',
    2 => 'Air Filters / Intakes',
    3 => 'Batteries & Accessories',
    4 => 'Bearings & Seals',
    5 => 'Belts, Hoses & Pulleys',
    6 => 'Brake System',
    7 => 'Climate Control System',
    8 => 'Drive Train',
    9 => 'Electronics & Gauges',
    10 => 'Emission System',
    11 => 'Engine & Engine Parts',
    12 => 'Engine Cooling',
    13 => 'Exhaust System',
    14 => 'Fuel System',
    15 => 'Gaskets',
    16 => 'Ignition & Electrical',
    17 => 'Performance Lighting',
    18 => 'Safety Equipment',
    19 => 'Shocks, Struts & Suspension',
    20 => 'Starters & Alternators',
    21 => 'Steering System',
    22 => 'Switches & Relays',
    23 => 'Windshield Wipers & Washers',
  ),
) ?>