<?php return array (
  'SubcategoryID' => 2567,
  'SubcategoryName' => 'SGFoodWater',
  'PropertyName' => 'SGFoodSizeDimensions',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '1 Serving',
    1 => '12 oz',
    2 => '16 oz',
    3 => '16.9 oz.',
    4 => '18 oz',
    5 => '2 Servings',
    6 => '20 oz',
    7 => '21 oz',
    8 => '24 oz',
    9 => '3 Servings',
    10 => '32 oz',
    11 => '4 Servings',
    12 => '40 oz',
    13 => '64 oz',
    14 => 'Not Available',
  ),
) ?>