<?php return array (
  'SubcategoryID' => 699,
  'SubcategoryName' => 'ProjectorScreens',
  'PropertyName' => 'ProjectorScreenBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '2C',
    1 => 'ACCO',
    2 => 'AccuScreens',
    3 => 'CHIEF MANUFACTURING',
    4 => 'DA-LITE',
    5 => 'DRAPER',
    6 => 'Elitescreens',
    7 => 'EluneVision',
    8 => 'EPSON',
    9 => 'Grandview',
    10 => 'InFocus',
    11 => 'inland',
    12 => 'lp morgan',
    13 => 'MITSUBISHI',
    14 => 'MUSTANG',
    15 => 'NEC',
    16 => 'Quartet',
    17 => 'Sima',
    18 => 'Trend Times Toys',
    19 => 'ViewSonic',
    20 => 'Vutec',
  ),
) ?>