<?php return array (
  'SubcategoryID' => 1019,
  'SubcategoryName' => 'SportsGiftSets',
  'PropertyName' => 'SportgiftColor',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Beige',
    1 => 'Black',
    2 => 'Blue',
    3 => 'Brown',
    4 => 'Clear',
    5 => 'Coral',
    6 => 'Gold',
    7 => 'Green',
    8 => 'Grey',
    9 => 'Ivory',
    10 => 'Multi',
    11 => 'Orange',
    12 => 'Pink',
    13 => 'Purple',
    14 => 'Red',
    15 => 'Silver',
    16 => 'Teal',
    17 => 'White',
    18 => 'Yellow',
  ),
) ?>