<?php return array (
  'SubcategoryID' => 863,
  'SubcategoryName' => 'BodyJewelry',
  'PropertyName' => 'BodyJewelryColor',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Amethyst',
    1 => 'Aquamarine',
    2 => 'Black',
    3 => 'Blue Zircon',
    4 => 'Clear',
    5 => 'Crystal AB',
    6 => 'Emerald',
    7 => 'Fuchsia',
    8 => 'Light Sapphire',
    9 => 'Peridot',
    10 => 'Pink',
    11 => 'Red',
    12 => 'Sapphire',
    13 => 'Tanzanite',
  ),
) ?>