<?php return array (
  'SubcategoryID' => 863,
  'SubcategoryName' => 'BodyJewelry',
  'PropertyName' => 'BodyJewelryDesign',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Animals',
    1 => 'Birthstone & Zodiac',
    2 => 'Coin',
    3 => 'Family',
    4 => 'Gemstone',
    5 => 'Hobby',
    6 => 'Insects',
    7 => 'Lockets',
    8 => 'Military',
    9 => 'Names, ID\'s & Initials',
    10 => 'Novelty',
    11 => 'Photo',
    12 => 'Plain/Engravable',
    13 => 'Professions',
    14 => 'Religious',
    15 => 'Sports',
    16 => 'Symbols',
    17 => 'Team & School',
    18 => 'Themed',
  ),
) ?>