<?php return array (
  'SubcategoryID' => 2074,
  'SubcategoryName' => 'HIWaterPurificationFiltration',
  'PropertyName' => 'HIWaterDispensersType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Backwashing Filters',
    1 => 'Bag Filter Housings',
    2 => 'Beverage & Ice Machine Filters',
    3 => 'Coolant Filters And Cartridges',
    4 => 'Drinking Water Systems',
    5 => 'Drinking Water Systems Accessories',
    6 => 'Filter Bags',
    7 => 'Filter Cartridges',
    8 => 'Filter Housings',
    9 => 'Filtration Accessories',
    10 => 'Filtration Bag Magnet',
    11 => 'Filtration System Accessories',
    12 => 'Filtration Systems',
    13 => 'Inline Filters',
    14 => 'Inline Strainers',
    15 => 'Reverse Osmosis Systems',
    16 => 'RO Systems',
    17 => 'RO Systems Accessories',
    18 => 'Scale Inhibitor System',
    19 => 'Specialty Filters',
    20 => 'Treatment Chemicals',
    21 => 'UV Systems',
    22 => 'UV Systems Accessories',
    23 => 'UV Water Sterilizers',
    24 => 'Water Inlet Solenoids',
    25 => 'Water Inslet Solenoids',
    26 => 'Water Softeners',
    27 => 'Water Test Kit',
    28 => 'Y and Basket Strainers',
  ),
) ?>