<?php return array (
  'SubcategoryID' => 667,
  'SubcategoryName' => 'ThermoPots',
  'PropertyName' => 'ThermoPotBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Aroma',
    1 => 'Black & Decker',
    2 => 'Bloomfield',
    3 => 'Fujitronic',
    4 => 'HOMEIMAGE',
    5 => 'NARITA',
    6 => 'Panasonic',
    7 => 'Rosewill',
    8 => 'Sunbeam',
    9 => 'Sunpentown',
    10 => 'TATUNG',
    11 => 'Tayama',
    12 => 'TIGER',
    13 => 'Toastess',
    14 => 'WAGAN',
    15 => 'West Bend',
    16 => 'Whynter',
    17 => 'ZOJIRUSHI',
  ),
) ?>