<?php return array (
  'SubcategoryID' => 850,
  'SubcategoryName' => 'SurveillanceHomeSafetySecurity',
  'PropertyName' => 'SURHSType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Alarm System',
    1 => 'Door / Window Sensor',
    2 => 'Door Chime',
    3 => 'Electric Lock',
    4 => 'Flashlight',
    5 => 'Key Lock Box',
    6 => 'Keyless Entry System',
    7 => 'Keypad Door Locks',
    8 => 'Ladder',
    9 => 'Motion Alarm System',
    10 => 'Other',
    11 => 'Personal Security',
    12 => 'Push Button Switch',
    13 => 'Security & Motion',
    14 => 'Siren',
    15 => 'Smoke / Carbon Monoxide Alarm',
    16 => 'Smoke Detector',
    17 => 'Water Detector',
  ),
) ?>