<?php return array (
  'SubcategoryID' => 239,
  'SubcategoryName' => 'AccessoriesStorageDevicesTapeZip',
  'PropertyName' => 'TapeBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Acer',
    1 => 'APC',
    2 => 'Brother',
    3 => 'CERTANCE',
    4 => 'Cisco',
    5 => 'CRU-DataPort',
    6 => 'Dell',
    7 => 'Drobo',
    8 => 'E-Filliate',
    9 => 'EXABYTE',
    10 => 'FUJIFILM',
    11 => 'HP',
    12 => 'IBM',
    13 => 'imation',
    14 => 'iomega',
    15 => 'Lenovo',
    16 => 'maxell',
    17 => 'Overland',
    18 => 'Plasmon',
    19 => 'Qnap',
    20 => 'Quantum',
    21 => 'Ram Mount',
    22 => 'Seagate',
    23 => 'Shurtech',
    24 => 'SONY',
    25 => 'Synology',
    26 => 'TANDBERG DATA',
    27 => 'TDK',
    28 => 'Verbatim',
  ),
) ?>