<?php return array (
  'SubcategoryID' => 2177,
  'SubcategoryName' => 'HLKitchenStorageOrganization',
  'PropertyName' => 'HLStorageType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 1,
  'PropertyValueList' => 
  array (
    0 => 'Baskets',
    1 => 'Buckets and Bins',
    2 => 'Cabinet & Drawer Liners',
    3 => 'Cabinet Organizers',
    4 => 'Caddies',
    5 => 'Condiment Organizers',
    6 => 'Dinnerware & Stemware Storage',
    7 => 'Dish Racks',
    8 => 'Flatware & Utensil Storage',
    9 => 'Food Pantries',
    10 => 'Hall Trees and Coat Racks',
    11 => 'Hooks and Racks',
    12 => 'Kitchen Mats',
    13 => 'Kitchen Racks & Shelving',
    14 => 'Lazy Susans',
    15 => 'Mug Holders',
    16 => 'Napkin Holders',
    17 => 'Paper Towel Holders',
    18 => 'Plate Stands',
    19 => 'Pot Racks',
    20 => 'Pot Stands',
    21 => 'Refrigerator & Freezer Organizers',
    22 => 'Refrigerator Magnets',
    23 => 'Shopping Carts',
    24 => 'Spice Jars & Racks',
    25 => 'Stepstools & Stepladders',
    26 => 'Trash Can',
    27 => 'Turntables',
    28 => 'Under Cabinet Stemware Rack',
    29 => 'Wall and Door Organizers',
    30 => 'Wine Glass Racks',
  ),
) ?>