<?php return array (
  'SubcategoryID' => 2177,
  'SubcategoryName' => 'HLKitchenStorageOrganization',
  'PropertyName' => 'HLStorageBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Adesso',
    1 => 'ATE',
    2 => 'Butler',
    3 => 'Drive Medical',
    4 => 'Fellowes Mfg. Co.',
    5 => 'Home Basics',
    6 => 'Ideaworks',
    7 => 'Jobar',
    8 => 'KidKraft',
    9 => 'KooLuLu',
    10 => 'Lavish Home',
    11 => 'Levels of Discovery',
    12 => 'Lorell',
    13 => 'Montana woodworks',
    14 => 'Quartet',
    15 => 'Ragalta',
    16 => 'Rubbermaid Commercial Products',
    17 => 'Stalwart',
    18 => 'Swivel Store',
    19 => 'The Laundry POD',
    20 => 'Two Elephants',
    21 => 'Uttermost',
    22 => 'Zuo Modern',
  ),
) ?>