<?php return array (
  'SubcategoryID' => 914,
  'SubcategoryName' => 'BroochesPinsClips',
  'PropertyName' => 'BroochDiamondColor',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'D',
    1 => 'D-E',
    2 => 'D-F',
    3 => 'E',
    4 => 'E-F',
    5 => 'F',
    6 => 'F-G',
    7 => 'G',
    8 => 'G-H',
    9 => 'G-J',
    10 => 'H',
    11 => 'H-I',
    12 => 'I',
    13 => 'I-J',
    14 => 'J',
    15 => 'J-K',
    16 => 'K',
    17 => 'K-L',
    18 => 'K-M',
    19 => 'L',
    20 => 'M',
    21 => 'N-Z',
  ),
) ?>