<?php return array (
  'SubcategoryID' => 1685,
  'SubcategoryName' => 'FitnessAccessories',
  'PropertyName' => 'FitnessAccessoriesBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Ab Rocket',
    1 => 'Acu-Hoop',
    2 => 'Cando',
    3 => 'Exerpeutic',
    4 => 'Gofit',
    5 => 'Hype',
    6 => 'Ironman',
    7 => 'Jawbone',
    8 => 'Mio',
    9 => 'Progear Fitness',
    10 => 'Remedy',
    11 => 'Rocket Fitness',
    12 => 'TG',
    13 => 'Trademark',
    14 => 'Twelve 1 Ten',
    15 => 'Whestone',
  ),
) ?>