<?php return array (
  'SubcategoryID' => 612,
  'SubcategoryName' => 'CellPhoneCaseCovers',
  'PropertyName' => 'CellphoneACCCaseType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Accessory',
    1 => 'Amplifier',
    2 => 'Armband',
    3 => 'Battery Case',
    4 => 'Bumper',
    5 => 'Case',
    6 => 'Emergency Kit',
    7 => 'Flip Case',
    8 => 'Holster',
    9 => 'Lanyard',
    10 => 'Privacy Filter',
    11 => 'Replacement Part',
    12 => 'Screen Protector',
    13 => 'Skin',
    14 => 'Sleeve',
    15 => 'Waistband',
    16 => 'Wallet Case',
  ),
) ?>