<?php return array (
  'SubcategoryID' => 420,
  'SubcategoryName' => 'CDDVDROMRWDrivesExternal',
  'PropertyName' => 'ODDPanelColor',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '2-Tone',
    1 => '3-Tone',
    2 => 'Beige',
    3 => 'Black',
    4 => 'Blue',
    5 => 'Brown',
    6 => 'Gold',
    7 => 'Gray',
    8 => 'Green',
    9 => 'Ivory',
    10 => 'Pink',
    11 => 'Purple',
    12 => 'Red',
    13 => 'Silver',
    14 => 'White',
    15 => 'Yellow',
  ),
) ?>