<?php return array (
  'SubcategoryID' => 3410,
  'SubcategoryName' => 'MachineryMotorsParts',
  'PropertyName' => 'MachineryMotorType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'AC Motors',
    1 => 'Air Motors',
    2 => 'Car Wash Motors',
    3 => 'Commutator Rotary',
    4 => 'DC Motors',
    5 => 'Definite Purpose AC Motors',
    6 => 'Gas Engines',
    7 => 'Gearmotors',
    8 => 'General Purpose AC Motors',
    9 => 'HVAC Motors',
    10 => 'Hydraulic Motors',
    11 => 'Motor Capacitors',
    12 => 'Motor Mounts, Bases & Accessories',
    13 => 'Oil Coolers',
    14 => 'Pump Motors',
    15 => 'Replacement Parts',
    16 => 'Rotary',
    17 => 'Speed-Controlled Motors',
  ),
) ?>