<?php return array (
  'SubcategoryID' => 3137,
  'SubcategoryName' => 'EngagementRingsBridalSets',
  'PropertyName' => 'EngagementStyle',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '3 Stone',
    1 => '5 Stone',
    2 => 'Bar',
    3 => 'Basket',
    4 => 'Bezel',
    5 => 'Bypass',
    6 => 'Cathedral',
    7 => 'Channel',
    8 => 'Classic',
    9 => 'Double Halo',
    10 => 'Eternity',
    11 => 'Half-Bezel',
    12 => 'Halo',
    13 => 'Invisible',
    14 => 'Modern',
    15 => 'Pave',
    16 => 'Prong',
    17 => 'Romantic',
    18 => 'Side Stones',
    19 => 'Solitaire',
    20 => 'Split Shank',
    21 => 'Tension',
    22 => 'Vintage',
  ),
) ?>