<?php return array (
  'SubcategoryID' => 3137,
  'SubcategoryName' => 'EngagementRingsBridalSets',
  'PropertyName' => 'EWRingGemType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 1,
  'IsRequired' => 1,
  'PropertyValueList' => 
  array (
    0 => 'Akoya Pearl',
    1 => 'Alexandrite',
    2 => 'Amethyst',
    3 => 'Aquamarine',
    4 => 'Citrine',
    5 => 'Conch Pearl',
    6 => 'Diamond',
    7 => 'Emerald',
    8 => 'Freshwater Pearl',
    9 => 'Garnet',
    10 => 'Gold South Sea Pearl',
    11 => 'Imitation Pearl',
    12 => 'Jade',
    13 => 'Moissanite',
    14 => 'Morganite',
    15 => 'Multiple Types',
    16 => 'Onyx',
    17 => 'Opal',
    18 => 'Pearl',
    19 => 'Peridot',
    20 => 'Quartz',
    21 => 'Ruby',
    22 => 'Sapphire',
    23 => 'Tahitian Pearl',
    24 => 'Tanzanite',
    25 => 'Topaz',
    26 => 'Tourmaline',
    27 => 'Tsavorite',
    28 => 'Turquoise',
    29 => 'White South Sea Pearl',
  ),
) ?>