<?php return array (
  'SubcategoryID' => 3137,
  'SubcategoryName' => 'EngagementRingsBridalSets',
  'PropertyName' => 'JewelryPearlShape',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Baroque',
    1 => 'Button',
    2 => 'Circled Baroque',
    3 => 'Coin',
    4 => 'Drop',
    5 => 'Drop / Oval',
    6 => 'Irregular',
    7 => 'Keshi',
    8 => 'Mixed Shapes',
    9 => 'Near-Round',
    10 => 'Off-Round',
    11 => 'Oval',
    12 => 'Potato',
    13 => 'Round',
    14 => 'Semi-Baroque',
  ),
) ?>