<?php return array (
  'SubcategoryID' => 32,
  'SubcategoryName' => 'Notebooks',
  'PropertyName' => 'NBVideoPort',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '1 x DisplayPort',
    1 => '1 x DVI',
    2 => '1 x DVI, 1 x Displayport',
    3 => '1 x DVI, 1 x S-Video TV-out',
    4 => '1 x Mini DisplayPort',
    5 => '1 x S-Video TV-out',
    6 => '1 x Thunderbolt',
    7 => '1 x Thunderbolt, 1 x DisplayPort',
    8 => '1 x Thunderbolt, 1 x Mini DisplayPort',
    9 => '1 x VGA',
    10 => '1 x VGA, 1 x DisplayPort',
    11 => '1 x VGA, 1 x DisplayPort, 1 x Thunderbolt',
    12 => '1 x VGA, 1 x DVI',
    13 => '1 x VGA, 1 x DVI, 1 x DisplayPort',
    14 => '1 x VGA, 1 x DVI, 1 x S-Video TV-out',
    15 => '1 x VGA, 1 x Mini DisplayPort',
    16 => '1 x VGA, 1 x S-Video TV-out',
    17 => '1 x VGA, 1 x Thunderbolt',
    18 => '1 x VGA, 2 x Mini DisplayPort',
    19 => '2 x DisplayPorts',
    20 => '2 x Mini DisplayPorts',
    21 => '2 x Thunderbolts',
    22 => '4 x Thunderbolts',
  ),
) ?>