<?php return array (
  'SubcategoryID' => 1899,
  'SubcategoryName' => 'HIConduitFittings',
  'PropertyName' => 'HIConduitType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Aluminum Service Poles',
    1 => 'Cable & Hose Carriers',
    2 => 'Cable & Pipe Seals',
    3 => 'Cable Safety Springs',
    4 => 'Cable Support Grips',
    5 => 'Cable Tie Accessories',
    6 => 'Cable Tie Mounting Bases',
    7 => 'Cable Tie Tools',
    8 => 'Cable Ties',
    9 => 'Conduit',
    10 => 'Conduit Benders',
    11 => 'Conduit Bodies',
    12 => 'Conduit Fishing',
    13 => 'Conduit Fittings',
    14 => 'Conduit Mounting',
    15 => 'Conduit Reducing Bushings & Washers',
    16 => 'Corrugated Tubing',
    17 => 'Corrugated Tubing Fittings',
    18 => 'Electrical Cable Clamps & Holders',
    19 => 'Prewired Raceways',
    20 => 'Raceway Fitting Accessories',
    21 => 'Raceway Fittings',
    22 => 'Raceways',
    23 => 'Strain Relief Cord Grips',
    24 => 'Strut Channel',
    25 => 'Strut Channel Accessories',
    26 => 'Wire & Cable Staples',
    27 => 'Wiring Duct Accessories',
  ),
) ?>