<?php return array (
  'SubcategoryID' => 428,
  'SubcategoryName' => 'AccessoriesBareboneSystems',
  'PropertyName' => 'BareboneAccBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '4XEM',
    1 => 'Aopen',
    2 => 'ASRock',
    3 => 'ASUS',
    4 => 'BIOSTAR',
    5 => 'ECS',
    6 => 'Foxconn',
    7 => 'Giada',
    8 => 'GIGABYTE',
    9 => 'Intel',
    10 => 'Jetway',
    11 => 'Minix',
    12 => 'MSI',
    13 => 'Sapphire',
    14 => 'Seeed',
    15 => 'Shuttle',
    16 => 'SONY',
    17 => 'ZOTAC',
  ),
) ?>