<?php return array (
  'SubcategoryID' => 513,
  'SubcategoryName' => 'HomeTheaterProjectors',
  'PropertyName' => 'MonitorDisplayPanel',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'A-MVA',
    1 => 'a-si TFT/PVA LCD',
    2 => 'Active Matrix, TFT LCD',
    3 => 'AH-IPS',
    4 => 'AHVA',
    5 => 'IPS',
    6 => 'MVA',
    7 => 'PLS',
    8 => 'PVA',
    9 => 'S-IPS',
    10 => 'S-PVA',
    11 => 'TFT LCD',
    12 => 'TN',
    13 => 'VA',
  ),
) ?>