<?php return array (
  'SubcategoryID' => 227,
  'SubcategoryName' => 'CellPhonesNoContractPhone',
  'PropertyName' => 'MWExpansionSlotType',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Card slot: microSD, up to 32GB',
    1 => 'MicroSD',
    2 => 'MicroSD (TF Card)',
    3 => 'MicroSDHC',
    4 => 'MicroSDXC',
    5 => 'MiniSD',
    6 => 'MiniSDHC',
    7 => 'MMC',
    8 => 'MS DUO (PRO DUO)',
    9 => 'MS Micro (M2)',
    10 => 'None',
    11 => 'SD',
    12 => 'SDHC',
    13 => 'SDIO',
    14 => 'SDXC',
  ),
) ?>