<?php return array (
  'SubcategoryID' => 227,
  'SubcategoryName' => 'CellPhonesNoContractPhone',
  'PropertyName' => 'MWMaxStorageExpansion',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Card slot: microSD, up to 32GB',
    1 => 'Up to 128GB',
    2 => 'Up to 16GB',
    3 => 'Up to 1GB',
    4 => 'Up to 200GB',
    5 => 'Up to 256GB',
    6 => 'Up to 2GB',
    7 => 'Up to 2TB',
    8 => 'up to 32 GB',
    9 => 'Up to 32GB',
    10 => 'Up to 4GB',
    11 => 'Up to 512MB',
    12 => 'Up to 64GB',
    13 => 'Up to 8GB',
  ),
) ?>