<?php return array (
  'SubcategoryID' => 1572,
  'SubcategoryName' => 'ToysPlushedStuffed',
  'PropertyName' => 'ToysPlushedStuffedColor',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Assorted',
    1 => 'Beige',
    2 => 'Black',
    3 => 'Blue',
    4 => 'Brown',
    5 => 'Burgundy',
    6 => 'Camo',
    7 => 'Clear',
    8 => 'Coral',
    9 => 'Dark Blue',
    10 => 'Dark Green',
    11 => 'Dress',
    12 => 'Gold',
    13 => 'Green',
    14 => 'Grey',
    15 => 'Ivory',
    16 => 'Khaki',
    17 => 'Kiwi',
    18 => 'Light Blue',
    19 => 'Light Green',
    20 => 'Metallic',
    21 => 'Multi-Color',
    22 => 'Orange',
    23 => 'Pink',
    24 => 'Pink / White Swirl',
    25 => 'Platinum',
    26 => 'Purple',
    27 => 'Purple / Pink',
    28 => 'Purple / Pink / White',
    29 => 'Red',
    30 => 'Silver',
    31 => 'Teal',
    32 => 'White',
    33 => 'Yellow',
    34 => 'Yellow / White Swirl',
  ),
) ?>