<?php return array (
  'SubcategoryID' => 2071,
  'SubcategoryName' => 'HIApplianceParts',
  'PropertyName' => 'HIAppliancePartsType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Accessories',
    1 => 'Black - Adapters',
    2 => 'Black - Collars',
    3 => 'Black - Elbows',
    4 => 'Black - Pipe',
    5 => 'Black - Supports',
    6 => 'Black - Tees',
    7 => 'Ceiling Plate',
    8 => 'Chimney Cleaning',
    9 => 'Electric Fireplace',
    10 => 'Fire Starter',
    11 => 'Pellet Rod',
    12 => 'Rope Gasket',
    13 => 'Sealant',
    14 => 'Spark Arrestor',
    15 => 'Stainless - Adapter',
    16 => 'Stainless - Collars',
    17 => 'Stainless - Elbows',
    18 => 'Stainless - Firestop',
    19 => 'Stainless - Flashings',
    20 => 'Stainless - Locking Bands',
    21 => 'Stainless - Pipe',
    22 => 'Stainless - Roof Brace',
    23 => 'Stainless - Round Top',
    24 => 'Stainless - Support Kits',
    25 => 'Stainless - Supports',
    26 => 'Stainless - Tees',
    27 => 'Stainless - Thimbles',
    28 => 'Stainless - Wall Bands',
    29 => 'Tank Shield',
    30 => 'Thermometer',
  ),
) ?>