<?php return array (
  'SubcategoryID' => 766,
  'SubcategoryName' => 'Fans',
  'PropertyName' => 'HAFanColor',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '2 Tone',
    1 => 'Aged Bronze',
    2 => 'Baby Blue',
    3 => 'Black',
    4 => 'Blue',
    5 => 'Bronze',
    6 => 'Brown',
    7 => 'Charcoal Gray',
    8 => 'Cherrywood',
    9 => 'Chrome',
    10 => 'Clear',
    11 => 'Dark Gray',
    12 => 'English Bronze',
    13 => 'Fuchsia',
    14 => 'Gray',
    15 => 'Green',
    16 => 'Grey',
    17 => 'Milky Ivory',
    18 => 'Mysterious Black',
    19 => 'Oil Rubbed Bronze',
    20 => 'Oil Rubbed Bronze with Black Blades',
    21 => 'Oil-Rubbed Bronze',
    22 => 'Orange',
    23 => 'Pink',
    24 => 'Platinum',
    25 => 'Red',
    26 => 'Red Wood',
    27 => 'Satin Nickel',
    28 => 'Silver',
    29 => 'Sonic Silver',
    30 => 'Spicy Red',
    31 => 'Stainless Steel',
    32 => 'Tan',
    33 => 'White',
    34 => 'Wood Grain',
    35 => 'Wrought Iron Black',
    36 => 'Yellow',
  ),
) ?>