<?php return array (
  'SubcategoryID' => 549,
  'SubcategoryName' => 'MaciPodPlayers',
  'PropertyName' => 'CNETMP3Color',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '2-Tone',
    1 => 'Black',
    2 => 'Black/Silver',
    3 => 'Black/Yellow',
    4 => 'Blue',
    5 => 'Blue/Silver',
    6 => 'Bronze',
    7 => 'Brown',
    8 => 'Camo',
    9 => 'Champagne',
    10 => 'Gold',
    11 => 'Graphite',
    12 => 'Gray',
    13 => 'Green',
    14 => 'Indigo',
    15 => 'Light Blue',
    16 => 'Orange',
    17 => 'Pearl',
    18 => 'Pink',
    19 => 'Purple',
    20 => 'Red',
    21 => 'Silver',
    22 => 'Teal',
    23 => 'Titanium',
    24 => 'White',
    25 => 'Yellow',
  ),
) ?>