<?php return array (
  'SubcategoryID' => 849,
  'SubcategoryName' => 'SurveillanceVideoRecorders',
  'PropertyName' => 'GroupSURVRChannels',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '16 Channel',
    1 => '16 Channel (1TB HDD)',
    2 => '16 Channel (2TB HDD)',
    3 => '16 Channel (No HDD)',
    4 => '24 Channel',
    5 => '32 Channel',
    6 => '4 Channel',
    7 => '4 Channel (1TB HDD)',
    8 => '4 Channel (No HDD)',
    9 => '8 Channel',
    10 => '8 Channel (1TB HDD)',
    11 => '8 Channel (No HDD)',
    12 => '9 Channel',
    13 => '9 Channel w/ 2 HDD Bays',
  ),
) ?>