<?php return array (
  'SubcategoryID' => 2639,
  'SubcategoryName' => 'ATAirFresheners',
  'PropertyName' => 'AutoScent',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Angel Snow',
    1 => 'Apple',
    2 => 'Assorted',
    3 => 'Black Cherry',
    4 => 'Black Musk',
    5 => 'Black Squash',
    6 => 'Black Vanilla',
    7 => 'Cherry',
    8 => 'Cherry Squash',
    9 => 'Clean Squash',
    10 => 'Cologne',
    11 => 'Cool Squash',
    12 => 'Jasmine',
    13 => 'Lavender',
    14 => 'Lemon',
    15 => 'Light Squash',
    16 => 'Luxury Scent',
    17 => 'Marine Squash',
    18 => 'New Car',
    19 => 'Peach',
    20 => 'Peach & Kiss',
    21 => 'Squash',
    22 => 'White Peach',
    23 => 'White Water',
  ),
) ?>