<?php return array (
  'SubcategoryID' => 1694,
  'SubcategoryName' => 'SoccerBalls',
  'PropertyName' => 'SoccerBallsColor',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Beige',
    1 => 'Black',
    2 => 'Blue',
    3 => 'Blue - Italy',
    4 => 'Brown',
    5 => 'Burgundy',
    6 => 'Clear',
    7 => 'Coral',
    8 => 'Dark Blue',
    9 => 'Dark Green',
    10 => 'Gold',
    11 => 'Green',
    12 => 'Green - Brazil',
    13 => 'Grey',
    14 => 'Ivory',
    15 => 'Khaki',
    16 => 'Light Blue',
    17 => 'Light Green',
    18 => 'Lt. Blue - Argentina',
    19 => 'Metallic',
    20 => 'Multi-Color',
    21 => 'Orange',
    22 => 'Pink',
    23 => 'Platinum',
    24 => 'Purple',
    25 => 'Red',
    26 => 'Red - Manchester',
    27 => 'Scarlet - Barcelona',
    28 => 'Silver',
    29 => 'Teal',
    30 => 'White',
    31 => 'White - Real Madrid',
    32 => 'Yellow',
    33 => 'Yellow - Spain',
  ),
) ?>