<?php return array (
  'SubcategoryID' => 1565,
  'SubcategoryName' => 'ToysActionFigures',
  'PropertyName' => 'ToysActionFiguresCharacter',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Alice in Wonderland',
    1 => 'Assassin\'s Creed',
    2 => 'Astro Boy',
    3 => 'Avatar: The Last Airbender',
    4 => 'Bakugan',
    5 => 'Batman',
    6 => 'G.I. Joe',
    7 => 'Godzilla',
    8 => 'Halo',
    9 => 'Harry Potter',
    10 => 'Iron Man',
    11 => 'Metal Gear Solid',
    12 => 'NBA',
    13 => 'NFL',
    14 => 'Pirates of the Caribbean',
    15 => 'Star Trek',
    16 => 'Star Wars',
    17 => 'Super Mario',
    18 => 'Superman',
    19 => 'The Walking Dead',
    20 => 'Transformers',
    21 => 'Twilight',
    22 => 'WWE',
    23 => 'X-Men',
  ),
) ?>