<?php return array (
  'SubcategoryID' => 1565,
  'SubcategoryName' => 'ToysActionFigures',
  'PropertyName' => 'ToysActionFiguresColor',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Assorted',
    1 => 'Beige',
    2 => 'Black',
    3 => 'Blue',
    4 => 'Brown',
    5 => 'Burgundy',
    6 => 'Clear',
    7 => 'Coral',
    8 => 'Dark Blue',
    9 => 'Dark Green',
    10 => 'Gold',
    11 => 'Green',
    12 => 'Grey',
    13 => 'Ivory',
    14 => 'Khaki',
    15 => 'Light Blue',
    16 => 'Light Green',
    17 => 'Metallic',
    18 => 'Multi-Color',
    19 => 'Orange',
    20 => 'Orange-Five Stars',
    21 => 'Orange-Four Stars',
    22 => 'Orange-One Star',
    23 => 'Orange-Seven Stars',
    24 => 'Orange-Six Stars',
    25 => 'Orange-Three Stars',
    26 => 'Orange-Two Stars',
    27 => 'Pink',
    28 => 'Platinum',
    29 => 'Purple',
    30 => 'Red',
    31 => 'Silver',
    32 => 'Teal',
    33 => 'White',
    34 => 'Yellow',
  ),
) ?>