<?php return array (
  'SubcategoryID' => 1558,
  'SubcategoryName' => 'ShoeProtectantsCleaners',
  'PropertyName' => 'ShoeCleanersColor',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 1,
  'PropertyValueList' => 
  array (
    0 => 'Black',
    1 => 'Blue',
    2 => 'Brown',
    3 => 'Cordovan',
    4 => 'Gray',
    5 => 'Green',
    6 => 'Light Brown',
    7 => 'Neutral',
    8 => 'Pink',
    9 => 'Purple',
    10 => 'Red',
    11 => 'Tan',
    12 => 'USMC Black',
    13 => 'White',
    14 => 'Yellow',
  ),
) ?>