<?php return array (
  'SubcategoryID' => 255,
  'SubcategoryName' => 'AccessoriesCaseRackmount',
  'PropertyName' => 'GroupCaseAccColor',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '50 Fan Screws-M5',
    1 => '50 Screws-#6-32',
    2 => '50 Screws-M3',
    3 => '50 Standoffs-#6-32 (inner) to M3 (outer)',
    4 => '50 Thumbscrews-#6-32',
    5 => 'Black',
    6 => 'Blue',
    7 => 'Brown',
    8 => 'Clear',
    9 => 'Green',
    10 => 'HUE',
    11 => 'HUE+',
    12 => 'HUE+ Extension Kit',
    13 => 'Kit-Assortment',
    14 => 'Low Profile',
    15 => 'Purple',
    16 => 'Red',
    17 => 'RGB',
    18 => 'RGB 330',
    19 => 'RGB 350',
    20 => 'Standard',
    21 => 'UV',
    22 => 'White',
    23 => 'Yellow',
  ),
) ?>