<?php return array (
  'SubcategoryID' => 1539,
  'SubcategoryName' => 'MensSweaters',
  'PropertyName' => 'MensSweatersSize',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 1,
  'IsRequired' => 1,
  'PropertyValueList' => 
  array (
    0 => '1XL',
    1 => '2X-Large',
    2 => '2XL',
    3 => '3X-Large',
    4 => '3XL',
    5 => '4X-Large',
    6 => '4XL',
    7 => '5XL',
    8 => '6XL',
    9 => '7XL',
    10 => '8XL',
    11 => 'L',
    12 => 'Large',
    13 => 'Large/X-Large',
    14 => 'M',
    15 => 'Medium',
    16 => 'One Size (Plus)',
    17 => 'One Size Fits Most',
    18 => 'OSFM',
    19 => 'Small',
    20 => 'Small/Medium',
    21 => 'X-Large',
    22 => 'X-Small',
    23 => 'XL',
    24 => 'XX-Large',
    25 => 'XX-Small',
    26 => 'XXL',
    27 => 'XXS',
    28 => 'XXX-Large',
    29 => 'XXXX-Large',
    30 => 'XXXXX-Large',
  ),
) ?>