<?php return array (
  'SubcategoryID' => 294,
  'SubcategoryName' => 'NetworkPowerline',
  'PropertyName' => 'PLPowerlineSpeeds',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Up to 1.2Gbps',
    1 => 'Up to 100Mbps',
    2 => 'Up to 12Mbps',
    3 => 'Up to 14Mbps',
    4 => 'Up to 150Mbps',
    5 => 'Up to 190Mbps',
    6 => 'Up to 1Gbps',
    7 => 'Up to 2.0Gbps',
    8 => 'Up to 200Mbps',
    9 => 'Up to 210Mbps',
    10 => 'Up to 300Mbps',
    11 => 'Up to 500Mbps',
    12 => 'Up to 50Mbps',
    13 => 'Up to 600Mbps',
    14 => 'Up to 85Mbps',
  ),
) ?>