<?php return array (
  'SubcategoryID' => 1502,
  'SubcategoryName' => 'GolfCompleteSets',
  'PropertyName' => 'GolfSetsFlex',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '3.5',
    1 => '4.0',
    2 => '4.5',
    3 => '5.0',
    4 => '5.5',
    5 => '6.0',
    6 => '6.5',
    7 => '7.0',
    8 => '7.5',
    9 => 'Extra Stiff',
    10 => 'Firm',
    11 => 'Ladies',
    12 => 'Lite',
    13 => 'Regular',
    14 => 'Senior',
    15 => 'Soft Regular',
    16 => 'Stiff',
    17 => 'Uniflex',
  ),
) ?>