<?php return array (
  'SubcategoryID' => 1047,
  'SubcategoryName' => 'DecorationsProps',
  'PropertyName' => 'DecorPropsType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 1,
  'PropertyValueList' => 
  array (
    0 => '3D Stick On',
    1 => 'Animated Props',
    2 => 'Banner',
    3 => 'Body Parts',
    4 => 'Cemetery Props',
    5 => 'Clock',
    6 => 'Confetti',
    7 => 'Decoration',
    8 => 'Decorative Lights',
    9 => 'Door Poster',
    10 => 'Finger Puppets',
    11 => 'Fixture',
    12 => 'Fogging Decoration',
    13 => 'Hanging Prop Decorations',
    14 => 'Indoor Décor',
    15 => 'Inflatable Cooler',
    16 => 'Insta-Theme Decorations',
    17 => 'Kit',
    18 => 'Labels',
    19 => 'Lawn & Yard',
    20 => 'Mold',
    21 => 'Picks',
    22 => 'Pumpkin Carving & Accessories',
    23 => 'Pumpkin Light',
    24 => 'Reproductions',
    25 => 'Scary Creatures',
    26 => 'Signs & Door & Wall Hangings',
    27 => 'Skulls & Skeletons',
    28 => 'Special Effects',
    29 => 'Spiders & Webs',
    30 => 'Spray Streamer',
    31 => 'Tabletop Decoration',
    32 => 'Twirly Whirlys',
    33 => 'Wall Decoration',
    34 => 'Water Fountain',
    35 => 'Webcaster Sticks',
    36 => 'Wind-Up Toys',
  ),
) ?>