<?php return array (
  'SubcategoryID' => 1772,
  'SubcategoryName' => 'BabyGifts',
  'PropertyName' => 'BabyGiftsColor',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Aqua/Brown',
    1 => 'Black',
    2 => 'Black Classique',
    3 => 'Blue',
    4 => 'Camel',
    5 => 'Chocolate',
    6 => 'Classic Rock',
    7 => 'Clear',
    8 => 'Dark Tan',
    9 => 'For the Birds',
    10 => 'Green',
    11 => 'Green Camo',
    12 => 'Green Dots',
    13 => 'Grey',
    14 => 'Jungle Jam',
    15 => 'Leopard Sand',
    16 => 'Liam the Brave',
    17 => 'Mahogany',
    18 => 'Multicolor',
    19 => 'Natural',
    20 => 'Olive',
    21 => 'Orange',
    22 => 'Pink',
    23 => 'Pink Camo',
    24 => 'Pink Center Stripe',
    25 => 'Purple',
    26 => 'Purple/Green',
    27 => 'Red',
    28 => 'Sparkle Silver',
    29 => 'Steel',
    30 => 'Tan',
    31 => 'White',
    32 => 'Yellow',
    33 => 'Zebra Brown',
  ),
) ?>