<?php return array (
  'SubcategoryID' => 561,
  'SubcategoryName' => 'MacDesktops',
  'PropertyName' => 'DTOpticalDriveType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'BD Combo',
    1 => 'BD-ROM',
    2 => 'Blu-ray Burner',
    3 => 'Blu-ray Reader/DVD-Writer',
    4 => 'Blu-ray/HD DVD Player',
    5 => 'CD-ROM',
    6 => 'CD-RW',
    7 => 'DVD Super Multi',
    8 => 'DVD+R/RW',
    9 => 'DVD-R/RW',
    10 => 'DVD-ROM',
    11 => 'DVD/CD-RW Combo',
    12 => 'DVD±R/±RW',
    13 => 'DVD±RW',
    14 => 'HD DVD/Blu-ray Reader/DVD-Writer',
    15 => 'HD-DVD',
    16 => 'No',
    17 => 'SuperDrive',
  ),
) ?>