<?php return array (
  'SubcategoryID' => 3392,
  'SubcategoryName' => 'AirDistributionDuctWorkVentilation',
  'PropertyName' => 'AirDistributionType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Attic Fans',
    1 => 'Confined Space Fans',
    2 => 'Dampers',
    3 => 'Diffusers',
    4 => 'Duct & Duct Pipe',
    5 => 'Duct Fans & Accessories',
    6 => 'Duct Fittings',
    7 => 'Duct Insulation',
    8 => 'Duct, Exhaust & Vacuum Hose Fittings',
    9 => 'Exhaust Fans',
    10 => 'Fan Blades & Propellers',
    11 => 'Flexible Ducts',
    12 => 'Gas Vent Pipe',
    13 => 'Gas Vent Pipe Supports',
    14 => 'Grease Duct & Hi-Temp Access Doors',
    15 => 'Pipe & Tubing',
    16 => 'Pipe Insulation',
    17 => 'Replacement Motors, Heads & Mounts',
    18 => 'Roof Exhausters',
    19 => 'Specialty Fans & Accessories',
    20 => 'Tubeaxial Fans & Accessories',
    21 => 'Ventilation',
  ),
) ?>