<?php return array (
  'SubcategoryID' => 3313,
  'SubcategoryName' => 'NeedleArts',
  'PropertyName' => 'NeedleArtType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 1,
  'PropertyValueList' => 
  array (
    0 => 'Counted Cross Stitch',
    1 => 'Crewel Kits',
    2 => 'Crochet Hooks',
    3 => 'Crochet Thread & Floss',
    4 => 'Embroidery Thread',
    5 => 'Felt Applique',
    6 => 'Hoops & Frames',
    7 => 'Knitting Needles',
    8 => 'Latch Hook Accessories & Kits',
    9 => 'Locker Hooking',
    10 => 'Looms & Knitters',
    11 => 'Needle Felting',
    12 => 'Needle Point',
    13 => 'Notions',
    14 => 'Other Accessories',
    15 => 'Patterns & Kits',
    16 => 'Plastic Canvas',
    17 => 'Punch Needle',
    18 => 'Rug Punch Hooking',
    19 => 'Stamped Cross Stitch',
    20 => 'Yarn',
  ),
) ?>