<?php return array (
  'SubcategoryID' => 3390,
  'SubcategoryName' => 'Blowers',
  'PropertyName' => 'BlowerType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Air Curtains',
    1 => 'Backward Incline Blowers',
    2 => 'Backward Inclined Blowers',
    3 => 'Belt Drive Double Inlet Forward Curve Blowers',
    4 => 'Blower Accessories',
    5 => 'Centrifugal Blowers',
    6 => 'Confined Space Blowers',
    7 => 'Corrosion-Resistant Blowers',
    8 => 'Crossflow & Tangential Blowers',
    9 => 'Direct Drive Blower Wheels',
    10 => 'Draft Inducer Blowers',
    11 => 'Forward Cuver Blowers',
    12 => 'Heat Slingers',
    13 => 'High Pressure Radial Blade Blowers',
    14 => 'Plenum Fans',
    15 => 'Plug Fans',
    16 => 'Portable Blowers',
    17 => 'Radial Blade Blowers',
    18 => 'Spark Resistant Blowers',
  ),
) ?>