<?php return array (
  'SubcategoryID' => 336,
  'SubcategoryName' => 'HomeGadgets',
  'PropertyName' => 'AVColor',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Black',
    1 => 'Blue',
    2 => 'Clay',
    3 => 'Clear',
    4 => 'Gray',
    5 => 'Green',
    6 => 'Grey',
    7 => 'Hurricanes Mango',
    8 => 'Multi',
    9 => 'Orange',
    10 => 'Pink',
    11 => 'Purple',
    12 => 'Red',
    13 => 'Silver',
    14 => 'Walnut',
    15 => 'White',
    16 => 'WILLIAM & MARY TRIBE TC',
    17 => 'Yellow',
  ),
) ?>