<?php return array (
  'SubcategoryID' => 1512,
  'SubcategoryName' => 'Cufflinks',
  'PropertyName' => 'CufflinkMaterial',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 1,
  'PropertyValueList' => 
  array (
    0 => 'Base',
    1 => 'Brass',
    2 => 'Copper',
    3 => 'Crystal',
    4 => 'Glass',
    5 => 'Gold-Plated',
    6 => 'Gunmetal',
    7 => 'Plastic',
    8 => 'PVD',
    9 => 'Rhodium',
    10 => 'Rhodium Plated',
    11 => 'Rhodium Plated Base Metal',
    12 => 'Silver',
    13 => 'Silver Plated',
    14 => 'Silver Plated Base',
    15 => 'Stainless Steel',
    16 => 'Sterling Silver',
    17 => 'Titanium',
    18 => 'Token Metal',
    19 => 'White Gold',
    20 => 'Yellow Gold',
  ),
) ?>