<?php return array (
  'SubcategoryID' => 71,
  'SubcategoryName' => 'CDDVDRRWMedia',
  'PropertyName' => 'DISCType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'BD-R',
    1 => 'BD-R DL',
    2 => 'BD-R LTH',
    3 => 'BD-RE',
    4 => 'BD-RE DL',
    5 => 'BD-XL',
    6 => 'CD-R',
    7 => 'CD-RW',
    8 => 'Dataplay',
    9 => 'DVD+R',
    10 => 'DVD+R DL',
    11 => 'DVD+RW',
    12 => 'DVD-R',
    13 => 'DVD-R DL',
    14 => 'DVD-RAM',
    15 => 'DVD-RW',
    16 => 'HD DVD-R',
    17 => 'HD DVD-R DL',
    18 => 'M-DISC',
    19 => 'Mini CD-R',
    20 => 'Mini DVD+RW',
    21 => 'Mini DVD-R',
    22 => 'Mini DVD-R DL',
    23 => 'Mini DVD-RAM',
    24 => 'Mini DVD-RW',
    25 => 'Mixed Pack',
  ),
) ?>