<?php return array (
  'SubcategoryID' => 3286,
  'SubcategoryName' => 'OSGlueAdhesives',
  'PropertyName' => 'GlueAdhesivesType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 1,
  'PropertyValueList' => 
  array (
    0 => 'Adhesive Kits',
    1 => 'Adhesive Primers & Activators',
    2 => 'Adhesive Remover',
    3 => 'Construction Adhesives',
    4 => 'Contact Cement',
    5 => 'Dispensers',
    6 => 'Envelope Moisteners',
    7 => 'Epoxy',
    8 => 'Glue',
    9 => 'Glue Guns & Accessories',
    10 => 'Glue Sticks',
    11 => 'Hot Melt Adhesives',
    12 => 'Mounting Putty',
    13 => 'Retaining Compounds',
    14 => 'Roller Adhesives',
    15 => 'Rubber Cement',
    16 => 'Spray Adhesive',
    17 => 'Super Glue',
    18 => 'White Glue',
    19 => 'Wood Glue',
  ),
) ?>