<?php return array (
  'SubcategoryID' => 1009,
  'SubcategoryName' => 'GeneralCraftsAccessories',
  'PropertyName' => 'GeneralCraftsAccessoryType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Accessories & Tools',
    1 => 'Bags',
    2 => 'Clay Pot',
    3 => 'Cork',
    4 => 'Craft Bags & Sticks',
    5 => 'Craft Kits',
    6 => 'Cutting Tools',
    7 => 'Decorations & Accents',
    8 => 'Door Hangers',
    9 => 'Feathers',
    10 => 'Foam',
    11 => 'Glitter',
    12 => 'Kits',
    13 => 'Noodles & Rice',
    14 => 'Other Accessories',
    15 => 'Personalizable Items',
    16 => 'Pins & Magnets',
    17 => 'Plastic Lacing & Lanyards',
    18 => 'Pom Poms',
    19 => 'Shells & Stones',
    20 => 'Stems & Pipe Cleaners',
    21 => 'Styrofoam',
    22 => 'T-Shirts',
    23 => 'Washi Tape',
    24 => 'Wiggle Eyes',
    25 => 'Wire, Rope & String',
  ),
) ?>