<?php return array (
  'SubcategoryID' => 3325,
  'SubcategoryName' => 'DigitalSignageAccessories',
  'PropertyName' => 'DigiSignAccBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'AG Neovo Technology',
    1 => 'Avnu Digital',
    2 => 'Cilutions',
    3 => 'E-Data Tech',
    4 => 'Elo',
    5 => 'Ergotron',
    6 => 'HP',
    7 => 'IAdea',
    8 => 'InFocus',
    9 => 'LG',
    10 => 'NEC Display Solutions',
    11 => 'Panasonic',
    12 => 'Peerless',
    13 => 'Philips',
    14 => 'Planar',
    15 => 'Premier Mounts',
    16 => 'PROMETHEAN',
    17 => 'Samsung',
    18 => 'Sharp',
    19 => 'SIGNAGELIVE',
    20 => 'V7',
    21 => 'ViewSonic',
  ),
) ?>