<?php return array (
  'SubcategoryID' => 2851,
  'SubcategoryName' => 'HISemiFlush',
  'PropertyName' => 'HISemiflushCollection',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Alexander',
    1 => 'Aquarius',
    2 => 'Argon',
    3 => 'Ark',
    4 => 'Atom',
    5 => 'Beta',
    6 => 'Bling',
    7 => 'Cobalt',
    8 => 'Comet',
    9 => 'Cristal de Lisbon',
    10 => 'Elba',
    11 => 'Galeana',
    12 => 'Helius',
    13 => 'Kane',
    14 => 'Kristal',
    15 => 'Krome',
    16 => 'Legato',
    17 => 'Luna',
    18 => 'Mirage',
    19 => 'Nebula',
    20 => 'Nido',
    21 => 'Noya',
    22 => 'Phoebe',
    23 => 'Quarry',
    24 => 'Safari',
    25 => 'Saturn',
    26 => 'Sol',
    27 => 'Tara',
    28 => 'Titanium',
    29 => 'Triton',
    30 => 'Venus',
    31 => 'Versahl',
    32 => 'Vetraio',
    33 => 'Viper',
    34 => 'Vision',
    35 => 'Vitalia',
  ),
) ?>