<?php return array (
  'SubcategoryID' => 2851,
  'SubcategoryName' => 'HISemiFlush',
  'PropertyName' => 'HISemiflushfeatures',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '3 Way',
    1 => 'Ambient Lighting',
    2 => 'Battery Operated',
    3 => 'Dimmable',
    4 => 'Down Lighting',
    5 => 'Dusk-to-Dawn',
    6 => 'Eco-Friendly',
    7 => 'Energy Saver/Energy Efficient',
    8 => 'Fluorescent',
    9 => 'Indoor',
    10 => 'Innovative',
    11 => 'Interconnected',
    12 => 'LED',
    13 => 'Motion Sensor',
    14 => 'Photo Sensor',
    15 => 'Remote Control',
    16 => 'Solar',
    17 => 'Touch On/Off',
    18 => 'UL Rated',
    19 => 'Up Lighting',
    20 => 'Wet Location',
  ),
) ?>