<?php return array (
  'SubcategoryID' => 889,
  'SubcategoryName' => 'JewelryBeading',
  'PropertyName' => 'JewelryBeadType',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Beadelle Crystal',
    1 => 'Beading Kits',
    2 => 'Cabochons',
    3 => 'Chatons',
    4 => 'Cinnabar Beads',
    5 => 'Cultured Sea Glass',
    6 => 'Czech Crystal Beads',
    7 => 'Czech Glass Beads',
    8 => 'Czech Seed Beads',
    9 => 'European Style Beads',
    10 => 'Gemstone Beads',
    11 => 'Lampwork Glass',
    12 => 'Metal Beads',
    13 => 'Miyuki Beads',
    14 => 'Pearls',
    15 => 'Plastic, Lucite Beads',
    16 => 'Toho Beads',
    17 => 'Wood Beads',
  ),
) ?>