<?php return array (
  'SubcategoryID' => 784,
  'SubcategoryName' => 'DSLR',
  'PropertyName' => 'DSLRImageProcessor',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'BIONZ',
    1 => 'BIONZ X',
    2 => 'DIGIC 4',
    3 => 'DIGIC 4+',
    4 => 'DIGIC 5',
    5 => 'DIGIC 5+',
    6 => 'DIGIC 6',
    7 => 'DIGIC 6+',
    8 => 'DIGIC II',
    9 => 'DIGIC III',
    10 => 'Dual DIGIC 4',
    11 => 'Dual DIGIC 6',
    12 => 'Dual DIGIC III',
    13 => 'EXPEED',
    14 => 'EXPEED 3',
    15 => 'EXPEED 5A',
    16 => 'EXR Processor II',
    17 => 'PRIME II',
    18 => 'PRIME III',
    19 => 'TruePic III',
    20 => 'TruePic TURBO',
    21 => 'TruePic V',
    22 => 'TruePic VI',
    23 => 'TruePic VII',
    24 => 'TruePic VIII',
    25 => 'Venus Engine HD',
  ),
) ?>