<?php return array (
  'SubcategoryID' => 784,
  'SubcategoryName' => 'DSLR',
  'PropertyName' => 'DSLRBodyColor',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Black',
    1 => 'Blue',
    2 => 'Cocoa Brown',
    3 => 'Gold',
    4 => 'Gray',
    5 => 'Green',
    6 => 'Lilac',
    7 => 'Metal Brown',
    8 => 'Metal Green',
    9 => 'Metal Navy',
    10 => 'Mint',
    11 => 'No',
    12 => 'Olive Green',
    13 => 'Orange',
    14 => 'Pink',
    15 => 'Purple',
    16 => 'Red',
    17 => 'Sand Beige',
    18 => 'Silver',
    19 => 'Violet',
    20 => 'White',
    21 => 'Yellow',
  ),
) ?>