<?php return array (
  'SubcategoryID' => 1513,
  'SubcategoryName' => 'Buckles',
  'PropertyName' => 'BucklesStyle',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Alcohol',
    1 => 'Animals',
    2 => 'Astrology',
    3 => 'Cars & Trucks',
    4 => 'Fantasy & Renaissance',
    5 => 'Gambling',
    6 => 'Luck',
    7 => 'Military & Weapons',
    8 => 'Motorcycle',
    9 => 'Music',
    10 => 'Novelty',
    11 => 'Plain',
    12 => 'Religious',
    13 => 'Southern',
    14 => 'Sports',
    15 => 'Superheroes & Cartoons',
    16 => 'TV & Movies',
    17 => 'Vintage & Retro',
    18 => 'Women\'s',
  ),
) ?>