<?php return array (
  'SubcategoryID' => 551,
  'SubcategoryName' => 'MacMemory',
  'PropertyName' => 'MacMEMBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'A-DATA',
    1 => 'AddOn',
    2 => 'AMC Optics',
    3 => 'Apple',
    4 => 'Axiom',
    5 => 'BUFFALO',
    6 => 'Centon',
    7 => 'CORSAIR',
    8 => 'Crucial',
    9 => 'EDGE',
    10 => 'G.SKILL',
    11 => 'GEIL',
    12 => 'iRam',
    13 => 'Kingston',
    14 => 'Laintek',
    15 => 'Mushkin Enhanced',
    16 => 'Nemix Ram',
    17 => 'OCZ',
    18 => 'Patriot Memory',
    19 => 'PNY',
    20 => 'SimpleTech',
    21 => 'SuperTalent',
    22 => 'Team',
    23 => 'Techworks by Buffalo',
    24 => 'Transcend',
    25 => 'V-Color',
    26 => 'Visiontek',
    27 => 'WINTEC',
  ),
) ?>