<?php return array (
  'SubcategoryID' => 2857,
  'SubcategoryName' => 'WaterSportsActivewearAccessories',
  'PropertyName' => 'WSActivewearSizeDimensions',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '11',
    1 => '13',
    2 => '15',
    3 => '2X-Large',
    4 => '3',
    5 => '3X-Large',
    6 => '4X-Large',
    7 => '5',
    8 => '7',
    9 => '9',
    10 => 'Large',
    11 => 'Medium',
    12 => 'Small',
    13 => 'X-Large',
    14 => 'X-Small',
  ),
) ?>