<?php return array (
  'SubcategoryID' => 3404,
  'SubcategoryName' => 'JanitorialIndoorMaintenance',
  'PropertyName' => 'GlobalBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '3M',
    1 => 'Apex Tool Group, LLC',
    2 => 'Baldwin',
    3 => 'Black & Decker',
    4 => 'C2G',
    5 => 'DeWalt',
    6 => 'Diablo',
    7 => 'Dremel',
    8 => 'Freud',
    9 => 'Gardner Bender',
    10 => 'Gone Fishing',
    11 => 'Great Neck',
    12 => 'Hitachi Power Tools',
    13 => 'HitLights',
    14 => 'Honeywell',
    15 => 'Humble Bee',
    16 => 'Hunter',
    17 => 'Johnson Level and Tool',
    18 => 'King',
    19 => 'Klein Tools',
    20 => 'leatherman',
    21 => 'LG',
    22 => 'Makita',
    23 => 'MICHIGAN',
    24 => 'Olympia Tools',
    25 => 'Platinum Tools',
    26 => 'Rockwell',
    27 => 'Rosewill',
    28 => 'Sainty',
    29 => 'Stalwart',
    30 => 'Stanley',
    31 => 'StoppClipp',
    32 => 'TEKTON',
    33 => 'Texsport',
    34 => 'Trademark Fine Art',
    35 => 'Westbrass',
  ),
) ?>