<?php return array (
  'SubcategoryID' => 3404,
  'SubcategoryName' => 'JanitorialIndoorMaintenance',
  'PropertyName' => 'JanitorialMaintenanceType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 1,
  'PropertyValueList' => 
  array (
    0 => 'Adhesive, Graffiti & Rust Removers',
    1 => 'All-Purpose Cleaners & Degreasers',
    2 => 'Bathroom Cleaners',
    3 => 'Bleach',
    4 => 'Brooms, Brushes & Dusters',
    5 => 'Buckets, Pails & Wringers',
    6 => 'Carpet, Floor & Upholstry Cleaners',
    7 => 'Detergents',
    8 => 'Drain Cleaners & Openers',
    9 => 'Dust Mops, Dusters & Cleaning Pads',
    10 => 'Floor Signs',
    11 => 'Glass Cleaners',
    12 => 'Grill, Range & Oven Cleaners',
    13 => 'Handles & Poles',
    14 => 'Janitorial & Cleaning Carts',
    15 => 'Laundry Products',
    16 => 'Leak Detector',
    17 => 'Leak Diverter',
    18 => 'Maintenance Furniture',
    19 => 'Metal, Stone & Furniture Polishes & Cleaners',
    20 => 'Mop & Broom Wall Hooks',
    21 => 'Mops',
    22 => 'Odor Control',
    23 => 'Paper Products',
    24 => 'Portion Control System Checmicals',
    25 => 'Pre-Measured Chemical Dispensers',
    26 => 'Rags & Wipes',
    27 => 'Recycling Equipment',
    28 => 'Specialty Cleaners',
    29 => 'Squeegees & Window Washers',
    30 => 'Toilet, Urinal, Blocks & Screens',
    31 => 'Towels & Tissues',
    32 => 'Trash Cans, Bags & Compactors',
    33 => 'Vehicle & Pressure Washing Cleaners',
  ),
) ?>