<?php return array (
  'SubcategoryID' => 1569,
  'SubcategoryName' => 'ToysDollsAccessories',
  'PropertyName' => 'ToysDollsTheme',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Blover',
    1 => 'Cherry Bomb',
    2 => 'Ethnic',
    3 => 'Fashion & Celebrity',
    4 => 'Fume-shroom',
    5 => 'Jalapeno',
    6 => 'Kernel-pult',
    7 => 'Marigold',
    8 => 'Melon-pult',
    9 => 'Peashooter',
    10 => 'Potato Mine',
    11 => 'Princesses & Fairies',
    12 => 'Purple Zombie',
    13 => 'Snow Pea',
    14 => 'Squash',
    15 => 'Sun-shroom',
    16 => 'Sunflower',
    17 => 'Wall-nut',
    18 => 'Winter Melon',
    19 => 'Zombie',
  ),
) ?>