<?php return array (
  'SubcategoryID' => 2076,
  'SubcategoryName' => 'HIBathFansAccessories',
  'PropertyName' => 'HIBathFansAccFinish',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Bronze',
    1 => 'Brushed Nickel',
    2 => 'Chrome / Polished Brass',
    3 => 'Corsican Gold',
    4 => 'Designer White',
    5 => 'Galvanized',
    6 => 'Oil Rubbed Bronze',
    7 => 'Pewter',
    8 => 'Rustic Gold',
    9 => 'Spot Resist Brushed Nickel',
    10 => 'Stainless Steel',
    11 => 'Textured White',
    12 => 'White',
    13 => 'Wrought Iron',
  ),
) ?>