<?php return array (
  'SubcategoryID' => 613,
  'SubcategoryName' => 'CellPhoneCables',
  'PropertyName' => 'CellphoneACCChargerType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '30-Pin Cable',
    1 => 'AC Adapter',
    2 => 'Adapter',
    3 => 'All-In-One Cable',
    4 => 'Auto Adapter',
    5 => 'Auto/AC Adapter',
    6 => 'Auto/Airline/AC Adapter',
    7 => 'Aux Cable',
    8 => 'Battery Adapter',
    9 => 'Cable Kit',
    10 => 'Car Charger',
    11 => 'Charger Kit',
    12 => 'DC Converter',
    13 => 'Desktop Charger',
    14 => 'HDMI Cable',
    15 => 'Lightning Cable',
    16 => 'Micro USB Cable',
    17 => 'Mini USB Cable',
    18 => 'Solar Adapter',
    19 => 'USB Cable',
    20 => 'Wall Charger',
  ),
) ?>