<?php return array (
  'SubcategoryID' => 1046,
  'SubcategoryName' => 'CostumeAccessories',
  'PropertyName' => 'CostumeAccTheme',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Angels & Devils',
    1 => 'Animals & Insects',
    2 => 'Around the World',
    3 => 'Biblical',
    4 => 'Careers & Occupations',
    5 => 'Classic',
    6 => 'Couples',
    7 => 'Easter Bunny Costumes',
    8 => 'Fairytale & Storybook',
    9 => 'Food & Beverages',
    10 => 'Historical',
    11 => 'Holiday',
    12 => 'Horror & Gothic',
    13 => 'Humorous',
    14 => 'Pirates',
    15 => 'Princesses & Divas',
    16 => 'Renaissance & Medieval',
    17 => 'Santa Suits',
    18 => 'Seasonal & Holiday',
    19 => 'Sexy',
    20 => 'Space & Aliens',
    21 => 'Steampunk',
    22 => 'Superheroes',
    23 => 'TV & Movies',
    24 => 'Witches & Monsters',
  ),
) ?>