<?php return array (
  'SubcategoryID' => 1046,
  'SubcategoryName' => 'CostumeAccessories',
  'PropertyName' => 'CostumeAccOccasion',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '4th of July',
    1 => 'Baby Shower',
    2 => 'Bachelorette Party',
    3 => 'Birthday',
    4 => 'Bridal Shower',
    5 => 'Christmas',
    6 => 'Cinco de Mayo',
    7 => 'Easter',
    8 => 'Graduation',
    9 => 'Halloween',
    10 => 'Hanukkah',
    11 => 'Mardi Gras',
    12 => 'Masquerade',
    13 => 'New Year\'s',
    14 => 'St. Patrick\'s Day',
    15 => 'Thanksgiving',
    16 => 'Valentine\'s Day',
    17 => 'Wedding',
  ),
) ?>