<?php return array (
  'SubcategoryID' => 1046,
  'SubcategoryName' => 'CostumeAccessories',
  'PropertyName' => 'CostumeAccType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 1,
  'PropertyValueList' => 
  array (
    0 => 'Badges',
    1 => 'Belts & Suspenders',
    2 => 'Blocks',
    3 => 'Boas, Scarves & Stoles',
    4 => 'Boot Covers',
    5 => 'Bracelets, Armbands & Wristbands',
    6 => 'Brooches & Pins',
    7 => 'Capes, Coats & Vests',
    8 => 'Claws & Fingernails',
    9 => 'Clown',
    10 => 'Costume Kits',
    11 => 'Costume Props',
    12 => 'Eyewear & Glasses',
    13 => 'Fangs & Teeth',
    14 => 'Fans',
    15 => 'Gloves & Hands',
    16 => 'Hair Color & Accessories',
    17 => 'Hats & Headpieces',
    18 => 'Instruments & Microphones',
    19 => 'Jewelry',
    20 => 'Make-up & Tattoos',
    21 => 'Masks',
    22 => 'Petticoats',
    23 => 'Prosthetics',
    24 => 'Purses & Handbags',
    25 => 'Shirts & Tops',
    26 => 'Shoes, Sandals & Boots',
    27 => 'Skirts',
    28 => 'Stockings, Tights & Socks',
    29 => 'Tails, Ears & Noses',
    30 => 'Ties, Canes & Sashes',
    31 => 'Treat Pails, Bags & Baskets',
    32 => 'Undergarments',
    33 => 'Wands, Scepters & Staffs',
    34 => 'Weapons & Armor',
    35 => 'Wigs & Facial Hair',
    36 => 'Wings',
  ),
) ?>