<?php return array (
  'SubcategoryID' => 1046,
  'SubcategoryName' => 'CostumeAccessories',
  'PropertyName' => 'SubcatCostumeAccLink',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Aliens',
    1 => 'Antiquity',
    2 => 'Apparel',
    3 => 'Avatar',
    4 => 'Avengers',
    5 => 'Batman',
    6 => 'Civil War',
    7 => 'Colonial',
    8 => 'Fairy Tale',
    9 => 'Funny',
    10 => 'Halo',
    11 => 'Headwear',
    12 => 'Human',
    13 => 'Lord of the Rings',
    14 => 'Mario',
    15 => 'Medieval & Renaissance',
    16 => 'Monster High',
    17 => 'Occupations',
    18 => 'Power Rangers',
    19 => 'Princess/Diva',
    20 => 'Sexy',
    21 => 'Spiderman',
    22 => 'Star Trek',
    23 => 'Star Wars',
    24 => 'Tools',
    25 => 'Weapons',
  ),
) ?>