<?php return array (
  'SubcategoryID' => 2787,
  'SubcategoryName' => 'Shoes',
  'PropertyName' => 'ShoesType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 1,
  'PropertyValueList' => 
  array (
    0 => 'Athletic Sneakers',
    1 => 'Boat Shoes',
    2 => 'Boots',
    3 => 'Casual',
    4 => 'Clogs',
    5 => 'Cowboy/Western',
    6 => 'Dress',
    7 => 'Espadrilles',
    8 => 'Flats',
    9 => 'Hiking, Trail',
    10 => 'Indoor',
    11 => 'Loafers & Oxfords',
    12 => 'Moccasins',
    13 => 'Protective Footwear',
    14 => 'Pumps',
    15 => 'Sandals & Flip-Flops',
    16 => 'Slides & Slip-Ons',
    17 => 'Slippers & House Shoes',
    18 => 'Water Shoes',
    19 => 'Wedding & Formal',
    20 => 'Work',
  ),
) ?>