<?php return array (
  'SubcategoryID' => 2010,
  'SubcategoryName' => 'PedestalBasin',
  'PropertyName' => 'PedestalBasinFinish',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Almond',
    1 => 'Balsa',
    2 => 'Biscuit',
    3 => 'Bisque',
    4 => 'Black',
    5 => 'Bone',
    6 => 'Cashmere',
    7 => 'Cotton',
    8 => 'Dune',
    9 => 'Ice Gray',
    10 => 'Ice Grey',
    11 => 'Innocent Blush',
    12 => 'Linen',
    13 => 'Mexican Sand',
    14 => 'Oil-rubbed Bronze',
    15 => 'Sandbar',
    16 => 'Skylight',
    17 => 'Stainless Steel',
    18 => 'Sunlight',
    19 => 'Tea Green',
    20 => 'Thunder Grey',
    21 => 'White',
    22 => 'White Alpine',
  ),
) ?>