<?php return array (
  'SubcategoryID' => 1559,
  'SubcategoryName' => 'Luggage',
  'PropertyName' => 'LuggageBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Accessory Innovations',
    1 => 'Aleon',
    2 => 'Andare',
    3 => 'Antec',
    4 => 'Ben Sherman Luggage',
    5 => 'Carbon Sesto',
    6 => 'Case Logic',
    7 => 'Concept One by USPA Accessories',
    8 => 'DENY Designs',
    9 => 'Goodhope Bags',
    10 => 'Lily Bloom',
    11 => 'Lowepro - Wynit',
    12 => 'Pacific Coast',
    13 => 'Perry Mackin',
    14 => 'Piel Leather',
    15 => 'Traveler\'s Choice',
    16 => 'Tutto',
    17 => 'Victorinox',
    18 => 'Visconti',
  ),
) ?>