<?php return array (
  'SubcategoryID' => 748,
  'SubcategoryName' => 'BroomStickVacuums',
  'PropertyName' => 'FloorCareColor',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '2-Tone',
    1 => 'Black',
    2 => 'Blue',
    3 => 'Brown',
    4 => 'Chrome',
    5 => 'Fushia',
    6 => 'Gold',
    7 => 'Gray',
    8 => 'Green',
    9 => 'Orange',
    10 => 'Pearl',
    11 => 'Pink',
    12 => 'Powder White',
    13 => 'Purple',
    14 => 'Red',
    15 => 'Red/Gray',
    16 => 'Silver',
    17 => 'Teal',
    18 => 'Titanium',
    19 => 'White',
    20 => 'Yellow',
  ),
) ?>