<?php return array (
  'SubcategoryID' => 639,
  'SubcategoryName' => 'CordlessPhones',
  'PropertyName' => 'CordlessPhoneBodyColor',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Beige',
    1 => 'Black',
    2 => 'Black/Sliver',
    3 => 'Black/White',
    4 => 'Black/Yellow',
    5 => 'Blue',
    6 => 'Blue/White',
    7 => 'Champagne',
    8 => 'Gold',
    9 => 'Gray',
    10 => 'Orange',
    11 => 'Platinum',
    12 => 'Red',
    13 => 'Silver',
    14 => 'Titanium',
    15 => 'Violet',
    16 => 'White',
  ),
) ?>