<?php return array (
  'SubcategoryID' => 2594,
  'SubcategoryName' => 'SGAirsoftGuns',
  'PropertyName' => 'SGAirGunsColor',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'As Shown',
    1 => 'Beige',
    2 => 'Black',
    3 => 'Blue',
    4 => 'Bronze',
    5 => 'Brown',
    6 => 'Burgundy',
    7 => 'Clear',
    8 => 'Copper',
    9 => 'Coral',
    10 => 'Cream',
    11 => 'Dark Blue',
    12 => 'Dark Brown Wood',
    13 => 'Dark Green',
    14 => 'Gold',
    15 => 'Green',
    16 => 'Grey',
    17 => 'Ivory',
    18 => 'Khaki',
    19 => 'Light Blue',
    20 => 'Light Green',
    21 => 'Medium Brown Wood',
    22 => 'Metallic',
    23 => 'Multi',
    24 => 'Multi-Color',
    25 => 'Multicolor',
    26 => 'Natural/Light Brown Wood',
    27 => 'Orange',
    28 => 'Pink',
    29 => 'Platinum',
    30 => 'Purple',
    31 => 'Red',
    32 => 'Silver',
    33 => 'Teal',
    34 => 'White',
    35 => 'Yellow',
  ),
) ?>