<?php return array (
  'SubcategoryID' => 514,
  'SubcategoryName' => 'MonitorsTouchscreen',
  'PropertyName' => 'MonitorDisplayTouchscreenType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '4-wire Resistive',
    1 => '5-wire Resistive',
    2 => 'AccuTouch',
    3 => 'Acoustic Pulse',
    4 => 'Capacitive',
    5 => 'CarrollTouch',
    6 => 'ChassisTouch',
    7 => 'Dispersive Touch',
    8 => 'Infrared',
    9 => 'Infrared Blocking Detection',
    10 => 'IntelliTouch',
    11 => 'IR touch',
    12 => 'iTouch',
    13 => 'Mastouch Projected Capacitive',
    14 => 'MicroTouch',
    15 => 'No',
    16 => 'Optical',
    17 => 'Projected Capacitive',
    18 => 'Resistive',
    19 => 'SecureTouch',
    20 => 'Surface Acoustic Wave',
    21 => 'Surface Capacitive',
  ),
) ?>