<?php return array (
  'SubcategoryID' => 3475,
  'SubcategoryName' => 'ToughCameras',
  'PropertyName' => 'ACColor',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 1,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Amber',
    1 => 'Black',
    2 => 'Blue',
    3 => 'Camo',
    4 => 'Clear',
    5 => 'Gold',
    6 => 'Graphite',
    7 => 'Gray',
    8 => 'Green',
    9 => 'Gunmetal',
    10 => 'Lime',
    11 => 'Orange',
    12 => 'Pink',
    13 => 'Purple',
    14 => 'Red',
    15 => 'Silver',
    16 => 'White',
    17 => 'Yellow',
  ),
) ?>