<?php return array (
  'SubcategoryID' => 2843,
  'SubcategoryName' => 'HLFloorLamps',
  'PropertyName' => 'HIFloorlampsfeatures',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '3 Way',
    1 => 'Battery Operated',
    2 => 'Dimmable',
    3 => 'Dusk-to-Dawn',
    4 => 'Eco-Friendly',
    5 => 'Energy Saver/Energy Efficient',
    6 => 'Fluorescent',
    7 => 'Foot Switch',
    8 => 'Height Adjustable',
    9 => 'Innovative',
    10 => 'Interconnected',
    11 => 'LED',
    12 => 'Motion Sensor',
    13 => 'Photo Sensor',
    14 => 'Remote Control',
    15 => 'Solar',
    16 => 'Touch On/Off',
    17 => 'UL Rated',
    18 => 'Wet Location',
  ),
) ?>