<?php return array (
  'SubcategoryID' => 3086,
  'SubcategoryName' => 'iPodAccessoriesOEM',
  'PropertyName' => 'ACCEMP3Type',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Battery',
    1 => 'Bluetooth Receiver',
    2 => 'Bluetooth Transmitter',
    3 => 'Bracket',
    4 => 'Cable',
    5 => 'Card Adapter',
    6 => 'Case',
    7 => 'Cassette Adapter',
    8 => 'Charger',
    9 => 'Dock',
    10 => 'FM Transmitters',
    11 => 'Headphones',
    12 => 'Kit',
    13 => 'Micro Component System',
    14 => 'Microphones',
    15 => 'Others',
    16 => 'Protector',
    17 => 'Remote Control',
    18 => 'Skin',
    19 => 'Speaker Grill',
    20 => 'Speakers',
    21 => 'Stylus',
    22 => 'Wireless',
  ),
) ?>