<?php return array (
  'SubcategoryID' => 3395,
  'SubcategoryName' => 'CommercialKitchenAppliances',
  'PropertyName' => 'CommercialKitchenType',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 1,
  'PropertyValueList' => 
  array (
    0 => 'Beer Dispensers',
    1 => 'Beverage Equipment',
    2 => 'Cappuccino/Espresso Machines',
    3 => 'Commercial Coffee Makers',
    4 => 'Commercial Ice Machines',
    5 => 'Commercial Microwave Ovens',
    6 => 'Commercial Restaurant Ranges',
    7 => 'Commercial Rice Cookers',
    8 => 'Convection Ovens',
    9 => 'Electric Countertop Fryers',
    10 => 'Electric Countertop Griddles',
    11 => 'Gas Floor Fryers',
    12 => 'Heavy Duty Reach-In Refrigeration',
    13 => 'Sandwich/Salad Prep Refrigerators',
    14 => 'Undercounter Refrigeration',
    15 => 'Walk In Freezers',
  ),
) ?>