<?php return array (
  'SubcategoryID' => 2862,
  'SubcategoryName' => 'HILandscapeLighting',
  'PropertyName' => 'HILandscapelightingStyle',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Asian',
    1 => 'Childrens',
    2 => 'Coastal',
    3 => 'Contemporary',
    4 => 'Cottage',
    5 => 'Country',
    6 => 'CountryFrench',
    7 => 'Industrial',
    8 => 'Lodge',
    9 => 'MidCentury',
    10 => 'Mission',
    11 => 'Moroccan',
    12 => 'Nautical',
    13 => 'Novelty',
    14 => 'OldWorld',
    15 => 'Retro',
    16 => 'Rustic',
    17 => 'Shaker',
    18 => 'Southwestern',
    19 => 'SpanishColonial',
    20 => 'Sports',
    21 => 'Tiffany',
    22 => 'Traditional',
    23 => 'Transitional',
    24 => 'Tropical',
    25 => 'Tuscan',
    26 => 'Vintage',
  ),
) ?>