<?php return array (
  'SubcategoryID' => 2862,
  'SubcategoryName' => 'HILandscapeLighting',
  'PropertyName' => 'HILandscapelightingBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'ALLSOP',
    1 => 'Brinkmann',
    2 => 'Coleman Cable',
    3 => 'Malibu',
    4 => 'Maxsa',
    5 => 'Nature Power',
    6 => 'Northern International',
    7 => 'Northwest',
    8 => 'Paradise',
    9 => 'Pure Garden',
    10 => 'Rosewill',
    11 => 'Sparkle Magic',
    12 => 'Sunforce',
    13 => 'Viatek',
    14 => 'Westinghouse',
  ),
) ?>