<?php return array (
  'SubcategoryID' => 2862,
  'SubcategoryName' => 'HILandscapeLighting',
  'PropertyName' => 'HILandscapelightingMaterial',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Acrylic',
    1 => 'Alabaster',
    2 => 'Aluminium',
    3 => 'Bamboo',
    4 => 'Beaded',
    5 => 'Ceramic',
    6 => 'Crystal',
    7 => 'EtchedGlass',
    8 => 'Fabric',
    9 => 'FauxLeather',
    10 => 'FossilStone',
    11 => 'Glass',
    12 => 'Iron',
    13 => 'Leather',
    14 => 'Linen',
    15 => 'Metal',
    16 => 'Mica',
    17 => 'Mosaic',
    18 => 'Paper',
    19 => 'Plastic',
    20 => 'Rattan',
    21 => 'ReclaimedWood',
    22 => 'Resin',
    23 => 'Silk',
    24 => 'Slate',
    25 => 'stainless steel',
    26 => 'Stone',
    27 => 'TiffanyGlass',
    28 => 'Wicker',
    29 => 'Wood',
  ),
) ?>