<?php return array (
  'SubcategoryID' => 893,
  'SubcategoryName' => 'Aromatherapy',
  'PropertyName' => 'AromatherapyFragrances',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Ambery',
    1 => 'Aromatic',
    2 => 'Bright Floral',
    3 => 'Chypre',
    4 => 'Citrus',
    5 => 'Citrus/Fruity',
    6 => 'Floral',
    7 => 'Floral Boutique',
    8 => 'Fougere',
    9 => 'Fresh',
    10 => 'Fruity',
    11 => 'Gourmand',
    12 => 'Green',
    13 => 'Herbs & Spices',
    14 => 'Holiday',
    15 => 'Leather',
    16 => 'Oceanic & Ozonic',
    17 => 'Oceanic/Ozone',
    18 => 'Oriental',
    19 => 'Single Floral',
    20 => 'Unscented',
    21 => 'Woody',
  ),
) ?>