<?php return array (
  'SubcategoryID' => 736,
  'SubcategoryName' => 'HairDryers',
  'PropertyName' => 'HairDryersBrand',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'andis',
    1 => 'BaByliss PRO TT',
    2 => 'BaBylissPro',
    3 => 'BED HEAD',
    4 => 'BRAUN',
    5 => 'CONAIR',
    6 => 'Conair Pro',
    7 => 'Helen of Troy Limited',
    8 => 'Laila Ali',
    9 => 'Ovente',
    10 => 'Panasonic',
    11 => 'Pro Beauty',
    12 => 'Ragalta',
    13 => 'REMINGTON',
    14 => 'REVLON',
    15 => 'Sunbeam',
    16 => 'T3',
    17 => 'Toni & Guy',
    18 => 'VIDAL SASSOON',
    19 => 'Wahl',
  ),
) ?>