<?php return array (
  'SubcategoryID' => 1536,
  'SubcategoryName' => 'MensPantsShorts',
  'PropertyName' => 'ApparelMaterial',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => '100% Acrylic',
    1 => '100% Acrylic Knit',
    2 => '100% Cashmere',
    3 => '100% Nylon',
    4 => '30% Cashmere 70% wool',
    5 => '50% Cashmere 50% Wool',
    6 => 'Acrylic Blend',
    7 => 'Alligator Skin',
    8 => 'Cotton Blend',
    9 => 'Genuine Leather',
    10 => 'Italian Silk',
    11 => 'Polyester, 100% Polyester',
    12 => 'Rhodium Plated',
    13 => 'Stainless Steel',
    14 => 'Wool Blend',
  ),
) ?>