<?php return array (
  'SubcategoryID' => 2014,
  'SubcategoryName' => 'Toilets',
  'PropertyName' => 'ToiletsFinish',
  'IsAdvancedSearch' => 1,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Aged Brass',
    1 => 'Almond',
    2 => 'Balsa',
    3 => 'Biscuit',
    4 => 'Bisque',
    5 => 'Black',
    6 => 'Black Black',
    7 => 'Bone',
    8 => 'Cashmere',
    9 => 'Chrome',
    10 => 'Dune',
    11 => 'Historic Nickel',
    12 => 'Honed White',
    13 => 'Ice Grey',
    14 => 'Innocent Blush',
    15 => 'Linen',
    16 => 'Mexican Sand',
    17 => 'Mission',
    18 => 'Old Bronze',
    19 => 'Sandbar',
    20 => 'Skylight',
    21 => 'Sunlight',
    22 => 'Tea Green',
    23 => 'Thunder Grey',
    24 => 'White',
    25 => 'White Alpin',
    26 => 'White Alpine',
    27 => 'White Satin Nickel',
    28 => 'White without WonderGliss',
  ),
) ?>