<?php return array (
  'SubcategoryID' => 2014,
  'SubcategoryName' => 'Toilets',
  'PropertyName' => 'ToiletsCollection',
  'IsAdvancedSearch' => 0,
  'IsGroupBy' => 0,
  'IsRequired' => 0,
  'PropertyValueList' => 
  array (
    0 => 'Archer',
    1 => 'Barrington',
    2 => 'Cimarron',
    3 => 'Escale',
    4 => 'Gabrielle',
    5 => 'Highcrest',
    6 => 'Highline',
    7 => 'Kathryn',
    8 => 'Kingston',
    9 => 'Memoirs',
    10 => 'Persuade',
    11 => 'Portrait',
    12 => 'Primary',
    13 => 'Revival',
    14 => 'Saile',
    15 => 'San Raphael',
    16 => 'Wellcomme',
    17 => 'Wellworth',
  ),
) ?>